import { useCallback, useEffect, useState } from "react";
import { api, clearSession, getSession, saveSession, type Session, API_BASE_URL } from "./lib/api";
import { ArrowIcon, BellIcon, CalendarIcon, CardIcon, ChevronIcon, CloseIcon, CommentIcon, GlobeIcon, HeartIcon, HelpIcon, HomeIcon, LockIcon, LogOutIcon, MenuIcon, MessageIcon, MoreIcon, PlusIcon, ReDomMark, SearchIcon, SettingsIcon, ShareIcon, ShieldIcon, ShopIcon, SlidersIcon, SparkIcon, StarIcon, UserIcon, UsersIcon, VideoIcon } from "./components/Icons";

type Page = "landing"|"home"|"search"|"notifications"|"messages"|"chat"|"profile"|"friends"|"groups"|"events"|"marketplace"|"saved"|"ai"|"settings"|"orders"|"stars"|"subscriptions"|"payments"|"support"|"terms"|"report"|"login"|"register"|"verify";
type User = { id:string; username:string; publicId:string; profileId:string; firstName:string; lastName:string; email:string|null; phoneNumber:string|null; profilePhoto?:string|null; verified?:boolean };
type FeedPost = { id:string; content:string|null; publishedAt:string; firstName:string; lastName:string; username:string; profilePhoto:string|null; verified?:boolean; media?:Array<Record<string,unknown>>; reactionSummary?:{total:number;counts:Record<string,number>;myReaction:string|null}; authorId:string };

const routeFromHash=():Page=>{const p=location.hash.replace(/^#/,"").split("/")[0];const ok=["home","search","notifications","messages","chat","profile","friends","groups","events","marketplace","saved","ai","settings","orders","stars","subscriptions","payments","support","terms","report","login","register","verify"];return ok.includes(p)?p as Page:"landing"};
const initials=(u:any)=>String(u?.firstName||u?.name||"R").slice(0,1).toUpperCase();
const ago=(v:string)=>{const n=Date.now()-new Date(v).getTime(),m=Math.floor(n/60000);if(m<1)return"now";if(m<60)return m+"m";if(m<1440)return Math.floor(m/60)+"h";return Math.floor(m/1440)+"d"};

function Avatar({user,size=42}:{user:any;size?:number}){return user?.profilePhoto?<img className="avatar-img" src={user.profilePhoto} alt="" style={{width:size,height:size}}/>:<span className="avatar-fallback" style={{width:size,height:size,fontSize:Math.max(12,size/2.5)}}>{initials(user)}</span>}

export default function App(){
 const[page,setPage]=useState<Page>(routeFromHash()),[user,setUser]=useState<User|null>(null),[boot,setBoot]=useState(true),[menu,setMenu]=useState(false),[dark,setDark]=useState(localStorage.getItem("redom.web.dark")==="1"),[pending,setPending]=useState<any>(null);
 const nav=useCallback((p:string)=>{location.hash=p;setPage(routeFromHash());setMenu(false);window.scrollTo(0,0)},[]);
 useEffect(()=>{const h=()=>setPage(routeFromHash());addEventListener("hashchange",h);return()=>removeEventListener("hashchange",h)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("redom.web.dark",dark?"1":"0")},[dark]);
 useEffect(()=>{(async()=>{const s=getSession();if(s){try{const r=await api<any>("/profile");if(r.profile)setUser({...r.profile,id:r.profile.userId})}catch{clearSession()}}setBoot(false)})()},[]);
 const logout=async()=>{try{await api("/auth/logout",{method:"POST"})}catch{}clearSession();setUser(null);nav("landing")};
 if(boot)return <div className="boot"><ReDomMark size={58}/><b>ReDom</b><span>Loading your world…</span></div>;
 if(!user&&!["login","register","verify"].includes(page))return <Landing nav={nav}/>;
 return <div className="app-shell"><Header user={user} nav={nav} openMenu={()=>setMenu(true)} logout={logout}/>{menu?<Drawer user={user} page={page} nav={nav} close={()=>setMenu(false)} logout={logout} dark={dark} setDark={setDark}/>:null}<div className="app-layout">{user?<Sidebar page={page} nav={nav}/>:null}<main className="app-main">
 {page==="login"?<Login onSuccess={(u,s)=>{setUser(u);saveSession(s);nav("home")}} onRegister={()=>nav("register")}/>:null}
 {page==="register"?<Register onSuccess={(u,s)=>{setUser(u);saveSession(s);nav("home")}} onVerify={v=>{setPending(v);nav("verify")}} onLogin={()=>nav("login")}/>:null}
 {page==="verify"?<Verify data={pending} onSuccess={(u,s)=>{setUser(u);saveSession(s);nav("home")}} back={()=>nav("login")}/>:null}
 {user&&page==="home"?<Home user={user} nav={nav}/>:null}{user&&page==="search"?<Search nav={nav}/>:null}{user&&page==="notifications"?<Notifications/>:null}{user&&page==="messages"?<Messages/>:null}{user&&page==="chat"?<Chat nav={nav}/>:null}{user&&page==="profile"?<Profile user={user} nav={nav}/>:null}{user&&page==="friends"?<Friends nav={nav}/>:null}{user&&page==="groups"?<Groups/>:null}{user&&page==="events"?<Events/>:null}{user&&page==="marketplace"?<Marketplace/>:null}{user&&page==="saved"?<Saved/>:null}{user&&page==="ai"?<AI/>:null}{user&&page==="settings"?<Settings dark={dark} setDark={setDark} nav={nav}/>:null}{user&&page==="orders"?<Orders nav={nav}/>:null}{user&&page==="stars"?<Stars nav={nav}/>:null}{user&&page==="subscriptions"?<Subscriptions/>:null}{user&&page==="payments"?<Payments/>:null}{user&&page==="support"?<Support/>:null}{user&&page==="terms"?<Terms/>:null}{user&&page==="report"?<Report/>:null}
 </main></div></div>
}

function Landing({nav}:{nav:(p:string)=>void}){return <div className="landing"><header className="landing-nav"><button className="brand" onClick={()=>nav("landing")}><ReDomMark/><span>ReDom</span></button><nav><a href="#features">Features</a><a href="#about">About</a><a href="#download">Get ReDom</a></nav><div className="nav-actions"><button className="btn ghost" onClick={()=>nav("login")}>Sign in</button><button className="btn primary" onClick={()=>nav("register")}>Create account</button></div><button className="icon-btn mobile-only"><MenuIcon/></button></header>
<section className="hero-landing"><div className="hero-copy"><span className="eyebrow"><i/> ReDom is here</span><h1>Your world.<br/><span>Connected.</span></h1><p>ReDom is a social platform for sharing, discovering, messaging, building communities, and staying connected with the people around you.</p><div className="hero-buttons"><button className="btn primary xl" onClick={()=>nav("register")}>Get started <ArrowIcon/></button><button className="btn secondary xl" onClick={()=>nav("login")}>Sign in</button></div><div className="trusted"><span>Social</span><span>Messaging</span><span>Communities</span><span>Payments</span></div></div><div className="hero-art"><div className="orb orb-a"/><div className="orb orb-b"/><div className="web-preview"><div className="preview-top"><div className="brand"><ReDomMark size={28}/><b>ReDom</b></div><span className="pill">Home</span></div><div className="preview-stories"><i/><i/><i/><i/></div><div className="preview-post"><div className="row"><span className="avatar-fallback sm">R</span><div><b>ReDom</b><small>Just now</small></div></div><p>Welcome to ReDom. This is where your social experience begins.</p><div className="preview-media"><ReDomMark size={76}/></div><div className="preview-actions"><span>Like</span><span>Comment</span><span>Share</span></div></div></div></div></section>
<section id="features" className="section light"><div className="section-head"><span className="eyebrow">Built for connection</span><h2>Everything starts with people.</h2><p>One ReDom identity across conversations, content, communities, discovery, and more.</p></div><div className="feature-grid"><Feature icon={<UsersIcon/>} title="Connect" text="Find friends, follow people, discover communities, and stay close to what matters."/><Feature icon={<ShareIcon/>} title="Share" text="Publish posts, photos, videos and stories with a responsive social experience."/><Feature icon={<SparkIcon/>} title="Discover" text="Search people, explore groups and events, and meet new communities."/><Feature icon={<MessageIcon/>} title="Message" text="Keep conversations organized with ReDom messaging infrastructure."/><Feature icon={<StarIcon/>} title="ReDom Pay" text="Manage payment methods, Stars, subscriptions and transactions."/><Feature icon={<ShieldIcon/>} title="Control" text="Settings, privacy, security, support and policies in one place."/></div></section>
<section id="about" className="about"><div><span className="eyebrow">The ReDom experience</span><h2>One identity across your ReDom world.</h2></div><p>The web experience is its own React and TypeScript application while sharing the same production backend as ReDom mobile. The browser uses Vite environment configuration and authenticated API calls to the Render backend.</p></section>
<section id="download" className="join"><div className="join-card"><ReDomMark size={62}/><div><span className="eyebrow">ReDom</span><h2>Join the network.</h2><p>Create an account or sign in to open the live ReDom experience.</p></div><button className="btn primary" onClick={()=>nav("register")}>Create account <ArrowIcon/></button></div></section>
<footer className="landing-footer"><div className="brand"><ReDomMark size={28}/><b>ReDom</b></div><span>© 2026 ReDom Platforms, Inc.</span><div><a href="#about">About</a><a href="#features">Features</a><a href="#download">Get ReDom</a></div></footer></div>}
function Feature({icon,title,text}:{icon:any;title:string;text:string}){return <article className="feature"><div className="feature-icon">{icon}</div><span className="feature-num">ReDom</span><h3>{title}</h3><p>{text}</p></article>}

function Header({user,nav,openMenu,logout}:{user:User|null;nav:(p:string)=>void;openMenu:()=>void;logout:()=>void}){const[open,setOpen]=useState(false);return <header className="app-header"><button className="brand header-brand" onClick={()=>nav("home")}><ReDomMark size={34}/><span>ReDom</span></button><button className="header-search" onClick={()=>nav("search")}><SearchIcon/><span>Search ReDom</span></button><div className="header-actions"><button className="circle-btn" onClick={()=>nav("messages")}><MessageIcon/></button><button className="circle-btn" onClick={()=>nav("notifications")}><BellIcon/></button><button className="profile-chip" onClick={()=>setOpen(!open)}><Avatar user={user} size={34}/><span>{user?.firstName}</span><ChevronIcon/></button><button className="circle-btn menu-mobile" onClick={openMenu}><MenuIcon/></button></div>{open?<div className="account-popover"><button onClick={()=>nav("profile")}><UserIcon/>Profile</button><button onClick={()=>nav("settings")}><SettingsIcon/>Settings & privacy</button><button onClick={logout}><LogOutIcon/>Log out</button></div>:null}</header>}

function Sidebar({page,nav}:{page:Page;nav:(p:string)=>void}){const items:any[]=[["home","Home",HomeIcon],["search","Search",SearchIcon],["messages","Messages",MessageIcon],["notifications","Notifications",BellIcon],["profile","Profile",UserIcon],["friends","Friends",UsersIcon],["groups","Groups",UsersIcon],["events","Events",CalendarIcon],["marketplace","Marketplace",ShopIcon],["saved","Saved",StarIcon],["ai","ReDom AI",SparkIcon],["orders","Orders & payments",CardIcon]];return <aside className="sidebar"><div className="side-label">ReDom</div>{items.map(([p,l,I])=><button key={p} className={page===p?"active":""} onClick={()=>nav(p)}><I/><span>{l}</span></button>)}<div className="side-divider"/><button onClick={()=>nav("settings")}><SettingsIcon/><span>Settings & privacy</span></button><button onClick={()=>nav("support")}><HelpIcon/><span>Help & support</span></button><div className="side-status"><i/>API connected<small>{API_BASE_URL.replace("https://","")}</small></div></aside>}

function Drawer({user,page,nav,close,logout,dark,setDark}:{user:User|null;page:Page;nav:(p:string)=>void;close:()=>void;logout:()=>void;dark:boolean;setDark:(v:boolean)=>void}){const items:any[]=[["profile","Profile",UserIcon],["friends","Friends",UsersIcon],["groups","Groups",UsersIcon],["events","Events",CalendarIcon],["marketplace","Marketplace",ShopIcon],["saved","Saved",StarIcon],["ai","ReDom AI",SparkIcon],["orders","Orders & payments",CardIcon],["settings","Settings & privacy",SettingsIcon],["support","Help & support",HelpIcon]];return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div className="brand"><ReDomMark size={34}/><b>ReDom</b></div><button className="circle-btn" onClick={close}><CloseIcon/></button></div><div className="drawer-user"><Avatar user={user} size={50}/><div><b>{user?.firstName} {user?.lastName}</b><small>@{user?.username}</small></div></div>{items.map(([p,l,I])=><button className={page===p?"active":""} key={p} onClick={()=>nav(p)}><I/><span>{l}</span><ChevronIcon/></button>)}<div className="drawer-bottom"><button onClick={()=>setDark(!dark)}><span>{dark?"Light mode":"Dark mode"}</span><span className="switch"><i className={dark?"on":""}/></span></button><button onClick={logout}><LogOutIcon/><span>Log out</span></button></div></aside></div>}

function AuthPage({title,subtitle,children}:{title:string;subtitle:string;children:any}){return <div className="auth-wrap"><div className="auth-card"><div className="auth-brand"><ReDomMark size={46}/><b>ReDom</b></div><h1>{title}</h1><p>{subtitle}</p>{children}<small className="auth-foot">ReDom · secure account access</small></div></div>}
function Field({label,value,onChange,type="text",placeholder=""}:{label:string;value:string;onChange:(v:string)=>void;type?:string;placeholder?:string}){return <label className="field"><span>{label}</span><input type={type} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Alert({text}:{text:string}){return <div className="alert">{text}</div>}

function Login({onSuccess,onRegister}:{onSuccess:(u:User,s:Session)=>void;onRegister:()=>void}){const[id,setId]=useState(""),[pw,setPw]=useState(""),[busy,setBusy]=useState(false),[err,setErr]=useState("");const submit=async(e:any)=>{e.preventDefault();setBusy(true);setErr("");try{const r=await api<any>("/auth/login",{method:"POST",body:JSON.stringify({identifier:id,password:pw,platform:"web",browser:navigator.userAgent,deviceType:"browser",loginSource:"web"})});if(r.requiresVerification||r.requiresTwoFactor){sessionStorage.setItem("redom.pendingVerification",JSON.stringify(r));location.hash="verify";return}if(r.success&&r.user&&r.session)onSuccess(r.user,r.session);else setErr(r.message||"Unable to sign in.")}catch(e){setErr(e instanceof Error?e.message:"Unable to sign in.")}finally{setBusy(false)}};return <AuthPage title="Welcome back" subtitle="Sign in to your ReDom account."><form className="auth-form" onSubmit={submit}>{err?<Alert text={err}/>:null}<Field label="Email, phone or username" value={id} onChange={setId}/><Field label="Password" type="password" value={pw} onChange={setPw}/><button className="btn primary xl full" disabled={busy}>{busy?"Signing in…":"Sign in"}</button><button type="button" className="text-btn">Forgot password?</button><div className="auth-divider">or</div><button type="button" className="btn secondary xl full" onClick={onRegister}>Create new account</button></form></AuthPage>}

function Register({onSuccess,onVerify,onLogin}:{onSuccess:(u:User,s:Session)=>void;onVerify:(v:any)=>void;onLogin:()=>void}){const[step,setStep]=useState(1),[f,setF]=useState<any>({firstName:"",lastName:"",username:"",dateOfBirth:"",gender:"male",email:"",phoneNumber:"",password:""}),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const set=(k:string,v:string)=>setF({...f,[k]:v});const next=async()=>{setErr("");if(step===1&&(!f.firstName||!f.lastName))return setErr("Enter your first and last name.");if(step===2&&!f.dateOfBirth)return setErr("Enter your date of birth.");if(step===3&&!f.username)return setErr("Choose a username.");if(step===4&&!f.email&&!f.phoneNumber)return setErr("Add an email or phone number.");if(step<5)return setStep(step+1);setBusy(true);try{const r=await api<any>("/auth/register",{method:"POST",body:JSON.stringify({...f,platform:"web",browser:navigator.userAgent,loginSource:"web"})});if(r.requiresVerification||r.verification){onVerify(r);return}if(r.success&&r.user&&r.session)onSuccess(r.user,r.session);else setErr(r.message||"Registration failed.")}catch(e){setErr(e instanceof Error?e.message:"Registration failed.")}finally{setBusy(false)}};return <AuthPage title="Create your ReDom account" subtitle={"Step "+step+" of 5"}><div className="stepbar">{[1,2,3,4,5].map(i=><i key={i} className={i<=step?"done":""}/>)}</div>{err?<Alert text={err}/>:null}<div className="auth-form">{step===1?<div className="two"><Field label="First name" value={f.firstName} onChange={v=>set("firstName",v)}/><Field label="Last name" value={f.lastName} onChange={v=>set("lastName",v)}/></div>:null}{step===2?<><Field label="Date of birth" type="date" value={f.dateOfBirth} onChange={v=>set("dateOfBirth",v)}/><div className="choice-grid">{["male","female","custom"].map(x=><button type="button" className={f.gender===x?"choice selected":"choice"} key={x} onClick={()=>set("gender",x)}>{x}</button>)}</div></>:null}{step===3?<Field label="Username" value={f.username} onChange={v=>set("username",v)} placeholder="yourname"/>:null}{step===4?<><Field label="Email" value={f.email} onChange={v=>set("email",v)} placeholder="you@example.com"/><Field label="Phone number" value={f.phoneNumber} onChange={v=>set("phoneNumber",v)} placeholder="Optional"/></>:null}{step===5?<Field label="Password" type="password" value={f.password} onChange={v=>set("password",v)}/>:null}<button className="btn primary xl full" onClick={()=>void next()} disabled={busy}>{busy?"Creating…":step<5?"Continue":"Create account"}</button>{step>1?<button className="btn secondary xl full" onClick={()=>setStep(step-1)}>Back</button>:null}<button className="text-btn" onClick={onLogin}>Already have an account? Sign in</button></div></AuthPage>}

function Verify({data,onSuccess,back}:{data:any;onSuccess:(u:User,s:Session)=>void;back:()=>void}){const stored=data||JSON.parse(sessionStorage.getItem("redom.pendingVerification")||"null")||{};const v=stored.verification||stored.twoFactorVerification||stored;const two=!!stored.requiresTwoFactor;const[code,setCode]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);const submit=async()=>{setBusy(true);try{let path="/auth/verify-login-device",body:any={challengeId:v.challengeId,code};if(two){path="/auth/verify-login-2fa"}else if(v.verificationChallengeId){path="/auth/register/verification/"+v.verificationChallengeId+"/verify";body={verificationChallengeId:v.verificationChallengeId,code}}const r=await api<any>(path,{method:"POST",body:JSON.stringify(body)});if(r.success&&r.user&&r.session){sessionStorage.removeItem("redom.pendingVerification");onSuccess(r.user,r.session)}else setErr(r.message||"Code not accepted.")}catch(e){setErr(e instanceof Error?e.message:"Verification failed.")}finally{setBusy(false)}};return <AuthPage title="Verify your account" subtitle={v.maskedTarget?"Code sent to "+v.maskedTarget:"Enter your verification code"}><div className="auth-form">{err?<Alert text={err}/>:null}<Field label="Verification code" value={code} onChange={v=>setCode(v.replace(/\\D/g,"").slice(0,8))}/><button className="btn primary xl full" disabled={busy||code.length<4} onClick={()=>void submit()}>{busy?"Verifying…":"Verify"}</button><button className="btn secondary xl full" onClick={back}>Back</button></div></AuthPage>}

function PageHeader({title,subtitle,actions}:{title:string;subtitle:string;actions?:any}){return <div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions}</div>}
function Card({title,children}:{title:string;children:any}){return <section className="card"><div className="card-title"><h3>{title}</h3></div>{children}</section>}
function Empty({icon,title,text}:{icon:any;title:string;text:string}){return <div className="empty"><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>}
function Skeleton(){return <div className="skeleton"><i/><i/><i/></div>}
function Quick({icon,label,onClick}:{icon:any;label:string;onClick:()=>void}){return <button className="quick-row" onClick={onClick}><span>{icon}</span><b>{label}</b><ChevronIcon/></button>}
function SettingRow({icon,title,text,action,toggle}:{icon:any;title:string;text:string;action:()=>void;toggle?:boolean}){return <button className="setting-row" onClick={action}><span className="setting-icon">{icon}</span><span><b>{title}</b><small>{text}</small></span>{toggle!==undefined?<span className="switch"><i className={toggle?"on":""}/></span>:<ChevronIcon/>}</button>}

function Home({user,nav}:{user:User;nav:(p:string)=>void}){const[posts,setPosts]=useState<FeedPost[]>([]),[stories,setStories]=useState<any[]>([]),[suggestions,setSuggestions]=useState<any[]>([]),[loading,setLoading]=useState(true);const load=useCallback(async()=>{setLoading(true);try{const r=await api<any>("/feed/home?refresh="+Date.now());setPosts(r.posts||[]);setStories(r.stories||[]);setSuggestions(r.friendSuggestions||[])}catch{}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const react=async(p:FeedPost)=>{try{const r=await api<any>("/feed/post-reaction",{method:"POST",body:JSON.stringify({postId:p.id,reactionType:p.reactionSummary?.myReaction?"":"like"})});setPosts(v=>v.map(x=>x.id===p.id?{...x,reactionSummary:{...x.reactionSummary,...r}}:x))}catch{}};return <div className="page"><PageHeader title={"Good to see you, "+user.firstName+"."} subtitle="Your ReDom feed, conversations and communities in one place." actions={<button className="btn secondary" onClick={()=>void load()}>Refresh</button>}/><div className="feed-layout"><section><div className="composer"><Avatar user={user} size={48}/><button>What's on your mind, {user.firstName}?</button><button className="composer-add"><PlusIcon/></button></div><div className="story-strip"><button className="story-create"><PlusIcon/><b>Create story</b></button>{stories.slice(0,8).map(s=><button className="story-item" key={s.id}><Avatar user={s} size={52}/><b>{s.firstName}</b><small>Story</small></button>)}</div>{loading?<Skeleton/>:posts.length?posts.map(p=><Post key={p.id} post={p} react={()=>void react(p)} nav={nav}/>):<Empty icon={<HomeIcon/>} title="Your feed is ready" text="Connect with people and communities to see posts here."/>}</section><aside className="right-rail"><Card title="People you may know">{suggestions.slice(0,5).map(s=><div className="person-row" key={s.userId}><Avatar user={s} size={42}/><div><b>{s.firstName} {s.lastName}</b><small>{s.friendCount||0} friends</small></div><button className="mini-btn" onClick={()=>nav("profile")}>View</button></div>)}</Card><Card title="Quick access"><Quick icon={<StarIcon/>} label="ReDom Stars" onClick={()=>nav("stars")}/><Quick icon={<CardIcon/>} label="Orders & payments" onClick={()=>nav("orders")}/><Quick icon={<SparkIcon/>} label="ReDom AI" onClick={()=>nav("ai")}/></Card></aside></div></div>}

function Post({post,react,nav}:{post:FeedPost;react:()=>void;nav:(p:string)=>void}){const[open,setOpen]=useState(false),[comments,setComments]=useState<any[]>([]),[text,setText]=useState("");const load=async()=>{if(open){setOpen(false);return}try{const r=await api<any>("/comments/post/"+post.id+"?limit=20");setComments(r.comments||[]);setOpen(true)}catch{}};const comment=async()=>{if(!text.trim())return;try{const r=await api<any>("/comments/post/"+post.id,{method:"POST",body:JSON.stringify({content:text.trim(),parentCommentId:null})});setComments(v=>[...v,r.comment]);setText("")}catch{}};const media=post.media?.[0] as any;return <article className="post"><div className="post-head"><button onClick={()=>nav("profile")}><Avatar user={post} size={46}/></button><div className="post-author"><b>{post.firstName} {post.lastName}{post.verified?<span className="verified">✓</span>:null}</b><small>@{post.username} · {ago(post.publishedAt)}</small></div><button className="icon-btn"><MoreIcon/></button></div>{post.content?<p className="post-content">{post.content}</p>:null}{media?.objectKey?<img className="post-image" src={media.objectKey} alt=""/>:<div className="post-art"><ReDomMark size={78}/></div>}<div className="post-meta"><span>{post.reactionSummary?.total||0} reactions</span><span>{comments.length} comments</span></div><div className="post-actions"><button className={post.reactionSummary?.myReaction?"selected":""} onClick={react}><HeartIcon/>Like</button><button onClick={()=>void load()}><CommentIcon/>Comment</button><button><ShareIcon/>Share</button></div>{open?<div className="comments">{comments.map(c=><div className="comment" key={c.id}><Avatar user={c.author} size={34}/><div><b>{c.author?.firstName} {c.author?.lastName}</b><p>{c.content}</p></div></div>)}<div className="comment-compose"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a comment…"/><button onClick={()=>void comment()}><ArrowIcon/></button></div></div>:null}</article>}

function Search({nav}:{nav:(p:string)=>void}){const[q,setQ]=useState(""),[r,setR]=useState<any[]>([]);const go=async()=>{if(!q.trim())return;try{const x=await api<any>("/search?q="+encodeURIComponent(q));setR(x.results||[])}catch{}};return <div className="page"><PageHeader title="Search ReDom" subtitle="Find people and profiles across ReDom."/><div className="search-large"><SearchIcon/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void go()} placeholder="Search people and usernames"/><button className="btn primary" onClick={()=>void go()}>Search</button></div><div className="result-list">{r.map(x=><button className="result-card" key={x.userId} onClick={()=>nav("profile")}><Avatar user={x} size={52}/><div><b>{x.firstName} {x.lastName} {x.verified?<span className="verified">✓</span>:null}</b><small>@{x.username}</small></div><ChevronIcon/></button>)}</div></div>}

function Notifications(){const[n,setN]=useState<any[]>([]);useEffect(()=>{api<any>("/product/notifications").then(r=>setN(r.notifications||[])).catch(()=>{})},[]);return <div className="page"><PageHeader title="Notifications" subtitle="Updates about your ReDom account and activity." actions={<button className="btn secondary" onClick={async()=>{await api("/product/notifications/read-all",{method:"POST"});setN(v=>v.map(x=>({...x,unread:false})))}}>Mark all read</button>}/><div className="notification-list">{n.map(x=><button className={"notification "+(x.unread?"unread":"")} key={x.id} onClick={async()=>{await api("/product/notifications/"+x.id+"/read",{method:"POST"});setN(v=>v.map(a=>a.id===x.id?{...a,unread:false}:a))}}><span className="notification-icon"><BellIcon/></span><div><b>{x.title||"ReDom notification"}</b><p>{x.body||"You have a new ReDom update."}</p><small>{ago(x.createdAt)}</small></div>{x.unread?<i/>:null}</button>)}</div></div>}

function Messages(){const[c,setC]=useState<any[]>([]);useEffect(()=>{api<any>("/messages/inbox").then(r=>setC(r.conversations||[])).catch(()=>{})},[]);return <div className="page"><PageHeader title="Messages" subtitle="Your ReDom conversations."/><div className="messages-shell"><div className="message-list">{c.map(x=><button className="conversation" key={x.id||x.conversationId} onClick={()=>location.hash="chat/"+(x.id||x.conversationId)}><Avatar user={{firstName:x.title||x.name||"R",profilePhoto:x.profilePhoto}} size={50}/><div><b>{x.title||x.name||"Conversation"}</b><p>{x.lastMessagePreview||"Encrypted conversation"}</p><small>{x.updatedAt?ago(x.updatedAt):"Recent"}</small></div></button>)}{!c.length?<Empty icon={<MessageIcon/>} title="No conversations" text="Your ReDom conversations will appear here."/>:null}</div><div className="message-empty"><MessageIcon/><h3>Choose a conversation</h3><p>Open a conversation to view messages.</p></div></div></div>}

function Chat({nav}:{nav:(p:string)=>void}){const id=location.hash.split("/")[1]||"",[m,setM]=useState<any[]>([]);useEffect(()=>{if(id)api<any>("/messages/conversations/"+encodeURIComponent(id)).then(r=>setM(r.messages||[])).catch(()=>{});if(id)api("/messages/conversations/"+encodeURIComponent(id)+"/read",{method:"POST"}).catch(()=>{})},[id]);return <div className="page chat-page"><div className="chat-head"><button className="icon-btn" onClick={()=>nav("messages")}><ChevronIcon/></button><div><b>ReDom conversation</b><small>Encrypted conversation</small></div><button className="circle-btn"><MoreIcon/></button></div><div className="chat-messages">{m.length?m.map((x:any,i)=><div className="bubble-wrap" key={x.id||i}><div className="bubble">{x.content||x.text||"Encrypted message"}</div></div>):<Empty icon={<LockIcon/>} title="Encrypted conversation" text="The web reads the same conversation endpoint as mobile. Message decryption and encrypted sending remain tied to ReDom's device-key flow."/>}</div><div className="chat-compose"><input placeholder="Message…"/><button className="btn primary" onClick={()=>alert("Web message sending uses the same E2EE device-key flow as mobile and is being wired into this browser composer.")}><ArrowIcon/></button></div></div>}

function Profile({user,nav}:{user:User;nav:(p:string)=>void}){const[p,setP]=useState<any>(null);useEffect(()=>{api<any>("/profile").then(r=>setP(r.profile)).catch(()=>{})},[]);return <div className="page"><div className="profile-cover">{p?.coverPhoto?<img src={p.coverPhoto} alt=""/>:<div/>}<button><CameraIcon/></button></div><div className="profile-main"><div className="profile-identity"><Avatar user={{...user,profilePhoto:p?.profilePhoto}} size={104}/><div><h1>{p?.firstName} {p?.lastName} {p?.verified?<span className="verified">✓</span>:null}</h1><p>@{p?.username}</p><small>{p?.friendCount||0} friends · {p?.followerCount||0} followers · {p?.postCount||0} posts</small></div><div className="profile-buttons"><button className="btn secondary" onClick={()=>nav("settings")}><SettingsIcon/>Manage</button><button className="btn primary" onClick={()=>nav("friends")}><UsersIcon/>Friends</button></div></div><div className="profile-tabs"><button className="active">All</button><button>Reels</button><button>Photos</button><button>Events</button></div><div className="profile-grid"><section>{(p?.posts||[]).map((x:any)=><article className="post" key={x.id}><div className="post-head"><Avatar user={user} size={42}/><div className="post-author"><b>{p?.firstName} {p?.lastName}</b><small>{x.publishedAt?ago(x.publishedAt):"Post"}</small></div></div>{x.content?<p className="post-content">{x.content}</p>:null}{x.mediaUrl?<img className="post-image" src={x.mediaUrl} alt=""/>:<div className="post-art small"><ReDomMark size={58}/></div>}</article>)}</section><aside><Card title="About"><p className="muted">{p?.bio||"Tell people a little about yourself on ReDom."}</p>{p?.location?<div className="about-row"><GlobeIcon/>{p.location}</div>:null}</Card></aside></div></div></div>}

function Friends({nav}:{nav:(p:string)=>void}){const[p,setP]=useState<any[]>([]),[tab,setTab]=useState("all");useEffect(()=>{const u=tab==="suggested"?"/friends/suggested":tab==="requests"?"/friends/requests":"/friends";api<any>(u).then(r=>setP(tab==="requests"?[...(r.incoming||[]),...(r.outgoing||[])]:r.people||[])).catch(()=>{})},[tab]);return <div className="page"><PageHeader title="Friends" subtitle="Manage friends, suggestions and requests."/><div className="tabs"><button className={tab==="all"?"active":""} onClick={()=>setTab("all")}>All friends</button><button className={tab==="suggested"?"active":""} onClick={()=>setTab("suggested")}>Suggestions</button><button className={tab==="requests"?"active":""} onClick={()=>setTab("requests")}>Requests</button></div><div className="people-grid">{p.map(x=><article className="person-card" key={x.userId}><Avatar user={x} size={68}/><b>{x.firstName} {x.lastName}</b><small>@{x.username}</small><div><button className="btn secondary" onClick={()=>nav("profile")}>Profile</button>{!x.friend&&!x.requestSent?<button className="btn primary" onClick={()=>api("/friends/requests/"+x.userId,{method:"POST"}).then(()=>setP(v=>v.map(a=>a.userId===x.userId?{...a,requestSent:true}:a))}>Add</button>:<button className="btn secondary">{x.friend?"Friends":"Requested"}</button>}</div></article>)}</div></div>}

function Groups(){const[g,setG]=useState<any[]>([]);useEffect(()=>{api<any>("/public-groups").then(r=>setG(r.groups||[])).catch(()=>{})},[]);return <div className="page"><PageHeader title="Groups" subtitle="Discover and join public ReDom communities."/><div className="people-grid">{g.map(x=><article className="group-card" key={x.id}><div className="group-art"><UsersIcon/></div><h3>{x.name}</h3><p>{x.description||"A ReDom community."}</p><small>{x.memberCount||0} members</small><button className="btn primary" onClick={()=>api("/public-groups/"+x.id+"/join",{method:"POST"}).catch(()=>{})}>Join group</button></article>)}</div>{!g.length?<Empty icon={<UsersIcon/>} title="No public groups returned" text="The page is connected to /public-groups."/>:null}</div>}

function Events(){const[e,setE]=useState<any[]>([]),[mode,setMode]=useState("for_you");useEffect(()=>{api<any>("/events?mode="+mode).then(r=>setE(r.events||[])).catch(()=>{})},[mode]);return <div className="page"><PageHeader title="Events" subtitle="Discover events and respond to the ones you want to attend."/><div className="tabs"><button className={mode==="for_you"?"active":""} onClick={()=>setMode("for_you")}>For you</button><button className={mode==="local"?"active":""} onClick={()=>setMode("local")}>Local</button></div><div className="event-grid">{e.map(x=><article className="event-card" key={x.id}><div className="event-date"><b>{new Date(x.start_at).toLocaleDateString(undefined,{month:"short"})}</b><strong>{new Date(x.start_at).getDate()}</strong></div><div><h3>{x.name}</h3><p>{x.description||"ReDom event"}</p><small>{x.location_name||x.event_type} · {x.going_count||0} going</small><button className="btn secondary" onClick={()=>api("/events/"+x.id+"/rsvp",{method:"POST",body:JSON.stringify({status:"going"})})}>{x.viewer_status==="going"?"Going":"I'm going"}</button></div></article>)}</div></div>}

function Marketplace(){return <div className="page"><PageHeader title="Marketplace" subtitle="Products and commerce on ReDom."/><div className="market-hero"><div className="market-icon"><ShopIcon/></div><h2>Marketplace web surface</h2><p>The mobile Marketplace screen is currently lightweight; the web route is ready for the same product APIs as they expand.</p><button className="btn primary" onClick={()=>location.hash="orders"}>Open orders & payments</button></div></div>}
function Saved(){const[s,setS]=useState<any[]>([]);useEffect(()=>{api<any>("/product/saved?tab=all").then(r=>setS(r.saved||[])).catch(()=>{})},[]);return <div className="page"><PageHeader title="Saved" subtitle="Content you chose to keep."/><div className="saved-grid">{s.map(x=><article className="saved-card" key={x.id}><span>{x.contentType}</span><h3>{x.content?.content||"Saved ReDom content"}</h3><small>{x.createdAt?ago(x.createdAt):""}</small></article>)}</div>{!s.length?<Empty icon={<StarIcon/>} title="Nothing saved yet" text="Saved posts, reels and products will appear here."/>:null}</div>}

function AI(){const[h,setH]=useState<any[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false);const send=async()=>{const m=input.trim();if(!m)return;setInput("");setH(v=>[...v,{role:"user",content:m}]);setBusy(true);try{const r=await api<any>("/ai/chat",{method:"POST",body:JSON.stringify({message:m,history:h.slice(-20)})});setH(v=>[...v,{role:"assistant",content:r.reply||"No response."}])}catch(e){setH(v=>[...v,{role:"assistant",content:e instanceof Error?e.message:"AI request failed."}])}finally{setBusy(false)}};return <div className="page ai-page"><div className="ai-hero"><span className="ai-mark"><SparkIcon/></span><div><span className="eyebrow">ReDom intelligence</span><h1>ReDom AI</h1><p>Ask questions using the same /ai/chat backend used by the mobile app.</p></div></div><div className="ai-chat">{h.length?h.map((m,i)=><div className={"ai-message "+m.role} key={i}><b>{m.role==="user"?"You":"ReDom AI"}</b><p>{m.content}</p></div>):<div className="ai-empty"><SparkIcon/><h3>What can I help you with?</h3><button onClick={()=>setInput("What can ReDom AI do?")}>What can you do?</button><button onClick={()=>setInput("Help me understand ReDom settings.")}>Explain settings</button></div>}{busy?<div className="ai-message assistant"><b>ReDom AI</b><p>Thinking…</p></div>:null}</div><div className="ai-compose"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void send()} placeholder="Ask ReDom AI…"/><button className="btn primary" onClick={()=>void send()}><ArrowIcon/></button></div></div>}

function Settings({dark,setDark,nav}:{dark:boolean;setDark:(v:boolean)=>void;nav:(p:string)=>void}){const[s,setS]=useState<any>(null);useEffect(()=>{api<any>("/product/settings").then(r=>setS(r.settings)).catch(()=>{})},[]);return <div className="page"><PageHeader title="Settings & privacy" subtitle="Manage your ReDom account, preferences, security and services."/><div className="settings-search"><SearchIcon/>Search settings</div><SettingsSection title="Your account" desc="Manage account information and connected ReDom services."><SettingRow icon={<UserIcon/>} title="Profile details" text="Your public profile and personal information." action={()=>nav("profile")}/><SettingRow icon={<ShieldIcon/>} title="Security" text="Account protection and verification." action={()=>alert("Security controls are connected to the authenticated backend session.")}/></SettingsSection><SettingsSection title="Preferences" desc="Customize how ReDom looks and works."><SettingRow icon={<GlobeIcon/>} title="Language and region" text={s?.language||"English"} action={()=>alert("Language and region will use the same preference data model as mobile.")}/><SettingRow icon={<SparkIcon/>} title="Dark mode" text={dark?"On":"Off"} action={()=>setDark(!dark)} toggle={dark}/><SettingRow icon={<BellIcon/>} title="Notifications" text="Notification preferences" action={()=>nav("notifications")}/><SettingRow icon={<SlidersIcon/>} title="Content preferences" text="Feed, sensitive content, autoplay and translation." action={()=>alert("Content preferences use /product/settings.")}/></SettingsSection><SettingsSection title="Audience and visibility" desc="Control who can see and interact with your content."><SettingRow icon={<UsersIcon/>} title="Friends" text="Manage connections and requests." action={()=>nav("friends")}/><SettingRow icon={<LockIcon/>} title="Blocking and privacy" text="Review privacy policies and account controls." action={()=>nav("terms")}/></SettingsSection><SettingsSection title="Payments" desc="Handle payments, Stars and subscriptions."><SettingRow icon={<CardIcon/>} title="Orders and payments" text="Payment methods, transactions, Stars and subscriptions." action={()=>nav("orders")}/></SettingsSection><SettingsSection title="Community Standards and legal policies" desc="Review ReDom legal and policy documents."><SettingRow icon={<ShieldIcon/>} title="Terms and policies" text="Terms, privacy, messaging, payments and more." action={()=>nav("terms")}/></SettingsSection></div>}
function SettingsSection({title,desc,children}:{title:string;desc:string;children:any}){return <section className="settings-section"><div><h2>{title}</h2><p>{desc}</p></div><div className="settings-card">{children}</div></section>}

function Orders({nav}:{nav:(p:string)=>void}){const[o,setO]=useState<any>({payments:[],orders:[]}),[stars,setStars]=useState(0);useEffect(()=>{Promise.all([api<any>("/orders-payments/overview"),api<any>("/orders-payments/stars/activity")]).then(([a,b])=>{setO(a);setStars(Number(b.balance||0))}).catch(()=>{})},[]);return <div className="page"><PageHeader title="Orders and payments" subtitle="Manage ReDom Pay, transactions, Stars and subscriptions."/><div className="payment-grid"><Card title="ReDom Pay"><div className="pay-balance"><CardIcon/><div><small>Transactions</small><b>{o.payments?.length||0}</b></div></div><button className="btn primary" onClick={()=>nav("payments")}>Manage ReDom Pay</button></Card><Card title="ReDom Stars"><div className="star-balance"><StarIcon/><div><small>Current balance</small><b>{stars} Stars</b></div></div><button className="btn primary" onClick={()=>nav("stars")}>Buy Stars</button></Card><Card title="Subscriptions"><p className="muted">View your ReDom subscriptions.</p><button className="btn secondary" onClick={()=>nav("subscriptions")}>Open subscriptions</button></Card></div><section className="table-card"><div className="card-title"><h3>Recent payments</h3></div>{(o.payments||[]).slice(0,10).map((x:any)=><div className="table-row" key={x.id}><div><b>{x.productName||x.purpose||"ReDom payment"}</b><small>{x.reference}</small></div><span>{x.currency} {(Number(x.amountMinor||0)/100).toFixed(2)}</span><em>{x.status}</em></div>)}</section></div>}

function Stars({nav}:{nav:(p:string)=>void}){const[c,setC]=useState<any>(null),[countries,setCountries]=useState<any[]>([]),[packs,setPacks]=useState<any[]>([]),[a,setA]=useState<any[]>([]);useEffect(()=>{Promise.all([api<any>("/orders-payments/stars/catalog"),api<any>("/orders-payments/stars/activity")]).then(([x,y])=>{setC(x.selectedCountry);setCountries(x.countries||[]);setPacks(x.packages||[]);setA(y.activity||[])}).catch(()=>{})},[]);const buy=async(p:any)=>{if(!c)return;try{const r=await api<any>("/orders-payments/stars/initialize",{method:"POST",body:JSON.stringify({packageKey:p.key,countryCode:c.isoCode,email:"",preferredChannel:"card"})});if(r.checkoutUrl)location.href=r.checkoutUrl;else alert("Checkout initialized. Reference: "+(r.reference||""))}catch(e){alert(e instanceof Error?e.message:"Unable to initialize Stars checkout.")}};return <div className="page"><PageHeader title="ReDom Stars" subtitle="Live Stars catalog and checkout." actions={<button className="btn secondary" onClick={()=>nav("orders")}>Back</button>}/><div className="stars-banner"><div><span className="eyebrow">Country</span><h2>{c?.name||"Select country"} <small>{c?.currency||"USD"}</small></h2></div><select value={c?.isoCode||""} onChange={async e=>{const x=await api<any>("/orders-payments/stars/catalog?country="+encodeURIComponent(e.target.value));setC(x.selectedCountry);setPacks(x.packages||[])}}>{countries.map(x=><option key={x.isoCode} value={x.isoCode}>{x.name+" · "+x.currency}</option>)}</select></div><div className="stars-grid">{packs.map(p=><article className={p.popular?"star-card popular":"star-card"} key={p.key}><span className="star-symbol"><StarIcon/></span><h3>{Number(p.stars).toLocaleString()} Stars</h3><b>{p.localAmountFormatted||p.currency+" "+p.localAmount}</b><small>{p.firstPurchaseDiscountPercent?p.firstPurchaseDiscountPercent+"% first-purchase discount":""}</small><button className="btn primary full" disabled={p.payable===false} onClick={()=>void buy(p)}>{p.payable===false?"Unavailable":"Buy Stars"}</button></article>)}</div><section className="table-card"><div className="card-title"><h3>Stars activity</h3></div>{a.slice(0,8).map(x=><div className="table-row" key={x.id}><div><b>{x.type}</b><small>{x.reference||"Stars transaction"}</small></div><span>{x.stars} Stars</span><em>{x.balanceAfter} balance</em></div>)}</section></div>}

function Payments(){const[m,setM]=useState<any[]>([]),[a,setA]=useState<any[]>([]),[s,setS]=useState<any>(null);useEffect(()=>{Promise.all([api<any>("/orders-payments/payment-methods"),api<any>("/orders-payments/payment-addresses"),api<any>("/orders-payments/settings")]).then(([x,y,z])=>{setM(x.methods||[]);setA(y.addresses||[]);setS(z.settings)}).catch(()=>{})},[]);return <div className="page"><PageHeader title="ReDom Pay" subtitle="Payment methods, addresses, security and currency settings."/><div className="payment-methods"><section className="table-card"><div className="card-title"><h3>Payment methods</h3><button className="btn primary" onClick={()=>alert("Add card uses the existing Stripe publishable-key and payment-method setup endpoints from ReDom mobile.")}><PlusIcon/>Add card</button></div>{m.map(x=><div className="method-card" key={x.id}><CardIcon/><div><b>{x.brand||x.bank||"Payment method"} {x.last4?"•••• "+x.last4:""}</b><small>{x.currency||"Default"} · {x.status||"active"}</small></div><ChevronIcon/></div>)}{!m.length?<Empty icon={<CardIcon/>} title="No saved payment methods" text="Add a card to use saved ReDom Pay checkout."/>:null}</section><aside><Card title="Payment settings"><SettingRow icon={<GlobeIcon/>} title="Currency" text={s?.currency||"USD"} action={()=>alert("Currency uses the existing ReDom Pay settings endpoint.")}/><SettingRow icon={<LockIcon/>} title="Security" text="PIN, biometrics and backup methods." action={()=>alert("Security controls use the existing payment-security endpoints.")}/><SettingRow icon={<GlobeIcon/>} title="Payment address" text={a[0]?a[0].address_line1+", "+a[0].city:"Add a payment address"} action={()=>alert("Address management uses /orders-payments/payment-addresses.")}/></Card></aside></div></div>}

function Subscriptions(){const[s,setS]=useState<any[]>([]);useEffect(()=>{api<any>("/orders-payments/subscriptions").then(r=>setS(r.subscriptions||[])).catch(()=>{})},[]);return <div className="page"><PageHeader title="Subscriptions" subtitle="Your ReDom subscription status."/><div className="saved-grid">{s.map(x=><article className="saved-card" key={x.id}><span>{x.subscriptionStatus}</span><h3>{x.subscriptionType}</h3><p>{x.billingCycle}</p><small>{x.expiresAt?"Expires "+new Date(x.expiresAt).toLocaleDateString():"No expiry listed"}</small></article>)}</div>{!s.length?<Empty icon={<CardIcon/>} title="No active subscriptions" text="Your ReDom subscriptions will appear here."/>:null}</div>}

function Support(){const[msg,setMsg]=useState(""),[done,setDone]=useState("");const send=async()=>{if(!msg.trim())return;try{const r=await api<any>("/support/payment-problem",{method:"POST",body:JSON.stringify({description:msg.trim(),email:""})});setDone("Support case created"+(r.caseNumber?": "+r.caseNumber:""));setMsg("")}catch(e){setDone(e instanceof Error?e.message:"Unable to create support case.")}};return <div className="page"><PageHeader title="Help & support" subtitle="Get help with your ReDom account and payments."/><div className="support-grid"><Card title="ReDom Support"><HelpIcon/><p className="muted">Describe your question or problem.</p><textarea value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Tell us what you need help with…"/><button className="btn primary" onClick={()=>void send()}>Send to support</button>{done?<div className="success-box"><CheckIcon/>{done}</div>:null}</Card><Card title="Security"><SettingRow icon={<ShieldIcon/>} title="Account security" text="Authenticated backend session is active." action={()=>alert("Your browser is using a ReDom access token for API calls.")}/></Card></div></div>}

function Terms(){const[p,setP]=useState<any>(null),[slug,setSlug]=useState("terms");useEffect(()=>{api<any>("/product/policies/"+slug).then(setP).catch(()=>{})},[slug]);return <div className="page"><PageHeader title="Terms & policies" subtitle="Policy documents loaded from ReDom's backend."/><div className="policy-tabs">{["terms","privacy","community","messaging","payments","security","ai","refunds"].map(x=><button className={slug===x?"active":""} key={x} onClick={()=>setSlug(x)}>{x}</button>)}</div><article className="policy-card"><span className="eyebrow">{p?.version||"ReDom policy"}</span><h1>{p?.document?.title||"Loading policy…"}</h1><p>{p?.document?.summary||"Policy content is retrieved from the backend."}</p>{(p?.document?.sections||[]).map((x:any,i:number)=><section key={i}><h2>{x.heading}</h2><p>{x.body}</p></section>)}</article></div>}

function Report(){const[d,setD]=useState(""),[cat,setCat]=useState("technical"),[r,setR]=useState("");const send=async()=>{if(!d.trim())return;try{const x=await api<any>("/bug-reports",{method:"POST",body:JSON.stringify({product:"ReDom Web",category:cat,description:d,includeDiagnostics:true,diagnostics:{userAgent:navigator.userAgent,language:navigator.language,online:navigator.onLine}})});setR(x.report?.reportId?"Report ID: "+x.report.reportId:"Report submitted");setD("")}catch(e){setR(e instanceof Error?e.message:"Unable to submit report.")}};return <div className="page"><PageHeader title="Report a problem" subtitle="Send diagnostics and a description to ReDom Support."/><div className="report-card"><label className="field"><span>Product</span><input value="ReDom Web" readOnly/></label><label className="field"><span>Category</span><select value={cat} onChange={e=>setCat(e.target.value)}><option value="technical">Technical</option><option value="account">Account</option><option value="payments">Payments</option><option value="messaging">Messaging</option><option value="other">Other</option></select></label><label className="field"><span>Describe the problem</span><textarea value={d} onChange={e=>setD(e.target.value)} placeholder="Describe what happened…"/></label><button className="btn primary xl" onClick={()=>void send()}>Submit report</button>{r?<div className="success-box"><CheckIcon/>{r}</div>:null}</div></div>}

function SettingsSection({title,desc,children}:{title:string;desc:string;children:any}){return <section className="settings-section"><div><h2>{title}</h2><p>{desc}</p></div><div className="settings-card">{children}</div></section>}

function SettingRow({icon,title,text,action,toggle}:{icon:any;title:string;text:string;action:()=>void;toggle?:boolean}){return <button className="setting-row" onClick={action}><span className="setting-icon">{icon}</span><span><b>{title}</b><small>{text}</small></span>{toggle!==undefined?<span className="switch"><i className={toggle?"on":""}/></span>:<ChevronIcon/>}</button>}
