export type WebRoute = { key: string; category: string; title: string; path: string; description: string };

export const WEB_SCREEN_REGISTRY: WebRoute[] = [
  { key: "Login", category: "Authentication", title: "Sign in to ReDom", path: "/app/login", description: "Mobile parity reference for the sign in to ReDom screen, aligned with the current ReDom mobile screen reference." },
  { key: "FindAccount", category: "Authentication", title: "Find an existing ReDom account", path: "/app/findAccount", description: "Mobile parity reference for the find account screen, aligned with the current ReDom mobile screen reference." },
  { key: "DeviceVerification", category: "Authentication", title: "Verify a new browser or device", path: "/app/deviceVerification", description: "Mobile parity reference for device verification." },
  { key: "LoginTwoFactor", category: "Authentication", title: "Complete two-factor authentication", path: "/app/loginTwoFactor", description: "Mobile parity reference for two-factor authentication." },
  { key: "RegistrationWelcome", category: "Registration", title: "Start protected registration", path: "/app/registrationWelcome", description: "Mobile parity reference for registration welcome." },
  { key: "RegistrationIdentity", category: "Registration", title: "Enter account identity", path: "/app/registrationIdentity", description: "Mobile parity reference for registration identity." },
  { key: "RegistrationBirthday", category: "Registration", title: "Enter date of birth", path: "/app/registrationBirthday", description: "Mobile parity reference for registration birthday." },
  { key: "RegistrationGender", category: "Registration", title: "Choose identity and pronouns", path: "/app/registrationGender", description: "Mobile parity reference for registration gender." },
  { key: "RegistrationPhone", category: "Registration", title: "Add and verify mobile number", path: "/app/registrationPhone", description: "Mobile parity reference for registration phone." },
  { key: "RegistrationEmail", category: "Registration", title: "Add email address", path: "/app/registrationEmail", description: "Mobile parity reference for registration email." },
  { key: "RegistrationPassword", category: "Registration", title: "Create a strong password", path: "/app/registrationPassword", description: "Mobile parity reference for registration password." },
  { key: "RegistrationReview", category: "Registration", title: "Review account details and policies", path: "/app/registrationReview", description: "Mobile parity reference for registration review." },
  { key: "RegistrationVerification", category: "Registration", title: "Verify registration code", path: "/app/registrationVerification", description: "Mobile parity reference for registration verification." },
  { key: "CustomizingExperience", category: "Registration", title: "Prepare account and session", path: "/app/customizingExperience", description: "Mobile parity reference for account customization." },
  { key: "HomeFeed", category: "Core", title: "Home Feed", path: "/app/homeFeed", description: "Mobile parity reference for the ReDom Home Feed." },
  { key: "Profile", category: "Core", title: "Profile", path: "/app/profile", description: "Mobile parity reference for the ReDom profile." },
  { key: "EditProfile", category: "Profile", title: "Edit profile", path: "/app/editProfile", description: "Mobile parity reference for editing profile information." },
  { key: "EditBio", category: "Profile", title: "Edit biography", path: "/app/editBio", description: "Mobile parity reference for editing a biography." },
  { key: "EditLocationSearch", category: "Profile", title: "Search location", path: "/app/editLocationSearch", description: "Mobile parity reference for location search." },
  { key: "EditLocationConfirm", category: "Profile", title: "Confirm location", path: "/app/editLocationConfirm", description: "Mobile parity reference for confirming a location." },
  { key: "EditBirthday", category: "Profile", title: "Edit birthday", path: "/app/editBirthday", description: "Mobile parity reference for editing birthday." },
  { key: "ProfilePictureAdjust", category: "Profile", title: "Adjust profile picture", path: "/app/profilePictureAdjust", description: "Mobile parity reference for profile picture adjustment." },
  { key: "ProfilePicturePreview", category: "Profile", title: "Preview profile picture", path: "/app/profilePicturePreview", description: "Mobile parity reference for profile picture preview." },
  { key: "ProfilePictureViewer", category: "Profile", title: "View profile picture", path: "/app/profilePictureViewer", description: "Mobile parity reference for profile picture viewer." },
  { key: "CoverPhotoAdjust", category: "Profile", title: "Adjust cover photo", path: "/app/coverPhotoAdjust", description: "Mobile parity reference for cover photo adjustment." },
  { key: "CoverPhotoPreview", category: "Profile", title: "Preview cover photo", path: "/app/coverPhotoPreview", description: "Mobile parity reference for cover photo preview." },
  { key: "CoverPhotoViewer", category: "Profile", title: "View cover photo", path: "/app/coverPhotoViewer", description: "Mobile parity reference for cover photo viewer." },
  { key: "Foundation", category: "Core", title: "ReDom Foundation", path: "/app/foundation", description: "Mobile parity reference for the ReDom Foundation." },
  { key: "Search", category: "Core", title: "Search ReDom", path: "/app/search", description: "Mobile parity reference for ReDom search." },
  { key: "Notifications", category: "Core", title: "Notifications", path: "/app/notifications", description: "Mobile parity reference for notifications." },
  { key: "Messages", category: "Messaging", title: "Messages", path: "/app/messages", description: "Mobile parity reference for messages." },
  { key: "Saved", category: "Content", title: "Saved", path: "/app/saved", description: "Mobile parity reference for saved content." },
  { key: "Marketplace", category: "Commerce", title: "Marketplace", path: "/app/marketplace", description: "Mobile parity reference for Marketplace." },
  { key: "Groups", category: "Groups", title: "Groups", path: "/app/groups", description: "Mobile parity reference for groups." },
  { key: "Friends", category: "Social", title: "Friends", path: "/app/friends", description: "Mobile parity reference for friends." },
  { key: "Events", category: "Social", title: "Events", path: "/app/events", description: "Mobile parity reference for events." },
  { key: "ReDomAI", category: "AI", title: "ReDom AI", path: "/app/reDomAI", description: "Mobile parity reference for ReDom AI." },
  { key: "ReDomVideoStudio", category: "AI", title: "ReDom Video Studio", path: "/app/reDomVideoStudio", description: "Create videos, movies, episodic stories and cartoons with automatic prompt-language captions." },
  { key: "ReDomAIInfo", category: "AI", title: "About ReDom AI", path: "/app/reDomAIInfo", description: "Mobile parity reference for ReDom AI information." },
  { key: "ReDomAIPolicy", category: "AI", title: "ReDom AI Policy", path: "/app/reDomAIPolicy", description: "Mobile parity reference for the ReDom AI policy." },
  { key: "Chat", category: "Messaging", title: "Chat", path: "/app/chat", description: "Mobile parity reference for chat." },
  { key: "ChatContactInfo", category: "Messaging", title: "Chat contact information", path: "/app/chatContactInfo", description: "Mobile parity reference for chat contact information." },
  { key: "ChatEncryptionVerification", category: "Messaging", title: "Chat encryption verification", path: "/app/chatEncryptionVerification", description: "Mobile parity reference for chat encryption verification." },
  { key: "ChatMediaGallery", category: "Messaging", title: "Chat media gallery", path: "/app/chatMediaGallery", description: "Mobile parity reference for chat media gallery." },
  { key: "AddToGroups", category: "Groups", title: "Add member to groups", path: "/app/addToGroups", description: "Mobile parity reference for adding a member to groups." },
  { key: "Call", category: "Calling", title: "Call", path: "/app/call", description: "Mobile parity reference for voice and video calling." },
  { key: "CallLinkJoin", category: "Calling", title: "Join call link", path: "/app/callLinkJoin", description: "Mobile parity reference for joining a call link." },
  { key: "CreateGroup", category: "Groups", title: "Create group", path: "/app/createGroup", description: "Mobile parity reference for creating a group." },
  { key: "CreatePublicGroup", category: "Groups", title: "Create public group", path: "/app/createPublicGroup", description: "Mobile parity reference for creating a public group." },
  { key: "GroupInfo", category: "Groups", title: "Group information", path: "/app/groupInfo", description: "Mobile parity reference for group information." },
  { key: "GroupPermissions", category: "Groups", title: "Group permissions", path: "/app/groupPermissions", description: "Mobile parity reference for group permissions." },
  { key: "GroupInvite", category: "Groups", title: "Group invite", path: "/app/groupInvite", description: "Mobile parity reference for group invitations." },
  { key: "GroupMemberChanges", category: "Groups", title: "Group member changes", path: "/app/groupMemberChanges", description: "Mobile parity reference for group member changes." },
  { key: "GroupAddMembers", category: "Groups", title: "Add group members", path: "/app/groupAddMembers", description: "Mobile parity reference for adding group members." },
  { key: "GroupSettings", category: "Groups", title: "Group settings", path: "/app/groupSettings", description: "Mobile parity reference for group settings." },
  { key: "GroupIcon", category: "Groups", title: "Group icon", path: "/app/groupIcon", description: "Mobile parity reference for group icon management." },
  { key: "GroupPrivacyInfo", category: "Groups", title: "Group privacy", path: "/app/groupPrivacyInfo", description: "Mobile parity reference for group privacy." },
  { key: "GroupAdmins", category: "Groups", title: "Group admins", path: "/app/groupAdmins", description: "Mobile parity reference for group administrators." },
  { key: "ScheduleGroupCall", category: "Calling", title: "Schedule group call", path: "/app/scheduleGroupCall", description: "Mobile parity reference for scheduling a group call." },
  { key: "GroupReport", category: "Groups", title: "Report group", path: "/app/groupReport", description: "Mobile parity reference for reporting a group." },
  { key: "Settings", category: "Settings", title: "Settings", path: "/app/settings", description: "Mobile parity reference for Settings." },
  { key: "Language", category: "Settings", title: "Language", path: "/app/language", description: "Mobile parity reference for language settings." },
  { key: "DarkMode", category: "Settings", title: "Dark mode", path: "/app/darkMode", description: "Mobile parity reference for dark mode." },
  { key: "NotificationSettings", category: "Settings", title: "Notification settings", path: "/app/notificationSettings", description: "Mobile parity reference for notification settings." },
  { key: "PrivacySettings", category: "Settings", title: "Privacy settings", path: "/app/privacySettings", description: "Mobile parity reference for privacy settings." },
  { key: "SecuritySettings", category: "Security", title: "Security settings", path: "/app/securitySettings", description: "Mobile parity reference for security settings." },
  { key: "LinkedDevices", category: "Security", title: "Linked devices", path: "/app/linkedDevices", description: "Mobile parity reference for linked devices." },
  { key: "LinkDevice", category: "Security", title: "Link a device", path: "/app/linkDevice", description: "Mobile parity reference for linking a device." },
  { key: "LinkHistory", category: "Security", title: "Link history", path: "/app/linkHistory", description: "Mobile parity reference for link history." },
  { key: "OrdersPayments", category: "Payments", title: "Orders and Payments", path: "/app/ordersPayments", description: "Mobile parity reference for Orders and Payments." },
  { key: "ReDomPayTransactions", category: "Payments", title: "ReDom Pay transactions", path: "/app/reDomPayTransactions", description: "Mobile parity reference for ReDom Pay transactions." },
  { key: "ReDomPayManage", category: "Payments", title: "ReDom Pay manage", path: "/app/reDomPayManage", description: "Mobile parity reference for managing ReDom Pay." },
  { key: "PaymentTransactionDetails", category: "Payments", title: "Payment transaction details", path: "/app/paymentTransactionDetails", description: "Mobile parity reference for payment transaction details." },
  { key: "RefundCase", category: "Payments", title: "Refund case", path: "/app/refundCase", description: "Mobile parity reference for refund cases." },
  { key: "PaymentMethods", category: "Payments", title: "Payment methods", path: "/app/paymentMethods", description: "Mobile parity reference for payment methods." },
  { key: "AddPaymentMethod", category: "Payments", title: "Add payment method", path: "/app/addPaymentMethod", description: "Mobile parity reference for adding a payment method." },
  { key: "AddCard", category: "Payments", title: "Add card", path: "/app/addCard", description: "Mobile parity reference for adding a card." },
  { key: "ReviewPaymentInfo", category: "Payments", title: "Review payment information", path: "/app/reviewPaymentInfo", description: "Mobile parity reference for reviewing payment information." },
  { key: "SavedProducts", category: "Commerce", title: "Saved products", path: "/app/savedProducts", description: "Mobile parity reference for saved products." },
  { key: "Cart", category: "Commerce", title: "Cart", path: "/app/cart", description: "Mobile parity reference for the shopping cart." },
  { key: "StarsActivity", category: "Payments", title: "ReDom Stars activity", path: "/app/starsActivity", description: "Mobile parity reference for ReDom Stars activity." },
  { key: "BuyStars", category: "Payments", title: "Buy ReDom Stars", path: "/app/buyStars", description: "Mobile parity reference for buying ReDom Stars." },
  { key: "StarsCheckout", category: "Payments", title: "Stars checkout", path: "/app/starsCheckout", description: "Mobile parity reference for ReDom Stars checkout." },
  { key: "Subscriptions", category: "Payments", title: "Subscriptions", path: "/app/subscriptions", description: "Mobile parity reference for subscriptions." },
  { key: "SubscriptionDetails", category: "Payments", title: "Subscription details", path: "/app/subscriptionDetails", description: "Mobile parity reference for subscription details." },
  { key: "PaymentSecurity", category: "Payments", title: "Payment security", path: "/app/paymentSecurity", description: "Mobile parity reference for payment security." },
  { key: "PaymentPin", category: "Payments", title: "Payment PIN", path: "/app/paymentPin", description: "Mobile parity reference for payment PIN." },
  { key: "PaymentAddresses", category: "Payments", title: "Payment addresses", path: "/app/paymentAddresses", description: "Mobile parity reference for payment addresses." },
  { key: "PaymentCurrency", category: "Payments", title: "Payment currency", path: "/app/paymentCurrency", description: "Mobile parity reference for payment currency." },
  { key: "BlockedUsers", category: "Privacy", title: "Blocked users", path: "/app/blockedUsers", description: "Mobile parity reference for blocked users." },
  { key: "Verification", category: "Security", title: "Account verification", path: "/app/verification", description: "Mobile parity reference for account verification." },
  { key: "Support", category: "Support", title: "Help and Support", path: "/app/support", description: "Mobile parity reference for Help and Support." },
  { key: "MetaPaySupport", category: "Payments", title: "Payment support", path: "/app/metaPaySupport", description: "Mobile parity reference for payment support." },
  { key: "MetaPayArticle", category: "Payments", title: "Payment support article", path: "/app/metaPayArticle", description: "Mobile parity reference for payment support articles." },
  { key: "PayoutSupport", category: "Payments", title: "Payout support", path: "/app/payoutSupport", description: "Mobile parity reference for payout support." },
  { key: "SupportInbox", category: "Support", title: "Support inbox", path: "/app/supportInbox", description: "Mobile parity reference for the support inbox." },
  { key: "SupportMessage", category: "Support", title: "Support message", path: "/app/supportMessage", description: "Mobile parity reference for support messages." },
  { key: "SubscriptionRenewal", category: "Payments", title: "Subscription renewal", path: "/app/subscriptionRenewal", description: "Mobile parity reference for subscription renewal." },
  { key: "SelectCurrency", category: "Payments", title: "Select currency", path: "/app/selectCurrency", description: "Mobile parity reference for currency selection." },
  { key: "ReportProblem", category: "Support", title: "Report a problem", path: "/app/reportProblem", description: "Mobile parity reference for reporting a problem." },
  { key: "TermsPolicies", category: "Policies", title: "Terms and Policies", path: "/app/termsPolicies", description: "Mobile parity reference for Terms and Policies." },
  { key: "Policy", category: "Policies", title: "Policy", path: "/app/policy", description: "Mobile parity reference for individual policy documents." },
];

