import type { LanguageCode } from "./language";

type Vars = Record<string, string>;
type Messages = Record<string, string>;

const messages: Partial<Record<LanguageCode, Messages>> = {
  en: {
    networkNotice: "By proceeding you agree to {provider} Terms and Conditions, which includes letting ReDom request and receive your phone number.",
    networkTermsFallback: "Your Network Provider Terms",
    deviceInit: "Unable to initialize this device.", loginFailed: "Login failed. Please try again.", loginIncomplete: "Login could not be completed.", providerOpenFailed: "Unable to open your network provider's website.",
    recoveryNext: "Password recovery is being connected next.", findPrompt: "Enter your mobile number or email address.", findFallback: "If the account exists, recovery instructions have been sent.", findFailed: "Unable to find your account.",
    verifyDevice: "Verify this device", verificationSent: "We sent a {channel} to {target}. Enter the verification code to finish signing in.", verify: "Verify device", expires: "Code expires in {time}", expired: "This code has expired.", backLogin: "Back to Login", verificationWrong: "The verification code is incorrect.", verificationFailed: "Verification failed. Please try again.",
    nameMin: "{name} must be at least 3 characters.", nameUnsupported: "{name} contains unsupported characters.", nameLetters: "{name} must contain letters.", namePunctuation: "{name} has invalid punctuation.", nameReal: "Enter the {name} you use in real life.", nameSaved: "Your name is securely saved to this registration flow.", nameSaveFailed: "Unable to save your name. Please try again.",
    foundationSubtitle: "Your authenticated ReDom app shell is ready.", welcome: "Welcome", logout: "Log out",
    progress1: "Account creation progress, step 1 of 6", progress2: "Account creation progress, step 2 of 6",
  },
  es: {
    networkNotice: "Al continuar, aceptas los Términos y condiciones de {provider}, lo que incluye permitir que ReDom solicite y reciba tu número de teléfono.",
    networkTermsFallback: "Términos de tu operador de red", deviceInit: "No se pudo inicializar este dispositivo.", loginFailed: "No se pudo iniciar sesión. Inténtalo de nuevo.", loginIncomplete: "No se pudo completar el inicio de sesión.", providerOpenFailed: "No se pudo abrir el sitio web de tu operador de red.", recoveryNext: "La recuperación de contraseña se conectará próximamente.",
    findPrompt: "Introduce tu número móvil o correo electrónico.", findFallback: "Si la cuenta existe, se han enviado instrucciones de recuperación.", findFailed: "No se pudo encontrar tu cuenta.", verifyDevice: "Verifica este dispositivo", verificationSent: "Enviamos un {channel} a {target}. Introduce el código de verificación para terminar de iniciar sesión.", verify: "Verificar dispositivo", expires: "El código caduca en {time}", expired: "Este código ha caducado.", backLogin: "Volver a iniciar sesión", verificationWrong: "El código de verificación es incorrecto.", verificationFailed: "La verificación falló. Inténtalo de nuevo.",
    nameMin: "{name} debe tener al menos 3 caracteres.", nameUnsupported: "{name} contiene caracteres no compatibles.", nameLetters: "{name} debe contener letras.", namePunctuation: "{name} tiene puntuación no válida.", nameReal: "Introduce el {name} que usas en la vida real.", nameSaved: "Tu nombre se ha guardado de forma segura en este flujo de registro.", nameSaveFailed: "No se pudo guardar tu nombre. Inténtalo de nuevo.", foundationSubtitle: "La base autenticada de tu aplicación ReDom está lista.", welcome: "Bienvenido", logout: "Cerrar sesión", progress1: "Progreso de creación de cuenta, paso 1 de 6", progress2: "Progreso de creación de cuenta, paso 2 de 6",
  },
  fr: { networkNotice: "En continuant, vous acceptez les conditions de {provider}, notamment l'autorisation pour ReDom de demander et recevoir votre numéro de téléphone.", deviceInit: "Impossible d'initialiser cet appareil.", loginFailed: "Connexion impossible. Réessayez.", loginIncomplete: "La connexion n'a pas pu être terminée.", recoveryNext: "La récupération du mot de passe sera connectée prochainement.", findPrompt: "Saisissez votre numéro de mobile ou votre adresse e-mail.", findFailed: "Impossible de trouver votre compte.", verifyDevice: "Vérifier cet appareil", verificationWrong: "Le code de vérification est incorrect.", verificationFailed: "Échec de la vérification. Réessayez.", verify: "Vérifier l'appareil", expired: "Ce code a expiré.", backLogin: "Retour à la connexion", nameSaved: "Votre nom est enregistré en toute sécurité dans ce flux d'inscription.", nameSaveFailed: "Impossible d'enregistrer votre nom. Réessayez.", logout: "Se déconnecter", welcome: "Bienvenue", foundationSubtitle: "Votre espace ReDom authentifié est prêt." },
  de: { networkNotice: "Mit dem Fortfahren stimmst du den Bedingungen von {provider} zu, einschließlich der Erlaubnis für ReDom, deine Telefonnummer anzufordern und zu erhalten.", deviceInit: "Dieses Gerät konnte nicht initialisiert werden.", loginFailed: "Anmeldung fehlgeschlagen. Bitte versuche es erneut.", loginIncomplete: "Die Anmeldung konnte nicht abgeschlossen werden.", recoveryNext: "Die Passwortwiederherstellung wird als Nächstes verbunden.", findPrompt: "Gib deine Handynummer oder E-Mail-Adresse ein.", findFailed: "Dein Konto konnte nicht gefunden werden.", verifyDevice: "Dieses Gerät bestätigen", verificationWrong: "Der Bestätigungscode ist falsch.", verificationFailed: "Bestätigung fehlgeschlagen. Bitte versuche es erneut.", verify: "Gerät bestätigen", expired: "Dieser Code ist abgelaufen.", backLogin: "Zurück zur Anmeldung", nameSaved: "Dein Name wurde sicher in diesem Registrierungsablauf gespeichert.", nameSaveFailed: "Dein Name konnte nicht gespeichert werden. Bitte versuche es erneut.", logout: "Abmelden", welcome: "Willkommen", foundationSubtitle: "Deine authentifizierte ReDom-App ist bereit." },
  pt: { networkNotice: "Ao continuar, você concorda com os Termos e Condições da {provider}, incluindo permitir que a ReDom solicite e receba seu número de telefone.", deviceInit: "Não foi possível inicializar este dispositivo.", loginFailed: "Não foi possível entrar. Tente novamente.", loginIncomplete: "Não foi possível concluir o login.", recoveryNext: "A recuperação de senha será conectada em seguida.", findPrompt: "Digite seu número de celular ou e-mail.", findFailed: "Não foi possível encontrar sua conta.", verifyDevice: "Verificar este dispositivo", verificationWrong: "O código de verificação está incorreto.", verificationFailed: "Falha na verificação. Tente novamente.", verify: "Verificar dispositivo", expired: "Este código expirou.", backLogin: "Voltar ao login", nameSaved: "Seu nome foi salvo com segurança neste fluxo de cadastro.", nameSaveFailed: "Não foi possível salvar seu nome. Tente novamente.", logout: "Sair", welcome: "Bem-vindo", foundationSubtitle: "Seu aplicativo ReDom autenticado está pronto." },
  it: { deviceInit: "Impossibile inizializzare questo dispositivo.", loginFailed: "Accesso non riuscito. Riprova.", loginIncomplete: "Non è stato possibile completare l'accesso.", recoveryNext: "Il recupero della password verrà collegato successivamente.", findPrompt: "Inserisci il numero di cellulare o l'e-mail.", findFailed: "Impossibile trovare il tuo account.", verifyDevice: "Verifica questo dispositivo", verificationWrong: "Il codice di verifica non è corretto.", verificationFailed: "Verifica non riuscita. Riprova.", verify: "Verifica dispositivo", expired: "Questo codice è scaduto.", backLogin: "Torna al login", nameSaved: "Il tuo nome è stato salvato in modo sicuro in questo flusso di registrazione.", nameSaveFailed: "Impossibile salvare il nome. Riprova.", logout: "Esci", welcome: "Benvenuto", foundationSubtitle: "La tua app ReDom autenticata è pronta." },
  nl: { deviceInit: "Dit apparaat kan niet worden geïnitialiseerd.", loginFailed: "Inloggen mislukt. Probeer het opnieuw.", loginIncomplete: "Inloggen kon niet worden voltooid.", recoveryNext: "Wachtwoordherstel wordt hierna verbonden.", findPrompt: "Voer je mobiele nummer of e-mailadres in.", findFailed: "Je account kon niet worden gevonden.", verifyDevice: "Dit apparaat verifiëren", verificationWrong: "De verificatiecode is onjuist.", verificationFailed: "Verificatie mislukt. Probeer het opnieuw.", verify: "Apparaat verifiëren", expired: "Deze code is verlopen.", backLogin: "Terug naar inloggen", nameSaved: "Je naam is veilig opgeslagen in deze registratieflow.", nameSaveFailed: "Je naam kon niet worden opgeslagen. Probeer het opnieuw.", logout: "Uitloggen", welcome: "Welkom", foundationSubtitle: "Je geauthenticeerde ReDom-app is klaar." },
  ar: { deviceInit: "تعذر تهيئة هذا الجهاز.", loginFailed: "تعذر تسجيل الدخول. حاول مرة أخرى.", loginIncomplete: "تعذر إكمال تسجيل الدخول.", recoveryNext: "سيتم ربط استرداد كلمة المرور لاحقًا.", findPrompt: "أدخل رقم هاتفك المحمول أو بريدك الإلكتروني.", findFailed: "تعذر العثور على حسابك.", verifyDevice: "تحقق من هذا الجهاز", verificationWrong: "رمز التحقق غير صحيح.", verificationFailed: "فشل التحقق. حاول مرة أخرى.", verify: "التحقق من الجهاز", expired: "انتهت صلاحية هذا الرمز.", backLogin: "العودة إلى تسجيل الدخول", nameSaved: "تم حفظ اسمك بأمان في تدفق التسجيل هذا.", nameSaveFailed: "تعذر حفظ اسمك. حاول مرة أخرى.", logout: "تسجيل الخروج", welcome: "مرحبًا", foundationSubtitle: "تطبيق ReDom الموثق جاهز." },
  zh: { deviceInit: "无法初始化此设备。", loginFailed: "登录失败，请重试。", loginIncomplete: "无法完成登录。", recoveryNext: "密码恢复功能即将接入。", findPrompt: "请输入手机号码或电子邮箱。", findFailed: "找不到你的账户。", verifyDevice: "验证此设备", verificationWrong: "验证码不正确。", verificationFailed: "验证失败，请重试。", verify: "验证设备", expired: "此验证码已过期。", backLogin: "返回登录", nameSaved: "你的姓名已安全保存到此注册流程。", nameSaveFailed: "无法保存姓名，请重试。", logout: "退出登录", welcome: "欢迎", foundationSubtitle: "你的 ReDom 已验证应用已准备就绪。" },
  ja: { deviceInit: "このデバイスを初期化できません。", loginFailed: "ログインに失敗しました。もう一度お試しください。", loginIncomplete: "ログインを完了できませんでした。", recoveryNext: "パスワード復旧機能は次に接続されます。", findPrompt: "携帯電話番号またはメールアドレスを入力してください。", findFailed: "アカウントが見つかりませんでした。", verifyDevice: "このデバイスを確認", verificationWrong: "確認コードが正しくありません。", verificationFailed: "確認に失敗しました。もう一度お試しください。", verify: "デバイスを確認", expired: "このコードは期限切れです。", backLogin: "ログインに戻る", nameSaved: "名前がこの登録フローに安全に保存されました。", nameSaveFailed: "名前を保存できませんでした。もう一度お試しください。", logout: "ログアウト", welcome: "ようこそ", foundationSubtitle: "認証済みのReDomアプリが準備できました。" },
  ko: { deviceInit: "이 기기를 초기화할 수 없습니다.", loginFailed: "로그인하지 못했습니다. 다시 시도하세요.", loginIncomplete: "로그인을 완료할 수 없습니다.", recoveryNext: "비밀번호 복구 기능은 다음 단계에서 연결됩니다.", findPrompt: "휴대폰 번호 또는 이메일을 입력하세요.", findFailed: "계정을 찾을 수 없습니다.", verifyDevice: "이 기기 확인", verificationWrong: "인증 코드가 올바르지 않습니다.", verificationFailed: "인증에 실패했습니다. 다시 시도하세요.", verify: "기기 확인", expired: "이 코드는 만료되었습니다.", backLogin: "로그인으로 돌아가기", nameSaved: "이름이 이 가입 흐름에 안전하게 저장되었습니다.", nameSaveFailed: "이름을 저장하지 못했습니다. 다시 시도하세요.", logout: "로그아웃", welcome: "환영합니다", foundationSubtitle: "인증된 ReDom 앱이 준비되었습니다." },
  hi: { deviceInit: "इस डिवाइस को प्रारंभ नहीं किया जा सका।", loginFailed: "लॉगिन विफल हुआ। फिर से प्रयास करें।", loginIncomplete: "लॉगिन पूरा नहीं किया जा सका।", recoveryNext: "पासवर्ड रिकवरी अगला कनेक्ट किया जाएगा।", findPrompt: "अपना मोबाइल नंबर या ईमेल दर्ज करें।", findFailed: "आपका खाता नहीं मिला।", verifyDevice: "इस डिवाइस की पुष्टि करें", verificationWrong: "सत्यापन कोड गलत है।", verificationFailed: "सत्यापन विफल हुआ। फिर से प्रयास करें।", verify: "डिवाइस सत्यापित करें", expired: "यह कोड समाप्त हो गया है।", backLogin: "लॉगिन पर वापस जाएँ", nameSaved: "आपका नाम इस पंजीकरण प्रवाह में सुरक्षित रूप से सहेजा गया है।", nameSaveFailed: "नाम सहेजा नहीं जा सका। फिर से प्रयास करें।", logout: "लॉग आउट", welcome: "स्वागत है", foundationSubtitle: "आपका प्रमाणित ReDom ऐप तैयार है।" },
  ru: { deviceInit: "Не удалось инициализировать это устройство.", loginFailed: "Не удалось войти. Попробуйте ещё раз.", loginIncomplete: "Не удалось завершить вход.", recoveryNext: "Восстановление пароля будет подключено далее.", findPrompt: "Введите номер телефона или адрес электронной почты.", findFailed: "Не удалось найти ваш аккаунт.", verifyDevice: "Подтвердите это устройство", verificationWrong: "Неверный код подтверждения.", verificationFailed: "Ошибка проверки. Попробуйте ещё раз.", verify: "Подтвердить устройство", expired: "Срок действия кода истёк.", backLogin: "Вернуться ко входу", nameSaved: "Ваше имя безопасно сохранено в этом процессе регистрации.", nameSaveFailed: "Не удалось сохранить имя. Попробуйте ещё раз.", logout: "Выйти", welcome: "Добро пожаловать", foundationSubtitle: "Ваше авторизованное приложение ReDom готово." },
  tr: { deviceInit: "Bu cihaz başlatılamadı.", loginFailed: "Giriş başarısız. Lütfen tekrar deneyin.", loginIncomplete: "Giriş tamamlanamadı.", recoveryNext: "Şifre kurtarma sonraki adımda bağlanacak.", findPrompt: "Cep telefonu numaranızı veya e-postanızı girin.", findFailed: "Hesabınız bulunamadı.", verifyDevice: "Bu cihazı doğrula", verificationWrong: "Doğrulama kodu yanlış.", verificationFailed: "Doğrulama başarısız. Tekrar deneyin.", verify: "Cihazı doğrula", expired: "Bu kodun süresi doldu.", backLogin: "Girişe dön", nameSaved: "Adınız bu kayıt akışına güvenli şekilde kaydedildi.", nameSaveFailed: "Adınız kaydedilemedi. Lütfen tekrar deneyin.", logout: "Çıkış yap", welcome: "Hoş geldiniz", foundationSubtitle: "Kimliği doğrulanmış ReDom uygulamanız hazır." },
};

export function uiMessage(language: LanguageCode, key: string, vars: Vars = {}) {
  const value = messages[language]?.[key] ?? messages.en?.[key] ?? key;
  return value.replace(/\{(\w+)\}/g, (_, name) => vars[name] ?? `{${name}}`);
}
