import { Router } from "express";
import { authController } from "../controllers/auth.controller";
import { passwordRecoveryController } from "../controllers/password-recovery.controller";
import { networkProviderController } from "../controllers/network-provider.controller";
import { registrationChallengeController } from "../controllers/registration-challenge.controller";
import { registrationFlowController } from "../controllers/registration-flow.controller";
import { registrationFlowEmailController } from "../controllers/registration-flow-email.controller";
import { registrationFlowPasswordController } from "../controllers/registration-flow-password.controller";
import { registrationVerificationController } from "../controllers/registration-verification.controller";
import { registrationInitializationController } from "../controllers/registration-initialization.controller";
import { pendingRegistrationController } from "../controllers/pending-registration.controller";
import { totpController } from "../controllers/totp.controller";
import { authMiddleware } from "../middleware/auth.middleware";
import { authRateLimit, networkProviderRateLimit, passwordResetRateLimit, registrationRateLimit, registrationVerificationRateLimit, verificationRateLimit } from "../middleware/rate-limit.middleware";
const router = Router();
router.get("/network-provider", networkProviderRateLimit, networkProviderController.get.bind(networkProviderController));
router.post("/register", registrationRateLimit, authController.register.bind(authController));
router.post("/register/flow", registrationRateLimit, registrationFlowController.reserve.bind(registrationFlowController));
router.get("/register/flow/:reservationId/memory", registrationRateLimit, registrationFlowController.getMemory.bind(registrationFlowController));
router.patch("/register/flow/:reservationId/name", registrationRateLimit, registrationFlowController.saveName.bind(registrationFlowController));
router.patch("/register/flow/:reservationId/birthday", registrationRateLimit, registrationFlowController.saveBirthday.bind(registrationFlowController));
router.patch("/register/flow/:reservationId/gender", registrationRateLimit, registrationFlowController.saveGender.bind(registrationFlowController));
router.get("/register/flow/:reservationId/phone-country", registrationRateLimit, registrationFlowController.detectPhoneCountry.bind(registrationFlowController));
router.patch("/register/flow/:reservationId/phone", registrationRateLimit, registrationFlowController.savePhone.bind(registrationFlowController));
router.get("/register/flow/:reservationId/security", registrationRateLimit, registrationFlowController.inspectSecurity.bind(registrationFlowController));
router.post("/register/flow/:reservationId/security/consent", registrationRateLimit, registrationFlowController.consentSecurity.bind(registrationFlowController));
router.patch("/register/flow/:reservationId/email", registrationRateLimit, registrationFlowEmailController.save.bind(registrationFlowEmailController));
router.patch("/register/flow/:reservationId/password", registrationRateLimit, registrationFlowPasswordController.save.bind(registrationFlowPasswordController));
router.post("/register/challenge", registrationRateLimit, registrationChallengeController.start.bind(registrationChallengeController));
router.get("/register/challenge/:challengeId", registrationRateLimit, registrationChallengeController.getFlow.bind(registrationChallengeController));
router.patch("/register/challenge/:challengeId", registrationRateLimit, registrationChallengeController.saveStep.bind(registrationChallengeController));
router.post("/register/challenge/:challengeId/complete", registrationRateLimit, registrationChallengeController.complete.bind(registrationChallengeController));
router.post("/register/verification/:verificationChallengeId/verify", registrationVerificationRateLimit, registrationChallengeController.verify.bind(registrationChallengeController));
router.post("/register/verification/:verificationChallengeId/resend", registrationVerificationRateLimit, registrationVerificationController.resend.bind(registrationVerificationController));
router.post("/register/verification/:verificationChallengeId/switch-contact", registrationVerificationRateLimit, registrationVerificationController.switchContact.bind(registrationVerificationController));
router.post("/register/initialize", registrationRateLimit, registrationInitializationController.initialize.bind(registrationInitializationController));
router.post("/pending-registration/options", passwordResetRateLimit, pendingRegistrationController.options.bind(pendingRegistrationController));
router.post("/pending-registration/send", passwordResetRateLimit, pendingRegistrationController.sendCode.bind(pendingRegistrationController));
router.post("/pending-registration/invalidate", verificationRateLimit, pendingRegistrationController.verifyAndInvalidate.bind(pendingRegistrationController));
router.post("/login", authRateLimit, authController.login.bind(authController));
router.post("/verify-login-device", verificationRateLimit, authController.verifyLoginDevice.bind(authController));
router.post("/verify-login-2fa", verificationRateLimit, authController.verifyLoginTwoFactor.bind(authController));
router.post("/verify-email", verificationRateLimit, authController.verifyEmail.bind(authController));
router.post("/verify-phone", verificationRateLimit, authController.verifyPhone.bind(authController));
router.post("/resend-email-code", verificationRateLimit, authController.resendEmailCode.bind(authController));
router.post("/resend-phone-code", verificationRateLimit, authController.resendPhoneCode.bind(authController));
router.post("/find-account", passwordResetRateLimit, passwordRecoveryController.findAccount.bind(passwordRecoveryController));
router.post("/password-reset/send", passwordResetRateLimit, passwordRecoveryController.sendCode.bind(passwordRecoveryController));
router.post("/password-reset/verify", verificationRateLimit, passwordRecoveryController.verifyCode.bind(passwordRecoveryController));
router.post("/password-reset/change", passwordResetRateLimit, passwordRecoveryController.changePassword.bind(passwordRecoveryController));
router.post("/forgot-password", passwordResetRateLimit, authController.forgotPassword.bind(authController));
router.post("/reset-password", passwordResetRateLimit, authController.resetPassword.bind(authController));
router.post("/logout", authMiddleware, authController.logout.bind(authController));
router.post("/refresh", authRateLimit, authController.refreshSession.bind(authController));
router.post("/security/2fa/authenticator/setup", authMiddleware, authRateLimit, totpController.beginSetup.bind(totpController));
router.post("/security/2fa/authenticator/confirm", authMiddleware, verificationRateLimit, totpController.confirmSetup.bind(totpController));
router.post("/security/2fa/authenticator/recovery-code", authMiddleware, verificationRateLimit, totpController.useRecoveryCode.bind(totpController));
export default router;