import { randomBytes } from "node:crypto";
import { Router } from "express";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { authMiddleware } from "../middleware/auth.middleware";
import { db, pool } from "../database/db";
import { calls } from "../database/calls";
import { conversationParticipants } from "../database/conversationParticipants";
import { userProfiles } from "../database/userProfiles";

const router = Router();
const MAX_LINK_HOURS = 24;
async function profileIdFor(userId: string) { const [profile] = await db.select({ id: userProfiles.id }).from(userProfiles).where(eq(userProfiles.userId, userId)).limit(1); return profile?.id ?? null; }
async function memberOf(conversationId: string, profileId: string) { const [member] = await db.select({ id: conversationParticipants.id, canJoinCalls: conversationParticipants.canJoinCalls }).from(conversationParticipants).where(and(eq(conversationParticipants.conversationId, conversationId), eq(conversationParticipants.userId, profileId), eq(conversationParticipants.activeMember, true), eq(conversationParticipants.temporarilySuspended, false), eq(conversationParticipants.permanentlyRemoved, false))).limit(1); return member ?? null; }
async function ensureSchema() { await pool.query(`CREATE TABLE IF NOT EXISTS redom_call_links (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), call_id uuid NOT NULL REFERENCES calls(id) ON DELETE CASCADE, conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, created_by uuid NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE, token varchar(128) UNIQUE NOT NULL, call_type varchar(12) NOT NULL CHECK (call_type IN ('voice','video')), require_approval boolean NOT NULL DEFAULT false, expires_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()); CREATE TABLE IF NOT EXISTS redom_call_link_joins (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), link_id uuid NOT NULL REFERENCES redom_call_links(id) ON DELETE CASCADE, profile_id uuid NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE, status varchar(16) NOT NULL CHECK (status IN ('pending','approved','rejected','left')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(link_id, profile_id)); CREATE INDEX IF NOT EXISTS redom_call_link_token_idx ON redom_call_links(token); CREATE INDEX IF NOT EXISTS redom_call_link_join_idx ON redom_call_link_joins(link_id,status);`); }
function token() { return randomBytes(24).toString("base64url"); }
router.use(authMiddleware);
router.post("/conversations/:conversationId", async (req, res) => { if (!req.user?.userId) return void res.status(401).json({ success: false, message: "Authentication required." }); const conversationId = z.string().uuid().safeParse(req.params.conversationId); const body = z.object({ callType: z.enum(["voice","video"]), requireApproval: z.boolean().default(false), expiresInHours: z.number().min(1).max(MAX_LINK_HOURS).default(24) }).strict().safeParse(req.body); if (!conversationId.success || !body.success) return void res.status(400).json({ success: false, message: "A valid call-link request is required." }); const profileId = await profileIdFor(req.user.userId); if (!profileId) return void res.status(404).json({ success: false, message: "Profile not found." }); const member = await memberOf(conversationId.data, profileId); if (!member?.canJoinCalls) return void res.status(403).json({ success: false, message: "You cannot create a call link for this conversation." }); await ensureSchema(); const [call] = await db.insert(calls).values({ conversationId: conversationId.data, startedByUserId: profileId, callType: body.data.callType, conversationType: "group", callStatus: "ringing", active: true, participantCount: 1, maxParticipants: 32, microphoneEnabled: true, speakerEnabled: true, cameraEnabled: body.data.callType === "video", usingFrontCamera: true, screenSharing: false, encrypted: true }).returning(); if (!call) return void res.status(500).json({ success: false, message: "Unable to create call." }); const expiresAt = new Date(Date.now() + body.data.expiresInHours * 60 * 60 * 1000); const linkToken = token(); await pool.query("INSERT INTO redom_call_links(call_id,conversation_id,created_by,token,call_type,require_approval,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7)",[call.id,conversationId.data,profileId,linkToken,body.data.callType,body.data.requireApproval,expiresAt]); res.status(201).json({ success: true, callId: call.id, token: linkToken, callType: body.data.callType, requireApproval: body.data.requireApproval, expiresAt: expiresAt.toISOString(), deepLink: `redom://call-link/${linkToken}` }); });
router.get("/:token", async (req, res) => { const tokenValue = z.string().min(20).max(128).safeParse(req.params.token); if (!tokenValue.success) return void res.status(400).json({ success: false, message: "Invalid call link." }); await ensureSchema(); const result = await pool.query("SELECT l.*, c.call_status, c.active FROM redom_call_links l JOIN calls c ON c.id=l.call_id WHERE l.token=$1 LIMIT 1",[tokenValue.data]); const link=result.rows[0]; if(!link||link.revoked_at||new Date(link.expires_at).getTime()<=Date.now()||!link.active)return void res.status(410).json({success:false,message:"This call link has expired or been revoked."}); res.json({success:true,callId:link.call_id,conversationId:link.conversation_id,callType:link.call_type,requireApproval:link.require_approval,expiresAt:new Date(link.expires_at).toISOString()}); });
router.post("/:token/join", async (req,res)=>{ if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."}); const tokenValue=z.string().min(20).max(128).safeParse(req.params.token); if(!tokenValue.success)return void res.status(400).json({success:false,message:"Invalid call link."}); const profileId=await profileIdFor(req.user.userId); if(!profileId)return void res.status(404).json({success:false,message:"Profile not found."}); await ensureSchema(); const result=await pool.query("SELECT * FROM redom_call_links WHERE token=$1 LIMIT 1",[tokenValue.data]); const link=result.rows[0]; if(!link||link.revoked_at||new Date(link.expires_at).getTime()<=Date.now())return void res.status(410).json({success:false,message:"This call link has expired or been revoked."}); const member=await memberOf(link.conversation_id,profileId); if(member){ await pool.query("INSERT INTO redom_call_link_joins(link_id,profile_id,status) VALUES($1,$2,'approved') ON CONFLICT(link_id,profile_id) DO UPDATE SET status='approved',updated_at=now()",[link.id,profileId]); return res.json({success:true,status:"approved",callId:link.call_id,conversationId:link.conversation_id,callType:link.call_type}); } if(link.require_approval){ const join=await pool.query("INSERT INTO redom_call_link_joins(link_id,profile_id,status) VALUES($1,$2,'pending') ON CONFLICT(link_id,profile_id) DO UPDATE SET updated_at=now() RETURNING status",[link.id,profileId]); return res.json({success:true,status:join.rows[0].status,callId:link.call_id,conversationId:link.conversation_id,callType:link.call_type}); } return res.status(403).json({success:false,message:"This call link requires approval before you can join."}); });
router.get("/:token/requests", async (req,res)=>{ if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."}); const tokenValue=z.string().min(20).max(128).safeParse(req.params.token); if(!tokenValue.success)return void res.status(400).json({success:false,message:"Invalid call link."}); const profileId=await profileIdFor(req.user.userId); if(!profileId)return void res.status(404).json({success:false,message:"Profile not found."}); await ensureSchema(); const r=await pool.query("SELECT l.id,l.call_id,j.id AS join_id,j.profile_id,j.status,j.created_at,p.display_name FROM redom_call_links l JOIN redom_call_link_joins j ON j.link_id=l.id JOIN user_profiles p ON p.id=j.profile_id WHERE l.token=$1 AND l.created_by=$2 ORDER BY j.created_at ASC",[tokenValue.data,profileId]); res.json({success:true,requests:r.rows}); });
router.post("/:token/requests/:profileId", async (req,res)=>{ if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."}); const tokenValue=z.string().min(20).max(128).safeParse(req.params.token); const target=z.string().uuid().safeParse(req.params.profileId); const body=z.object({decision:z.enum(["approved","rejected"])}).strict().safeParse(req.body); if(!tokenValue.success||!target.success||!body.success)return void res.status(400).json({success:false,message:"Invalid call-link approval request."}); const profileId=await profileIdFor(req.user.userId); if(!profileId)return void res.status(404).json({success:false,message:"Profile not found."}); await ensureSchema(); const owner=await pool.query("SELECT id FROM redom_call_links WHERE token=$1 AND created_by=$2 AND revoked_at IS NULL LIMIT 1",[tokenValue.data,profileId]); if(!owner.rows.length)return void res.status(403).json({success:false,message:"Only the call-link owner can approve a join request."}); const updated=await pool.query("UPDATE redom_call_link_joins SET status=$1,updated_at=now() WHERE link_id=(SELECT id FROM redom_call_links WHERE token=$2) AND profile_id=$3 AND status='pending' RETURNING status",[body.data.decision,tokenValue.data,target.data]); if(!updated.rows.length)return void res.status(404).json({success:false,message:"Pending join request not found."}); res.json({success:true,status:updated.rows[0].status}); });
router.post("/:token/revoke", async (req,res)=>{ if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."}); const tokenValue=z.string().min(20).max(128).safeParse(req.params.token); if(!tokenValue.success)return void res.status(400).json({success:false,message:"Invalid call link."}); const profileId=await profileIdFor(req.user.userId); if(!profileId)return void res.status(404).json({success:false,message:"Profile not found."}); await ensureSchema(); const updated=await pool.query("UPDATE redom_call_links SET revoked_at=now() WHERE token=$1 AND created_by=$2 AND revoked_at IS NULL RETURNING id",[tokenValue.data,profileId]); if(!updated.rows.length)return void res.status(404).json({success:false,message:"Call link not found."}); res.json({success:true,revoked:true}); });
export default router;
