import { Router } from "express";
import { and, eq, ne, sql } from "drizzle-orm";
import { GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { authMiddleware } from "../middleware/auth.middleware";
import { authRateLimit } from "../middleware/rate-limit.middleware";
import { db, pool } from "../database/db";
import { conversations } from "../database/conversations";
import { conversationParticipants } from "../database/conversationParticipants";
import { messages } from "../database/messages";
import { messageAttachments } from "../database/messageAttachments";
import { notifications } from "../database/notifications";
import { userProfiles } from "../database/userProfiles";
import { env } from "../config/env";

const router = Router(); const MAX_BYTES = 10 * 1024 * 1024;
const envelope = z.object({ version: z.literal(1), algorithm: z.literal("X25519-AES-256-GCM"), ephemeralPublicKey: z.string().regex(/^[0-9a-f]{64}$/i), encryptedMediaKey: z.string().min(32).max(10000) }).strict();
const bodySchema = z.object({ type: z.enum(["photo","video","voice","audio","document","gif","sticker"]), ciphertextDataUri: z.string().min(30), mimeType: z.string().max(120), caption: z.string().max(5000).optional(), parentMessageId: z.string().uuid().optional(), durationSeconds: z.number().int().min(0).max(86400).optional(), waveform: z.array(z.number().min(0).max(1)).max(256).optional(), mediaEnvelopes: z.record(z.string().uuid(), envelope), viewOnce: z.boolean().default(false) }).strict();
const r2 = new S3Client({ region: env.cloudflare.r2.region || "auto", endpoint: env.cloudflare.r2.endpoint, credentials: { accessKeyId: env.cloudflare.r2.accessKeyId, secretAccessKey: env.cloudflare.r2.secretAccessKey } });
async function profileId(userId: string) { const [p] = await db.select({ id: userProfiles.id }).from(userProfiles).where(eq(userProfiles.userId, userId)).limit(1); return p?.id ?? null; }
async function isMember(conversationId: string, profile: string) { const [m] = await db.select({ id: conversationParticipants.id }).from(conversationParticipants).where(and(eq(conversationParticipants.conversationId, conversationId), eq(conversationParticipants.userId, profile), eq(conversationParticipants.activeMember, true), eq(conversationParticipants.temporarilySuspended, false), eq(conversationParticipants.permanentlyRemoved, false))).limit(1); return Boolean(m); }
function decode(value: string) { const m = /^data:[^;,]+;base64,([A-Za-z0-9+/=]+)$/.exec(value); if (!m) throw new Error("Invalid encrypted media payload."); const data = Buffer.from(m[1], "base64"); if (!data.length || data.length > MAX_BYTES) throw new Error("Encrypted media must be 10 MB or smaller."); return data; }
router.use(authMiddleware, authRateLimit);
router.post("/conversations/:conversationId/encrypted-media", async (req,res) => {
  if (!req.user?.userId) return void res.status(401).json({ success:false,message:"Authentication required." }); const cid=z.string().uuid().safeParse(req.params.conversationId); const parsed=bodySchema.safeParse(req.body); if(!cid.success||!parsed.success) return void res.status(400).json({success:false,message:"Invalid encrypted media payload."}); const me=await profileId(req.user.userId); if(!me||!await isMember(cid.data,me)) return void res.status(403).json({success:false,message:"You cannot send media in this conversation."});
  const active=await db.select({userId:conversationParticipants.userId}).from(conversationParticipants).where(and(eq(conversationParticipants.conversationId,cid.data),eq(conversationParticipants.activeMember,true),eq(conversationParticipants.temporarilySuspended,false),eq(conversationParticipants.permanentlyRemoved,false))); const ids=new Set(active.map(x=>x.userId)); ids.add(me); for(const id of Object.keys(parsed.data.mediaEnvelopes)) if(!ids.has(id)) return void res.status(400).json({success:false,message:"Encrypted media recipient is not an active participant."}); if(parsed.data.viewOnce&&!new Set(["photo","video","voice"]).has(parsed.data.type)) return void res.status(400).json({success:false,message:"View Once is supported for photos, videos and voice messages."});
  try { const bytes=decode(parsed.data.ciphertextDataUri); const key=`messages/${cid.data}/${randomUUID()}.redom`; await r2.send(new PutObjectCommand({Bucket:env.cloudflare.r2.bucketName,Key:key,Body:bytes,ContentType:"application/octet-stream"})); const [created]=await db.insert(messages).values({conversationId:cid.data,senderId:me,parentMessageId:parsed.data.parentMessageId,messageType:parsed.data.type,message:null,caption:null,sent:true,delivered:false,read:false,aiReviewed:false,moderationStatus:"approved"}).returning(); if(!created) throw new Error("Unable to create encrypted message."); const expires=parsed.data.viewOnce?new Date(Date.now()+14*24*60*60*1000):null; const [attachment]=await db.insert(messageAttachments).values({messageId:created.id,attachmentType:parsed.data.type,fileUrl:`/messages/media/${key}`,fileName:`${created.id}.redom`,mimeType:parsed.data.mimeType,fileExtension:"redom",fileSize:bytes.length,durationSeconds:parsed.data.durationSeconds,waveform:parsed.data.waveform?JSON.stringify(parsed.data.waveform):null,compressed:false,exifRemoved:true,processingCompleted:true,active:true,processing:false,failed:false,virusScanned:false}).returning(); await pool.query("UPDATE message_attachments SET encrypted=true,encryption_version=1,view_once=$1,view_once_expires_at=$2 WHERE id=$3",[parsed.data.viewOnce,expires,attachment.id]); for(const [recipient,item] of Object.entries(parsed.data.mediaEnvelopes)) await pool.query("INSERT INTO message_media_envelopes(message_id,recipient_profile_id,version,algorithm,ephemeral_public_key,encrypted_media_key) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(message_id,recipient_profile_id) DO UPDATE SET ephemeral_public_key=EXCLUDED.ephemeral_public_key,encrypted_media_key=EXCLUDED.encrypted_media_key",[created.id,recipient,item.version,item.algorithm,item.ephemeralPublicKey,item.encryptedMediaKey]); await db.update(conversations).set({messageCount:sql`${conversations.messageCount}+1`,updatedAt:new Date()}).where(eq(conversations.id,cid.data)); for(const recipient of active.filter(x=>x.userId!==me)){await db.update(conversationParticipants).set({unreadMessageCount:sql`${conversationParticipants.unreadMessageCount}+1`}).where(and(eq(conversationParticipants.conversationId,cid.data),eq(conversationParticipants.userId,recipient.userId))); await db.insert(notifications).values({recipientUserId:recipient.userId,actorUserId:me,messageId:created.id,conversationId:cid.data,notificationType:"message",title:parsed.data.viewOnce?"View Once message":"Encrypted media message",body:"You received a new ReDom encrypted media message.",actionUrl:`redom://messages/${cid.data}`,unread:true,read:false,inAppDelivered:true,priority:"normal"});} res.status(201).json({success:true,message:{...created,encrypted:true},attachment:{...attachment,encrypted:true,viewOnce:parsed.data.viewOnce,viewOnceExpiresAt:expires}});
  } catch(e){res.status(400).json({success:false,message:e instanceof Error?e.message:"Unable to store encrypted media."});}
});
router.get("/messages/:messageId/media-key",async(req,res)=>{if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."});const id=z.string().uuid().safeParse(req.params.messageId);if(!id.success)return void res.status(400).json({success:false,message:"Invalid message."});const me=await profileId(req.user.userId);if(!me)return void res.status(404).json({success:false,message:"Profile not found."});const r=await pool.query("SELECT version,algorithm,ephemeral_public_key,encrypted_media_key FROM message_media_envelopes WHERE message_id=$1 AND recipient_profile_id=$2 LIMIT 1",[id.data,me]);if(!r.rows[0])return void res.status(404).json({success:false,message:"Encrypted media key unavailable."});res.json({success:true,envelope:{version:r.rows[0].version,algorithm:r.rows[0].algorithm,ephemeralPublicKey:r.rows[0].ephemeral_public_key,encryptedMediaKey:r.rows[0].encrypted_media_key}});});
export default router;
