import { Router } from "express";
import { pool } from "../database/db";
import { authMiddleware } from "../middleware/auth.middleware";
import { authRateLimit } from "../middleware/rate-limit.middleware";
const router=Router(); router.use(authMiddleware,authRateLimit);
async function profileId(userId:string){const r=await pool.query("SELECT id FROM user_profiles WHERE user_id=$1 LIMIT 1",[userId]);return r.rows[0]?.id??null;}
const personSql="SELECT u.id AS \"userId\",p.id AS \"profileId\",u.first_name AS \"firstName\",u.last_name AS \"lastName\",u.username,p.profile_photo AS \"profilePhoto\",p.current_city AS \"currentCity\",p.hometown,p.profile_type AS \"profileType\",p.verified, CASE WHEN EXISTS(SELECT 1 FROM friends f WHERE ((f.user_id=$1 AND f.friend_user_id=u.id) OR (f.user_id=u.id AND f.friend_user_id=$1)) AND f.friendship_status='active') THEN true ELSE false END AS friend, CASE WHEN EXISTS(SELECT 1 FROM friend_requests fr WHERE fr.sender_id=$1 AND fr.receiver_id=u.id AND fr.status='pending') THEN true ELSE false END AS \"requestSent\", (SELECT fr.id FROM friend_requests fr WHERE fr.sender_id=$1 AND fr.receiver_id=u.id AND fr.status='pending' LIMIT 1) AS \"outgoingRequestId\", CASE WHEN EXISTS(SELECT 1 FROM friend_requests fr WHERE fr.sender_id=u.id AND fr.receiver_id=$1 AND fr.status='pending') THEN true ELSE false END AS \"requestReceived\", (SELECT fr.id FROM friend_requests fr WHERE fr.sender_id=u.id AND fr.receiver_id=$1 AND fr.status='pending' LIMIT 1) AS \"incomingRequestId\", CASE WHEN EXISTS(SELECT 1 FROM following fw WHERE fw.user_id=$1 AND fw.following_id=u.id) THEN true ELSE false END AS following FROM users u JOIN user_profiles p ON p.user_id=u.id";
router.get("/",async(req,res)=>{const me=await profileId(req.user!.userId);if(!me)return void res.status(404).json({success:false,message:"Profile not found."});const q=String(req.query.q??"").trim();const where=q?" AND (u.first_name||' '||u.last_name ILIKE $2 OR COALESCE(u.username,'') ILIKE $2)":"";const params:any[]=[req.user!.userId];if(q)params.push("%"+q+"%");const r=await pool.query(personSql+" WHERE u.id<>$1 AND EXISTS(SELECT 1 FROM friends f WHERE ((f.user_id=$1 AND f.friend_user_id=u.id) OR (f.user_id=u.id AND f.friend_user_id=$1)) AND f.friendship_status='active'"+where+" ORDER BY u.first_name,u.last_name LIMIT 100",params);res.json({success:true,people:r.rows});});
router.get("/following",async(req,res)=>{const me=await profileId(req.user!.userId);if(!me)return void res.status(404).json({success:false,message:"Profile not found."});const r=await pool.query(personSql+" WHERE u.id<>$1 AND EXISTS(SELECT 1 FROM following fw WHERE fw.user_id=$1 AND fw.following_id=u.id) ORDER BY u.first_name,u.last_name LIMIT 100",[req.user!.userId]);res.json({success:true,people:r.rows});});
router.get("/suggested",async(req,res)=>{const me=req.user!.userId,q=String(req.query.q??"").trim(),where=q?" AND (u.first_name||' '||u.last_name ILIKE $2 OR COALESCE(u.username,'') ILIKE $2)":"";const params:any[]=[me];if(q)params.push("%"+q+"%");const r=await pool.query(personSql+" WHERE u.id<>$1"+where+" AND NOT EXISTS(SELECT 1 FROM friends f WHERE ((f.user_id=$1 AND f.friend_user_id=u.id) OR (f.user_id=u.id AND f.friend_user_id=$1)) AND f.friendship_status='active') AND NOT EXISTS(SELECT 1 FROM friend_requests fr WHERE ((fr.sender_id=$1 AND fr.receiver_id=u.id) OR (fr.sender_id=u.id AND fr.receiver_id=$1)) AND fr.status='pending') AND NOT EXISTS(SELECT 1 FROM blocked_users b WHERE (b.user_id=$1 AND b.blocked_user_id=u.id) OR (b.user_id=u.id AND b.blocked_user_id=$1)) ORDER BY p.friend_count DESC NULLS LAST,u.created_at DESC LIMIT 100",params);res.json({success:true,people:r.rows});});
router.get("/common",async(req,res)=>{const me=req.user!.userId;const r=await pool.query(personSql+" WHERE u.id<>$1 AND (p.current_city IN (SELECT current_city FROM user_profiles WHERE user_id=$1 AND current_city IS NOT NULL) OR p.hometown IN (SELECT hometown FROM user_profiles WHERE user_id=$1 AND hometown IS NOT NULL)) AND NOT EXISTS(SELECT 1 FROM friends f WHERE ((f.user_id=$1 AND f.friend_user_id=u.id) OR (f.user_id=u.id AND f.friend_user_id=$1)) AND f.friendship_status='active') ORDER BY p.friend_count DESC NULLS LAST LIMIT 100",[me]);res.json({success:true,people:r.rows});});
router.post("/requests/:targetUserId",async(req,res)=>{const me=req.user!.userId,target=req.params.targetUserId;if(me===target)return void res.status(400).json({success:false,message:"You cannot add yourself."});const blocked=await pool.query("SELECT 1 FROM blocked_users WHERE (user_id=$1 AND blocked_user_id=$2) OR (user_id=$2 AND blocked_user_id=$1) LIMIT 1",[me,target]);if(blocked.rowCount)return void res.status(403).json({success:false,message:"This connection is unavailable."});const existing=await pool.query("SELECT id FROM friend_requests WHERE ((sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1)) AND status='pending' LIMIT 1",[me,target]);if(existing.rowCount)return void res.status(409).json({success:false,message:"A friend request already exists."});const friendship=await pool.query("SELECT 1 FROM friends WHERE ((user_id=$1 AND friend_user_id=$2) OR (user_id=$2 AND friend_user_id=$1)) AND friendship_status='active' LIMIT 1",[me,target]);if(friendship.rowCount)return void res.status(409).json({success:false,message:"You are already friends."});const r=await pool.query("INSERT INTO friend_requests(sender_id,receiver_id,status) VALUES($1,$2,'pending') RETURNING id",[me,target]);res.status(201).json({success:true,requestId:r.rows[0].id});});
router.delete("/requests/:targetUserId",async(req,res)=>{const r=await pool.query("UPDATE friend_requests SET status='cancelled',cancelled_at=now(),updated_at=now() WHERE sender_id=$1 AND receiver_id=$2 AND status='pending' RETURNING id",[req.user!.userId,req.params.targetUserId]);res.json({success:true,cancelled:!!r.rowCount});});
router.post("/requests/:requestId/accept",async(req,res)=>{const client=await pool.connect();try{await client.query("BEGIN");const r=await client.query("SELECT * FROM friend_requests WHERE id=$1 AND receiver_id=$2 AND status='pending' FOR UPDATE",[req.params.requestId,req.user!.userId]);if(!r.rowCount){await client.query("ROLLBACK");return void res.status(404).json({success:false,message:"Friend request not found."});}const x=r.rows[0];await client.query("UPDATE friend_requests SET status='accepted',accepted_at=now(),updated_at=now() WHERE id=$1",[x.id]);await client.query("INSERT INTO friends(user_id,friend_user_id,friendship_status) VALUES($1,$2,'active'),($2,$1,'active')",[x.sender_id,x.receiver_id]);await client.query("UPDATE user_profiles SET friend_count=friend_count+1 WHERE user_id IN ($1,$2)",[x.sender_id,x.receiver_id]);await client.query("COMMIT");res.json({success:true});}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}});
router.post("/requests/:requestId/decline",async(req,res)=>{const r=await pool.query("UPDATE friend_requests SET status='declined',declined_at=now(),updated_at=now() WHERE id=$1 AND receiver_id=$2 AND status='pending' RETURNING id",[req.params.requestId,req.user!.userId]);res.json({success:true,declined:!!r.rowCount});});
router.delete("/:targetUserId",async(req,res)=>{const me=req.user!.userId,target=req.params.targetUserId;const r=await pool.query("UPDATE friends SET friendship_status='removed',updated_at=now() WHERE ((user_id=$1 AND friend_user_id=$2) OR (user_id=$2 AND friend_user_id=$1)) AND friendship_status='active'",[me,target]);if(r.rowCount)await pool.query("UPDATE user_profiles SET friend_count=GREATEST(friend_count-1,0) WHERE user_id IN ($1,$2)",[me,target]);res.json({success:true,unfriended:!!r.rowCount});});
router.post("/block/:targetUserId",async(req,res)=>{const me=req.user!.userId,target=req.params.targetUserId;await pool.query("INSERT INTO blocked_users(user_id,blocked_user_id) VALUES($1,$2)",[me,target]);await pool.query("UPDATE friends SET friendship_status='removed',updated_at=now() WHERE ((user_id=$1 AND friend_user_id=$2) OR (user_id=$2 AND friend_user_id=$1)) AND friendship_status='active'",[me,target]);await pool.query("UPDATE friend_requests SET status='cancelled',cancelled_at=now(),updated_at=now() WHERE ((sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1)) AND status='pending'",[me,target]);res.json({success:true});});
router.post("/unfollow/:targetUserId",async(req,res)=>{const r=await pool.query("DELETE FROM following WHERE user_id=$1 AND following_id=$2",[req.user!.userId,req.params.targetUserId]);res.json({success:true,unfollowed:!!r.rowCount});});
export default router;