import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRoutes from "./auth.routes";
import sessionRoutes from "./session.routes";
import aiRoutes from "./ai.routes";
import supportRoutes from "./support.routes";
import refundRoutes from "./refund.routes";
import knowledgeRoutes from "./knowledge.routes";
import feedRoutes from "./feed.routes";
import commentRoutes from "./comment.routes";
import profileRoutes from "./profile.routes";
import profileEditRoutes from "./profile-edit.routes";
import profileMediaRoutes from "./profile-media.routes";
import productRoutes from "./product.routes";
import messagesRoutes from "./messages.routes";
import { profileMediaExpiryMiddleware } from "../middleware/profile-media-expiry.middleware";

const router: IRouter = Router();
router.use(healthRouter);
router.use("/auth", authRoutes);
router.use("/sessions", sessionRoutes);
router.use("/ai", aiRoutes);
router.use("/support", supportRoutes);
router.use("/refunds", refundRoutes);
router.use("/ai", knowledgeRoutes);
router.use("/feed", feedRoutes);
router.use("/comments", commentRoutes);
router.use("/product", productRoutes);
router.use("/messages", messagesRoutes);
router.use("/profile", profileMediaExpiryMiddleware);
router.use("/profile/edit", profileEditRoutes);
router.use("/profile/media", profileMediaRoutes);
router.use("/profile", profileRoutes);
export default router;
