import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRoutes from "./auth.routes";
import sessionRoutes from "./session.routes";
import aiRoutes from "./ai.routes";
import supportRoutes from "./support.routes";
import refundRoutes from "./refund.routes";
import knowledgeRoutes from "./knowledge.routes";
import feedRoutes from "./feed.routes";
import commentRoutes from "./comment.routes";
import profileRoutes from "./profile.routes";
import profileEditRoutes from "./profile-edit.routes";
import profileMediaRoutes from "./profile-media.routes";
import productRoutes from "./product.routes";
import messagingPolicyRoutes from "./messaging-policy.routes";
import messagesRoutes from "./messages.routes";
import messageMediaRoutes from "./message-media.routes";
import encryptedMediaRoutes from "./encrypted-media.routes";
import callsRoutes from "./calls.routes";
import messageReactionRoutes from "./message-reactions.routes";
import messagingCompletionRoutes from "./messaging-completion.routes";
import messagingGroupsRoutes from "./messaging-groups.routes";
import messagingGroupApprovalRoutes from "./messaging-group-approval.routes";
import messagingGuardsRoutes from "./messaging-guards.routes";
import messagingE2eeRoutes from "./messaging-e2ee.routes";
import linkedDeviceLinkRoutes from "./linked-device-link.routes";
import messageDraftRoutes from "./message-drafts.routes";
import messageReadReceiptRoutes from "./message-read-receipts.routes";
import messagingInboxRoutes from "./messaging-inbox.routes";
import searchRoutes from "./search.routes";
import { messagingRateLimit } from "../middleware/rate-limit.middleware";
import { profileMediaExpiryMiddleware } from "../middleware/profile-media-expiry.middleware";
const router: IRouter = Router();
router.use(healthRouter); router.use("/auth", authRoutes); router.use("/sessions", sessionRoutes); router.use("/ai", aiRoutes); router.use("/support", supportRoutes); router.use("/refunds", refundRoutes); router.use("/ai", knowledgeRoutes); router.use("/feed", feedRoutes); router.use("/comments", commentRoutes); router.use("/product", messagingPolicyRoutes); router.use("/product", productRoutes); router.use("/messages", messagingRateLimit, encryptedMediaRoutes); router.use("/messages", messagingRateLimit, messageMediaRoutes); router.use("/messages", messagingRateLimit, messagingCompletionRoutes); router.use("/messages", messagingRateLimit, messagingGroupsRoutes); router.use("/messages", messagingRateLimit, messagingGroupApprovalRoutes); router.use("/messages", messagingRateLimit, messagingGuardsRoutes); router.use("/messages", messagingRateLimit, linkedDeviceLinkRoutes); router.use("/messages", messagingRateLimit, messagingE2eeRoutes); router.use("/messages", messagingRateLimit, messageDraftRoutes); router.use("/messages", messagingRateLimit, messageReadReceiptRoutes); router.use("/messages", messagingRateLimit, messagingInboxRoutes); router.use("/messages", messagingRateLimit, messagesRoutes); router.use("/calls", messagingGuardsRoutes); router.use("/calls", callsRoutes); router.use("/message-reactions", messageReactionRoutes); router.use("/search", searchRoutes); router.use("/profile", profileMediaExpiryMiddleware); router.use("/profile/edit", profileEditRoutes); router.use("/profile/media", profileMediaRoutes); router.use("/profile", profileRoutes);
export default router;