import { Router } from "express";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { authMiddleware } from "../middleware/auth.middleware";
import { db, pool } from "../database/db";
import { conversations } from "../database/conversations";
import { conversationParticipants } from "../database/conversationParticipants";
import { userProfiles } from "../database/userProfiles";
import { scheduledGroupCalls } from "../database/scheduledGroupCalls";
const router=Router();router.use(authMiddleware);let schemaReady:Promise<void>|null=null;
async function ensure(){await pool.query(`CREATE TABLE IF NOT EXISTS scheduled_group_calls (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, created_by uuid NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE, call_type varchar(12) NOT NULL CHECK(call_type IN ('voice','video')), title varchar(160) NOT NULL, description varchar(2048), scheduled_at timestamptz NOT NULL, status varchar(16) NOT NULL DEFAULT 'scheduled', created_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS scheduled_group_calls_conversation_idx ON scheduled_group_calls(conversation_id,scheduled_at);`)}
async function profile(userId:string){const[p]=await db.select({id:userProfiles.id}).from(userProfiles).where(eq(userProfiles.userId,userId)).limit(1);return p?.id??null}
router.use(async(_req,_res,next)=>{try{schemaReady??=(ensure().catch(e=>{schemaReady=null;throw e}));await schemaReady;next()}catch(e){next(e)}});
router.post("/groups/:conversationId/scheduled-calls",async(req,res)=>{if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."});const id=z.string().uuid().safeParse(req.params.conversationId);const body=z.object({callType:z.enum(["voice","video"]),title:z.string().trim().min(1).max(160),description:z.string().trim().max(2048).optional(),scheduledAt:z.string().datetime()}).strict().safeParse(req.body);if(!id.success||!body.success)return void res.status(400).json({success:false,message:"Invalid scheduled call."});const me=await profile(req.user.userId);if(!me)return void res.status(404).json({success:false,message:"Profile not found."});const[m]=await db.select({id:conversationParticipants.id}).from(conversationParticipants).where(and(eq(conversationParticipants.conversationId,id.data),eq(conversationParticipants.userId,me),eq(conversationParticipants.activeMember,true),eq(conversationParticipants.temporarilySuspended,false),eq(conversationParticipants.permanentlyRemoved,false))).limit(1);if(!m)return void res.status(403).json({success:false,message:"You are not a member of this group."});const[g]=await db.select({type:conversations.conversationType,status:conversations.status,deleted:conversations.deleted}).from(conversations).where(eq(conversations.id,id.data)).limit(1);if(!g||g.type!=="group"||g.deleted||g.status!=="active")return void res.status(404).json({success:false,message:"Group not found."});const when=new Date(body.data.scheduledAt);if(when.getTime()<=Date.now())return void res.status(400).json({success:false,message:"Scheduled time must be in the future."});const[created]=await db.insert(scheduledGroupCalls).values({conversationId:id.data,createdBy:me,callType:body.data.callType,title:body.data.title,description:body.data.description??null,scheduledAt:when,status:"scheduled"}).returning();res.status(201).json({success:true,scheduledCall:created});});
router.get("/groups/:conversationId/scheduled-calls",async(req,res)=>{if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."});const id=z.string().uuid().safeParse(req.params.conversationId);if(!id.success)return void res.status(400).json({success:false,message:"Invalid group."});const me=await profile(req.user.userId);if(!me)return void res.status(404).json({success:false,message:"Profile not found."});const[m]=await db.select({id:conversationParticipants.id}).from(conversationParticipants).where(and(eq(conversationParticipants.conversationId,id.data),eq(conversationParticipants.userId,me),eq(conversationParticipants.activeMember,true))).limit(1);if(!m)return void res.status(403).json({success:false,message:"You are not a group member."});const rows=await db.select().from(scheduledGroupCalls).where(eq(scheduledGroupCalls.conversationId,id.data)).orderBy(desc(scheduledGroupCalls.scheduledAt)).limit(50);res.json({success:true,scheduledCalls:rows});});
export default router;