import { Router } from "express";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { authMiddleware } from "../middleware/auth.middleware";
import { db, pool } from "../database/db";
import { conversations } from "../database/conversations";
import { conversationParticipants } from "../database/conversationParticipants";
import { userProfiles } from "../database/userProfiles";
import { users } from "../database/schema";
const router = Router(); router.use(authMiddleware);
let ready: Promise<void> | null = null;
async function ensureColumns() { if (!ready) ready = Promise.all(["business_address","business_email","business_category","business_hours"].map((column) => pool.query(`ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS ${column} varchar(255)`))).then(() => undefined).catch((e) => { ready = null; throw e; }); return ready; }
async function profileForUser(userId: string) { const [profile] = await db.select({ id: userProfiles.id }).from(userProfiles).where(eq(userProfiles.userId, userId)).limit(1); return profile?.id ?? null; }
router.get("/conversations/:conversationId/business-profile", async (req,res)=>{ await ensureColumns(); if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."}); const me=await profileForUser(req.user.userId); if(!me)return void res.status(404).json({success:false,message:"Profile not found."}); const conversationId=z.string().uuid().safeParse(req.params.conversationId); if(!conversationId.success)return void res.status(400).json({success:false,message:"Invalid conversation."}); const [member]=await db.select({userId:conversationParticipants.userId}).from(conversationParticipants).where(and(eq(conversationParticipants.conversationId,conversationId.data),eq(conversationParticipants.userId,me),eq(conversationParticipants.activeMember,true))).limit(1); if(!member)return void res.status(403).json({success:false,message:"Conversation access denied."}); const peers=await db.select({profileId:userProfiles.id,profileType:userProfiles.profileType,displayName:userProfiles.displayName,verified:userProfiles.verified,businessAddress:sql`user_profiles.business_address`,businessEmail:sql`user_profiles.business_email`,businessCategory:sql`user_profiles.business_category`,businessHours:sql`user_profiles.business_hours`,accountEmail:users.email}).from(conversationParticipants).innerJoin(userProfiles,eq(userProfiles.id,conversationParticipants.userId)).innerJoin(users,eq(users.id,userProfiles.userId)).where(and(eq(conversationParticipants.conversationId,conversationId.data),eq(conversationParticipants.activeMember,true))); const peer=peers.find((item)=>item.profileId!==me); res.json({success:true,business:peer?{isBusiness:peer.profileType==="business",displayName:peer.displayName,verified:peer.verified,address:peer.businessAddress,email:peer.businessEmail||peer.accountEmail,category:peer.businessCategory,hours:peer.businessHours}:null}); });
router.patch("/business-profile", async (req,res)=>{ await ensureColumns(); if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."}); const parsed=z.object({address:z.string().trim().max(255).nullable().optional(),email:z.string().trim().email().max(255).nullable().optional(),category:z.string().trim().max(255).nullable().optional(),hours:z.string().trim().max(255).nullable().optional()}).safeParse(req.body); if(!parsed.success)return void res.status(400).json({success:false,message:"Invalid business profile."}); const profileId=await profileForUser(req.user.userId); if(!profileId)return void res.status(404).json({success:false,message:"Profile not found."}); const [profile]=await db.select({profileType:userProfiles.profileType}).from(userProfiles).where(eq(userProfiles.id,profileId)).limit(1); if(profile?.profileType!=="business")return void res.status(403).json({success:false,message:"Only business profiles can edit business details."}); await pool.query(`UPDATE user_profiles SET business_address=$1,business_email=$2,business_category=$3,business_hours=$4,updated_at=now() WHERE id=$5`,[parsed.data.address??null,parsed.data.email??null,parsed.data.category??null,parsed.data.hours??null,profileId]); res.json({success:true}); });
export default router;
