import { Router } from "express";
import { and, eq, inArray } from "drizzle-orm";
import { z } from "zod";
import { authMiddleware } from "../middleware/auth.middleware";
import { db } from "../database/db";
import { conversations } from "../database/conversations";
import { conversationParticipants } from "../database/conversationParticipants";
import { userProfiles } from "../database/userProfiles";

const router=Router(); router.use(authMiddleware);
async function me(userId:string){const [p]=await db.select({id:userProfiles.id}).from(userProfiles).where(eq(userProfiles.userId,userId)).limit(1);return p?.id??null;}
async function member(conversationId:string,profileId:string){const [m]=await db.select({id:conversationParticipants.id,role:conversationParticipants.role}).from(conversationParticipants).where(and(eq(conversationParticipants.conversationId,conversationId),eq(conversationParticipants.userId,profileId),eq(conversationParticipants.activeMember,true),eq(conversationParticipants.permanentlyRemoved,false))).limit(1);return m??null;}
router.get("/groups/:conversationId/details",async(req,res)=>{if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."});const id=z.string().uuid().safeParse(req.params.conversationId);if(!id.success)return void res.status(400).json({success:false,message:"Invalid group."});const mine=await me(req.user.userId);if(!mine)return void res.status(404).json({success:false,message:"Profile not found."});const actor=await member(id.data,mine);if(!actor)return void res.status(403).json({success:false,message:"You do not have access to this group."});const[g]=await db.select().from(conversations).where(and(eq(conversations.id,id.data),eq(conversations.conversationType,"group"))).limit(1);if(!g)return void res.status(404).json({success:false,message:"Group not found."});const rows=await db.select({id:conversationParticipants.id,profileId:conversationParticipants.userId,role:conversationParticipants.role,memberTag:conversationParticipants.memberTag,joinedAt:conversationParticipants.joinedAt,online:conversationParticipants.online,displayName:userProfiles.displayName,profilePhoto:userProfiles.profilePhoto,verified:userProfiles.verified}).from(conversationParticipants).innerJoin(userProfiles,eq(userProfiles.id,conversationParticipants.userId)).where(and(eq(conversationParticipants.conversationId,id.data),eq(conversationParticipants.activeMember,true),eq(conversationParticipants.permanentlyRemoved,false))).orderBy(conversationParticipants.joinedAt);res.json({success:true,group:{id:g.id,groupName:g.groupName,groupDescription:g.groupDescription,groupPhoto:g.groupPhoto,participantCount:g.participantCount,anyoneCanEditInfo:g.anyoneCanEditInfo,anyoneCanInvite:g.anyoneCanInvite,anyoneCanShareInvite:g.anyoneCanShareInvite,anyoneCanSendMessages:g.anyoneCanSendMessages,anyoneCanSendHistory:g.anyoneCanSendHistory,anyoneCanRemoveMembers:g.anyoneCanRemoveMembers,joinApprovalRequired:g.joinApprovalRequired,encrypted:g.encrypted,isAdmin:actor.role==="owner"||actor.role==="admin"},members:rows});});
router.patch("/groups/:conversationId/photo",async(req,res)=>{if(!req.user?.userId)return void res.status(401).json({success:false,message:"Authentication required."});const id=z.string().uuid().safeParse(req.params.conversationId);const body=z.object({groupPhoto:z.string().url().max(500).nullable()}).strict().safeParse(req.body);if(!id.success||!body.success)return void res.status(400).json({success:false,message:"Invalid group photo."});const mine=await me(req.user.userId);const actor=mine?await member(id.data,mine):null;if(!actor||!(actor.role==="owner"||actor.role==="admin"))return void res.status(403).json({success:false,message:"Only group admins can change the group icon."});await db.update(conversations).set({groupPhoto:body.data.groupPhoto,updatedAt:new Date()}).where(eq(conversations.id,id.data));res.json({success:true,groupPhoto:body.data.groupPhoto});});
export default router;