import { Router } from "express";
const router=Router();
const messagingPolicy={version:"2.9.0",effectiveAt:"2026-09-15T00:00:00.000Z",sections:[
{heading:"Your chats are private",body:"Your personal conversations are protected with end-to-end encryption. Messages and calls stay between you and the people in the conversation. ReDom is designed so private conversation content is not available to ReDom for ordinary reading, listening or sharing."},
{heading:"End-to-end encryption",body:"End-to-end encryption is on for private messaging. A conversation is secured before normal messages can be sent. The whole conversation has an active encryption context, and every message or shared item is protected within that conversation."},
{heading:"What is protected",body:"End-to-end encryption protects your text and voice messages, photos, videos, documents, audio, shared locations, and other private conversation content. Calls use secure call media protection as part of the private conversation experience."},
{heading:"Encryption happens before sending",body:"ReDom does not send a private message first and encrypt it later. The conversation must be ready for encryption before content is sent. If the conversation cannot be securely protected, ReDom does not fall back to sending the content without encryption."},
{heading:"Only people in the chat",body:"Only authorized people and their active authorized devices can access the current encrypted conversation. Joining a conversation does not give a new participant access to content protected by an earlier membership key."},
{heading:"New devices",body:"When you use another authorized device, that device must be securely connected to your encrypted conversations before it can access current protected content. Removing or revoking a device prevents it from receiving future conversation encryption updates."},
{heading:"Group privacy",body:"Group conversations use the same privacy principle. When membership changes, ReDom refreshes the conversation's encryption so a person who leaves or is removed cannot receive content protected after that change, while a newly added member receives only the current authorized conversation protection."},
{heading:"Security verification",body:"You can verify the security identity of a conversation from its encryption verification screen. Verification helps you notice when a participant's security identity changes. ReDom never asks you to reveal a private encryption key to verify a conversation."},
{heading:"Privacy notice in every conversation",body:"ReDom shows a clear privacy notice at the beginning of an encrypted conversation: 'Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them.' Select Learn more to open this Messaging Policy."},
{heading:"Message and media controls",body:"Encrypted conversations support the messaging controls available in ReDom, including replies, reactions, editing, deletion, disappearing messages, view-once content, forwarding limits and protected media. These controls do not turn off conversation encryption."},
{heading:"Calls",body:"Audio and video calls are available only to authorized conversation participants. Call privacy is part of ReDom's private communication experience and is protected separately from the message content encryption context."},
{heading:"Privacy and safety",body:"You control who you communicate with through ReDom's account, blocking, reporting, conversation and group controls. Encryption does not remove these safety controls. ReDom may provide safety features around a conversation without making private conversation content generally readable to ReDom."},
{heading:"ReDom AI",body:"ReDom AI is a separate, user-invoked experience. Private conversation content is not automatically provided to ReDom AI simply because you are viewing a chat. If you deliberately provide conversation content, an image, a file or a voice prompt to ReDom AI, that material is handled as part of that AI request rather than as encrypted personal-chat content."},
{heading:"ReDom Image-2",body:"ReDom Image-2 is ReDom's image creation and editing experience. Images are created or edited only when you explicitly request the feature. A private conversation is not silently inspected for image creation or editing."},
{heading:"AI information and chat history",body:"ReDom AI conversations are separate from your encrypted personal-message history. ReDom AI may use the information you deliberately provide to an AI conversation, while your private messages remain within their conversation privacy boundary unless you explicitly choose to share content."},
{heading:"If encryption is unavailable",body:"ReDom fails safely when encryption is unavailable. You may be asked to reconnect or authorize a device before continuing. Private content is not sent as readable fallback content simply to make the message go through."},
{heading:"Learn more",body:"For a conversation-specific security check, open the chat's encryption verification screen. For the broader rules that govern private messaging, return to this Messaging Policy from the encryption notice or ReDom's policy navigation."}
]};
router.get("/policies/messaging",(_req,res)=>res.json({success:true,slug:"messaging",title:"ReDom Messaging Policy",summary:"Privacy, security and messaging rules for ReDom conversations, groups, calls, media and ReDom AI features.",...messagingPolicy}));
export default router;
