import { Router } from "express";

const router = Router();
const document = {
  title: "ReDom Messaging Policy",
  summary: "How ReDom private messaging, groups, media, calls, privacy controls, AI assistance and safety features work.",
  referencePrinciples: [
    "Behavior is derived from current WhatsApp Help Center and Facebook/Messenger Help Center behavior where the products document the corresponding capability; ReDom implementation must not claim stronger guarantees than the platform can actually enforce.",
    "Private personal message content remains end-to-end encrypted. Server-side authorization, routing, delivery metadata and notifications may operate on metadata without exposing plaintext message content.",
    "ReDom AI is a separate, explicit AI workflow. AI context is not silently read from private chats; content is sent to the AI service only when the user invokes an AI feature that needs it.",
  ],
  sections: [
    { heading: "Conversation access", body: "Messaging requires authentication and an active conversation membership. Backend authorization is authoritative; opening a deep link, changing a client value or using an AI request never grants access." },
    { heading: "End-to-end encryption", body: "ReDom private personal messaging uses client-side encryption before transmission. Each installed device has its own X25519 encryption identity. A message is encrypted into a separate recipient envelope for every active authorized device, including the sender's devices for local history. The backend stores ciphertext/envelopes and metadata but does not require plaintext for send, edit, list or notification delivery." },
    { heading: "Conversation discovery and previews", body: "Conversation-list endpoints return conversation metadata, unread state and safe message metadata only; they do not expose plaintext previews from encrypted chats. The authorized chat screen loads encrypted message envelopes and decrypts them on the user's device." },
    { heading: "Message types", body: "Supported messaging includes text, replies, reactions, photos, video, voice messages, audio, documents, GIFs, stickers and supported shared content. Availability is controlled by platform capability and regional policy." },
    { heading: "Drafts", body: "Drafts are per-user and per-conversation. A draft is private to its owner, must not be exposed through conversation history or notification previews, and should be synchronized only for the authenticated owner's devices. Draft persistence must not turn unsent plaintext into a message visible to other participants." },
    { heading: "Edit", body: "A sent text message may be edited only inside ReDom's supported edit window. The edit must remain authorized for the sender and must preserve encrypted-message handling; encrypted edits are sent as new recipient-device envelopes rather than server-readable plaintext." },
    { heading: "Delete", body: "A user can delete their own copy without changing recipients' copies. Supported messages can be deleted for everyone within the applicable window and are replaced with a deletion placeholder. Group admins may remove another member's message when the group permission permits it. Deleted content is not returned as readable message content." },
    { heading: "Disappearing messages", body: "Conversation message timers apply to new messages only. ReDom supports Off, 24 hours, 7 days and 90 days, matching WhatsApp's documented durations. Existing messages are not retroactively changed. Group permissions can restrict who may change the timer. Messages may be kept where the ReDom lifecycle supports that behavior." },
    { heading: "View once", body: "Photos, videos and voice messages can be marked View Once. A recipient can open the item once; it is then treated as opened and no longer returned as normal attachment content. View Once content cannot be forwarded, copied, saved or starred through ReDom. It expires if not opened within the supported 14-day window. Device-level recording or another camera can still defeat visual privacy, so ReDom does not promise absolute capture prevention." },
    { heading: "Replies and reactions", body: "Replies must target a message in the same authorized conversation. Reactions belong to the authenticated user and can be changed or removed. Deleted or inaccessible messages cannot be used to obtain private content through a reply target." },
    { heading: "Groups", body: "Groups support an owner, admins and members, with backend-enforced permissions for group information, adding members, removing members, admin roles, invite behavior and join approval. ReDom groups support up to 1,024 active members. Group owners cannot be removed and must transfer ownership before leaving." },
    { heading: "Group calls", body: "Group voice calls are designed around authorized group membership and backend-confirmed call state. The product target follows the documented ReDom call capacity rather than allowing a client to invent participants or bypass call permissions." },
    { heading: "Calls", body: "Voice and video calls require authorized conversation membership plus operating-system microphone/camera permission. Ringing, connecting, active, ended, declined, missed, cancelled and failed states are backend-confirmed. ReDom does not expose provider credentials or private signaling secrets." },
    { heading: "Block and report", body: "Blocking stops supported direct messages and calls from the blocked account. Reporting can target a specific message and may optionally block the sender. Reports enter human-review/moderation workflows; AI may assist with explanation or safety signals but cannot silently impose a final moderation decision." },
    { heading: "Notifications and read state", body: "Delivery, read and typing state come from backend state and events. Encrypted message notifications use generic previews such as ‘New message’ and do not include decrypted message text. Recipient notification preferences and mute settings are authoritative. A client cannot fabricate a read receipt, delivery receipt or notification state." },
    { heading: "Read receipts", body: "Read state is conversation-authorized and may be controlled by privacy settings. ReDom must preserve the distinction between unread-count clearing for the local participant and a sender-visible read receipt. Group and direct-chat semantics may differ according to the documented platform behavior being followed." },
    { heading: "Media privacy", body: "Message media is encrypted on the sending device with a random media key. That key is separately wrapped to each active recipient device and stored with that device identifier. The encrypted media object can be stored server-side, but decryption requires the authorized device's private key. Revoked devices cannot retrieve their media-key envelope." },
    { heading: "Linked devices", body: "Each ReDom device has its own X25519 encryption identity and can be independently registered or revoked by the account owner. A new device must present an 8-character, short-lived one-time linking code and the active primary device must approve it before the new device's encryption identity is registered. ReDom permits up to four non-primary linked devices. Encrypted text, edits and media are wrapped separately for every active device in an authorized conversation. Newly linked devices receive messages sent after registration; historical-message transfer is not claimed until a dedicated encrypted history-transfer protocol is implemented. Revoked devices stop receiving new envelopes." },
    { heading: "ReDom AI discovery and navigation", body: "ReDom exposes a dedicated ReDom AI surface from the Chats screen and from an individual Chat. The AI control uses a dedicated SVG ReDom AI logo/icon rather than emoji or text glyphs. The dedicated AI screen provides a new-chat flow, recent AI-chat history, chat options, a general composer, voice prompting, image input and image generation." },
    { heading: "ReDom AI purpose", body: "ReDom AI is a general-purpose assistant, not ReDom Support. It can answer general questions, research, coding, writing, planning, translation, explanations, creative requests and humor. It responds in the language the user is chatting in. The current implementation uses OpenAI server-side with GPT-5.6 Luna and OpenAI web search for current or niche information when useful." },
    { heading: "AI response controls", body: "AI responses support copy, share, positive feedback, negative feedback with a reason, and regenerate. AI-generated images additionally support save-to-photo-library, share, copy of the image prompt, edit/restyle, regenerate and report. Negative feedback uses reasons matching the documented Meta AI feedback pattern: Not relevant, Not accurate, Too repetitive, Harmful or offensive, and Something else." },
    { heading: "AI voice prompts", body: "Users can record a voice prompt from the AI composer. ReDom sends the user-selected recording to the authenticated backend for OpenAI transcription and then submits the resulting transcript as the AI prompt. The OpenAI credential remains server-side. Voice prompting is optional and requires operating-system microphone permission." },
    { heading: "AI image generation and editing", body: "Users can explicitly enter Create image mode or choose Create image from the AI attachment tools. The prompt is sent to the authenticated ReDom backend and OpenAI's configured GPT-Image-2 model returns an image displayed in the AI conversation. A generated image can be explicitly edited/restyled by supplying a new prompt against that selected image. Generated-image actions are explicit and do not silently inspect personal-chat media." },
    { heading: "AI image input", body: "Users can explicitly select a photo from the device gallery or take a new camera photo and attach it to an AI prompt. ReDom compresses the selected image on-device and sends the image data only as part of that user-initiated AI request. AI image input is outside the private-message E2EE boundary because the user explicitly chooses to provide the image to AI." },
    { heading: "AI file analysis", body: "Users can explicitly select a document/file from the system document picker and ask ReDom AI to analyze it. ReDom copies the selected file into app cache, limits AI file analysis to 25 MB, and sends the selected file only for the requested AI workflow. The file is treated as untrusted content and cannot override AI/system instructions. File analysis is outside the private-message E2EE boundary because the user explicitly submits the file to AI." },
    { heading: "AI chat history", body: "ReDom currently keeps AI conversation threads locally on the authenticated device for the dedicated AI screen, including topic titles and response text needed to continue a local thread. Users can start a new AI chat, reopen a prior local AI thread, clear the current thread or delete it. This local history is distinct from encrypted personal message history and is not claimed to be linked-device synchronized until a dedicated encrypted/signed AI-history synchronization protocol exists." },
    { heading: "AI context sharing from Chat", body: "When AI is opened from an individual Chat, ReDom may provide explicitly selected recent chat content to the AI workflow only after the user invokes the AI control. Private message plaintext is not automatically sent to AI merely because the user is in a Chat. Any user-selected chat context supplied to AI is outside the private-message E2EE boundary for that workflow." },
    { heading: "AI privacy and boundaries", body: "ReDom AI cannot read another person's private messages merely because a user asks, cannot bypass encryption, cannot approve reports or refunds, cannot change group ownership, cannot grant membership, cannot override blocks or regional policy, and cannot invent delivery, read, moderation or call states. The AI backend never receives the mobile OpenAI API key." },
    { heading: "AI web information", body: "ReDom AI may use OpenAI web search for current or niche information. Search use is part of the AI workflow and is not a mechanism for reading ReDom private-chat history. AI responses can be inaccurate, and users should verify important information." },
    { heading: "Messaging rate limits", body: "ReDom does not apply a rate limiter to normal Chat, messaging, message-reaction, call, linked-device or in-chat AI traffic. Those endpoints remain protected by authentication, conversation membership, device authorization, input validation and abuse/safety controls, but ordinary use does not consume a rate-limit bucket and cannot produce the previous Chat authentication-attempt rate-limit error." },
    { heading: "Regional policy", body: "Messaging, calling, SMS/email notifications, media and other capabilities can vary by country or region. The backend regional policy is authoritative and cannot be overridden by the client, AI or a provider response." },
    { heading: "Safety and audit", body: "Security-sensitive messaging actions are authorization-checked and may create activity/audit events. ReDom may apply spam, scam, malware and abuse protections using permitted metadata/signals without exposing private content outside an explicitly authorized workflow." },
  ],
};
router.get("/policies/messaging", (_req, res) => { res.json({ success: true, slug: "messaging", version: "2.1.0", effectiveAt: "2026-09-14T00:00:00.000Z", document }); });
export default router;
