import { Router } from "express";

const router = Router();

const document = {
  title: "ReDom Messaging Policy",
  summary: "Privacy, security and messaging rules for ReDom conversations, groups, calls, media and ReDom AI features.",
  version: "3.0.0",
  effectiveAt: "2026-09-15T00:00:00.000Z",
  sections: [
    { heading: "Your chats are private", body: "ReDom private conversations are designed around end-to-end encryption. Private message content is protected before it is sent, and the server routes encrypted content and authorized metadata without requiring private-chat plaintext for ordinary delivery." },
    { heading: "End-to-end encryption", body: "Private message text and message media are encrypted on the sending device. Each active recipient device receives its own protected encryption envelope. If a conversation cannot be securely protected, ReDom does not intentionally fall back to sending the private content as readable plaintext." },
    { heading: "What is protected", body: "The private messaging system protects supported text, replies, reactions, photos, videos, voice messages, audio, documents, GIFs, stickers, shared locations and other supported conversation content. Encrypted media remains protected when stored server-side and requires an authorized device to decrypt it." },
    { heading: "Security verification", body: "A conversation can expose a local encryption-verification surface using a device-derived QR payload and security number. Verification helps participants notice changes to conversation security identities. ReDom never asks users to reveal a private encryption key." },
    { heading: "Linked devices", body: "Each ReDom device has its own encryption identity and can be independently authorized or revoked. A newly authorized device must be securely connected to the account's protected conversations before it can access current encrypted content. A revoked device cannot receive future conversation encryption updates." },
    { heading: "Groups and membership", body: "Group conversations use backend-enforced membership, ownership and administrative permissions. When group membership changes, ReDom refreshes conversation protection so removed participants cannot receive content protected after the change, while newly added members receive only the current authorized conversation protection." },
    { heading: "Group permissions", body: "Group administrators can control who may edit group information, send new messages, add members, share invite links or QR codes, send message history, and whether new join requests require administrator approval. Permission changes are server-authorized and the client cannot bypass them." },
    { heading: "Group invites", body: "ReDom groups can use invitation links and QR codes. Authorized users can copy or share an active invite, and administrators can reset an invite so the previous link becomes inactive. When join approval is enabled, an invite does not by itself make a requester an active member; an administrator must approve the request." },
    { heading: "Group member controls", body: "Supported group management includes adding and removing members, administrator roles, member tags, member-change history and encrypted membership transitions. Administrative actions are enforced by the ReDom backend." },
    { heading: "Group organization", body: "A group can be added to Favorites and supported private chat lists for the authenticated participant. These organization settings do not change group membership, message authorization or another participant's settings." },
    { heading: "Chat controls", body: "ReDom messaging supports replies, reactions, editing, deletion, disappearing messages, View Once content, forwarding limits, media controls, chat lock and Advanced chat privacy. These controls do not turn off conversation encryption." },
    { heading: "Disappearing messages", body: "Supported conversations can use disappearing-message settings of 24 hours, 7 days, 90 days or Off. The selected timer controls new eligible messages and does not retroactively change earlier messages. A group may restrict who can change the timer through its group permissions." },
    { heading: "View Once", body: "Supported photos, videos and voice messages can be sent as View Once content. View Once content is handled outside the normal reusable media workflow and is not available for ordinary saving, starring or forwarding. Users should still share View Once content only with people they trust because recipients can use another device or recording method to capture what they see or hear." },
    { heading: "Forwarding", body: "Eligible messages can be forwarded to existing ReDom conversations subject to the product's forwarding limits. ReDom currently limits a forward operation to up to five destinations, with no more than one group destination; highly forwarded chains are further restricted. Advanced chat privacy blocks forwarding outside a protected conversation." },
    { heading: "Media and attachments", body: "The conversation attachment surface supports Gallery, Camera, Location, Contact, Document, Audio, Poll and Event. Message media uses the encrypted media pipeline. Shared structured content is encrypted before transmission and remains subject to conversation authorization." },
    { heading: "Media privacy", body: "Encrypted media is decrypted only on an authorized device for viewing. ReDom does not silently save encrypted message media to a device gallery. Explicit save actions remain user-controlled, and protected View Once content is excluded from normal gallery and save workflows." },
    { heading: "Notifications and privacy", body: "Group notification settings can enable or mute notifications and can use an All or Highlights preference for supported message notification filtering. Device notification permissions remain authoritative. ReDom notification previews must respect the recipient's current authorization." },
    { heading: "Calls", body: "Voice and video calls require authorized conversation membership and operating-system microphone and camera permissions. Call state and participant authorization are backend-confirmed. ReDom does not expose provider credentials or private signaling secrets through the messaging experience." },
    { heading: "Chat Lock", body: "Chat Lock is a device-local protection for supported conversations. When enabled, opening the protected conversation requires the device's enrolled biometric or device authentication. Chat Lock does not change encryption keys or grant the server additional access to private content." },
    { heading: "Advanced chat privacy", body: "Advanced chat privacy is a server-authorized conversation setting. In a protected conversation, ReDom blocks forwarding outside the chat and disables the in-chat ReDom AI context-sharing control. For groups, changing this setting requires the appropriate owner or administrator permission." },
    { heading: "Profiles and business conversations", body: "Direct chats and message profile actions use ReDom display names and profiles rather than making phone numbers the primary identity presentation. Business profiles may expose configured business information such as account type, verification state, address, email, category and hours; ReDom does not fabricate missing business fields." },
    { heading: "ReDom AI", body: "ReDom AI is a separate, user-invoked experience. Private conversation content is not automatically supplied to ReDom AI merely because a user is viewing a chat. If a user deliberately provides message content, an image, a file or a voice prompt to ReDom AI, that material is handled as part of that explicit AI request. Advanced chat privacy disables automatic chat-context entry for protected conversations." },
    { heading: "Responsible messaging", body: "Use ReDom to communicate lawfully and respectfully. Do not use messaging to harass, threaten, impersonate, defraud, distribute malware, coordinate harmful activity, or repeatedly contact people who do not want to hear from you. ReDom may apply spam, scam, abuse and account-safety controls and may provide blocking and reporting tools." },
    { heading: "Reporting and blocking", body: "Users can use supported blocking and reporting controls to manage unwanted contact and report supported messages or groups. Blocking and membership restrictions are enforced by the backend. Reporting does not give the reporting user access to unrelated private conversation content." },
    { heading: "Privacy boundary", body: "Private conversation content is not exposed through public profile surfaces, ordinary search or AI merely because a user asks for it. Conversation membership, device authorization, encryption and server-side access controls remain authoritative." },
    { heading: "If encryption is unavailable", body: "ReDom fails safely when protected messaging cannot be established. A user may be asked to reconnect or authorize a device before continuing. ReDom does not intentionally send private message content as readable fallback content merely to complete delivery." },
    { heading: "Learn more", body: "For a conversation-specific security check, open the conversation's encryption-verification screen. For group controls such as permissions, invites, disappearing messages, View Once, chat lock, forwarding and Advanced chat privacy, use the supported controls in Group Info and Chat Info. This policy describes the current ReDom messaging behavior and privacy boundary." },
  ],
};

router.get("/policies/messaging", (_req, res) => res.json({ success: true, slug: "messaging", document }));

export default router;
