import { Router } from "express";
const router=Router();
const groupPolicy={version:"2.8.0",effectiveAt:"2026-09-15T00:00:00.000Z",sections:[
{heading:"Conversation encryption boundary",body:"Every ReDom conversation has one conversation encryption context. The context is established before normal message content is allowed. The user-visible model is one encrypted chat, not a separate encryption setup for every message. Individual payloads use authenticated encryption framing with a fresh nonce under the active conversation key."},
{heading:"Conversation key generation and storage",body:"A conversation key is generated on an authorized client device. ReDom's server never receives or stores the plaintext conversation key. The server stores only encrypted key envelopes addressed to authorized active devices plus non-secret key-version and membership metadata."},
{heading:"Text and media encryption",body:"Text, voice messages, photos, videos, documents, audio, GIFs, stickers and other encrypted conversation content use the active conversation encryption context. Each AES-GCM payload has a fresh 96-bit nonce. Ciphertext is routed with authorized device metadata; plaintext is not required by the server for normal delivery."},
{heading:"Encryption readiness",body:"Normal encrypted sending is fail-closed. The client must have an encryption identity and the current conversation key before it can send. If a required identity, key envelope or key version is unavailable, ReDom blocks sending instead of falling back to plaintext or showing ciphertext as the message."},
{heading:"Key versions and rotation",body:"Conversation encryption is versioned. Membership and authorized-device changes advance the conversation key version. A newly generated key is wrapped only to the resulting authorized device set. Server-side envelopes from older versions are retired after rotation, while the client may retain previously authorized local key material needed for its own already-received history."},
{heading:"New members",body:"A newly active group member does not inherit an existing conversation key. Existing authorized clients rotate the conversation key and provision the new version to the active membership set. This prevents a newly added member from gaining access to content encrypted under an earlier membership key merely by joining the conversation."},
{heading:"Member removal and leaving",body:"Before future encrypted content is accepted after a group member is removed or leaves, the conversation key is rotated and the removed/leaving profile is excluded from the new key envelopes. The backend rejects encrypted payloads that identify an obsolete conversation-key version."},
{heading:"Linked-device revocation",body:"When an encryption device is logged out/revoked, affected conversation encryption state is invalidated and a fresh conversation key must be distributed by a remaining authorized device. The revoked device is excluded from future key envelopes. Until rotation succeeds, affected sends fail closed."},
{heading:"Device authorization",body:"Conversation encryption is addressed to active encryption devices, not phone numbers. Each device has its own X25519 identity. Revoked, suspended or inactive devices cannot receive new conversation-key envelopes or message recipients."},
{heading:"Message authentication and nonce safety",body:"Conversation payloads use AES-256-GCM authenticated encryption. Each payload generates a fresh 12-byte nonce. ReDom must never intentionally reuse a nonce with the same AES-GCM key. Authentication failure is treated as decryption failure and never displayed as plaintext."},
{heading:"Encryption verification",body:"Each chat exposes an encryption verification surface with a device-derived QR payload and a 60-digit security number based on active conversation device identities. Verification helps participants detect identity changes; it does not disclose private keys or conversation plaintext to the server."},
{heading:"Encryption privacy notice",body:"The conversation displays the privacy notice: 'Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them.' Tapping the notice opens the privacy sheet. The sheet's Learn more action opens the ReDom Messaging Policy so the user can read the authoritative encryption rules."},
{heading:"Call security",body:"ReDom call signaling is restricted to authenticated conversation members. Native WebRTC call media uses its encrypted media transport between call peers, while the ReDom backend handles authorization and signaling rather than call plaintext. Call transport encryption is a separate media security layer from the conversation message key."},
{heading:"Server privacy boundary",body:"The backend stores encrypted message payloads, encrypted media, encrypted key envelopes and routing/security metadata. It must not decrypt private conversation content merely to deliver it, and client UI state cannot grant access to a conversation or bypass encryption."},
{heading:"Failure and recovery",body:"Encryption failures are fail-closed. A device without the current conversation key cannot send or decrypt current content until an authorized device provisions it. If a conversation requires rotation after membership/device change, the client may recover by generating and distributing the next conversation key to the remaining authorized device set."},
{heading:"Groups",body:"ReDom groups support up to 1,024 active members. Every group has an owner, admins and members. The backend is authoritative for membership, admin roles, group settings, invite links and join approval."},
{heading:"Group permissions",body:"Group admins can control Edit group settings, Send new messages, Add other members, Send message history, Invite via link or QR code, Approve new members and group admin roles. A client cannot bypass an admin-only permission by changing local state."},
{heading:"Reference behavior",body:"ReDom follows corresponding current WhatsApp Help Center behavior where applicable, including the conversation privacy notice, group membership controls, invite behavior, reset semantics, member permissions, message-history option and admin approval model. ReDom's cryptographic protocol is its own implementation and does not claim to reproduce WhatsApp's private internal key schedule."}
]};
router.get("/policies/messaging",(_req,res)=>res.json({success:true,slug:"messaging",title:"ReDom Messaging Policy",summary:"Authoritative rules for ReDom encrypted conversations, messages, media, devices, groups and call security.",...groupPolicy}));
export default router;
