import { Router, type Request, type Response } from "express";
import { authMiddleware } from "../middleware/auth.middleware";
import { pool } from "../database/db";
import { env } from "../config/env";
const router = Router();
const mediaUrl = (key: string | null) => key ? `${env.cloudflare.r2.bucketEndpoint.replace(/\/$/, "")}/${key}` : null;
const formatDate = (value: string | Date | null) => value ? new Date(value).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" }) : null;
const formatMonthYear = (value: string | Date | null) => value ? new Date(value).toLocaleDateString("en-US", { month: "long", year: "numeric" }) : null;
async function getProfile(req: Request, res: Response) {
  try {
    const viewerId = req.user.userId;
    const requestedId = req.params.userId || viewerId;
    const profileResult = await pool.query(`SELECT u.id,u.first_name,u.last_name,u.username,u.public_id,u.profile_id,u.date_of_birth,u.created_at AS joined_at,p.profile_photo,p.cover_photo,p.current_city,p.profile_visibility,p.verified,p.display_join_date,p.friend_count,p.follower_count,p.post_count FROM users u LEFT JOIN user_profiles p ON p.user_id=u.id WHERE u.id=$1 OR u.public_id=$1 OR u.profile_id=$1 LIMIT 1`, [requestedId]);
    if (!profileResult.rows.length) return res.status(404).json({ success:false, message:"Profile not found." });
    const profile=profileResult.rows[0]; const owner=profile.id===viewerId;
    if (!owner && profile.profile_visibility === "private") return res.json({success:true,profile:{userId:profile.id,firstName:profile.first_name,lastName:profile.last_name,username:profile.username,publicId:profile.public_id,profileId:null,profilePhoto:mediaUrl(profile.profile_photo),coverPhoto:mediaUrl(profile.cover_photo),friendCount:profile.friend_count??0,followerCount:profile.follower_count??0,postCount:profile.post_count??0,location:null,birthday:null,joinedAt:formatMonthYear(profile.joined_at),joinedCountry:"Unavailable",verified:!!profile.verified,isOwner:false,friends:[],reels:[],photos:[],posts:[],suggestions:[]}});
    const [friends,posts,reels,photos,country,suggestions]=await Promise.all([
      pool.query(`SELECT u.id,u.first_name,u.last_name,u.username,p.profile_photo FROM friends f JOIN users u ON u.id=f.friend_user_id LEFT JOIN user_profiles p ON p.user_id=u.id WHERE f.user_id=$1 AND f.friendship_status='active' ORDER BY f.friends_since DESC LIMIT 50`,[profile.id]),
      pool.query(`SELECT p.id,p.type,p.content,p.published_at,pm.object_key,pm.thumbnail_key FROM posts p LEFT JOIN LATERAL (SELECT object_key,thumbnail_key FROM post_media WHERE post_id=p.id AND processing_status<>'failed' ORDER BY is_primary DESC,display_order ASC LIMIT 1) pm ON true WHERE p.user_id=$1 AND p.deleted=false ORDER BY p.published_at DESC LIMIT 50`,[profile.id]),
      pool.query(`SELECT p.id,p.published_at,pm.id AS media_id,pm.object_key,pm.thumbnail_key,COALESCE((SELECT COUNT(*) FROM video_views vv WHERE vv.media_id=pm.id AND vv.invalid_view=false),0)::int AS view_count FROM posts p JOIN post_media pm ON pm.post_id=p.id WHERE p.user_id=$1 AND p.deleted=false AND (p.type ILIKE '%reel%' OR pm.media_type ILIKE 'video%') ORDER BY p.published_at DESC LIMIT 20`,[profile.id]),
      pool.query(`SELECT p.id,p.published_at,pm.object_key,pm.thumbnail_key FROM posts p JOIN post_media pm ON pm.post_id=p.id WHERE p.user_id=$1 AND p.deleted=false AND pm.media_type ILIKE 'image%' ORDER BY p.published_at DESC LIMIT 30`,[profile.id]),
      pool.query(`SELECT country FROM login_history WHERE user_id=$1 AND country IS NOT NULL AND country<>'' ORDER BY login_time ASC LIMIT 1`,[profile.id]),
      pool.query(`SELECT u.id,u.first_name,u.last_name,u.username,u.public_id,u.profile_id,p.profile_photo,p.current_city,p.friend_count FROM users u LEFT JOIN user_profiles p ON p.user_id=u.id WHERE u.id<>$1 AND COALESCE(p.profile_visibility,'public')<>'private' AND NOT EXISTS(SELECT 1 FROM friends f WHERE f.user_id=$1 AND f.friend_user_id=u.id AND f.friendship_status='active') AND NOT EXISTS(SELECT 1 FROM friends f WHERE f.user_id=u.id AND f.friend_user_id=$1 AND f.friendship_status='active') ORDER BY p.friend_count DESC NULLS LAST,u.created_at DESC LIMIT 12`,[viewerId])
    ]);
    const result={userId:profile.id,firstName:profile.first_name,lastName:profile.last_name,username:profile.username,publicId:profile.public_id,profileId:profile.profile_id,profilePhoto:mediaUrl(profile.profile_photo),coverPhoto:mediaUrl(profile.cover_photo),friendCount:profile.friend_count??friends.rowCount??0,followerCount:profile.follower_count??0,postCount:profile.post_count??posts.rowCount??0,location:profile.current_city||null,birthday:formatDate(profile.date_of_birth),joinedAt:formatMonthYear(profile.joined_at),joinedCountry:country.rows[0]?.country||"Unavailable",verified:!!profile.verified,isOwner:owner,friends:friends.rows.map(f=>({userId:f.id,firstName:f.first_name,lastName:f.last_name,username:f.username,profilePhoto:mediaUrl(f.profile_photo)})),reels:reels.rows.map(r=>({id:r.id,thumbnail:mediaUrl(r.thumbnail_key||r.object_key),viewCount:r.view_count||0})),photos:photos.rows.map(r=>({id:r.id,url:mediaUrl(r.object_key),thumbnail:mediaUrl(r.thumbnail_key||r.object_key)})),posts:posts.rows.map(r=>({id:r.id,type:r.type,content:r.content,publishedAt:r.published_at,mediaUrl:mediaUrl(r.object_key),thumbnail:mediaUrl(r.thumbnail_key||r.object_key)})),suggestions:suggestions.rows.map(s=>({userId:s.id,firstName:s.first_name,lastName:s.last_name,username:s.username,publicId:s.public_id,profileId:s.profile_id,profilePhoto:mediaUrl(s.profile_photo),currentCity:s.current_city,friendCount:s.friend_count||0}))};
    return res.json({success:true,profile:result});
  } catch(error){ console.error("Profile request failed",error); return res.status(500).json({success:false,message:"Unable to load this profile right now."}); }
}
router.get("/",authMiddleware,getProfile);
router.get("/:userId",authMiddleware,getProfile);
router.post("/suggestions/:userId/add",authMiddleware,async(req:Request,res:Response)=>{try{const viewerId=req.user.userId,targetId=req.params.userId;const blocked=await pool.query(`SELECT 1 FROM blocked_users WHERE (user_id=$1 AND blocked_user_id=$2) OR (user_id=$2 AND blocked_user_id=$1) LIMIT 1`,[viewerId,targetId]);if(blocked.rowCount)return res.status(409).json({success:false,reason:"You might not know this person, or one of you has blocked the other."});const existing=await pool.query(`SELECT 1 FROM friends WHERE (user_id=$1 AND friend_user_id=$2) OR (user_id=$2 AND friend_user_id=$1) LIMIT 1`,[viewerId,targetId]);if(existing.rowCount)return res.json({success:false,reason:"You are already connected with this person."});const pending=await pool.query(`SELECT 1 FROM friend_requests WHERE ((sender_id=$1 AND receiver_id=$2) OR (sender_id=$2 AND receiver_id=$1)) AND status='pending' LIMIT 1`,[viewerId,targetId]);if(pending.rowCount)return res.json({success:false,reason:"A friend request between you is already pending."});return res.json({success:false,reason:"You might not know this person or you may be too far away to add them right now. ReDom limits some recommendations and connection requests for safety."});}catch{return res.status(500).json({success:false,reason:"We couldn't send the request right now. Please try again."});}});
export default router;
