import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import ReDomLogo from "../../assets/brand/redom-logo.svg";
import InfoBlack from "../../assets/auth/info-black.svg";
import { authService } from "../../auth/service";
import type { RootStackParamList } from "../../routing/types";
type Props = NativeStackScreenProps<RootStackParamList, "RegistrationVerification">;
const BLUE="#1877F2", TEXT="#1C1E21", MUTED="#65676B", ERROR="#E41E3F";
export function RegistrationVerificationScreen({route,navigation}:Props){const {verificationChallengeId,maskedTarget,channel,expiresAt}=route.params;const [code,setCode]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [seconds,setSeconds]=useState(()=>Math.max(0,Math.floor((new Date(expiresAt).getTime()-Date.now())/1000)));useEffect(()=>{const i=setInterval(()=>setSeconds(Math.max(0,Math.floor((new Date(expiresAt).getTime()-Date.now())/1000))),1000);return()=>clearInterval(i)},[expiresAt]);async function verify(){if(code.length!==6||busy||seconds<=0)return;setBusy(true);setError(null);try{await authService.verifyRegistrationChallenge(verificationChallengeId,code);navigation.replace("Login");}catch(e){setError(e instanceof Error?e.message:"The verification code is invalid or expired.");}finally{setBusy(false)}}return <View style={s.root}><View style={s.content}><ReDomLogo width={154} height={44}/><View style={s.icon}><InfoBlack width={26} height={26}/></View><Text style={s.title}>Enter Your Verification Code</Text><Text style={s.description}>We sent a 6-digit verification code by {channel === "sms" ? "SMS" : "email"} to {maskedTarget}.</Text><Text style={s.flow}>Flow ID: {route.params.flowId}</Text><TextInput value={code} onChangeText={v=>setCode(v.replace(/\D/g,"").slice(0,6))} keyboardType="number-pad" maxLength={6} autoFocus style={s.input} placeholder="000000" placeholderTextColor="#9A9DA1" editable={!busy&&seconds>0}/>{error?<Text style={s.error}>{error}</Text>:null}<Text style={s.timer}>{seconds>0?`Code expires in ${Math.floor(seconds/60).toString().padStart(2,"0")}:${(seconds%60).toString().padStart(2,"0")}`:"Code expired"}</Text><Pressable disabled={code.length!==6||busy||seconds<=0} onPress={()=>void verify()} style={[s.button,(code.length!==6||busy||seconds<=0)&&s.disabled]}>{busy?<ActivityIndicator color="#FFF"/>:<Text style={s.buttonText}>Verify Account</Text>}</Pressable><Text style={s.note}>Never share this verification code with anyone.</Text></View><View style={s.footer}><Text style={s.copy}>© ReDom</Text><ReDomLogo width={76} height={21}/></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#FFF"},content:{flex:1,alignItems:"center",padding:22,paddingTop:38},icon:{marginTop:45},title:{fontSize:28,lineHeight:34,fontWeight:"900",color:TEXT,textAlign:"center",marginTop:16},description:{fontSize:14.5,lineHeight:21,color:TEXT,textAlign:"center",marginTop:10},flow:{fontSize:13,color:BLUE,fontWeight:"800",marginTop:15},input:{width:"100%",height:62,borderWidth:1.5,borderColor:"#CCD0D5",borderRadius:14,textAlign:"center",fontSize:26,fontWeight:"900",letterSpacing:8,color:TEXT,marginTop:24},timer:{fontSize:12.5,color:MUTED,marginTop:12},button:{width:"100%",height:55,borderRadius:14,backgroundColor:BLUE,alignItems:"center",justifyContent:"center",marginTop:20},disabled:{opacity:.5},buttonText:{color:"#FFF",fontSize:16.5,fontWeight:"900"},error:{color:ERROR,fontWeight:"700",fontSize:13,marginTop:10,textAlign:"center"},note:{fontSize:12,color:MUTED,marginTop:15,textAlign:"center"},footer:{alignItems:"center",gap:5,marginTop:"auto",paddingBottom:24},copy:{color:MUTED,fontSize:12}});
