import { createHash, randomUUID } from "node:crypto";
import { and, count, eq, gt } from "drizzle-orm";
import { db } from "../database/db";
import { reDomAiSecurityEvents } from "../database/reDomAiSecurityEvents";
import { env } from "../config/env";
import { openai } from "../lib/openai";

type Risk = "SAFE" | "LOW" | "MODERATE" | "HIGH" | "CRITICAL";
type Decision = { requestId: string; action: "allow" | "block"; policyCode: string; riskLevel: Risk; providerSignals: Record<string, unknown>; userMessage?: string };
const GOVERNMENT = /\b(passport|driver\x27?s? license|national id|identity card|id card|voter(?:\x27s)? card|residence permit|visa|birth certificate|government id|mrz|barcode|official document)\b/i;
const FINANCIAL = /\b(bank statement|routing number|account number|iban|swift|invoice|credit card|debit card|balance|salary slip|pay stub|financial statement|transaction receipt)\b/i;
const FRAUD = /\b(fake|forged|forge|counterfeit|fabricat|falsif|make (?:it|this) look real|undetectable|bypass verification|evade detection|fake identity|stolen identity)\b/i;
const DECEPTIVE = /\b(deepfake|deep fake|impersonat|clone (?:a|the) (?:person|voice|face)|make (?:someone|a person) say|mislead|deceive|pretend to be|false evidence|fabricated evidence)\b/i;
const SEXUAL = /\b(porn|pornographic|explicit sex|sexual intercourse|nude|nudity|naked|sexually explicit|erotic sexual|genital|sexualized)\b/i;
const IDENTITY_EDIT = /\b(face|likeness|identity|portrait)\b.{0,80}\b(swap|replace|change|edit|alter|clone|impersonat|deepfake)\b/i;
const UNSAFE = /\b(extremist propaganda|terrorist propaganda|instructions? to (?:make|build) a weapon|graphic sexual violence|child sexual|exploit(?:ing|ative) minors)\b/i;
function userHash(userId: string) { return createHash("sha256").update(userId).digest("hex").slice(0, 24); }
async function record(userId: string, d: Decision, metadata?: Record<string, unknown>) { await db.insert(reDomAiSecurityEvents).values({ userId, requestId: d.requestId, operation: "video_generate", policyCode: d.policyCode, riskLevel: d.riskLevel, action: d.action, documentClass: "video", providerSignals: d.providerSignals, metadata: { ...metadata, user: userHash(userId) } }); }
async function recentBlocks(userId: string) { const since = new Date(Date.now() - 3600000); const rows = await db.select({ total: count() }).from(reDomAiSecurityEvents).where(and(eq(reDomAiSecurityEvents.userId, userId), eq(reDomAiSecurityEvents.action, "block"), gt(reDomAiSecurityEvents.createdAt, since))); return Number(rows[0]?.total ?? 0); }
async function moderate(prompt: string) { try { const r = await openai.moderations.create({ model: "omni-moderation-latest", input: prompt }); return { flagged: Boolean(r.results?.[0]?.flagged), categories: r.results?.[0]?.categories ?? {} }; } catch (error) { return { flagged: false, error: error instanceof Error ? error.message : "moderation unavailable" }; } }
async function geminiClassify(prompt: string) {
 const response = await fetch("https://generativelanguage.googleapis.com/v1beta/interactions", { method: "POST", headers: { "content-type": "application/json", "x-goog-api-key": env.gemini.apiKey }, body: JSON.stringify({ model: process.env.REDOM_VIDEO_SECURITY_GEMINI_MODEL?.trim() || "gemini-3.8-flash", store: false, input: "Classify this ReDom video request. Return JSON only. Detect identity manipulation, deceptive/deepfake media, fraud, forged evidence, sexual or explicit content, and unsafe content. Request: " + prompt }) });
 const body: any = await response.json(); if (!response.ok) throw new Error(body?.error?.message || "Gemini classification failed.");
 const text = body?.output_text || body?.outputs?.find((x: any) => x?.type === "text")?.text || body?.steps?.flatMap((x: any) => x?.content || []).find((x: any) => x?.type === "text")?.text; if (!text) throw new Error("Gemini returned no classification."); return JSON.parse(String(text).trim());
}
export async function enforceReDomVideoPromptSecurity(userId: string, prompt: string): Promise<Decision> {
 const clean = prompt.trim(); const requestId = "vidsec_" + randomUUID().replace(/-/g, "");
 if (await recentBlocks(userId) >= 5) { const d: Decision = { requestId, action: "block", policyCode: "UNKNOWN_HIGH_RISK", riskLevel: "CRITICAL", providerSignals: {}, userMessage: "Video generation is temporarily restricted after repeated blocked requests. Please try again later." }; await record(userId, d, { phase: "abuse-prevention" }); throw Object.assign(new Error(d.userMessage), { code: d.policyCode, status: 429 }); }
 const openaiSignal = await moderate(clean); if (openaiSignal.flagged) { const d: Decision = { requestId, action: "block", policyCode: "UNSAFE_CONTENT", riskLevel: "HIGH", providerSignals: { openai: openaiSignal }, userMessage: "I can’t create that video. Please make a request that follows ReDom’s video safety requirements." }; await record(userId, d); throw Object.assign(new Error(d.userMessage), { code: d.policyCode, status: 400 }); }
 let g: any = {}; try { g = await geminiClassify(clean); } catch (error) { g = { error: error instanceof Error ? error.message : "Gemini unavailable" }; }
 const identity = IDENTITY_EDIT.test(clean) || Boolean(g.identityManipulation); const deceptive = DECEPTIVE.test(clean) || Boolean(g.deceptiveMedia); const fraud = FRAUD.test(clean) || GOVERNMENT.test(clean) || FINANCIAL.test(clean) || Boolean(g.fraud) || Boolean(g.protectedDocument); const sexual = SEXUAL.test(clean) || Boolean(g.sexualContent); const unsafe = UNSAFE.test(clean) || Boolean(g.unsafeContent) || Boolean(g.blocked);
 let policyCode = "SAFE_TRANSFORMATION"; let riskLevel: Risk = "LOW"; let blocked = false;
 if (sexual) { blocked = true; policyCode = "SEXUALLY_EXPLICIT_MEDIA"; riskLevel = "CRITICAL"; } else if (identity) { blocked = true; policyCode = "IDENTITY_PHOTO_MODIFICATION"; riskLevel = "CRITICAL"; } else if (deceptive) { blocked = true; policyCode = "DECEPTIVE_MEDIA"; riskLevel = "CRITICAL"; } else if (fraud) { blocked = true; policyCode = "FRAUD_ASSISTANCE"; riskLevel = "CRITICAL"; } else if (unsafe) { blocked = true; policyCode = "UNSAFE_CONTENT"; riskLevel = "HIGH"; }
 const d: Decision = { requestId, action: blocked ? "block" : "allow", policyCode, riskLevel, providerSignals: { openai: openaiSignal, gemini: g }, userMessage: blocked ? "I can’t create or transform that video request. Please choose a safe creative request that does not manipulate identity, create deceptive evidence, assist fraud, or contain explicit sexual content." : undefined }; await record(userId, d, { phase: "input" }); if (blocked) throw Object.assign(new Error(d.userMessage), { code: policyCode, status: 400 }); return d;
}
export async function enforceReDomVideoOutputSecurity(userId: string, requestId: string, videoBytes: Buffer) {
 const start = await fetch("https://generativelanguage.googleapis.com/upload/v1beta/files", { method: "POST", headers: { "x-goog-api-key": env.gemini.apiKey, "X-Goog-Upload-Protocol": "resumable", "X-Goog-Upload-Command": "start", "X-Goog-Upload-Header-Content-Length": String(videoBytes.length), "X-Goog-Upload-Header-Content-Type": "video/mp4", "Content-Type": "application/json" }, body: JSON.stringify({ file: { display_name: "redom-video-" + requestId + ".mp4" } }) });
 if (!start.ok) throw new Error("Gemini video upload could not be started."); const uploadUrl = start.headers.get("x-goog-upload-url"); if (!uploadUrl) throw new Error("Gemini did not return a video upload URL.");
 const uploaded = await fetch(uploadUrl, { method: "POST", headers: { "Content-Length": String(videoBytes.length), "X-Goog-Upload-Offset": "0", "X-Goog-Upload-Command": "upload, finalize" }, body: videoBytes }); const uploadedBody: any = await uploaded.json(); if (!uploaded.ok) throw new Error(uploadedBody?.error?.message || "Gemini video upload failed.");
 const fileName = uploadedBody?.file?.name; const fileUri = uploadedBody?.file?.uri; if (!fileName || !fileUri) throw new Error("Gemini video file metadata is incomplete.");
 let state = "PROCESSING"; for (let i = 0; i < 90 && state === "PROCESSING"; i++) { await new Promise((resolve) => setTimeout(resolve, 2000)); const sr = await fetch("https://generativelanguage.googleapis.com/v1beta/" + fileName, { headers: { "x-goog-api-key": env.gemini.apiKey } }); const sb: any = await sr.json(); state = sb?.state || sb?.file?.state || "FAILED"; if (state === "FAILED") throw new Error("Gemini could not process the generated video."); }
 const interaction = await fetch("https://generativelanguage.googleapis.com/v1beta/interactions", { method: "POST", headers: { "content-type": "application/json", "x-goog-api-key": env.gemini.apiKey }, body: JSON.stringify({ model: process.env.REDOM_VIDEO_SECURITY_GEMINI_MODEL?.trim() || "gemini-3.8-flash", store: false, input: [{ type: "video", uri: fileUri, mime_type: "video/mp4", processing: "static" }, { type: "text", text: "Inspect the entire video. Return JSON only with booleans: identityManipulation, deceptiveMedia, fraud, sexualContent, unsafeContent, blocked. Detect unauthorized likeness/face replacement, deepfake deception, forged official/financial evidence, fraud assistance, explicit sexual content or nudity, child sexual content, and dangerous unsafe content. Ordinary fictional characters and harmless CGI are allowed." }] }) });
 const body: any = await interaction.json(); if (!interaction.ok) throw new Error(body?.error?.message || "Gemini output validation failed."); const text = body?.output_text || body?.outputs?.find((x: any) => x?.type === "text")?.text || body?.steps?.flatMap((x: any) => x?.content || []).find((x: any) => x?.type === "text")?.text; if (!text) throw new Error("Gemini returned no output validation."); const result = JSON.parse(String(text).trim());
 const blocked = Boolean(result.blocked || result.identityManipulation || result.deceptiveMedia || result.fraud || result.sexualContent || result.unsafeContent); const policyCode = result.sexualContent ? "SEXUALLY_EXPLICIT_MEDIA" : result.identityManipulation ? "IDENTITY_PHOTO_MODIFICATION" : result.deceptiveMedia ? "DECEPTIVE_MEDIA" : result.fraud ? "FRAUD_ASSISTANCE" : result.unsafeContent ? "UNSAFE_CONTENT" : "SAFE_TRANSFORMATION"; const d: Decision = { requestId, action: blocked ? "block" : "allow", policyCode, riskLevel: blocked ? "CRITICAL" : "LOW", providerSignals: { gemini: result }, userMessage: blocked ? "The generated video did not pass ReDom’s security validation and was not made available." : undefined }; await record(userId, d, { phase: "output" }); if (blocked) throw Object.assign(new Error(d.userMessage), { code: policyCode, status: 400 });
}