import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { messageService } from "../messages/messageService";
import { api } from "../api/client";
import { NavigationIcon } from "../components/NavigationIcon";
import { ChatInfoIcon } from "../components/ChatInfoIcon";
type Props=NativeStackScreenProps<RootStackParamList,"AddToGroups">;
export function AddToGroupsScreen({route,navigation}:Props){const [groups,setGroups]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState<string|null>(null);useEffect(()=>{let active=true;void messageService.listConversations().then((result)=>{if(active)setGroups(result.conversations.filter((item:any)=>item.type==="group"||item.conversationType==="group"));}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);const add=async(id:string,name:string)=>{setBusy(id);try{await api.post(`/messages/groups/${id}/members`,{profileIds:[route.params.profileId]});Alert.alert("Added to group",`${route.params.displayName} was added to ${name}.`);}catch(e){Alert.alert("Could not add contact",e instanceof Error?e.message:"The contact could not be added to this group.")}finally{setBusy(null)}};return <SafeAreaView style={styles.root}><View style={styles.header}><Pressable onPress={()=>navigation.goBack()}><NavigationIcon kind="back" size={27}/></Pressable><View style={styles.copy}><Text style={styles.title}>Add to groups</Text><Text style={styles.sub}>{route.params.displayName}</Text></View></View>{loading?<View style={styles.center}><ActivityIndicator size="large" color="#1877F2"/></View>:<FlatList data={groups} keyExtractor={(item)=>item.id} contentContainerStyle={styles.list} renderItem={({item})=><View style={styles.row}><View style={styles.icon}><ChatInfoIcon name="group" size={25} color="#FFF"/></View><View style={styles.copy}><Text style={styles.name}>{item.groupName||item.displayName||"Group"}</Text><Text style={styles.meta}>Group chat</Text></View><Pressable style={styles.add} disabled={Boolean(busy)} onPress={()=>void add(item.id,item.groupName||item.displayName||"Group")}><Text style={styles.addText}>{busy===item.id?"Adding…":"Add"}</Text></Pressable></View>} ListEmptyComponent={<View style={styles.center}><Text style={styles.empty}>You are not in any groups yet.</Text></View>}/>}</SafeAreaView>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:"#FFF"},header:{height:62,borderBottomWidth:1,borderBottomColor:"#EAECF0",flexDirection:"row",alignItems:"center",paddingHorizontal:14},copy:{flex:1,marginLeft:12},title:{fontSize:19,fontWeight:"800",color:"#101828"},sub:{fontSize:12,color:"#667085",marginTop:2},list:{padding:8},row:{minHeight:72,flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderBottomColor:"#EAECF0",paddingHorizontal:8},icon:{width:46,height:46,borderRadius:23,backgroundColor:"#19A974",alignItems:"center",justifyContent:"center"},name:{fontSize:15,fontWeight:"700",color:"#101828"},meta:{fontSize:12,color:"#667085",marginTop:2},add:{minWidth:72,minHeight:40,borderRadius:10,backgroundColor:"#1877F2",alignItems:"center",justifyContent:"center"},addText:{color:"#FFF",fontWeight:"800"},center:{flex:1,alignItems:"center",justifyContent:"center",padding:24},empty:{color:"#667085"}});
