import { useState } from "react";
import { useTheme } from "../theme/ThemeProvider";
import { ActivityIndicator, Modal, Pressable, Share, StyleSheet, Text, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { api } from "../api/client";
import { messageService } from "../messages/messageService";
import { AttachmentIcon } from "../messages/AttachmentIcon";

export function CallToolsOverlay({conversationId,visible,onClose}:{conversationId:string;visible:boolean;onClose:()=>void}){const navigation=useNavigation<any>();const [busy,setBusy]=useState(false);const [link,setLink]=useState<any>(null);async function start(callType:"voice"|"video"){setBusy(true);try{const r=await messageService.createCall(conversationId,callType);onClose();navigation.navigate("Call",{conversationId,callType,callId:r.call.id});}finally{setBusy(false);}}async function create(callType:"voice"|"video",requireApproval:boolean){setBusy(true);try{const r=await api.post<any>(`/calls/conversations/${conversationId}`,{callType,requireApproval,expiresInHours:24});setLink(r);}finally{setBusy(false);}}async function share(){if(!link)return;await Share.share({message:`Join my ReDom ${link.callType} call: ${link.deepLink}`});}return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.overlay}><View style={s.sheet}><View style={s.handle}/><View style={s.header}><Text style={s.title}>Call</Text><Pressable onPress={onClose}><Text style={s.close}>Close</Text></Pressable></View>{link?<><View style={s.link}><AttachmentIcon kind="callLink" size={24}/><Text style={s.linkText}>{link.deepLink}</Text></View><Text style={s.helper}>{link.requireApproval?"People who open this link enter a waiting room until you approve them.":"Anyone with this secure link can request to join the call."}</Text><Pressable style={s.primary} onPress={()=>void share()}><Text style={s.primaryText}>Share link</Text></Pressable><Pressable style={s.secondary} onPress={()=>setLink(null)}><Text style={s.secondaryText}>Create another link</Text></Pressable></>:<><View style={s.grid}><Pressable style={s.item} onPress={()=>void start("voice")}><View style={s.icon}><AttachmentIcon kind="voice" size={25}/></View><Text style={s.label}>Voice call</Text></Pressable><Pressable style={s.item} onPress={()=>void start("video")}><View style={s.icon}><AttachmentIcon kind="video" size={25}/></View><Text style={s.label}>Video call</Text></Pressable><Pressable style={s.item} onPress={()=>void create("video",false)}><View style={s.icon}><AttachmentIcon kind="callLink" size={25}/></View><Text style={s.label}>Send call link</Text></Pressable><Pressable style={s.item} onPress={()=>void create("video",true)}><View style={s.icon}><AttachmentIcon kind="callLink" size={25}/></View><Text style={s.label}>Call link with approval</Text></Pressable></View></>}{busy?<ActivityIndicator style={s.busy}/>:null}</View></View></Modal>}
function makeStyles(colors: ReturnType<typeof useTheme>["colors"]) { return StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(0,0,0,.35)",justifyContent:"flex-end"},sheet:{backgroundColor:colors.surface,borderTopLeftRadius:24,borderTopRightRadius:24,padding:16},handle:{width:40,height:4,borderRadius:2,backgroundColor:"#CCD0D5",alignSelf:"center",marginBottom:8},header:{minHeight:48,flexDirection:"row",alignItems:"center"},title:{flex:1,fontSize:20,fontWeight:"800",color:colors.text},close:{fontSize:14,fontWeight:"700",color:colors.primary},grid:{flexDirection:"row",flexWrap:"wrap"},item:{width:"50%",minHeight:110,alignItems:"center",justifyContent:"center"},icon:{width:54,height:54,borderRadius:27,backgroundColor:colors.background,alignItems:"center",justifyContent:"center"},label:{marginTop:7,fontSize:14,fontWeight:"700",color:colors.text,textAlign:"center"},busy:{marginTop:8},link:{flexDirection:"row",alignItems:"center",gap:10,backgroundColor:colors.background,padding:12,borderRadius:12},linkText:{flex:1,color:colors.textSecondary,fontSize:14},helper:{color:colors.textSecondary,fontSize:13,lineHeight:18,marginTop:10},primary:{minHeight:48,borderRadius:12,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",marginTop:14},primaryText:{color:"#fff",fontSize:16,fontWeight:"800"},secondary:{minHeight:48,alignItems:"center",justifyContent:"center",marginTop:4},secondaryText:{color:colors.primary,fontSize:15,fontWeight:"800"}}); }