import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Modal, Pressable, Share, StyleSheet, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as ImagePicker from "expo-image-picker";
import { File } from "expo-file-system";
import { useNavigation } from "@react-navigation/native";
import { messageService, type ConversationSummary } from "../messages/messageService";
import { sharedContentService, type SharedContentType } from "../messages/sharedContentService";
import { AttachmentIcon, type AttachmentIconKind } from "../messages/AttachmentIcon";
import { api } from "../api/client";

interface Props { conversationId: string; visible: boolean; mode: "attachment" | "call"; onClose: () => void; onChanged?: () => void; }
type ComposeKind="poll"|"event"|"location";

export function ChatToolsOverlay({ conversationId, visible, mode, onClose, onChanged }: Props) {
  const navigation=useNavigation<any>(); const [busy,setBusy]=useState(false); const [shareLink,setShareLink]=useState<{token:string;deepLink:string;callId:string;callType:"voice"|"video";requireApproval:boolean}|null>(null); const [compose,setCompose]=useState<ComposeKind|null>(null); const [title,setTitle]=useState(""); const [details,setDetails]=useState(""); const [contacts,setContacts]=useState<ConversationSummary[]>([]); const [contactPicker,setContactPicker]=useState(false); const [joinRequests,setJoinRequests]=useState<any[]>([]);
  const attachmentItems=useMemo<Array<{kind:AttachmentIconKind;label:string;action:()=>void}>>(()=>[
    {kind:"gallery",label:"Gallery",action:()=>void pickImage(false)}, {kind:"camera",label:"Camera",action:()=>void pickImage(true)}, {kind:"location",label:"Location",action:()=>setCompose("location")}, {kind:"contact",label:"Contact",action:()=>void openContacts()}, {kind:"document",label:"Document",action:()=>void pickDocument("document")}, {kind:"audio",label:"Audio",action:()=>void pickDocument("audio")}, {kind:"poll",label:"Poll",action:()=>setCompose("poll")}, {kind:"event",label:"Event",action:()=>setCompose("event")},
  ],[conversationId]);
  const callItems=[{kind:"voice" as AttachmentIconKind,label:"Voice call",action:()=>void startCall("voice")},{kind:"video" as AttachmentIconKind,label:"Video call",action:()=>void startCall("video")},{kind:"callLink" as AttachmentIconKind,label:"Send call link",action:()=>void createCallLink("video")}];
  function finish(){onClose();onChanged?.();}
  async function pickImage(camera:boolean){setBusy(true);try{const permission=camera?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)throw new Error(camera?"Camera access is required.":"Photo access is required.");const result=camera?await ImagePicker.launchCameraAsync({mediaTypes:["images"],quality:0.85,base64:true}):await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:0.85,base64:true});if(result.canceled||!result.assets[0]?.base64)return;const asset=result.assets[0];await messageService.sendMedia(conversationId,"photo",`data:image/jpeg;base64,${asset.base64}`);finish();}catch(e){Alert.alert("Attachment",e instanceof Error?e.message:"Unable to attach the image.");}finally{setBusy(false);}}
  async function pickDocument(kind:"document"|"audio"){setBusy(true);try{const result=await DocumentPicker.getDocumentAsync({type:kind==="audio"?"audio/*":"*/*",copyToCacheDirectory:true,multiple:false});if(result.canceled||!result.assets[0])return;const asset=result.assets[0];const file=new File(asset.uri);const base64=await file.base64();const type=kind==="audio"?"audio":"document";await messageService.sendMedia(conversationId,type,`data:${asset.mimeType||"application/octet-stream"};base64,${base64}`,{caption:asset.name});finish();}catch(e){Alert.alert("Attachment",e instanceof Error?e.message:"Unable to attach the file.");}finally{setBusy(false);}}
  async function openContacts(){setBusy(true);try{const result=await messageService.listConversations();setContacts(result.conversations.filter(x=>x.type==="direct"&&x.peerProfileId&&x.id!==conversationId));setContactPicker(true);}catch(e){Alert.alert("Contacts",e instanceof Error?e.message:"Unable to load contacts.");}finally{setBusy(false);}}
  async function shareContact(item:ConversationSummary){if(!item.peerProfileId)return;setBusy(true);try{await sharedContentService.send(conversationId,"contact",{profileId:item.peerProfileId,displayName:item.displayName||"ReDom profile"});setContactPicker(false);finish();}catch(e){Alert.alert("Contact",e instanceof Error?e.message:"Unable to share contact.");}finally{setBusy(false);}}
  async function sendStructured(){if(!compose||!title.trim())return;setBusy(true);try{let type:SharedContentType=compose;let payload:any={title:title.trim(),details:details.trim()};if(compose==="location"){const [lat,lon]=details.split(",").map(v=>Number(v.trim()));if(!Number.isFinite(lat)||!Number.isFinite(lon))throw new Error("Enter location as latitude, longitude.");payload={title:title.trim()||"Shared location",latitude:lat,longitude:lon,mapUrl:`https://www.google.com/maps/search/?api=1&query=${lat},${lon}`};}if(compose==="poll")payload={question:title.trim(),options:details.split(",").map(v=>v.trim()).filter(Boolean).slice(0,12)};if(compose==="event")payload={title:title.trim(),details:details.trim()};await sharedContentService.send(conversationId,type,payload);setCompose(null);setTitle("");setDetails("");finish();}catch(e){Alert.alert("Shared content",e instanceof Error?e.message:"Unable to send shared content.");}finally{setBusy(false);}}
  async function startCall(callType:"voice"|"video"){setBusy(true);try{const result=await messageService.createCall(conversationId,callType);onClose();navigation.navigate("Call",{conversationId,callType,callId:result.call.id});}catch(e){Alert.alert("Call",e instanceof Error?e.message:"Unable to start call.");}finally{setBusy(false);}}
  async function createCallLink(callType:"voice"|"video"){setBusy(true);try{const result=await api.post<any>(`/calls/conversations/${conversationId}`,{callType,requireApproval:false,expiresInHours:24});setShareLink(result);const requests=await api.get<any[]>(`/calls/${result.token}/requests`).catch(()=>({requests:[]}));setJoinRequests((requests as any).requests||[]);}catch(e){Alert.alert("Call link",e instanceof Error?e.message:"Unable to create call link.");}finally{setBusy(false);}}
  async function shareCreatedLink(){if(!shareLink)return;await Share.share({message:`Join my ReDom ${shareLink.callType} call: ${shareLink.deepLink}`});}
  async function approve(profileId:string,decision:"approved"|"rejected"){if(!shareLink)return;try{await api.post(`/calls/${shareLink.token}/requests/${profileId}`,{decision});const r=await api.get<any>(`/calls/${shareLink.token}/requests`);setJoinRequests(r.requests||[]);}catch(e){Alert.alert("Call approval",e instanceof Error?e.message:"Unable to update the request.");}}
  const items=mode==="attachment"?attachmentItems:callItems;
  return <>
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.handle}/><View style={styles.header}><Text style={styles.title}>{mode==="attachment"?"Attach":"Call"}</Text><Pressable onPress={onClose}><Text style={styles.close}>Close</Text></Pressable></View><FlatList data={items} numColumns={2} keyExtractor={(x)=>x.label} contentContainerStyle={styles.grid} renderItem={({item})=><Pressable disabled={busy} onPress={item.action} style={styles.item}><View style={styles.icon}><AttachmentIcon kind={item.kind} size={25}/></View><Text style={styles.label}>{item.label}</Text></Pressable>}/>{busy?<ActivityIndicator style={styles.busy}/>:null}</View></View></Modal>
    <Modal visible={!!compose} transparent animationType="slide" onRequestClose={()=>setCompose(null)}><View style={styles.overlay}><View style={styles.compose}><View style={styles.header}><Text style={styles.title}>{compose==="poll"?"Create poll":compose==="event"?"Create event":"Share location"}</Text><Pressable onPress={()=>setCompose(null)}><Text style={styles.close}>Close</Text></Pressable></View><TextInput value={title} onChangeText={setTitle} placeholder={compose==="location"?"Location name":"Title or question"} placeholderTextColor="#65676B" style={styles.input}/><TextInput value={details} onChangeText={setDetails} placeholder={compose==="poll"?"Options separated by commas":compose==="location"?"Latitude, longitude":"Details"} placeholderTextColor="#65676B" style={[styles.input,styles.multiline]} multiline/><Pressable disabled={!title.trim()||busy} onPress={()=>void sendStructured()} style={[styles.primary,(!title.trim()||busy)&&styles.disabled]}><Text style={styles.primaryText}>Share</Text></Pressable></View></View></Modal>
    <Modal visible={contactPicker} transparent animationType="slide" onRequestClose={()=>setContactPicker(false)}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.header}><Text style={styles.title}>Share contact</Text><Pressable onPress={()=>setContactPicker(false)}><Text style={styles.close}>Close</Text></Pressable></View><FlatList data={contacts} keyExtractor={(x)=>x.id} renderItem={({item})=><Pressable onPress={()=>void shareContact(item)} style={styles.contactRow}><AttachmentIcon kind="contact" size={22}/><Text style={styles.contactName}>{item.displayName||"ReDom profile"}</Text></Pressable>}/></View></View></Modal>
    <Modal visible={!!shareLink} transparent animationType="slide" onRequestClose={()=>setShareLink(null)}><View style={styles.overlay}><View style={styles.compose}><View style={styles.header}><AttachmentIcon kind="callLink" size={25}/><Text style={styles.title}>Share call link</Text><Pressable onPress={()=>setShareLink(null)}><Text style={styles.close}>Close</Text></Pressable></View><Text style={styles.linkText}>{shareLink?.deepLink}</Text><Pressable onPress={()=>void shareCreatedLink()} style={styles.primary}><Text style={styles.primaryText}>Share link</Text></Pressable><Text style={styles.sectionTitle}>Require approval to join</Text><Text style={styles.helper}>Create another link with approval enabled when you want to screen people before they enter.</Text>{joinRequests.length?joinRequests.map((r)=><View key={r.join_id} style={styles.request}><Text style={styles.contactName}>{r.display_name||r.profile_id}</Text><Text style={styles.status}>{r.status}</Text>{r.status==="pending"?<View style={styles.requestButtons}><Pressable onPress={()=>void approve(r.profile_id,"rejected")}><Text style={styles.danger}>Reject</Text></Pressable><Pressable onPress={()=>void approve(r.profile_id,"approved")}><Text style={styles.approve}>Approve</Text></Pressable></View>:null}</View>):null}</View></View></Modal>
  </>;
}
const styles=StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(0,0,0,.35)",justifyContent:"flex-end"},sheet:{backgroundColor:"#fff",borderTopLeftRadius:24,borderTopRightRadius:24,padding:14,maxHeight:"78%"},compose:{backgroundColor:"#fff",borderTopLeftRadius:24,borderTopRightRadius:24,padding:18},handle:{width:40,height:4,borderRadius:2,backgroundColor:"#CCD0D5",alignSelf:"center",marginBottom:8},header:{minHeight:48,flexDirection:"row",alignItems:"center",gap:10},title:{flex:1,fontSize:20,fontWeight:"800",color:"#050505"},close:{fontSize:14,fontWeight:"700",color:"#1877F2"},grid:{paddingBottom:20},item:{width:"50%",minHeight:92,alignItems:"center",justifyContent:"center"},icon:{width:52,height:52,borderRadius:26,backgroundColor:"#F0F2F5",alignItems:"center",justifyContent:"center"},label:{marginTop:7,fontSize:14,fontWeight:"700",color:"#050505"},busy:{marginVertical:12},input:{minHeight:48,borderRadius:12,backgroundColor:"#F0F2F5",paddingHorizontal:14,color:"#050505",fontSize:16,marginBottom:10},multiline:{minHeight:88,textAlignVertical:"top",paddingTop:12},primary:{minHeight:48,borderRadius:12,backgroundColor:"#1877F2",alignItems:"center",justifyContent:"center",marginTop:4},primaryText:{color:"#fff",fontSize:16,fontWeight:"800"},disabled:{opacity:.45},contactRow:{minHeight:58,flexDirection:"row",alignItems:"center",gap:12,paddingHorizontal:6},contactName:{fontSize:16,fontWeight:"700",color:"#101828",flex:1},linkText:{fontSize:14,color:"#475467",backgroundColor:"#F0F2F5",padding:12,borderRadius:12,marginBottom:10},sectionTitle:{fontSize:15,fontWeight:"800",color:"#101828",marginTop:18},helper:{fontSize:13,color:"#667085",marginTop:5},request:{paddingVertical:10,borderBottomWidth:1,borderBottomColor:"#EAECF0"},status:{fontSize:12,color:"#667085",marginTop:2},requestButtons:{flexDirection:"row",gap:20,marginTop:8},danger:{color:"#D92D20",fontWeight:"800"},approve:{color:"#1877F2",fontWeight:"800"}});
