import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { messageService, type ReDomMessage } from "../messages/messageService";

export function ChatScreen({ route }: NativeStackScreenProps<RootStackParamList, "Chat">) {
  const navigation = useNavigation();
  const [messages, setMessages] = useState<ReDomMessage[]>([]);
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const r = await messageService.getMessages(route.params.conversationId); setMessages(r.messages); await messageService.markRead(route.params.conversationId); } finally { setLoading(false); } }, [route.params.conversationId]);
  useEffect(() => { void load(); }, [load]);
  const send = async () => { const value = text.trim(); if (!value || sending) return; setSending(true); try { const r = await messageService.sendText(route.params.conversationId, value); setMessages((current) => [...current, r.message]); setText(""); } finally { setSending(false); } };
  return <SafeAreaView style={styles.root}><KeyboardAvoidingView style={styles.root} behavior={Platform.OS === "ios" ? "padding" : undefined}><View style={styles.header}><Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Conversation</Text><View style={{ width: 32 }} /></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color="#1877F2" /></View> : <ScrollView contentContainerStyle={styles.messages}>{messages.map((m) => <View key={m.id} style={styles.bubble}><Text style={styles.message}>{m.message || ""}</Text><Text style={styles.time}>{m.read ? "Read" : m.delivered ? "Delivered" : "Sent"} · {new Date(m.createdAt).toLocaleTimeString()}</Text></View>)}{!messages.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>Start the conversation</Text></View> : null}</ScrollView>}<View style={styles.composer}><TextInput value={text} onChangeText={setText} placeholder="Message" placeholderTextColor="#8A8D91" style={styles.input} multiline /><Pressable onPress={() => void send()} disabled={!text.trim() || sending} style={[styles.send, (!text.trim() || sending) && styles.sendDisabled]}><Text style={styles.sendText}>Send</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: "#F0F2F5" }, header: { height: 58, backgroundColor: "#FFF", borderBottomWidth: 1, borderBottomColor: "#E4E6EB", flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 12 }, back: { fontSize: 38, color: "#1877F2" }, title: { fontSize: 19, fontWeight: "800", color: "#050505" }, messages: { padding: 12, paddingBottom: 20 }, bubble: { alignSelf: "flex-end", maxWidth: "84%", backgroundColor: "#1877F2", borderRadius: 18, paddingHorizontal: 14, paddingVertical: 9, marginBottom: 7 }, message: { color: "#FFF", fontSize: 15, lineHeight: 21 }, time: { color: "#DDEBFF", fontSize: 10, marginTop: 4 }, composer: { backgroundColor: "#FFF", borderTopWidth: 1, borderTopColor: "#E4E6EB", padding: 8, flexDirection: "row", alignItems: "flex-end" }, input: { flex: 1, maxHeight: 110, minHeight: 42, backgroundColor: "#F0F2F5", borderRadius: 21, paddingHorizontal: 15, paddingVertical: 10, color: "#050505" }, send: { marginLeft: 8, height: 42, borderRadius: 21, backgroundColor: "#1877F2", paddingHorizontal: 16, alignItems: "center", justifyContent: "center" }, sendDisabled: { opacity: 0.45 }, sendText: { color: "#FFF", fontWeight: "800" }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, empty: { alignItems: "center", paddingTop: 80 }, emptyTitle: { fontSize: 18, fontWeight: "700", color: "#65676B" } });
