import { useEffect, useState } from "react";
import { Alert, Modal, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { api } from "../api/client";
import Globe from "../assets/home-feed/profile-audience-globe.svg";
import Group from "../assets/home-feed/profile-audience-group.svg";
import Friends from "../assets/home-feed/profile-audience-friends.svg";

type Props=NativeStackScreenProps<RootStackParamList,"EditBirthday">;type Privacy="public"|"friends_of_friends"|"friends"|"only_me"|"custom";
const label=(v:Privacy)=>({public:"Public",friends_of_friends:"Friends of friends",friends:"Friends",only_me:"Only Me",custom:"Custom"}[v]);
export function EditBirthdayScreen({navigation}:Props){const[birthday,setBirthday]=useState<string|null>(null);const[monthDay,setMonthDay]=useState<Privacy>("friends_of_friends");const[year,setYear]=useState<Privacy>("friends_of_friends");const[target,setTarget]=useState<"month"|"year"|null>(null);useEffect(()=>{void api.get<any>("/profile/edit").then(r=>{setBirthday(r.profile.birthday);setMonthDay(r.profile.birthdayMonthDayPrivacy||"friends_of_friends");setYear(r.profile.birthdayYearPrivacy||"friends_of_friends")})},[]);const save=async()=>{try{await api.patch("/profile/edit/details",{birthday_month_day_privacy:monthDay,birthday_year_privacy:year});navigation.goBack()}catch{Alert.alert("Birthday","Unable to save birthday privacy right now.")}};const d=birthday?new Date(birthday):null;return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>Birthday</Text><View style={{width:40}}/></View><View style={s.content}><Text style={s.heading}>Month and day</Text><Pressable style={s.selector} onPress={()=>setTarget("month")}><Text style={s.selectorText}>{label(monthDay)} ▾</Text></Pressable><View style={s.locked}><Text style={s.lockedTitle}>Month and day</Text><Text style={s.lockedValue}>{d?d.toLocaleDateString("en-US",{month:"long",day:"numeric"}):""}</Text></View><Text style={s.heading}>Year</Text><Pressable style={s.selector} onPress={()=>setTarget("year")}><Text style={s.selectorText}>{label(year)} ▾</Text></Pressable><View style={s.locked}><Text style={s.lockedTitle}>Year</Text><Text style={s.lockedValue}>{d?d.getFullYear():""}</Text></View><Pressable style={s.editRow} onPress={()=>Alert.alert("Edit your birthday","You can edit your birthday in Accounts Center.")}><Text style={s.editText}>Edit your birthday?</Text><Text style={s.arrow}>›</Text></Pressable><Pressable style={s.save} onPress={()=>void save()}><Text style={s.saveText}>Save</Text></Pressable></View><Audience visible={!!target} value={target==="year"?year:monthDay} onChange={v=>target==="year"?setYear(v):setMonthDay(v)} onClose={()=>setTarget(null)}/></SafeAreaView>}
function Audience({visible,value,onChange,onClose}:{visible:boolean;value:Privacy;onChange:(v:Privacy)=>void;onClose:()=>void}){const opts:[Privacy,string,any][]=[["public","Public",Globe],["friends_of_friends","Friends of friends",Group],["friends","Friends",Friends],["only_me","Only Me",Globe],["custom","Custom",Group]];return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.backdrop}><View style={s.modal}><Text style={s.modalTitle}>Choose audience</Text>{opts.map(([v,t,I])=><Pressable key={v} style={s.option} onPress={()=>{if(v==="custom"){onClose();return}onChange(v)}}><I width={25} height={25}/><Text style={s.opt}>{t}</Text><Text style={[s.radio,value===v&&s.radioOn]}>{value===v?"●":"○"}</Text></Pressable>)}<Pressable style={s.done} onPress={onClose}><Text style={s.doneText}>Done</Text></Pressable></View></View></Modal>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#fff"},header:{height:64,flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingHorizontal:20},back:{fontSize:44,fontWeight:"300"},title:{fontSize:24,fontWeight:"800"},content:{padding:23},heading:{fontSize:17,fontWeight:"800",marginTop:18},selector:{height:48,justifyContent:"center"},selectorText:{fontSize:15,fontWeight:"700",color:"#65676B"},locked:{borderWidth:1,borderColor:"#E4E6EB",backgroundColor:"#F0F2F5",borderRadius:9,padding:14,marginTop:4},lockedTitle:{fontSize:14,color:"#65676B"},lockedValue:{fontSize:18,fontWeight:"700",marginTop:4,color:"#65676B"},editRow:{minHeight:58,flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:24},editText:{fontSize:17,fontWeight:"700"},arrow:{fontSize:30,color:"#65676B"},save:{height:50,borderRadius:9,backgroundColor:"#1877F2",alignItems:"center",justifyContent:"center",marginTop:18},saveText:{color:"#fff",fontSize:17,fontWeight:"800"},backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.45)",justifyContent:"flex-end"},modal:{backgroundColor:"#fff",borderTopLeftRadius:20,borderTopRightRadius:20,padding:22},modalTitle:{fontSize:21,fontWeight:"800",marginBottom:12},option:{minHeight:62,flexDirection:"row",alignItems:"center",gap:12},opt:{flex:1,fontSize:16,fontWeight:"700"},radio:{fontSize:25,color:"#65676B"},radioOn:{color:"#1877F2"},done:{height:48,borderRadius:9,backgroundColor:"#1877F2",alignItems:"center",justifyContent:"center",marginTop:10},doneText:{color:"#fff",fontWeight:"800",fontSize:16}});
