import { useCallback, useEffect, useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { api } from "../api/client";
import BioIcon from "../assets/home-feed/profile-bio.svg";
import PinIcon from "../assets/home-feed/profile-pin.svg";
import LocationIcon from "../assets/home-feed/profile-location.svg";
import HometownIcon from "../assets/home-feed/profile-hometown.svg";
import BirthdayIcon from "../assets/home-feed/profile-birthday.svg";
type Props = NativeStackScreenProps<RootStackParamList, "EditProfile">;
type EditData = { firstName:string; lastName:string; bio:string; currentCity:string; hometown:string; birthday:string|null; gender:string|null; bioPrivacy:string; currentCityPrivacy:string; hometownPrivacy:string; birthdayMonthDayPrivacy:string; birthdayYearPrivacy:string };
const unavailable = () => Alert.alert("Feature unavailable", "This feature is unavailable in your location for now.");
export function EditProfileScreen({ navigation }: Props) { const[data,setData]=useState<EditData|null>(null);const[loading,setLoading]=useState(true);const load=useCallback(async()=>{try{const r=await api.get<{success:boolean;profile:EditData}>("/profile/edit");setData(r.profile)}catch{Alert.alert("Edit profile","Unable to load your profile right now.")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);if(loading||!data)return <SafeAreaView style={s.root}><Header onBack={()=>navigation.goBack()}/><Text style={s.loading}>Loading...</Text></SafeAreaView>;const row=(icon:React.ReactNode,title:string,value?:string,action?:()=>void,disabled=false)=><Pressable style={s.row} onPress={disabled?unavailable:action} accessibilityRole={disabled?undefined:"button"}><View style={s.icon}>{icon}</View><View style={s.rowBody}><Text style={[s.rowTitle,(!value||disabled)&&s.muted]}>{title}</Text>{value?<Text style={s.value}>{value}</Text>:null}</View>{action&&!disabled?<Text style={s.pencil}>✎</Text>:null}</Pressable>;return <SafeAreaView style={s.root}><Header onBack={()=>navigation.goBack()}/><ScrollView contentContainerStyle={s.content}><Section title="Intro"/>{row(<BioIcon width={30} height={30}/> ,"About you",data.bio||undefined,()=>navigation.navigate("EditBio"))}{row(<PinIcon width={30} height={30}/> ,"Pinned details",data.currentCity||data.hometown||undefined,()=>Alert.alert("Pinned details","This Setting Will be available in your region soon....."))}<Section title="Personal details"/>{row(<LocationIcon width={30} height={30}/> ,"Current city",data.currentCity||undefined,()=>navigation.navigate("EditLocationSearch",{kind:"location"}))}{row(<HometownIcon width={30} height={30}/> ,"Hometown",data.hometown||undefined,()=>navigation.navigate("EditLocationSearch",{kind:"hometown"}))}{row(<BirthdayIcon width={30} height={30}/> ,data.birthday?new Date(data.birthday).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"}):"Birthday",undefined,()=>navigation.navigate("EditBirthday"))}{row(<Text style={s.heart}>♡</Text>,"Relationship status",undefined,unavailable)}{row(<Text style={s.family}>♧</Text>,"Family",undefined,unavailable)}{row(<Text style={s.gender}>♂</Text>,data.gender?String(data.gender):"Gender",undefined,undefined,true)}{row(<Text style={s.language}>◈</Text>,"Languages",undefined,unavailable)}<Section title="Work"/>{row(<Text style={s.work}>▣</Text>,"Work experience",undefined,unavailable)}<Section title="Education"/>{row(<Text style={s.education}>♜</Text>,"High school or college",undefined,unavailable)}</ScrollView></SafeAreaView> }
function Header({onBack}:{onBack:()=>void}){return <View style={s.header}><Pressable onPress={onBack} accessibilityLabel="Back"><Text style={s.back}>‹</Text></Pressable><Text style={s.headerTitle}>Edit profile</Text><View style={{width:42}}/></View>};function Section({title}:{title:string}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text><Text style={s.chevron}>⌃</Text></View>};const s=StyleSheet.create({root:{flex:1,backgroundColor:"#fff"},header:{height:64,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:20},back:{fontSize:44,lineHeight:44,color:"#050505",fontWeight:"300"},headerTitle:{fontSize:25,fontWeight:"800",color:"#050505"},content:{paddingBottom:30},section:{paddingHorizontal:23,paddingTop:26,paddingBottom:12,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},sectionTitle:{fontSize:23,fontWeight:"800",color:"#050505"},chevron:{fontSize:31,fontWeight:"800"},row:{minHeight:72,paddingHorizontal:23,flexDirection:"row",alignItems:"center"},icon:{width:54,alignItems:"flex-start"},rowBody:{flex:1},rowTitle:{fontSize:20,fontWeight:"800",color:"#050505"},muted:{color:"#65676B"},value:{fontSize:18,color:"#050505",marginTop:3},pencil:{fontSize:29,color:"#65676B",paddingLeft:12},loading:{padding:24,color:"#65676B",fontSize:16},heart:{fontSize:38,color:"#050505"},family:{fontSize:34,color:"#050505"},gender:{fontSize:34,color:"#050505"},language:{fontSize:30,color:"#050505"},work:{fontSize:31,color:"#050505"},education:{fontSize:31,color:"#050505"}});
