import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { api } from "../api/client";

type Props=NativeStackScreenProps<RootStackParamList,"EditLocationSearch">;
type Result={id:string;name:string;placeName:string;latitude:number|null;longitude:number|null};
export function EditLocationSearchScreen({navigation,route}:Props){const[k,setK]=useState(route.params.kind);const[q,setQ]=useState("");const[results,setResults]=useState<Result[]>([]);const[busy,setBusy]=useState(false);useEffect(()=>{const t=setTimeout(async()=>{if(q.trim().length<3){setResults([]);return}setBusy(true);try{const r=await api.get<{success:boolean;results:Result[]}>(`/profile/edit/locations?q=${encodeURIComponent(q.trim())}`);setResults(r.results)}finally{setBusy(false)}},250);return()=>clearTimeout(t)},[q]);return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>{k==="hometown"?"Add hometown":"Add location"}</Text><View style={{width:40}}/></View><View style={s.searchWrap}><Text style={s.searchIcon}>⌕</Text><TextInput autoFocus value={q} onChangeText={setQ} placeholder="Search" placeholderTextColor="#65676B" style={s.input}/>{q?<Pressable onPress={()=>setQ("")}><Text style={s.clear}>×</Text></Pressable>:null}</View>{busy?<ActivityIndicator style={{margin:20}}/>:null}<ScrollView>{results.map(r=><Pressable key={r.id} style={s.result} onPress={()=>navigation.navigate("EditLocationConfirm",{kind:k,result:r.placeName})}><Text style={s.name}>{r.name}</Text><Text style={s.place}>{r.placeName}</Text></Pressable>)}{q.length>=3&&!busy&&!results.length?<Text style={s.empty}>No matching locations.</Text>:null}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#fff"},header:{height:64,flexDirection:"row",justifyContent:"space-between",alignItems:"center",paddingHorizontal:20},back:{fontSize:44,fontWeight:"300"},title:{fontSize:23,fontWeight:"800"},searchWrap:{marginHorizontal:20,height:48,borderRadius:24,backgroundColor:"#F0F2F5",flexDirection:"row",alignItems:"center",paddingHorizontal:14},searchIcon:{fontSize:27,color:"#65676B"},input:{flex:1,fontSize:16,color:"#050505",paddingHorizontal:8},clear:{fontSize:28,color:"#65676B"},result:{paddingHorizontal:22,paddingVertical:15,borderBottomWidth:1,borderBottomColor:"#E4E6EB"},name:{fontSize:17,fontWeight:"800",color:"#050505"},place:{fontSize:14,color:"#65676B",marginTop:3},empty:{padding:24,color:"#65676B"}});
