import { useEffect, useMemo, useState } from "react";
import { useTheme } from "../theme/ThemeProvider";
import { ActivityIndicator, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import ForwardIcon from "../assets/message-actions/forward.svg";
import ProfileIcon from "../assets/message-actions/profile.svg";
import type { ConversationSummary, ReDomMessage } from "../messages/messageService";
import { messageService } from "../messages/messageService";
import { forwardMessageService } from "../messages/forwardMessageService";
import { forwardMediaService } from "../messages/forwardMediaService";
import { AttachmentIcon } from "../messages/AttachmentIcon";

interface Props { visible: boolean; message: ReDomMessage | null; sourceConversationId: string; onClose: () => void; onComplete?: () => void; }

export function ForwardMessageSheet({ visible, message, sourceConversationId, onClose, onComplete }: Props) {
  const { colors } = useTheme();
  const styles = makeStyles(colors);
  const [items,setItems]=useState<ConversationSummary[]>([]); const [selected,setSelected]=useState<string[]>([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(false); const [sending,setSending]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{if(!visible)return;setSelected([]);setQuery("");setError("");setLoading(true);void messageService.listConversations().then(r=>setItems(r.conversations.filter(x=>x.id!==sourceConversationId))).catch(e=>setError(e instanceof Error?e.message:"Unable to load chats.")).finally(()=>setLoading(false));},[visible,sourceConversationId]);
  const filtered=useMemo(()=>{const n=query.trim().toLowerCase();if(!n)return items;return items.filter(x=>`${x.displayName||""} ${x.groupName||""}`.toLowerCase().includes(n));},[items,query]);
  const toggle=(id:string)=>setSelected(c=>c.includes(id)?c.filter(v=>v!==id):c.length>=5?c:[...c,id]);
  const send=async()=>{if(!message||!selected.length||sending)return;setSending(true);setError("");try{if(message.attachment?.encrypted)await forwardMediaService.forwardMedia(message,selected);else await forwardMessageService.forwardText(message,selected);onClose();onComplete?.();}catch(e){setError(e instanceof Error?e.message:"The message could not be forwarded.");}finally{setSending(false);}};
  const mediaLabel=message?.attachment?.attachmentType?message.attachment.attachmentType.charAt(0).toUpperCase()+message.attachment.attachmentType.slice(1):"Message";
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.sheet}><View style={styles.handle}/><View style={styles.header}><ForwardIcon width={25} height={25}/><Text style={styles.title}>Forward message</Text><Text style={styles.count}>{selected.length}/5</Text></View>{message?.attachment?.encrypted?<View style={styles.preview}><AttachmentIcon kind={message.attachment.attachmentType==="voice"?"voice":message.attachment.attachmentType==="video"?"video":"document"} size={20}/><Text style={styles.previewText}>{mediaLabel}{message.caption?` — ${message.caption}`:""}</Text></View>:null}<TextInput value={query} onChangeText={setQuery} placeholder="Search chats" placeholderTextColor="#65676B" style={styles.search} autoCapitalize="none"/>{error?<Text style={styles.error}>{error}</Text>:null}{loading?<View style={styles.center}><ActivityIndicator/></View>:<FlatList data={filtered} keyExtractor={x=>x.id} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>No chats found.</Text>} renderItem={({item})=>{const checked=selected.includes(item.id);return <Pressable onPress={()=>toggle(item.id)} style={styles.row}><View style={styles.iconBox}><ProfileIcon width={23} height={23}/></View><View style={styles.info}><Text numberOfLines={1} style={styles.name}>{item.groupName||item.displayName||"ReDom chat"}</Text><Text style={styles.type}>{item.type==="group"?"Group chat":"Chat"}</Text></View><View style={[styles.check,checked&&styles.checked]}>{checked?<AttachmentIcon kind="check" size={16} color="#FFF"/>:null}</View></Pressable>;}}/>}<View style={styles.footer}><Pressable onPress={onClose} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable><Pressable disabled={!selected.length||sending} onPress={()=>void send()} style={[styles.send,(!selected.length||sending)&&styles.disabled]}><Text style={styles.sendText}>{sending?"Sending…":`Send${selected.length?` (${selected.length})`:""}`}</Text></Pressable></View></View></View></Modal>;
}
function makeStyles(colors: ReturnType<typeof useTheme>["colors"]) { return StyleSheet.create({overlay:{flex:1,backgroundColor:"rgba(0,0,0,0.32)",justifyContent:"flex-end"},sheet:{backgroundColor:colors.surface,borderTopLeftRadius:22,borderTopRightRadius:22,paddingTop:10,paddingBottom:18,maxHeight:"88%"},handle:{alignSelf:"center",width:38,height:4,borderRadius:2,backgroundColor:"#CCD0D5",marginBottom:10},header:{minHeight:48,paddingHorizontal:18,flexDirection:"row",alignItems:"center"},title:{flex:1,marginLeft:10,fontSize:20,fontWeight:"800",color:colors.text},count:{color:colors.primary,fontWeight:"800",fontSize:14},preview:{marginHorizontal:16,marginBottom:8,minHeight:42,borderRadius:12,backgroundColor:colors.background,paddingHorizontal:12,flexDirection:"row",alignItems:"center",gap:9},previewText:{flex:1,fontSize:13,color:colors.textSecondary,fontWeight:"600"},search:{marginHorizontal:16,marginBottom:8,backgroundColor:colors.background,borderRadius:12,minHeight:44,paddingHorizontal:14,fontSize:16,color:colors.text},list:{paddingBottom:8},row:{minHeight:66,paddingHorizontal:16,flexDirection:"row",alignItems:"center"},iconBox:{width:46,height:46,borderRadius:23,backgroundColor:colors.background,alignItems:"center",justifyContent:"center"},info:{flex:1,marginLeft:12},name:{fontSize:16,fontWeight:"700",color:colors.text},type:{marginTop:3,fontSize:13,color:colors.textSecondary},check:{width:24,height:24,borderRadius:12,borderWidth:1.5,borderColor:colors.border,alignItems:"center",justifyContent:"center"},checked:{backgroundColor:colors.primary,borderColor:colors.primary},footer:{flexDirection:"row",gap:10,paddingHorizontal:16,paddingTop:8},cancel:{flex:1,minHeight:48,borderRadius:12,backgroundColor:colors.background,alignItems:"center",justifyContent:"center"},cancelText:{color:colors.primary,fontSize:16,fontWeight:"800"},send:{flex:1,minHeight:48,borderRadius:12,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center"},sendText:{color:"#FFF",fontSize:16,fontWeight:"800"},disabled:{opacity:0.45},error:{marginHorizontal:16,marginBottom:6,color:"#B42318",fontSize:13},center:{minHeight:240,alignItems:"center",justifyContent:"center"},empty:{textAlign:"center",color:colors.textSecondary,paddingVertical:40}}); }