import { useState } from "react";
import { useTheme } from "../theme/ThemeProvider";
import { Alert, Pressable, SafeAreaView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { groupService } from "../messages/groupService";
import { GroupActionIcon } from "../components/GroupActionIcon";
export function GroupAddMembersScreen({ route, navigation }: NativeStackScreenProps<RootStackParamList,"GroupAddMembers">) {
  const { colors } = useTheme();
  const s = makeStyles(colors);const[id,setId]=useState("");const[history,setHistory]=useState(false);const[saving,setSaving]=useState(false);const add=async()=>{const profileId=id.trim();if(!profileId)return;setSaving(true);try{const r=await groupService.addMembers(route.params.conversationId,[profileId],history);Alert.alert(r.pending?"Request pending":"Member added",r.pending?"The member will be active after admin approval.":history?"The member was added. Message history can now be prepared for delivery.":"The member was added.");setId("");}catch(e){Alert.alert("Unable to add member",e instanceof Error?e.message:"Please check the profile ID and try again.");}finally{setSaving(false);}};return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><GroupActionIcon kind="back" size={30} color="#111"/></Pressable><Text style={s.title}>Add members</Text><View style={{width:30}}/></View><View style={s.content}><Text style={s.label}>ReDom profile ID</Text><TextInput value={id} onChangeText={setId} autoCapitalize="none" autoCorrect={false} placeholder="Paste a profile ID" style={s.input}/><View style={s.history}><View style={{flex:1}}><Text style={s.historyTitle}>Send message history</Text><Text style={s.historyDesc}>Allow the newly added member to receive recent encrypted group history when supported.</Text></View><Switch value={history} onValueChange={setHistory} trackColor={{false:"#D0D5DD",true:"#22A96B"}} thumbColor="#FFF"/></View><Pressable disabled={!id.trim()||saving} onPress={()=>void add()} style={[s.button,(!id.trim()||saving)&&s.disabled]}><Text style={s.buttonText}>{saving?"Adding…":"Add member"}</Text></Pressable></View></SafeAreaView>}
function makeStyles(colors: ReturnType<typeof useTheme>["colors"]) { return StyleSheet.create({root:{flex:1,backgroundColor:colors.surface},header:{height:60,borderBottomWidth:1,borderBottomColor:colors.border,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{fontSize:20,fontWeight:"700",color:colors.text},content:{padding:22},label:{fontSize:14,fontWeight:"700",color:colors.textSecondary,marginBottom:8},input:{height:52,borderWidth:1,borderColor:colors.border,borderRadius:10,paddingHorizontal:14,fontSize:16,color:colors.text},history:{marginTop:20,padding:16,borderRadius:12,backgroundColor:colors.surfaceSecondary,flexDirection:"row",alignItems:"center",gap:14},historyTitle:{fontSize:16,fontWeight:"700",color:colors.text},historyDesc:{fontSize:13,color:colors.textSecondary,lineHeight:18,marginTop:4},button:{marginTop:26,height:50,borderRadius:25,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center"},disabled:{opacity:.45},buttonText:{color:"#FFF",fontWeight:"800",fontSize:16}}); }