import { useEffect, useState } from "react";
import { Alert, Modal, Pressable, Share, StyleSheet, Text, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { api } from "../api/client";
import { messageService } from "../messages/messageService";
import { groupService } from "../messages/groupService";
import { GroupActionIcon } from "../components/GroupActionIcon";
export function GroupChatHeaderTools({conversationId}:{conversationId:string}){const navigation=useNavigation<any>();const[group,setGroup]=useState<any>(null);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);useEffect(()=>{void groupService.getSettings(conversationId).then(r=>setGroup(r.settings)).catch(()=>setGroup(null));},[conversationId]);if(!group)return null;const call=async(type:"voice"|"video")=>{setBusy(true);try{const r=await messageService.createCall(conversationId,type);setOpen(false);navigation.navigate("Call",{conversationId,callType:type,callId:r.call.id});}catch(e){Alert.alert("Call unavailable",e instanceof Error?e.message:"Unable to start call.");}finally{setBusy(false);}};const link=async()=>{setBusy(true);try{const r=await api.post<any>(`/calls/conversations/${conversationId}`,{callType:"video",requireApproval:false,expiresInHours:24});await Share.share({message:`Join my ReDom call: ${r.deepLink}`});setOpen(false);}catch(e){Alert.alert("Call link unavailable",e instanceof Error?e.message:"Unable to create call link.");}finally{setBusy(false);}};return <><View style={s.header}><Pressable onPress={()=>void call("video")}><GroupActionIcon kind="video" size={25} color="#111"/></Pressable><Pressable onPress={()=>setOpen(true)}><Text style={s.chevron}>⌄</Text></Pressable><Pressable onPress={()=>setOpen(true)}><GroupActionIcon kind="more" size={25} color="#111"/></Pressable></View><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><Pressable style={s.backdrop} onPress={()=>setOpen(false)}><View style={s.menu}><Menu icon="audio" title="Voice call" onPress={()=>void call("voice")}/><Menu icon="video" title="Video call" onPress={()=>void call("video")}/><Menu icon="members" title="Select people" onPress={()=>{setOpen(false);navigation.navigate("GroupInfo",{conversationId});}}/><Menu icon="link" title="Send call link" onPress={()=>void link()}/><Menu icon="history" title="Schedule call" onPress={()=>{setOpen(false);Alert.alert("Schedule call","Choose a date and time from the ReDom Calls tab to schedule a group call.");}}/></View></Pressable></Modal>{busy?<View style={s.busy}><Text style={s.busyText}>Connecting…</Text></View>:null}</>}
function Menu({icon,title,onPress}:{icon:any;title:string;onPress:()=>void}){return <Pressable style={s.item} onPress={onPress}><GroupActionIcon kind={icon}/><Text style={s.itemText}>{title}</Text></Pressable>}
const s=StyleSheet.create({header:{position:"absolute",right:8,top:7,height:44,flexDirection:"row",alignItems:"center",gap:12,zIndex:30},chevron:{fontSize:20,color:"#111",marginTop:-5},backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.12)",alignItems:"flex-end",paddingTop:62,paddingRight:8},menu:{width:240,backgroundColor:"#FFF",borderRadius:12,elevation:8,shadowColor:"#000",shadowOpacity:.2,shadowRadius:12,shadowOffset:{width:0,height:5},paddingVertical:7},item:{minHeight:54,paddingHorizontal:18,flexDirection:"row",alignItems:"center",gap:18},itemText:{fontSize:16,color:"#111827"},busy:{position:"absolute",top:60,right:12,backgroundColor:"#FFF",paddingHorizontal:12,paddingVertical:7,borderRadius:8,elevation:3},busyText:{fontSize:12,color:"#667085"}});