import { useCallback,useEffect,useState } from "react";
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Switch,Text,View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { groupService,type GroupMember } from "../messages/groupService";
import { GroupActionIcon } from "../components/GroupActionIcon";

type Props=NativeStackScreenProps<RootStackParamList,"GroupAdmins">;
export function GroupAdminsScreen({route,navigation}:Props){const[members,setMembers]=useState<GroupMember[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const load=useCallback(async()=>{const r=await groupService.getMembers(route.params.conversationId);setMembers(r.members)},[route.params.conversationId]);useEffect(()=>{void load().finally(()=>setLoading(false))},[load]);const toggle=async(member:GroupMember)=>{if(member.role==="owner")return;setBusy(member.profileId);try{await groupService.setRole(route.params.conversationId,member.profileId,member.role==="admin"?"member":"admin");await load()}finally{setBusy("")}};if(loading)return <SafeAreaView style={s.root}><ActivityIndicator style={{marginTop:50}} color="#1877F2"/></SafeAreaView>;return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><GroupActionIcon kind="back" size={30} color="#111"/></Pressable><View><Text style={s.title}>Edit group admins</Text><Text style={s.sub}>Choose who can manage this group</Text></View><View style={{width:30}}/></View><ScrollView><Text style={s.info}>Group admins can change permissions, add or remove members, manage invites and appoint other admins. The group creator remains an admin unless they leave.</Text>{members.map(m=><View key={m.id} style={s.row}><View style={s.avatar}><Text style={s.initial}>{(m.displayName||"R").slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{m.displayName||m.profileId}</Text><Text style={s.meta}>{m.role==="owner"?"Group creator":m.role==="admin"?"Group Admin":"Member"}</Text></View>{m.role==="owner"?<Text style={s.creator}>Creator</Text>:<Switch disabled={busy===m.profileId} value={m.role==="admin"} onValueChange={()=>void toggle(m)} trackColor={{false:"#D0D5DD",true:"#22A96B"}} thumbColor="#FFF"/>}</View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#F7F8FA"},header:{height:64,backgroundColor:"#FFF",borderBottomWidth:1,borderBottomColor:"#E5E7EB",paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:14},title:{fontSize:20,fontWeight:"700",color:"#111827"},sub:{fontSize:13,color:"#667085",marginTop:2},info:{padding:20,backgroundColor:"#E8F3FF",fontSize:14,lineHeight:21,color:"#344054"},row:{minHeight:76,backgroundColor:"#FFF",paddingHorizontal:22,flexDirection:"row",alignItems:"center",gap:15,borderBottomWidth:1,borderBottomColor:"#F0F2F5"},avatar:{width:46,height:46,borderRadius:23,backgroundColor:"#E9EEF5",alignItems:"center",justifyContent:"center"},initial:{fontSize:18,fontWeight:"700",color:"#667085"},name:{fontSize:16,color:"#101828"},meta:{fontSize:13,color:"#667085",marginTop:3},creator:{fontSize:13,fontWeight:"700",color:"#1877F2"}});
