import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Linking, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useAuthContext } from "../auth/context";
import { validateLoginIdentifier, validatePassword } from "../auth/validation";
import { getNetworkProvider } from "../auth/networkProvider";
import { getDeviceId } from "../utils/device";
import ReDomLogo from "../assets/brand/redom-logo.svg";
import PasswordVisible from "../assets/auth/password-visible.svg";
import PasswordHidden from "../assets/auth/password-hidden.svg";
import { ReDomScreen } from "../layout/ReDomScreen";
import { LANGUAGES, useLanguage } from "../i18n/LanguageProvider";
import type { RootStackParamList } from "../routing/types";

const BLUE = "#1877F2"; const TEXT = "#1C1E21"; const MUTED = "#65676B"; const BORDER = "#CCD0D5";
type Props = NativeStackScreenProps<RootStackParamList, "Login">;
const PROVIDER_WEBSITES: Array<[string, string]> = [["verizon", "https://www.verizon.com/"], ["vodafone", "https://www.vodafone.com/"], ["mtn", "https://www.mtn.com/"], ["airtel", "https://www.airtel.com/"], ["glo", "https://www.gloworld.com/"], ["9mobile", "https://www.9mobile.com.ng/"], ["t-mobile", "https://www.t-mobile.com/"], ["at&t", "https://www.att.com/"], ["att", "https://www.att.com/"]];
function getProviderWebsite(provider: string | null) { if (!provider) return null; const normalized = provider.toLowerCase(); return PROVIDER_WEBSITES.find(([name]) => normalized.includes(name))?.[1] ?? null; }

export function LoginScreen({ navigation }: Props) {
  const { login } = useAuthContext(); const { language, languageName, setLanguage, t } = useLanguage();
  const [identifier, setIdentifier] = useState(""); const [password, setPassword] = useState(""); const [passwordVisible, setPasswordVisible] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [deviceId, setDeviceId] = useState<string | null>(null); const [networkProvider, setNetworkProvider] = useState<string | null>(null); const [languageOpen, setLanguageOpen] = useState(false);
  useEffect(() => { let mounted = true; setNetworkProvider(getNetworkProvider()); getDeviceId().then((id) => { if (mounted) setDeviceId(id); }).catch(() => { if (mounted) setError("Unable to initialize this device."); }); return () => { mounted = false; }; }, []);
  const submitLogin = useCallback(async () => { if (loading) return; setError(null); const normalizedIdentifier = identifier.trim(); const identifierError = validateLoginIdentifier(normalizedIdentifier); if (identifierError) return setError(identifierError); const passwordError = validatePassword(password); if (passwordError) return setError(passwordError); if (!deviceId) return setError("This device has not finished initializing. Please try again."); setLoading(true); try { const result = await login({ identifier: normalizedIdentifier, password, platform: Platform.OS, deviceId, deviceType: "mobile", deviceName: Platform.OS === "ios" ? "iPhone" : "Android Device", loginSource: "mobile", appVersion: "1.0.0" }); if (result.requiresVerification && result.verification) { navigation.navigate("DeviceVerification", { challengeId: result.verification.challengeId, channel: result.verification.channel, maskedTarget: result.verification.maskedTarget, expiresAt: new Date(result.verification.expiresAt).toISOString() }); return; } if (!result.success) setError(result.message || "Login could not be completed."); } catch (err) { setError(err instanceof Error ? err.message : "Login failed. Please try again."); } finally { setLoading(false); } }, [deviceId, identifier, loading, login, navigation, password]);
  const providerWebsite = getProviderWebsite(networkProvider); const openProviderTerms = async () => { if (!providerWebsite) return; try { await Linking.openURL(providerWebsite); } catch { setError("Unable to open your network provider's website."); } };
  const footer = <View style={styles.footerContent}><Text style={styles.footer}>© ReDom 2026</Text></View>;
  return <ReDomScreen footer={footer}><View style={styles.content}>
    <View style={styles.languageHeader}><Pressable onPress={() => setLanguageOpen((value) => !value)} accessibilityRole="button" accessibilityLabel={t("language")}><Text style={styles.languageCurrent}>{languageName} <Text style={styles.arrow}>{languageOpen ? "↓" : "↑"}</Text></Text></Pressable></View>
    {languageOpen ? <View style={styles.languagePanel}>{LANGUAGES.map((item) => <Pressable key={item.code} onPress={async () => { await setLanguage(item.code); setLanguageOpen(false); }} style={[styles.languageItem, item.code === language && styles.languageItemActive]}><Text style={[styles.languageText, item.code === language && styles.languageTextActive]}>{item.nativeName}</Text></Pressable>)}</View> : null}
    <View style={styles.logoContainer}><ReDomLogo width={190} height={53} /></View>
    <Text style={styles.heading}>{t("loginTitle")}</Text>
    <Text style={styles.notice}>By proceeding you agree to {providerWebsite ? <Text onPress={openProviderTerms} accessibilityRole="link" style={styles.link}>{networkProvider} Terms and Conditions</Text> : <Text style={styles.providerFallback}>{networkProvider ? `${networkProvider} Terms and Conditions` : "Your Network Provider Terms"}</Text>} which includes letting ReDom request and receive your phone number.</Text>
    <View style={styles.inputBox}><TextInput value={identifier} onChangeText={(value) => { setIdentifier(value); if (error) setError(null); }} placeholder={t("mobileOrEmail")} placeholderTextColor="#8A8D91" autoCapitalize="none" autoCorrect={false} spellCheck={false} keyboardType="email-address" autoComplete="username" maxLength={100} editable={!loading} style={styles.input} /></View>
    <View style={styles.inputBox}><TextInput value={password} onChangeText={(value) => { setPassword(value); if (error) setError(null); }} placeholder={t("password")} placeholderTextColor="#8A8D91" secureTextEntry={!passwordVisible} autoCapitalize="none" autoCorrect={false} autoComplete="current-password" maxLength={100} editable={!loading} returnKeyType="go" onSubmitEditing={() => void submitLogin()} style={[styles.input, styles.passwordInput]} /><Pressable accessibilityRole="button" accessibilityLabel={passwordVisible ? "Hide password" : "Show password"} disabled={loading} hitSlop={10} onPress={() => setPasswordVisible((current) => !current)} style={styles.eye}>{passwordVisible ? <PasswordVisible width={23} height={23} /> : <PasswordHidden width={23} height={23} />}</Pressable></View>
    {error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}
    <Pressable disabled={loading} onPress={() => void submitLogin()} style={[styles.loginButton, loading && styles.buttonDisabled]}>{loading ? <ActivityIndicator size="small" color="#FFFFFF" /> : <Text style={styles.loginButtonText}>{t("login")}</Text>}</Pressable>
    <Pressable disabled={loading} onPress={() => setError("Password recovery is being connected next.")} style={styles.forgotButton}><Text style={styles.link}>{t("forgotPassword")}</Text></Pressable>
    <View style={styles.dividerRow}><View style={styles.divider} /><Text style={styles.or}>{t("or")}</Text><View style={styles.divider} /></View>
    <Pressable disabled={loading} onPress={() => navigation.navigate("RegistrationWelcome")} style={[styles.signupButton, loading && styles.buttonDisabled]}><Text style={styles.signupButtonText}>{t("createAccount")}</Text></Pressable>
  </View></ReDomScreen>;
}
const styles = StyleSheet.create({ content: { flex: 1, width: "100%", justifyContent: "center", paddingVertical: 8 }, languageHeader: { alignItems: "center", marginBottom: 7 }, languageCurrent: { color: BLUE, fontSize: 14, fontWeight: "800" }, arrow: { fontSize: 15 }, languagePanel: { width: "100%", flexDirection: "row", flexWrap: "wrap", justifyContent: "center", gap: 7, marginBottom: 13, paddingVertical: 8, borderTopWidth: 1, borderBottomWidth: 1, borderColor: "#E4E6EB" }, languageItem: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 14 }, languageItemActive: { backgroundColor: "#E7F3FF" }, languageText: { color: MUTED, fontSize: 12, fontWeight: "600" }, languageTextActive: { color: BLUE, fontWeight: "800" }, logoContainer: { alignItems: "center", justifyContent: "center", marginBottom: 16 }, heading: { textAlign: "center", fontSize: 23, lineHeight: 30, fontWeight: "800", color: TEXT, marginBottom: 10 }, notice: { textAlign: "center", fontSize: 14, lineHeight: 22, color: MUTED, marginBottom: 24 }, link: { color: BLUE, fontWeight: "700" }, providerFallback: { color: BLUE, fontWeight: "600" }, inputBox: { position: "relative", marginBottom: 14 }, input: { width: "100%", height: 54, paddingHorizontal: 17, borderWidth: 1, borderColor: BORDER, borderRadius: 12, fontSize: 16, color: TEXT, backgroundColor: "#FFFFFF" }, passwordInput: { paddingRight: 58 }, eye: { position: "absolute", right: 16, top: 14, width: 26, height: 26, alignItems: "center", justifyContent: "center" }, error: { marginBottom: 12, textAlign: "center", fontSize: 14, lineHeight: 21, fontWeight: "600", color: "#E41E3F" }, loginButton: { width: "100%", height: 54, borderRadius: 12, backgroundColor: BLUE, alignItems: "center", justifyContent: "center" }, buttonDisabled: { opacity: 0.65 }, loginButtonText: { color: "#FFFFFF", fontSize: 17, fontWeight: "800" }, forgotButton: { height: 46, alignItems: "center", justifyContent: "center", marginTop: 5 }, dividerRow: { flexDirection: "row", alignItems: "center", gap: 12, marginVertical: 5 }, divider: { flex: 1, height: 1, backgroundColor: "#E4E6EB" }, or: { color: "#8A8D91", fontSize: 11, fontWeight: "700" }, signupButton: { width: "100%", height: 54, marginTop: 14, borderWidth: 2, borderColor: BLUE, borderRadius: 12, alignItems: "center", justifyContent: "center" }, signupButtonText: { color: BLUE, fontSize: 16, fontWeight: "800" }, footerContent: { width: "100%", alignItems: "center" }, footer: { textAlign: "center", fontSize: 13, color: MUTED, lineHeight: 21 } });
