import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Image, Pressable, StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import BackIcon from "../assets/navigation/back.svg";
import ChevronRight from "../assets/auth/chevron-right.svg";
import NeutralAvatar from "../assets/auth/neutral-avatar.svg";
import { ReDomScreen } from "../layout/ReDomScreen";
import { getDeviceAccounts, removeDeviceAccount, type DeviceAccount } from "../auth/deviceAccounts";
import type { RootStackParamList } from "../routing/types";

type Props=NativeStackScreenProps<RootStackParamList,"ManageProfiles">;
const TEXT="#1C1E21",MUTED="#65676B",BORDER="#CCD0D5",RED="#E41E3F";
export function ManageProfilesScreen({navigation,route}:Props){
 const [accounts,setAccounts]=useState<DeviceAccount[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);try{setAccounts(await getDeviceAccounts())}finally{setLoading(false)}}
 const selected=route.params?.userId ? accounts.find(x=>x.user.id===route.params!.userId) : undefined;
 if(route.params?.userId)return <ReDomScreen><View style={s.detail}><Pressable onPress={()=>navigation.goBack()} style={s.back}><BackIcon width={30} height={30}/></Pressable>{selected?<><View style={s.bigAvatar}>{selected.user.profilePhoto?<Image source={{uri:selected.user.profilePhoto}} style={s.bigImage}/>:<Text style={s.bigInitial}>{selected.user.firstName?.[0]||"R"}</Text>}</View><Text style={s.detailName}>{selected.user.firstName} {selected.user.lastName}</Text><Pressable onPress={()=>Alert.alert("Remove profile","Remove this profile from this device? This does not delete the ReDom account or revoke the device.",[{text:"Cancel",style:"cancel"},{text:"Remove profile",style:"destructive",onPress:async()=>{await removeDeviceAccount(selected.user.id);navigation.goBack();}}])} style={s.remove}><Text style={s.removeText}>Remove profile</Text></Pressable><Text style={s.explain}>This profile is recognized on this device. Removing the profile only removes its account association from the device.</Text></>:loading?<ActivityIndicator size="large"/>:<Text style={s.explain}>This profile is no longer recognized on this device.</Text>}</View></ReDomScreen>;
 return <ReDomScreen><View style={s.list}><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><BackIcon width={30} height={30}/></Pressable><Text style={s.title}>Manage profiles</Text><View style={s.headerSpace}/></View>{loading?<ActivityIndicator size="large"/>:accounts.map(a=><Pressable key={a.user.id} style={s.card} onPress={()=>navigation.navigate("ManageProfiles",{userId:a.user.id})}><View style={s.avatar}>{a.user.profilePhoto?<Image source={{uri:a.user.profilePhoto}} style={s.image}/>:<NeutralAvatar width={72} height={72}/>}</View><Text numberOfLines={1} style={s.name}>{a.user.firstName} {a.user.lastName}</Text><ChevronRight width={25} height={25}/></Pressable>)}</View></ReDomScreen>;
}
const s=StyleSheet.create({list:{flex:1,paddingHorizontal:30,paddingTop:20},header:{height:70,flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:28},headerSpace:{width:30},title:{fontSize:30,fontWeight:"800",color:"#050505"},card:{minHeight:126,borderWidth:1,borderColor:BORDER,borderRadius:24,paddingHorizontal:27,flexDirection:"row",alignItems:"center",gap:22,marginBottom:20},avatar:{width:72,height:72,borderRadius:36,overflow:"hidden",backgroundColor:"#E4E6EB",alignItems:"center",justifyContent:"center"},image:{width:72,height:72},initial:{fontSize:30,color:MUTED},name:{flex:1,fontSize:20,color:TEXT},detail:{flex:1,paddingHorizontal:30,paddingTop:20},back:{alignSelf:"flex-start"},bigAvatar:{width:190,height:190,borderRadius:95,overflow:"hidden",backgroundColor:"#DCE2F0",alignSelf:"center",marginTop:78,alignItems:"center",justifyContent:"center"},bigImage:{width:190,height:190},bigInitial:{fontSize:70,color:"#65676B"},detailName:{fontSize:31,fontWeight:"800",textAlign:"center",color:"#050505",marginTop:25},remove:{height:100,borderWidth:1,borderColor:BORDER,borderRadius:22,justifyContent:"center",paddingHorizontal:30,marginTop:72},removeText:{fontSize:22,color:RED},explain:{fontSize:18,lineHeight:26,color:MUTED,marginTop:30},center:{flex:1,alignItems:"center",justifyContent:"center"}});
