import { useCallback, useEffect, useRef, useState } from "react";
import { ActivityIndicator, Animated, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { messageService, type ConversationSummary } from "../messages/messageService";
import { fadeIn } from "../lib/animation";

export function MessagesScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const [items, setItems] = useState<ConversationSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");
  const [error, setError] = useState("");
  const opacity = useRef(new Animated.Value(0)).current;
  const load = useCallback(async () => { setLoading(true); setError(""); try { const r = await messageService.listConversations(); setItems(r.conversations); fadeIn(opacity).start(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load messages."); } finally { setLoading(false); } }, [opacity]);
  useEffect(() => { void load(); }, [load]);
  const visible = items.filter((item) => !query || (item.groupName || "").toLowerCase().includes(query.toLowerCase()) || (item.lastMessage?.message || "").toLowerCase().includes(query.toLowerCase()));
  return <SafeAreaView style={styles.root}><View style={styles.header}><Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Messages</Text><View style={{ width: 32 }} /></View><View style={styles.search}><TextInput value={query} onChangeText={setQuery} placeholder="Search messages" placeholderTextColor="#8A8D91" style={styles.input} /></View>{error ? <Pressable onPress={() => void load()} style={styles.error}><Text style={styles.errorText}>{error}  Tap to retry.</Text></Pressable> : null}{loading && !items.length ? <View style={styles.center}><ActivityIndicator size="large" color="#1877F2" /></View> : <Animated.ScrollView style={{ opacity }} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} />} contentContainerStyle={styles.list}>{visible.map((item) => <Pressable key={item.id} style={styles.row} onPress={() => navigation.navigate("Chat", { conversationId: item.id })}><View style={styles.avatar}><Text style={styles.avatarText}>{(item.groupName || "R").slice(0, 1).toUpperCase()}</Text></View><View style={styles.copy}><Text style={styles.name}>{item.groupName || "Direct conversation"}</Text><Text numberOfLines={1} style={styles.preview}>{item.lastMessage?.message || "No messages yet"}</Text></View>{item.unreadMessageCount > 0 ? <View style={styles.badge}><Text style={styles.badgeText}>{item.unreadMessageCount > 99 ? "99+" : item.unreadMessageCount}</Text></View> : null}</Pressable>)}{!visible.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>No conversations</Text><Text style={styles.preview}>Messages you can access will appear here.</Text></View> : null}</Animated.ScrollView>}</SafeAreaView>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: "#F0F2F5" }, header: { height: 58, backgroundColor: "#FFF", borderBottomWidth: 1, borderBottomColor: "#E4E6EB", flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 12 }, back: { fontSize: 38, color: "#1877F2" }, title: { fontSize: 19, fontWeight: "800", color: "#050505" }, search: { backgroundColor: "#FFF", padding: 10 }, input: { height: 42, backgroundColor: "#F0F2F5", borderRadius: 21, paddingHorizontal: 16, color: "#050505" }, error: { backgroundColor: "#FFF1F1", padding: 10 }, errorText: { color: "#B42318", textAlign: "center", fontSize: 13 }, list: { padding: 8 }, row: { minHeight: 70, backgroundColor: "#FFF", borderRadius: 14, marginBottom: 7, padding: 12, flexDirection: "row", alignItems: "center" }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: "#1877F2", alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFF", fontSize: 20, fontWeight: "800" }, copy: { flex: 1, marginLeft: 12 }, name: { fontSize: 15, fontWeight: "700", color: "#050505" }, preview: { marginTop: 4, color: "#65676B", fontSize: 14 }, badge: { minWidth: 24, height: 24, paddingHorizontal: 7, borderRadius: 12, backgroundColor: "#1877F2", alignItems: "center", justifyContent: "center" }, badgeText: { color: "#FFF", fontSize: 12, fontWeight: "800" }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, empty: { alignItems: "center", paddingTop: 80 }, emptyTitle: { fontSize: 20, fontWeight: "800", color: "#050505" } });
