import React,{useEffect,useState}from"react";
import{SafeAreaView,View,Text,Pressable,StyleSheet,ScrollView,ActivityIndicator,TextInput,Alert}from"react-native";
import{useNavigation}from"@react-navigation/native";
import{useTheme}from"../theme/ThemeProvider";
import BackIcon from"../assets/navigation/back.svg";
import{ordersPaymentsService,type PaymentAddress}from"../services/ordersPaymentsService";

export function PaymentAddressesScreen(){
 const n=useNavigation<any>();const{colors}=useTheme();const[addresses,setAddresses]=useState<PaymentAddress[]>([]);const[q,setQ]=useState("");const[suggestions,setSuggestions]=useState<any[]>([]);const[fullName,setFullName]=useState("");const[address,setAddress]=useState("");const[city,setCity]=useState("");const[state,setState]=useState("");const[postal,setPostal]=useState("");const[countryCode,setCountryCode]=useState("NG");const[countryName,setCountryName]=useState("Nigeria");const[placeId,setPlaceId]=useState<string|null>(null);const[lat,setLat]=useState<number|null>(null);const[lng,setLng]=useState<number|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await ordersPaymentsService.paymentAddresses();setAddresses(r.addresses)}catch(e){Alert.alert("Addresses",e instanceof Error?e.message:"Unable to load addresses.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 useEffect(()=>{const t=setTimeout(()=>{if(q.trim().length>=2)void ordersPaymentsService.addressSearch(q).then(r=>setSuggestions(r.suggestions)).catch(()=>setSuggestions([]));else setSuggestions([])},300);return()=>clearTimeout(t)},[q]);
 const select=(x:any)=>{setQ(x.placeName);setAddress(x.placeName);setPlaceId(x.id||null);setLat(x.latitude??null);setLng(x.longitude??null);setSuggestions([]);const ctx=Array.isArray(x.context)?x.context:[];const country=ctx.find((v:any)=>String(v.id||"").startsWith("country"));const region=ctx.find((v:any)=>String(v.id||"").startsWith("region"));const place=ctx.find((v:any)=>String(v.id||"").startsWith("place")||String(v.id||"").startsWith("locality"));if(country){setCountryCode(String(country.shortCode||"ng").slice(-2).toUpperCase());setCountryName(String(country.text||""));}if(region&&!state)setState(String(region.text||""));if(place&&!city)setCity(String(place.text||""));};
 const save=async()=>{if(!fullName.trim()||!address.trim()||!city.trim()||!countryCode.trim())return Alert.alert("Address","Enter your name, address, city and country.");setSaving(true);try{const r=await ordersPaymentsService.createPaymentAddress({countryCode,countryName,fullName:fullName.trim(),addressLine1:address.trim(),city:city.trim(),state:state.trim()||null,postalCode:postal.trim()||null,mapboxPlaceId:placeId,latitude:lat,longitude:lng,isDefault:addresses.length===0});setAddresses(v=>[r.address,...v.filter(x=>x.id!==r.address.id)]);setFullName("");setQ("");setAddress("");setCity("");setState("");setPostal("");setPlaceId(null);setLat(null);setLng(null);Alert.alert("Address saved","Your billing and shipping address is now available for ReDom Pay.");}catch(e){Alert.alert("Address",e instanceof Error?e.message:"Unable to save address.");}finally{setSaving(false)}};
 return <SafeAreaView style={[s.root,{backgroundColor:colors.background}]}>
  <View style={[s.header,{backgroundColor:colors.surface,borderBottomColor:colors.border}]}><Pressable onPress={()=>n.goBack()}><BackIcon width={24} height={24}/></Pressable><Text style={[s.title,{color:colors.text}]}>Addresses</Text><View style={{width:24}}/></View>
  <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
   <Text style={[s.heading,{color:colors.text}]}>Billing and shipping addresses</Text><Text style={[s.muted,{color:colors.textSecondary}]}>Search an address with Mapbox suggestions or enter it manually, then save it for secure checkout.</Text>
   <TextInput value={q} onChangeText={setQ} placeholder="Search address" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   {suggestions.map(x=><Pressable key={x.id} onPress={()=>select(x)} style={[s.suggestion,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={{color:colors.text}}>{x.placeName}</Text></Pressable>)}
   <TextInput value={fullName} onChangeText={setFullName} placeholder="Full name" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   <TextInput value={address} onChangeText={setAddress} placeholder="Address" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   <View style={s.row}><TextInput value={city} onChangeText={setCity} placeholder="City" placeholderTextColor={colors.textSecondary} style={[s.input,s.half,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/><TextInput value={state} onChangeText={setState} placeholder="State" placeholderTextColor={colors.textSecondary} style={[s.input,s.half,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/></View>
   <TextInput value={postal} onChangeText={setPostal} placeholder="Postal / ZIP code" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   <Pressable disabled={saving} onPress={()=>void save()} style={[s.button,{backgroundColor:saving?colors.border:colors.primary}]}><Text style={s.buttonText}>{saving?"Saving…":"Save address"}</Text></Pressable>
   <Text style={[s.section,{color:colors.text}]}>Saved addresses</Text>
   {loading?<ActivityIndicator color={colors.primary}/>:addresses.length===0?<Text style={[s.empty,{color:colors.textSecondary}]}>No saved payment addresses yet.</Text>:addresses.map(a=><View key={a.id} style={[s.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[s.name,{color:colors.text}]}>{a.full_name}{a.is_default?" · Default":""}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>{a.address_line1}{a.address_line2?" · "+a.address_line2:""}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>{a.city}{a.state?", "+a.state:""} {a.postal_code||""}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>{a.country_name}</Text></View>)}
  </ScrollView>
 </SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1},header:{height:58,borderBottomWidth:1,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:14},title:{fontSize:20,fontWeight:"800"},content:{padding:18,paddingBottom:40},heading:{fontSize:24,fontWeight:"900"},muted:{fontSize:14,lineHeight:21,marginTop:6},input:{height:54,borderWidth:1,borderRadius:13,paddingHorizontal:14,fontSize:16,marginTop:10},suggestion:{padding:14,borderWidth:1,borderRadius:11,marginTop:7},row:{flexDirection:"row",gap:10},half:{flex:1},button:{height:54,borderRadius:27,alignItems:"center",justifyContent:"center",marginTop:14},buttonText:{color:"#fff",fontSize:17,fontWeight:"800"},section:{fontSize:21,fontWeight:"900",marginTop:30,marginBottom:8},empty:{fontSize:16,paddingVertical:15},card:{borderWidth:1,borderRadius:14,padding:15,marginTop:10},name:{fontSize:17,fontWeight:"800"}});
