import React,{useEffect,useState}from"react";
import{SafeAreaView,View,Text,Pressable,StyleSheet,ActivityIndicator,Switch,ScrollView,Alert,Modal,TextInput}from"react-native";
import{useNavigation,useFocusEffect}from"@react-navigation/native";
import{useTheme}from"../theme/ThemeProvider";
import{ordersPaymentsService}from"../services/ordersPaymentsService";
import BackIcon from"../assets/navigation/back.svg";
import SecurityIcon from"../assets/home-feed/security-controls.svg";
import ChevronIcon from"../assets/home-feed/chevron-right.svg";

export function PaymentSecurityScreen(){
 const n=useNavigation<any>();const{colors}=useTheme();const[s,setS]=useState<any>(null);const[showDisable,setShowDisable]=useState(false);const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);
 const load=async()=>{try{const r=await ordersPaymentsService.getSettings();setS(r.settings)}catch(e){Alert.alert("Payment security",e instanceof Error?e.message:"Unable to load payment security.")}};
 useEffect(()=>{void load()},[]);useFocusEffect(React.useCallback(()=>{void load()},[]));
 const update=async(v:any)=>{try{const r=await ordersPaymentsService.updateSettings(v);setS(r.settings)}catch(e){Alert.alert("Payment security",e instanceof Error?e.message:"Unable to update payment security.")}};
 const confirmDisable=async()=>{if(!password.trim())return;setBusy(true);try{await ordersPaymentsService.disablePaymentPin(password);setPassword("");setShowDisable(false);await load();}catch(e){Alert.alert("Payment security",e instanceof Error?e.message:"Unable to disable the payment PIN.")}finally{setBusy(false)}};
 if(!s)return <SafeAreaView style={[st.root,{backgroundColor:colors.background}]}><ActivityIndicator style={{marginTop:30}} color={colors.primary}/></SafeAreaView>;
 return <SafeAreaView style={[st.root,{backgroundColor:colors.background}]}>
  <View style={[st.header,{backgroundColor:colors.surface,borderBottomColor:colors.border}]}><Pressable onPress={()=>n.goBack()}><BackIcon width={24} height={24}/></Pressable><Text style={[st.title,{color:colors.text}]}>Security and payment PIN</Text><View style={{width:24}}/></View>
  <Modal visible={showDisable} transparent animationType="fade" onRequestClose={()=>{setShowDisable(false);setPassword("")}}><View style={st.modalBackdrop}><View style={[st.modalCard,{backgroundColor:colors.surface}]}><Text style={[st.modalTitle,{color:colors.text}]}>Disable payment PIN</Text><Text style={[st.modalText,{color:colors.textSecondary}]}>Enter your ReDom account password to confirm. Your PIN will be removed.</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry autoCapitalize="none" placeholder="Account password" placeholderTextColor={colors.textSecondary} style={[st.input,{color:colors.text,borderColor:colors.border}]}/><View style={st.modalButtons}><Pressable onPress={()=>{setShowDisable(false);setPassword("")}}><Text style={[st.cancel,{color:colors.text}]}>Cancel</Text></Pressable><Pressable disabled={busy||!password.trim()} onPress={()=>void confirmDisable()} style={[st.disableButton,{backgroundColor:busy||!password.trim()?colors.border:"#D32F2F"}]}><Text style={st.disableText}>{busy?"Disabling…":"Disable"}</Text></Pressable></View></View></View></Modal>
  <ScrollView><Text style={[st.section,{color:colors.text}]}>Security</Text><View style={st.sectionIcon}><SecurityIcon width={28} height={28} color={colors.text}/></View>
   <Toggle title="Use PIN to confirm payments" text="PIN will be required for payment confirmations when enabled." value={Boolean(s.pin_enabled)} onChange={(v:boolean)=>{if(v)n.navigate("PaymentPin");else setShowDisable(true)}} colors={colors}/>
   <Toggle title="Use biometric data instead of PIN" text="Use supported device biometrics after the device has authenticated you." value={Boolean(s.biometric_enabled)} onChange={(v:boolean)=>void update({biometricEnabled:v})} colors={colors}/>
   <View style={[st.divider,{backgroundColor:colors.border}]}/><Text style={[st.section,{color:colors.text}]}>Currency</Text>
   <Pressable style={[st.currency,{borderBottomColor:colors.border}]} onPress={()=>n.navigate("SelectCurrency")}><Text style={[st.curLabel,{color:colors.text}]}>Currency</Text><View style={st.currencyValue}><Text style={[st.curValue,{color:colors.textSecondary}]}>{s.currency}</Text><ChevronIcon width={20} height={20}/></View></Pressable>
  </ScrollView>
 </SafeAreaView>
}
function Toggle(p:any){return <View style={st.toggle}><View style={{flex:1}}><Text style={[st.toggleTitle,{color:p.colors.text}]}>{p.title}</Text><Text style={[st.toggleText,{color:p.colors.textSecondary}]}>{p.text}</Text></View><Switch value={p.value} onValueChange={p.onChange} trackColor={{false:"#D9DDE3",true:"#9FC4FF"}} thumbColor={p.value?p.colors.primary:"#FFF"}/></View>}
const st=StyleSheet.create({root:{flex:1},header:{height:58,borderBottomWidth:1,flexDirection:"row",alignItems:"center",paddingHorizontal:14},title:{fontSize:18,fontWeight:"800",marginLeft:12},section:{fontSize:22,fontWeight:"900",paddingHorizontal:30,paddingTop:28,paddingBottom:18},sectionIcon:{paddingHorizontal:30,marginTop:-6,marginBottom:18},toggle:{paddingHorizontal:30,paddingBottom:22,flexDirection:"row",alignItems:"flex-start"},toggleTitle:{fontSize:20,fontWeight:"600"},toggleText:{fontSize:16,lineHeight:23,marginTop:8},divider:{height:1,marginHorizontal:30},currency:{minHeight:62,paddingHorizontal:30,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1},currencyValue:{flexDirection:"row",alignItems:"center",gap:8},curLabel:{fontSize:18},curValue:{fontSize:18},modalBackdrop:{flex:1,backgroundColor:"rgba(0,0,0,.45)",alignItems:"center",justifyContent:"center",padding:25},modalCard:{width:"100%",borderRadius:18,padding:20},modalTitle:{fontSize:20,fontWeight:"900"},modalText:{fontSize:15,lineHeight:21,marginTop:8},input:{height:52,borderWidth:1,borderRadius:12,paddingHorizontal:14,fontSize:16,marginTop:15},modalButtons:{flexDirection:"row",justifyContent:"flex-end",alignItems:"center",gap:18,marginTop:18},cancel:{fontWeight:"800",padding:10},disableButton:{paddingHorizontal:18,paddingVertical:11,borderRadius:22},disableText:{color:"#fff",fontWeight:"800"}});
