import React,{useEffect,useState} from "react";
import { SafeAreaView,View,Text,Pressable,StyleSheet,ScrollView,Alert } from "react-native";
import { useNavigation } from "@react-navigation/native";
import { useTheme } from "../theme/ThemeProvider";
import { ordersPaymentsService } from "../services/ordersPaymentsService";
const currencies=[["USD","US Dollar"],["NGN","Nigerian Naira"],["EUR","Euro"],["GBP","British Pound"],["CAD","Canadian Dollar"]];
export function PaymentCurrencyScreen(){
 const navigation=useNavigation<any>(); const {colors}=useTheme(); const [current,setCurrent]=useState("USD"); const [busy,setBusy]=useState(false);
 useEffect(()=>{void ordersPaymentsService.getSettings().then(r=>setCurrent(r.settings.currency)).catch(()=>undefined)},[]);
 const choose=async(code:string)=>{if(code===current){navigation.goBack();return;} setBusy(true); try{await ordersPaymentsService.updateSettings({currency:code});setCurrent(code);navigation.goBack();}catch(e){Alert.alert("Change currency?",e instanceof Error?e.message:"You can only change your currency once every 72 hours.",[{text:"CANCEL",style:"cancel"},{text:"OK"}]);}finally{setBusy(false);}};
 return <SafeAreaView style={[styles.root,{backgroundColor:colors.background}]}><View style={[styles.header,{backgroundColor:colors.surface,borderBottomColor:colors.border}]}><Pressable onPress={()=>navigation.goBack()}><Text style={[styles.back,{color:colors.text}]}>‹</Text></Pressable><Text style={[styles.title,{color:colors.text}]}>Currency</Text><View style={{width:42}}/></View><ScrollView>{currencies.map(([code,name])=><Pressable disabled={busy} key={code} onPress={()=>void choose(code)} style={[styles.row,{borderBottomColor:colors.border}]}><View><Text style={[styles.code,{color:colors.text}]}>{code}</Text><Text style={[styles.name,{color:colors.textSecondary}]}>{name}</Text></View><Text style={[styles.radio,{color:current===code?colors.primary:colors.muted}]}>{current===code?"●":"○"}</Text></Pressable>)}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({root:{flex:1},header:{height:58,borderBottomWidth:1,flexDirection:"row",alignItems:"center",paddingHorizontal:14},back:{fontSize:40,width:42},title:{fontSize:19,fontWeight:"800",flex:1,textAlign:"center"},row:{minHeight:72,paddingHorizontal:30,flexDirection:"row",alignItems:"center",justifyContent:"space-between",borderBottomWidth:1},code:{fontSize:18,fontWeight:"800"},name:{fontSize:14,marginTop:3},radio:{fontSize:25}});