import React,{useEffect,useState}from"react";
import{SafeAreaView,View,Text,Pressable,StyleSheet,ScrollView,TextInput,ActivityIndicator,Alert}from"react-native";
import{useNavigation}from"@react-navigation/native";
import{useTheme}from"../theme/ThemeProvider";
import BackIcon from"../assets/navigation/back.svg";
import{ordersPaymentsService}from"../services/ordersPaymentsService";import type{PaymentAddress}from"../services/ordersPaymentsService";

export function PaymentAddressesScreen(){
 const n=useNavigation<any>();const{colors}=useTheme();
 const[addresses,setAddresses]=useState<PaymentAddress[]>([]);const[q,setQ]=useState("");const[suggestions,setSuggestions]=useState<any[]>([]);
 const[fullName,setFullName]=useState("");const[address,setAddress]=useState("");const[city,setCity]=useState("");const[state,setState]=useState("");const[zip,setZip]=useState("");const[countryCode,setCountryCode]=useState("NG");const[countryName,setCountryName]=useState("Nigeria");const[placeId,setPlaceId]=useState<string|null>(null);const[lat,setLat]=useState<number|null>(null);const[lng,setLng]=useState<number|null>(null);const[saving,setSaving]=useState(false);const[loading,setLoading]=useState(true);
 const load=async()=>{try{const r=await ordersPaymentsService.paymentAddresses();setAddresses(r.addresses)}catch(e){Alert.alert("Addresses",e instanceof Error?e.message:"Unable to load addresses.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const t=setTimeout(()=>{if(q.trim().length>=3)void ordersPaymentsService.addressSearch(q).then(r=>setSuggestions(r.suggestions)).catch(()=>setSuggestions([]));else setSuggestions([])},300);return()=>clearTimeout(t)},[q]);
 const choose=(x:any)=>{setQ(x.placeName);setAddress(x.placeName);setPlaceId(x.id||null);setLat(x.latitude??null);setLng(x.longitude??null);const cc=Array.isArray(x.context)?x.context.find((v:any)=>String(v.id||"").startsWith("country.")):null;if(cc){setCountryName(String(cc.text||countryName));const code=String(cc.shortCode||"").split("-").pop().toUpperCase();if(code)setCountryCode(code)}setSuggestions([])};
 const save=async()=>{if(!fullName.trim()||!address.trim()||!city.trim()){Alert.alert("Save address","Enter your full name, address and city.");return}setSaving(true);try{await ordersPaymentsService.savePaymentAddress({country_code:countryCode,country_name:countryName,full_name:fullName.trim(),address_line1:address.trim(),address_line2:null,city:city.trim(),state:state.trim()||null,postal_code:zip.trim()||null,mapbox_place_id:placeId,latitude:lat,longitude:lng,is_default:addresses.length===0});setFullName("");setAddress("");setCity("");setState("");setZip("");setQ("");setPlaceId(null);setLat(null);setLng(null);await load();Alert.alert("Address saved","Your payment address is now available for checkout.")}catch(e){Alert.alert("Unable to save address",e instanceof Error?e.message:"Please try again.")}finally{setSaving(false)}};
 return <SafeAreaView style={[s.root,{backgroundColor:colors.background}]}>
  <View style={[s.header,{backgroundColor:colors.surface,borderBottomColor:colors.border}]}><Pressable onPress={()=>n.goBack()}><BackIcon width={24} height={24}/></Pressable><Text style={[s.title,{color:colors.text}]}>Addresses</Text><View style={{width:28}}/></View>
  <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
   <Text style={[s.heading,{color:colors.text}]}>Billing and shipping addresses</Text><Text style={[s.muted,{color:colors.textSecondary}]}>Search for a place, select a suggestion, complete the address and save it for checkout.</Text>
   <TextInput value={q} onChangeText={setQ} placeholder="Search address" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   {suggestions.map(x=><Pressable key={x.id} onPress={()=>choose(x)} style={[s.suggestion,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={{color:colors.text}}>{x.placeName}</Text></Pressable>)}
   <TextInput value={fullName} onChangeText={setFullName} placeholder="Full name" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   <TextInput value={address} onChangeText={setAddress} placeholder="Address" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   <View style={s.row}><TextInput value={city} onChangeText={setCity} placeholder="City" placeholderTextColor={colors.textSecondary} style={[s.input,s.half,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/><TextInput value={state} onChangeText={setState} placeholder="State" placeholderTextColor={colors.textSecondary} style={[s.input,s.half,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/></View>
   <TextInput value={zip} onChangeText={setZip} placeholder="Zip code" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   <Pressable disabled={saving} onPress={()=>void save()} style={[s.button,{backgroundColor:saving?colors.border:colors.primary}]}><Text style={s.buttonText}>{saving?"Saving…":"Save address"}</Text></Pressable>
   <Text style={[s.section,{color:colors.text}]}>Saved addresses</Text>
   {loading?<ActivityIndicator color={colors.primary}/>:addresses.length===0?<Text style={[s.empty,{color:colors.textSecondary}]}>No saved payment addresses yet.</Text>:addresses.map(a=><View key={a.id} style={[s.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[s.name,{color:colors.text}]}>{a.full_name}{a.is_default?" · Default":""}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>{a.address_line1}{a.address_line2?" · "+a.address_line2:""}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>{a.city}{a.state?", "+a.state:""} {a.postal_code||""}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>{a.country_name}</Text></View>)}
  </ScrollView>
 </SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1},header:{height:58,borderBottomWidth:1,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:14},title:{fontSize:20,fontWeight:"800"},content:{padding:18,paddingBottom:40},heading:{fontSize:24,fontWeight:"900"},muted:{fontSize:14,lineHeight:21,marginTop:6},input:{height:54,borderWidth:1,borderRadius:13,paddingHorizontal:14,fontSize:16,marginTop:12},suggestion:{padding:14,borderWidth:1,borderRadius:11,marginTop:7},row:{flexDirection:"row",gap:10},half:{flex:1},button:{height:54,borderRadius:27,alignItems:"center",justifyContent:"center",marginTop:16},buttonText:{color:"#fff",fontSize:17,fontWeight:"800"},section:{fontSize:21,fontWeight:"900",marginTop:28,marginBottom:8},card:{borderWidth:1,borderRadius:14,padding:15,marginTop:10},name:{fontSize:17,fontWeight:"800"},empty:{fontSize:16,textAlign:"center",paddingVertical:15}});
