import { useCallback, useMemo, useState } from "react";
import { useFocusEffect } from "@react-navigation/native";
import { Alert, Image, ImageBackground, Modal, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";
import * as Clipboard from "expo-clipboard";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import HomeIcon from "../assets/home-feed/home.svg";
import VideoIcon from "../assets/home-feed/video.svg";
import MarketplaceIcon from "../assets/home-feed/marketplace.svg";
import NotificationsIcon from "../assets/home-feed/notifications.svg";
import ProfilePlaceholder from "../assets/home-feed/profile-placeholder.svg";
import CameraIcon from "../assets/home-feed/profile-camera.svg";
import CoverCameraIcon from "../assets/home-feed/profile-cover-camera.svg";
import CoverEditIcon from "../assets/home-feed/profile-cover-edit.svg";
import CoverSearchIcon from "../assets/home-feed/profile-cover-search.svg";
import CoverMoreIcon from "../assets/home-feed/profile-cover-more.svg";
import LocationIcon from "../assets/home-feed/profile-location.svg";
import DropdownIcon from "../assets/home-feed/profile-dropdown.svg";
import AddStoryIcon from "../assets/home-feed/profile-add-story.svg";
import EditIcon from "../assets/home-feed/profile-edit.svg";
import CalendarIcon from "../assets/home-feed/profile-calendar.svg";
import EyeIcon from "../assets/home-feed/profile-eye.svg";
import ReDomRecordIcon from "../assets/home-feed/profile-redom.svg";
import MenuIcon from "../assets/home-feed/menu.svg";
import LinkIcon from "../assets/home-feed/profile-link.svg";
import GalleryIcon from "../assets/home-feed/profile-gallery.svg";
import ReelIcon from "../assets/home-feed/profile-reel.svg";
import LiveIcon from "../assets/home-feed/profile-live.svg";
import SettingsIcon from "../assets/home-feed/settings.svg";
import FollowIcon from "../assets/home-feed/follow.svg";
import PrivacyIcon from "../assets/home-feed/privacy-center.svg";
import ReportIcon from "../assets/home-feed/report.svg";
import ShareIcon from "../assets/home-feed/share.svg";
import SessionIcon from "../assets/home-feed/session.svg";
import { useAuthContext } from "../auth/context";
import { profileService, type ProfileData, type ProfileSuggestion } from "../profile/service";
import type { RootStackParamList } from "../routing/types";

type Props = NativeStackScreenProps<RootStackParamList, "Profile">;
type SheetKind = "owner" | "visitor" | "cover" | "avatar" | null;
type Tab = "All" | "Reels" | "Photos" | "Events";
function Avatar({ uri, size = 48 }: { uri?: string | null; size?: number }) { return uri ? <Image source={{ uri }} style={{ width: size, height: size, borderRadius: size / 2 }} /> : <ProfilePlaceholder width={size} height={size} />; }
function compact(value: number) { if (value < 1000) return String(value); if (value < 1000000) return `${(value / 1000).toFixed(value < 10000 ? 1 : 0).replace(/\.0$/, "")}K`; return `${(value / 1000000).toFixed(1).replace(/\.0$/, "")}M`; }
const PROFILE_PROMPTS = ["Share a song...", "What's on your mind?", "Share your favorite emoji?", "Oh, share a wish"];

export function ProfileScreen({ navigation, route }: Props) {
  const { user } = useAuthContext();
  const { width } = useWindowDimensions();
  const ui = useMemo(() => makeStyles(width), [width]);
  const [profile, setProfile] = useState<ProfileData | null>(null);
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [tab, setTab] = useState<Tab>("All");
  const [adding, setAdding] = useState<string | null>(null); const [sheet, setSheet] = useState<SheetKind>(null); const [searchOpen, setSearchOpen] = useState(false); const [searchText, setSearchText] = useState(""); const [filterOpen, setFilterOpen] = useState(false); const [promptIndex, setPromptIndex] = useState(0); const [visitorPreview, setVisitorPreview] = useState(false);
  const requestedUserId = route.params?.userId;
  const refreshProfile = useCallback(async () => { setRefreshing(true); setLoading(true); try { const result = await profileService.getProfile(requestedUserId); setProfile(result.profile); setPromptIndex((current) => (current + 1) % PROFILE_PROMPTS.length); } catch { Alert.alert("Profile", "Unable to load this profile right now."); } finally { setLoading(false); setRefreshing(false); } }, [requestedUserId]);
  useFocusEffect(useCallback(() => { setVisitorPreview(false); void refreshProfile(); }, [refreshProfile]));
  const p = profile; const owner = !!p && (p.isOwner || p.profileId === user?.profileId); const isVisitorView = !owner || visitorPreview; const canEdit = owner && !visitorPreview; const name = p ? `${p.firstName} ${p.lastName}`.trim() : user ? `${user.firstName} ${user.lastName}`.trim() : "Profile"; const firstName = p?.firstName || user?.firstName || "";
  const add = async (suggestion: ProfileSuggestion) => { if (adding) return; setAdding(suggestion.userId); try { const result = await profileService.addSuggestion(suggestion.userId); Alert.alert(result.success ? "Friend request sent" : "Couldn't add this person", result.success ? "Your friend request was sent." : (result.reason || "We couldn't send the request right now.")); } finally { setAdding(null); } };
  const openSuggestedProfile = (suggestion: ProfileSuggestion) => navigation.navigate("Profile", { userId: suggestion.userId });
  const copyProfileLink = async () => { if (!p?.shareUrl) return; await Clipboard.setStringAsync(p.shareUrl); Alert.alert("Copied", `${firstName || name}'s ReDom profile link was copied.`); };
  const enterVisitorPreview = () => { setSheet(null); setVisitorPreview(true); }; const leaveVisitorPreview = () => setVisitorPreview(false);
  return (<SafeAreaView style={ui.root}><View style={ui.nav}><Pressable style={ui.navItem} onPress={() => navigation.navigate("HomeFeed")}><HomeIcon width={ui.icon} height={ui.icon} /></Pressable><Pressable style={ui.navItem}><VideoIcon width={ui.icon} height={ui.icon} /></Pressable><Pressable style={ui.navItem}><MarketplaceIcon width={ui.icon} height={ui.icon} /></Pressable><Pressable style={ui.navItem}><NotificationsIcon width={ui.icon} height={ui.icon} /></Pressable><Pressable style={[ui.navItem, ui.activeNav]} onPress={() => (canEdit ? void refreshProfile() : navigation.navigate("Profile"))} accessibilityLabel={canEdit ? "Refresh current profile" : "Open my profile"}><Avatar uri={p?.profilePhoto || user?.profilePhoto} size={ui.navAvatar} /></Pressable></View>{visitorPreview ? <View style={ui.previewBanner}><EyeIcon width={ui.previewBannerIcon} height={ui.previewBannerIcon} /><Text style={ui.previewBannerText}>Viewing your profile as a visitor</Text><Pressable onPress={leaveVisitorPreview} style={ui.previewDone}><Text style={ui.previewDoneText}>Exit</Text></Pressable></View> : null}<ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={ui.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refreshProfile} />}>
  <View style={ui.coverWrap}>{p?.coverPhoto ? <ImageBackground source={{ uri: p.coverPhoto }} style={ui.cover} resizeMode="cover"><View style={ui.coverShade} /></ImageBackground> : <View style={ui.cover}><View style={ui.coverShade} /></View>}{canEdit ? <Pressable style={ui.menuButton} accessibilityLabel="Open profile navigation"><MenuIcon width={ui.coverToolIcon} height={ui.coverToolIcon} /></Pressable> : null}<View style={ui.coverTools}>{canEdit ? <Pressable accessibilityLabel="Edit cover photo"><CoverEditIcon width={ui.coverToolIcon} height={ui.coverToolIcon} /></Pressable> : null}<Pressable accessibilityLabel="Search profile" onPress={() => setSearchOpen(true)}><CoverSearchIcon width={ui.coverToolIcon} height={ui.coverToolIcon} /></Pressable><Pressable accessibilityLabel="More profile options" onPress={() => setSheet(owner ? "owner" : "visitor")}><CoverMoreIcon width={ui.coverToolIcon} height={ui.coverToolIcon} /></Pressable></View><Pressable style={ui.songBubble} accessibilityLabel="Profile prompt"><Text style={ui.songText}>{PROFILE_PROMPTS[promptIndex]}</Text></Pressable>{canEdit ? <Pressable style={ui.coverCamera} onPress={() => setSheet("cover")} accessibilityLabel="Change cover photo"><CoverCameraIcon width={ui.cameraIcon} height={ui.cameraIcon} /></Pressable> : null}<View style={ui.avatarPosition}><View style={ui.avatarRing}><Avatar uri={p?.profilePhoto || user?.profilePhoto} size={ui.profileAvatar} /></View>{canEdit ? <Pressable style={ui.profileCamera} onPress={() => setSheet("avatar")} accessibilityLabel="Change profile picture"><CameraIcon width={ui.cameraIcon} height={ui.cameraIcon} /></Pressable> : null}</View></View>
  <View style={ui.identityBlock}><View style={ui.identityTop}><View style={ui.identityText}><View style={ui.nameRow}><Text style={ui.name} numberOfLines={2}>{name}</Text>{p?.verified ? <Text style={ui.verifiedBadge}>✓</Text> : null}</View><Text style={ui.username}>{p?.username ? `@${p.username}` : ""}</Text><Text style={ui.countLine}>{p?.friendCount ?? 0} Friends <Text style={ui.dot}>•</Text> {p?.postCount ?? 0} posts</Text></View><Pressable style={ui.dropdown} accessibilityLabel="Additional profile information"><DropdownIcon width={ui.dropdownSize} height={ui.dropdownSize} /></Pressable></View>{p?.location ? <View style={ui.locationLine}><LocationIcon width={ui.detailIcon} height={ui.detailIcon} /><Text style={ui.locationText}>{p.location}</Text></View> : null}<View style={ui.mainButtons}>{canEdit ? <><Pressable style={ui.primaryButton} accessibilityLabel="Add to story"><AddStoryIcon width={ui.buttonIcon} height={ui.buttonIcon} /><Text style={ui.primaryText}>Add to story</Text></Pressable><Pressable style={ui.secondaryButton} onPress={() => navigation.navigate("EditProfile")} accessibilityLabel="Edit profile"><EditIcon width={ui.buttonIcon} height={ui.buttonIcon} /><Text style={ui.secondaryText}>Edit profile</Text></Pressable></> : owner ? <><View style={[ui.primaryButton, ui.disabledButton]}><Text style={ui.disabledButtonText}>Add Friend</Text></View><View style={[ui.secondaryButton, ui.disabledButton]}><Text style={ui.disabledButtonText}>Message</Text></View></> : <><Pressable style={ui.primaryButton} accessibilityLabel={`Add ${name} as a friend`}><Text style={ui.primaryText}>Add Friend</Text></Pressable><Pressable style={ui.secondaryButton} accessibilityLabel={`Message ${name}`}><Text style={ui.secondaryText}>Message</Text></Pressable></>}</View></View>
  {canEdit && p && p.suggestions.length > 0 ? <View style={ui.suggestionSection}><View style={ui.sectionTitleRow}><Text style={ui.sectionTitle}>People you may know</Text><Pressable accessibilityLabel="Dismiss suggestions"><Text style={ui.closeSuggestion}>×</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={ui.suggestionRail}>{p.suggestions.map((suggestion) => <View key={suggestion.userId} style={ui.suggestionCard}><Pressable style={ui.suggestionProfileTap} onPress={() => openSuggestedProfile(suggestion)} accessibilityRole="button" accessibilityLabel={`Open ${suggestion.firstName} ${suggestion.lastName}'s profile`}><View style={ui.suggestionAvatarWrap}><Avatar uri={suggestion.profilePhoto} size={ui.suggestionAvatar} /></View><Text style={ui.suggestionName} numberOfLines={1}>{suggestion.firstName} {suggestion.lastName}</Text></Pressable><Pressable style={ui.addButton} onPress={() => void add(suggestion)} disabled={adding === suggestion.userId}><Text style={ui.addText}>{adding === suggestion.userId ? "Adding..." : "Add"}</Text></Pressable></View>)}</ScrollView><Pressable style={ui.addAll} onPress={() => p.suggestions.forEach((suggestion) => void add(suggestion))}><Text style={ui.addAllText}>Add All</Text></Pressable></View> : null}
  <View style={ui.tabs}>{(["All", "Reels", "Photos", "Events"] as const).map((item) => <Pressable key={item} style={[ui.tab, tab === item && ui.tabActive]} onPress={() => setTab(item)}><Text style={[ui.tabText, tab === item && ui.tabTextActive]}>{item}</Text></Pressable>)}</View>
  {tab === "Reels" ? <View style={ui.mediaSection}><Text style={ui.sectionTitle}>Reels</Text>{p?.reels.length ? <View style={ui.reelGrid}>{p.reels.map((reel) => <View key={reel.id} style={ui.reelCard}>{reel.thumbnail ? <Image source={{ uri: reel.thumbnail }} style={ui.mediaImage} /> : <View style={ui.mediaImage} />}<View style={ui.viewOverlay}><EyeIcon width={ui.viewIcon} height={ui.viewIcon} /><Text style={ui.viewText}>{compact(reel.viewCount)}</Text></View></View>)}</View> : <Text style={ui.emptyText}>{canEdit ? "Please Upload a reel ....." : "No reels to show."}</Text>}</View> : null}
  {tab === "Photos" ? <View style={ui.mediaSection}><Text style={ui.sectionTitle}>Photos</Text>{p?.photos.length ? <View style={ui.photoGrid}>{p.photos.map((photo) => <Image key={photo.id} source={{ uri: photo.thumbnail || photo.url || "" }} style={ui.photoCard} />)}</View> : <Text style={ui.emptyText}>{canEdit ? "You haven't uploaded anything on ReDom yet" : "No photos to show."}</Text>}</View> : null}
  {tab === "Events" ? <View style={ui.mediaSection}><Text style={ui.sectionTitle}>Events</Text><Text style={ui.emptyText}>No events to show.</Text></View> : null}
  {tab === "All" ? <><View style={ui.detailsSection}><View style={ui.sectionTitleRow}><Text style={ui.sectionTitle}>Personal details</Text>{canEdit ? <Pressable accessibilityLabel="Edit personal details"><EditIcon width={ui.editIcon} height={ui.editIcon} /></Pressable> : null}</View>{p?.location ? <View style={ui.detailRow}><LocationIcon width={ui.detailIcon} height={ui.detailIcon} /><Text style={ui.detailText}>{p.location}</Text></View> : null}{p?.birthday ? <View style={ui.detailRow}><CalendarIcon width={ui.detailIcon} height={ui.detailIcon} /><Text style={ui.detailText}>{p.birthday}</Text></View> : null}</View><View style={ui.detailsSection}><Text style={ui.sectionTitle}>ReDom</Text><View style={ui.detailRow}><ReDomRecordIcon width={ui.detailIcon} height={ui.detailIcon} /><View style={ui.redomValue}><Text style={ui.detailText}>Joined ReDom</Text>{p?.joinedAt ? <Text style={ui.subDetail}>{p.joinedAt}</Text> : null}{p?.joinedCountry ? <Text style={ui.subDetail}>{p.joinedCountry}</Text> : null}</View></View></View><View style={ui.friendsSection}><View style={ui.sectionTitleRow}><Text style={ui.sectionTitle}>Friends</Text><Pressable accessibilityLabel="See all friends"><Text style={ui.seeAll}>See all</Text></Pressable></View>{p?.friends.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={ui.friendRail}>{p.friends.slice(0, 12).map((friend) => <View key={friend.userId} style={ui.friendCard}><Avatar uri={friend.profilePhoto} size={ui.friendAvatar} /><Text style={ui.friendName} numberOfLines={1}>{friend.firstName} {friend.lastName}</Text></View>)}</ScrollView> : <Text style={ui.emptyText}>No friends to show.</Text>}</View></> : null}
  <View style={ui.bottomSpacer} /></ScrollView>
  {searchOpen ? <Modal visible transparent animationType="fade" onRequestClose={() => setSearchOpen(false)}><View style={ui.modalBackdrop}><View style={ui.searchModal}><View style={ui.searchHeader}><Text style={ui.searchTitle}>Search profile</Text><Pressable onPress={() => setSearchOpen(false)}><Text style={ui.modalClose}>×</Text></Pressable></View><TextInput autoFocus value={searchText} onChangeText={setSearchText} placeholder="Search" style={ui.modalInput} /><Text style={ui.modalHint}>Search is available for profile content and people.</Text></View></View></Modal> : null}
  {filterOpen ? <Modal visible transparent animationType="slide" onRequestClose={() => setFilterOpen(false)}><View style={ui.modalBackdrop}><View style={ui.filterModal}><Text style={ui.searchTitle}>Filter</Text>{["Posts","Photos","Reels","Events"].map((item) => <Pressable key={item} style={ui.filterRow} onPress={() => setFilterOpen(false)}><Text style={ui.filterText}>{item}</Text><Text style={ui.modalArrow}>›</Text></Pressable>)}</View></View></Modal> : null}
  {sheet ? <Modal visible transparent animationType="slide" onRequestClose={() => setSheet(null)}><View style={ui.modalBackdrop}><View style={ui.sheetModal}>{sheet === "cover" || sheet === "avatar" ? <><Text style={ui.sheetTitle}>{sheet === "cover" ? "Cover photo" : "Profile picture"}</Text><Text style={ui.sheetHint}>Photo controls are ready for the next media action.</Text><Pressable style={ui.sheetClose} onPress={() => setSheet(null)}><Text style={ui.sheetCloseText}>Close</Text></Pressable></> : <><Text style={ui.sheetTitle}>{owner ? "Profile" : "Profile options"}</Text>{owner ? <><Pressable style={ui.sheetRow} onPress={enterVisitorPreview}><SettingsIcon width={25} height={25} /><Text style={ui.sheetRowText}>View profile as visitor</Text></Pressable><Pressable style={ui.sheetRow} onPress={() => void copyProfileLink()}><LinkIcon width={25} height={25} /><Text style={ui.sheetRowText}>Copy profile link</Text></Pressable></> : <><Pressable style={ui.sheetRow}><FollowIcon width={25} height={25} /><Text style={ui.sheetRowText}>Follow</Text></Pressable><Pressable style={ui.sheetRow}><ShareIcon width={25} height={25} /><Text style={ui.sheetRowText}>Share profile</Text></Pressable><Pressable style={ui.sheetRow}><PrivacyIcon width={25} height={25} /><Text style={ui.sheetRowText}>Privacy</Text></Pressable><Pressable style={ui.sheetRow}><ReportIcon width={25} height={25} /><Text style={ui.sheetRowText}>Report</Text></Pressable></>}<Pressable style={ui.sheetClose} onPress={() => setSheet(null)}><Text style={ui.sheetCloseText}>Close</Text></Pressable></>}</View></View></Modal> : null}
  {loading && !p ? <View style={ui.loadingOverlay}><Text style={ui.loadingText}>Loading profile...</Text></View> : null}
  </SafeAreaView>);
}
