import { useEffect, useState } from "react";
import { Alert, Image, Modal, Pressable, SafeAreaView, Share, StyleSheet, Text, TextInput, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import CloseIcon from "../assets/navigation/close.svg";
import LikeIcon from "../assets/home-feed/like.svg";
import CommentIcon from "../assets/home-feed/comment.svg";
import ShareIcon from "../assets/home-feed/share.svg";
import { api } from "../api/client";
import { profileService } from "../profile/service";

type Props = NativeStackScreenProps<RootStackParamList, "ProfilePictureViewer">;
export function ProfilePictureViewerScreen({ navigation }: Props) {
  const [media,setMedia]=useState<{postId:string;publishedAt:string;caption:string|null}|null>(null);
  const [uri,setUri]=useState<string|null>(null);
  const [commentOpen,setCommentOpen]=useState(false);
  const [comment,setComment]=useState("");
  const [liked,setLiked]=useState(false);
  useEffect(()=>{void Promise.all([api.get<any>("/profile/media/current"),profileService.getProfile()]).then(([m,p])=>{setMedia(m.media);setUri(p.profile.profilePhoto);}).catch(()=>undefined);},[]);
  const react=async()=>{if(!media)return;try{const r=await api.post<any>("/feed/post-reaction",{postId:media.postId,reactionType:"like"});setLiked(Boolean(r?.viewerReacted));}catch{Alert.alert("Like","Unable to update Like right now.");}};
  const sendComment=async()=>{if(!media||!comment.trim())return;try{await api.post(`/comments/post/${media.postId}`,{content:comment.trim()});setComment("");setCommentOpen(false);Alert.alert("Comment","Comment added.");}catch{Alert.alert("Comment","Unable to add your comment right now.");}};
  return <SafeAreaView style={styles.root}><View style={styles.top}><Pressable onPress={()=>navigation.goBack()}><CloseIcon width={30} height={30}/></Pressable><View style={styles.topActions}><Text style={styles.more}>⌃</Text><Text style={styles.more}>•••</Text></View></View><View style={styles.imageStage}>{uri?<Image source={{uri}} style={styles.image} resizeMode="contain"/>:null}</View><View style={styles.meta}><Text style={styles.name}>Profile picture</Text><Text style={styles.date}>{media?.publishedAt?new Date(media.publishedAt).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}).toUpperCase():""}  🌐</Text></View><View style={styles.actions}><Pressable style={styles.action} onPress={()=>void react()}><LikeIcon width={24} height={24}/><Text style={[styles.actionText,liked&&styles.liked]}>Like</Text></Pressable><Pressable style={styles.action} onPress={()=>setCommentOpen(true)}><CommentIcon width={24} height={24}/><Text style={styles.actionText}>Comment</Text></Pressable><Pressable style={styles.action} onPress={()=>void Share.share({message:`Profile picture on ReDom${media?.postId?` — ${media.postId}`:""}`})}><ShareIcon width={24} height={24}/><Text style={styles.actionText}>Share</Text></Pressable></View><Modal visible={commentOpen} transparent animationType="slide" onRequestClose={()=>setCommentOpen(false)}><View style={styles.backdrop}><View style={styles.commentSheet}><Text style={styles.commentTitle}>Write a comment</Text><TextInput value={comment} onChangeText={setComment} placeholder="Write a comment..." placeholderTextColor="#65676B" style={styles.input} multiline/><View style={styles.commentButtons}><Pressable onPress={()=>setCommentOpen(false)}><Text style={styles.cancel}>Cancel</Text></Pressable><Pressable onPress={()=>void sendComment()}><Text style={styles.post}>Post</Text></Pressable></View></View></View></Modal></SafeAreaView>;
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:"#000"},top:{height:58,paddingHorizontal:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},topActions:{flexDirection:"row",gap:25},more:{color:"#fff",fontSize:26},imageStage:{flex:1,justifyContent:"center",alignItems:"center"},image:{width:"100%",height:"75%"},meta:{paddingHorizontal:22,paddingBottom:12},name:{color:"#fff",fontSize:17,fontWeight:"700"},date:{color:"#fff",fontSize:12,marginTop:3},actions:{height:62,borderTopWidth:1,borderTopColor:"#333",flexDirection:"row",alignItems:"center",justifyContent:"space-around"},action:{flexDirection:"row",alignItems:"center",gap:7},actionText:{color:"#fff",fontSize:15},liked:{color:"#1877F2"},backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.5)",justifyContent:"flex-end"},commentSheet:{backgroundColor:"#fff",borderTopLeftRadius:24,borderTopRightRadius:24,padding:20},commentTitle:{fontSize:18,fontWeight:"700",color:"#050505",marginBottom:12},input:{minHeight:90,borderWidth:1,borderColor:"#CCD0D5",borderRadius:12,padding:12,fontSize:16,color:"#050505",textAlignVertical:"top"},commentButtons:{flexDirection:"row",justifyContent:"flex-end",gap:25,paddingTop:15},cancel:{color:"#65676B",fontSize:16},post:{color:"#1877F2",fontSize:16,fontWeight:"700"}});
