import { useEffect, useState } from "react";
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import BackIcon from "../assets/navigation/back.svg";
import PasswordVisible from "../assets/auth/password-visible.svg";
import PasswordHidden from "../assets/auth/password-hidden.svg";
import { ReDomScreen } from "../layout/ReDomScreen";
import { getDeviceAccounts, type DeviceAccount } from "../auth/deviceAccounts";
import { useAuthContext } from "../auth/context";
import { getDeviceId } from "../utils/device";
import type { RootStackParamList } from "../routing/types";

type Props=NativeStackScreenProps<RootStackParamList,"RecognizedPassword">;
const BLUE="#1877F2",TEXT="#1C1E21",MUTED="#65676B",BORDER="#8A8D91",ERROR="#E41E3F";
export function RecognizedPasswordScreen({navigation,route}:Props){
 const {login}=useAuthContext();const [account,setAccount]=useState<DeviceAccount["user"]>();const [pw,setPw]=useState("");const [show,setShow]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{void(async()=>{try{const a=await getDeviceAccounts();setAccount(a.find(x=>x.user.id===route.params.userId)?.user)}finally{setLoading(false)}})()},[route.params.userId]);
 const submit=async()=>{if(!account||!pw||busy)return;setBusy(true);setError("");try{const d=await getDeviceId();const r=await login({accountUserId:account.id,identifier:"recognized-account",password:pw,deviceId:d,deviceCredential:d,deviceType:"mobile",deviceName:Platform.OS==="ios"?"iPhone":"Android Device",platform:Platform.OS,loginSource:"mobile",appVersion:"1.0.0"});if(r.requiresVerification&&r.verification){navigation.navigate("DeviceVerification",r.verification);return}if(r.requiresTwoFactor&&r.twoFactorVerification){navigation.navigate("LoginTwoFactor",r.twoFactorVerification);return}navigation.reset({index:0,routes:[{name:"HomeFeed"}]})}catch(e){setError(e instanceof Error?e.message:"Invalid password.")}finally{setBusy(false)}};
 return <ReDomScreen><KeyboardAvoidingView style={s.wrap} behavior={Platform.OS==="ios"?"padding":undefined}><Pressable onPress={()=>navigation.goBack()} style={s.back}><BackIcon width={31} height={31}/></Pressable>{loading?<ActivityIndicator size="large" color={BLUE}/>:account?<><View style={s.avatar}>{account.profilePhoto?<Image source={{uri:account.profilePhoto}} style={s.image}/>:<Text style={s.initial}>{account.firstName?.[0]||"R"}</Text>}</View><Text style={s.name}>{account.firstName} {account.lastName}</Text><View style={s.field}><TextInput value={pw} onChangeText={v=>{setPw(v);setError("")}} secureTextEntry={!show} placeholder="Password" placeholderTextColor={MUTED} style={s.input}/><Pressable onPress={()=>setShow(v=>!v)} style={s.eye}>{show?<PasswordVisible width={28} height={28}/>:<PasswordHidden width={28} height={28}/>}</Pressable></View>{error?<Text style={s.error}>{error}</Text>:null}<Pressable onPress={()=>void submit()} disabled={!pw||busy} style={[s.login,busy&&{opacity:.7}]}>{busy?<ActivityIndicator color="#FFF"/>:<Text style={s.loginText}>Log in</Text>}</Pressable><Pressable onPress={()=>navigation.navigate("FindAccount")}><Text style={s.forgot}>Forgot password?</Text></Pressable></>:null}</KeyboardAvoidingView></ReDomScreen>;
}
const s=StyleSheet.create({wrap:{flex:1,paddingHorizontal:30},back:{marginTop:8,alignSelf:"flex-start"},avatar:{width:190,height:190,borderRadius:95,overflow:"hidden",backgroundColor:"#DCE2F0",alignSelf:"center",marginTop:78,alignItems:"center",justifyContent:"center"},image:{width:190,height:190},initial:{fontSize:70,color:MUTED},name:{fontSize:31,fontWeight:"800",textAlign:"center",color:"#050505",marginTop:25,marginBottom:80},field:{height:112,borderWidth:1.7,borderColor:BORDER,borderRadius:25,flexDirection:"row",alignItems:"center",paddingLeft:30,paddingRight:20},input:{flex:1,fontSize:24,color:TEXT},eye:{width:45,height:45,alignItems:"center",justifyContent:"center"},error:{color:ERROR,textAlign:"center",fontSize:16,marginTop:12},login:{height:85,borderRadius:43,backgroundColor:"#0866FF",alignItems:"center",justifyContent:"center",marginTop:35},loginText:{color:"#FFF",fontSize:28,fontWeight:"500"},forgot:{fontSize:23,color:"#111",textAlign:"center",marginTop:48}});
