import { useCallback, useState } from "react";
import { Alert, Modal, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useFocusEffect, useNavigation, useRoute } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { ordersPaymentsService, type SavedPaymentMethodDetails } from "../services/ordersPaymentsService";
import BackIcon from "../assets/navigation/back.svg";
import SecurityIcon from "../assets/home-feed/security.svg";
import HelpIcon from "../assets/home-feed/help-support.svg";
import VisaIcon from "../assets/payment/card-brands/visa.svg";
import MastercardIcon from "../assets/payment/card-brands/mastercard.svg";
import AmexIcon from "../assets/payment/card-brands/american-express.svg";
import DiscoverIcon from "../assets/payment/card-brands/discover.svg";
import JcbIcon from "../assets/payment/card-brands/jcb.svg";
import UnionPayIcon from "../assets/payment/card-brands/unionpay.svg";
import VerveIcon from "../assets/payment/card-brands/verve.svg";

type Nav=NativeStackNavigationProp<RootStackParamList>;
const blue="#1877F2";
function Brand({brand}:{brand:string|null}){const b=(brand||"").toLowerCase();const C=b==="visa"?VisaIcon:b==="mastercard"?MastercardIcon:b.includes("american")||b==="amex"?AmexIcon:b==="discover"?DiscoverIcon:b==="jcb"?JcbIcon:b==="unionpay"?UnionPayIcon:b==="verve"?VerveIcon:HelpIcon;return <C width={64} height={40}/>;}
function countryName(code:string|null){if(!code)return "Not available";try{return new Intl.DisplayNames(["en"],{type:"region"}).of(code)||code;}catch{return code||"Not available";}}

export function ReviewPaymentInfoScreen(){
 const navigation=useNavigation<Nav>();const route=useRoute<any>();const id=String(route.params?.paymentMethodId||"");
 const [method,setMethod]=useState<SavedPaymentMethodDetails|null>(null);const [loading,setLoading]=useState(true);const [securityOpen,setSecurityOpen]=useState(false);const [code,setCode]=useState("");const [target,setTarget]=useState("");const [expires,setExpires]=useState("");const [attempts,setAttempts]=useState(2);const [lockedUntil,setLockedUntil]=useState<string|null>(null);const [reportOpen,setReportOpen]=useState(false);const [report,setReport]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{setMethod((await ordersPaymentsService.paymentMethodDetails(id)).method);}catch{setMethod(null);}finally{setLoading(false);}},[id]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 const requestRemove=async()=>{try{const r=await ordersPaymentsService.requestPaymentMethodRemoval(id);setTarget(r.target);setExpires(r.expiresAt);setCode("");setAttempts(2);setLockedUntil(null);setSecurityOpen(true);}catch(e){Alert.alert("Remove Payment Method",e instanceof Error?e.message:"Unable to start security verification.");}};
 const verify=async()=>{if(code.length!==8)return;try{const r=await ordersPaymentsService.verifyPaymentMethodRemoval(id,code);if(r.success){setSecurityOpen(false);Alert.alert("Payment method removed","The payment method was removed from ReDom Pay.",[{text:"OK",onPress:()=>navigation.goBack()}]);return;}if(r.locked){setLockedUntil(r.lockedUntil||null);return;}if(r.codeInvalid){setAttempts(r.attemptsRemaining??1);setCode("");if(r.target)setTarget(r.target);if(r.expiresAt)setExpires(r.expiresAt);Alert.alert("Incorrect security code","The previous code is invalid. A new 8-digit code has been sent.");}}catch(e){Alert.alert("Security verification",e instanceof Error?e.message:"Unable to verify the security code.");}};
 const submitReport=async()=>{if(!report.trim())return;try{const r=await ordersPaymentsService.reportPaymentProblem({paymentMethodId:id,description:report.trim()});setReportOpen(false);setReport("");Alert.alert("Report submitted","Your ReDom Support case "+r.caseNumber+" has been created.");}catch(e){Alert.alert("Report problem",e instanceof Error?e.message:"Unable to submit the report.");}};
 if(loading)return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><BackIcon width={28} height={28}/></Pressable><Text style={s.headerTitle}>Review Payment Info</Text></View><Text style={s.loading}>Loading payment information...</Text></SafeAreaView>;
 if(!method)return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>navigation.goBack()}><BackIcon width={28} height={28}/></Pressable><Text style={s.headerTitle}>Review Payment Info</Text></View><View style={s.center}><Text style={s.errorTitle}>Payment method unavailable</Text><Pressable onPress={()=>navigation.goBack()} style={s.primary}><Text style={s.primaryText}>Go back</Text></Pressable></View></SafeAreaView>;
 return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>navigation.goBack()} style={s.back}><BackIcon width={28} height={28}/></Pressable><Text style={s.headerTitle}>Review Payment Info</Text><View style={s.back}/></View>
  <ScrollView contentContainerStyle={s.content}>
   <View style={s.cardHero}><Brand brand={method.brand}/><View style={{flex:1}}><Text style={s.cardName}>{method.brand||"Card"}-{method.last4}</Text><Text style={s.cardStatus}>{method.status==="active"?"Active":method.status==="suspended"?"Suspended":"Unavailable"}</Text></View></View>
   <View style={s.group}>
    <Info label="Card number" value={method.maskedLast4||"•••• "+(method.last4||"")} />
    <Info label="Card type / brand" value={method.brand||"Card"} />
    <Info label="Cardholder name" value={method.cardholderName||"Not available"} />
    <Info label="Country" value={countryName(method.countryCode)} />
    <Info label="Expiration" value={method.expMonth&&method.expYear?String(method.expMonth).padStart(2,"0")+"/"+String(method.expYear).slice(-2):"Not available"} />
    <Info label="CVC" value="•••" />
   </View>
   <Text style={s.security}><SecurityIcon width={22} height={22}/> Payment credentials are secured by Stripe. ReDom does not store raw card numbers or CVC.</Text>
   <View style={s.actions}>
    <Pressable onPress={()=>Alert.alert("Update Payment Method","Update Payment Method Not supported because of security reasons. Please Remove & add New method.")} style={s.secondary}><Text style={s.secondaryText}>Update Payment Method</Text></Pressable>
    <Pressable onPress={()=>void requestRemove()} style={s.danger}><Text style={s.dangerText}>Remove Payment Method</Text></Pressable>
    <Pressable onPress={()=>setReportOpen(true)} style={s.support}><HelpIcon width={25} height={25}/><Text style={s.supportText}>Report Problem To Support</Text></Pressable>
   </View>
  </ScrollView>
  <Modal transparent visible={securityOpen} animationType="slide" onRequestClose={()=>setSecurityOpen(false)}><View style={s.backdrop}><View style={s.sheet}><Text style={s.sheetTitle}>Verify payment-method removal</Text>{lockedUntil?<><Text style={s.lockTitle}>Removal locked for 72 hours</Text><Text style={s.sheetText}>Payment-method removal is temporarily locked for security after two incorrect verification attempts.</Text><Pressable onPress={()=>setSecurityOpen(false)} style={s.primary}><Text style={s.primaryText}>Close</Text></Pressable></>:<><Text style={s.sheetText}>Enter the 8-digit security code sent to {target}. This code expires in 10 minutes.</Text><Text style={s.warning}>Security warning: Never share this code with anyone.</Text><TextInput value={code} onChangeText={v=>setCode(v.replace(/\D/g,"").slice(0,8))} keyboardType="number-pad" placeholder="8-digit security code" style={s.codeInput}/><Text style={s.attempts}>{attempts} verification attempt{attempts===1?"":"s"} remaining.</Text><Pressable disabled={code.length!==8} onPress={()=>void verify()} style={[s.primary,code.length!==8&&s.disabled]}><Text style={s.primaryText}>Verify & Remove</Text></Pressable></>}</View></View></Modal>
  <Modal transparent visible={reportOpen} animationType="slide" onRequestClose={()=>setReportOpen(false)}><View style={s.backdrop}><View style={s.sheet}><Text style={s.sheetTitle}>Report Problem To Support</Text><Text style={s.sheetText}>Describe the problem. ReDom Support will receive safe payment-method metadata only; raw PAN and CVC/CVV are never included.</Text><TextInput value={report} onChangeText={setReport} multiline placeholder="Describe the problem" style={s.reportInput}/><View style={s.sheetActions}><Pressable onPress={()=>setReportOpen(false)} style={s.secondary}><Text style={s.secondaryText}>Cancel</Text></Pressable><Pressable disabled={!report.trim()} onPress={()=>void submitReport()} style={[s.primary,!report.trim()&&s.disabled]}><Text style={s.primaryText}>Submit</Text></Pressable></View></View></View></Modal>
 </SafeAreaView>;
}
function Info({label,value}:{label:string;value:string}){return <View style={s.info}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>;}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#fff"},header:{height:82,paddingHorizontal:22,flexDirection:"row",alignItems:"center"},back:{width:42},headerTitle:{flex:1,textAlign:"center",fontSize:23,fontWeight:"800"},content:{padding:22,paddingBottom:45},loading:{padding:30,color:"#65676B"},center:{flex:1,alignItems:"center",justifyContent:"center",padding:30},errorTitle:{fontSize:22,fontWeight:"800",marginBottom:20},cardHero:{borderWidth:1,borderColor:"#DADDE1",borderRadius:18,padding:18,flexDirection:"row",alignItems:"center",gap:14},cardName:{fontSize:20,fontWeight:"800"},cardStatus:{fontSize:14,color:"#65676B",marginTop:4},group:{borderWidth:1,borderColor:"#DADDE1",borderRadius:18,marginTop:18,overflow:"hidden"},info:{padding:17,borderBottomWidth:1,borderBottomColor:"#E4E6EB"},label:{fontSize:13,color:"#65676B"},value:{fontSize:17,fontWeight:"600",marginTop:4},security:{fontSize:13,lineHeight:19,color:"#65676B",marginTop:15,flexDirection:"row",alignItems:"center"},actions:{marginTop:20,gap:12},secondary:{minHeight:52,borderRadius:26,backgroundColor:"#F0F2F5",alignItems:"center",justifyContent:"center",paddingHorizontal:18},secondaryText:{fontSize:16,fontWeight:"700"},danger:{minHeight:52,borderRadius:26,borderWidth:1,borderColor:"#B42318",alignItems:"center",justifyContent:"center"},dangerText:{fontSize:16,fontWeight:"700",color:"#B42318"},support:{minHeight:52,borderRadius:26,borderWidth:1,borderColor:"#DADDE1",flexDirection:"row",gap:10,alignItems:"center",justifyContent:"center"},supportText:{fontSize:16,fontWeight:"700"},primary:{minHeight:52,borderRadius:26,backgroundColor:blue,alignItems:"center",justifyContent:"center",paddingHorizontal:20},primaryText:{color:"#fff",fontSize:16,fontWeight:"800"},disabled:{backgroundColor:"#A8C7FA"},backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.52)",justifyContent:"flex-end"},sheet:{backgroundColor:"#fff",borderTopLeftRadius:28,borderTopRightRadius:28,padding:24,paddingBottom:34},sheetTitle:{fontSize:24,fontWeight:"800"},sheetText:{fontSize:15,lineHeight:22,color:"#65676B",marginTop:9},warning:{fontSize:14,lineHeight:20,color:"#B42318",fontWeight:"700",marginTop:12},codeInput:{height:58,borderWidth:1,borderColor:"#DADDE1",borderRadius:14,paddingHorizontal:18,fontSize:22,letterSpacing:3,marginTop:16},attempts:{fontSize:13,color:"#65676B",marginVertical:10},lockTitle:{fontSize:20,fontWeight:"800",color:"#B42318",marginTop:18},sheetActions:{flexDirection:"row",gap:12,marginTop:16},reportInput:{height:130,borderWidth:1,borderColor:"#DADDE1",borderRadius:16,padding:15,textAlignVertical:"top",marginTop:16,fontSize:16}});
