import { useState } from "react";
import { useTheme } from "../theme/ThemeProvider";
import { ActivityIndicator, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";
import { searchService, type SearchResult } from "../search/searchService";

export function SearchScreen() {
  const { colors } = useTheme();
  const styles = makeStyles(colors);
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const [query, setQuery] = useState(""); const [results, setResults] = useState<SearchResult[]>([]); const [loading, setLoading] = useState(false); const [searched, setSearched] = useState(false);
  const search = async () => { const q = query.trim(); if (!q) return; setLoading(true); setSearched(true); try { const r = await searchService.search(q); setResults(r.results); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.root}><View style={styles.header}><Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>‹</Text></Pressable><Text style={styles.title}>Search</Text><View style={{ width: 32 }} /></View><View style={styles.searchRow}><TextInput autoFocus value={query} onChangeText={setQuery} onSubmitEditing={() => void search()} returnKeyType="search" placeholder="Search ReDom" placeholderTextColor="#8A8D91" style={styles.input} /><Pressable onPress={() => void search()} style={styles.button}><Text style={styles.buttonText}>Search</Text></Pressable></View>{loading ? <View style={styles.center}><ActivityIndicator size="large" color="#1877F2" /></View> : <ScrollView contentContainerStyle={styles.list}>{results.map((item) => <Pressable key={item.userId} style={styles.row} onPress={() => navigation.navigate("Profile", { userId: item.userId })}><View style={styles.avatar}>{item.profilePhoto ? <Image source={{ uri: item.profilePhoto }} style={styles.avatarImage} /> : <Text style={styles.initial}>{item.firstName.slice(0, 1)}</Text>}</View><View style={styles.copy}><Text style={styles.name}>{item.firstName} {item.lastName}{item.verified ? " ✓" : ""}</Text><Text style={styles.handle}>@{item.username}</Text><Text style={styles.id}>Public ID {item.publicId}</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}{searched && !results.length ? <View style={styles.empty}><Text style={styles.emptyTitle}>No results</Text><Text style={styles.emptyText}>Try a different name or @username.</Text></View> : null}</ScrollView>}</SafeAreaView>;
}
function makeStyles(colors: ReturnType<typeof useTheme>["colors"]) { return StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, header: { height: 58, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 12 }, back: { fontSize: 38, color: "#1877F2" }, title: { fontSize: 19, fontWeight: "800", color: colors.text }, searchRow: { backgroundColor: colors.surface, padding: 10, flexDirection: "row" }, input: { flex: 1, height: 44, borderRadius: 22, backgroundColor: colors.background, paddingHorizontal: 16, color: colors.text }, button: { marginLeft: 8, height: 44, borderRadius: 22, paddingHorizontal: 16, backgroundColor: "#1877F2", alignItems: "center", justifyContent: "center" }, buttonText: { color: "#FFF", fontWeight: "800" }, list: { padding: 8 }, row: { minHeight: 76, backgroundColor: colors.surface, borderRadius: 14, marginBottom: 8, padding: 12, flexDirection: "row", alignItems: "center" }, avatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: "#1877F2", overflow: "hidden", alignItems: "center", justifyContent: "center" }, avatarImage: { width: 50, height: 50 }, initial: { color: "#FFF", fontSize: 20, fontWeight: "800" }, copy: { flex: 1, marginLeft: 12 }, name: { color: colors.text, fontSize: 15, fontWeight: "700" }, handle: { marginTop: 3, color: colors.textSecondary, fontSize: 13 }, id: { marginTop: 2, color: colors.textSecondary, fontSize: 11 }, chevron: { fontSize: 28, color: colors.textSecondary }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, empty: { alignItems: "center", paddingTop: 80 }, emptyTitle: { fontSize: 20, fontWeight: "800", color: colors.text }, emptyText: { marginTop: 5, color: colors.textSecondary } }); }

