import { useEffect, useState } from "react";
import { Alert, Image, Modal, Pressable, SafeAreaView, Share, StyleSheet, Text, View } from "react-native";
import * as MediaLibrary from "expo-media-library";
import * as Sharing from "expo-sharing";
import { File, Paths } from "expo-file-system";
import * as ImageManipulator from "expo-image-manipulator";
import { env } from "../config/env";
import { getStoredSession } from "../auth/storage";
import { decryptMedia, decryptMediaKey } from "../messages/encryptedMedia";
import { getDeviceId } from "../messages/e2ee";
import { messageService, type ReDomMessage } from "../messages/messageService";
import { chatInfoService } from "../messages/chatInfoService";
import { ChatInfoIcon } from "../components/ChatInfoIcon";
import { NavigationIcon } from "../components/NavigationIcon";
import { useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import type { RootStackParamList } from "../routing/types";

function absoluteUrl(fileUrl: string) { return /^https?:\/\//i.test(fileUrl) ? fileUrl : `${env.apiBaseUrl}${fileUrl.startsWith("/") ? fileUrl : `/${fileUrl}`}`; }
function conversationIdFromFileUrl(fileUrl: string) { return /\/messages\/media\/messages\/([^/]+)\//.exec(fileUrl)?.[1] ?? null; }
function bytesToBase64(bytes: Uint8Array) { let out = ""; for (let i = 0; i < bytes.length; i += 0x8000) out += String.fromCharCode(...bytes.subarray(i, i + 0x8000)); return globalThis.btoa(out); }
async function dataUriToFile(dataUri: string, name: string) { const match = /^data:([^;]+);base64,(.+)$/s.exec(dataUri); if (!match) throw new Error("Invalid media data."); const file = new File(Paths.cache, name); file.create({ overwrite: true }); file.write(match[2], { encoding: "base64" }); return file; }

export function SecureMediaViewerModal({ visible, message, onClose }: { visible: boolean; message: ReDomMessage | null; onClose: () => void }) {
  const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>(); const [source, setSource] = useState<string | null>(null); const [mime, setMime] = useState("image/jpeg"); const [failed, setFailed] = useState(false); const [menu, setMenu] = useState<"main" | "more" | "set" | null>(null); const [rotation, setRotation] = useState(0);
  useEffect(() => { if (!visible || !message?.attachment?.fileUrl) return; let active = true; setSource(null); setFailed(false); setMenu(null); void (async () => { try { const session = await getStoredSession(); if (!session?.accessToken) throw new Error("Authentication required."); const response = await fetch(absoluteUrl(message.attachment!.fileUrl!), { headers: { Authorization: `Bearer ${session.accessToken}` }, cache: "no-store" }); if (!response.ok) throw new Error("Media unavailable."); const encrypted = response.headers.get("X-ReDom-Media-Encrypted") === "1"; const contentMime = response.headers.get("X-ReDom-Media-Mime") || response.headers.get("Content-Type") || message.attachment?.mimeType || "image/jpeg"; setMime(contentMime); const bytes = new Uint8Array(await response.arrayBuffer()); let dataUri: string; if (encrypted) { const messageId = response.headers.get("X-ReDom-Media-Message-Id") || message.id; const conversationId = conversationIdFromFileUrl(message.attachment!.fileUrl!); if (!conversationId) throw new Error("Conversation context is unavailable."); const deviceId = await getDeviceId(); const key = await messageService.getEncryptedMediaKey(messageId); const mediaKey = await decryptMediaKey(key.envelope, conversationId, deviceId); dataUri = await decryptMedia(bytesToBase64(bytes), mediaKey, contentMime); } else dataUri = `data:${contentMime};base64,${bytesToBase64(bytes)}`; if (active) setSource(dataUri); } catch { if (active) setFailed(true); } })(); return () => { active = false; }; }, [visible, message?.id, message?.attachment?.fileUrl]);
  if (!visible || !message) return null;
  const save = async () => { if (!source) return; try { const permission = await MediaLibrary.requestPermissionsAsync(true); if (!permission.granted) { Alert.alert("Permission required", "Allow ReDom to save this media to your photo library."); return; } const file = await dataUriToFile(source, `redom-${message.id}.${mime.includes("png") ? "png" : "jpg"}`); await MediaLibrary.saveToLibraryAsync(file.uri); Alert.alert("Saved", "The media was saved to your photo library."); } catch (e) { Alert.alert("Could not save", e instanceof Error ? e.message : "The media could not be saved."); } };
  const share = async () => { if (!source) return; try { const file = await dataUriToFile(source, `redom-${message.id}.${mime.includes("png") ? "png" : "jpg"}`); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(file.uri, { mimeType: mime }); else await Share.share({ message: message.caption || "Shared from ReDom" }); } catch { /* user cancelled */ } };
  const star = async () => { try { await chatInfoService.starMessage(message.id); Alert.alert("Starred", "This message was added to Starred messages."); } catch (e) { Alert.alert("Could not star", e instanceof Error ? e.message : "This message could not be starred."); } };
  const createSticker = async () => { if (!source) return; try { const file = await dataUriToFile(source, `redom-sticker-${message.id}.jpg`); const edited = await ImageManipulator.manipulateAsync(file.uri, [{ resize: { width: 512, height: 512 } }], { compress: 1, format: ImageManipulator.SaveFormat.PNG, base64: true }); if (!edited.base64) throw new Error("The sticker image could not be prepared."); await messageService.sendMedia(message.conversationId, "sticker", `data:image/png;base64,${edited.base64}`, { caption: undefined }); setMenu(null); Alert.alert("Sticker sent", "The image was converted to a ReDom sticker and sent to this chat."); } catch (e) { Alert.alert("Could not create sticker", e instanceof Error ? e.message : "The sticker could not be created."); } };
  const askAi = () => { setMenu(null); navigation.navigate("ReDomAI", { conversationId: message.conversationId, context: message.caption ? `Help me understand this media. Caption: ${message.caption}` : "Help me understand this media from the chat." }); };
  const setWallpaper = async (value: string) => { try { await chatInfoService.updateSettings(message.conversationId, { wallpaper: value }); Alert.alert("Wallpaper updated", "This chat wallpaper was updated."); } catch (e) { Alert.alert("Could not update wallpaper", e instanceof Error ? e.message : "Wallpaper could not be updated."); } setMenu(null); };
  const topActions = [{ label: "Edit", icon: "edit" as const, onPress: () => { setRotation((current) => (current + 90) % 360); setMenu(null); } }, { label: "Share", icon: "share" as const, onPress: share }, { label: "Star", icon: "star" as const, onPress: star }, { label: "Show in chat", icon: "media" as const, onPress: onClose }, { label: "Create sticker", icon: "sticker" as const, onPress: createSticker }, { label: "Ask ReDom AI", icon: "ai" as const, onPress: askAi }, { label: "Delete", icon: "clear" as const, onPress: () => Alert.alert("Delete media", "Use the message action menu to delete this message.") }, { label: "Report", icon: "report" as const, onPress: () => Alert.alert("Report media", "Use Report from the message action menu to submit a report.") }];
  return <Modal visible={visible} animationType="fade" onRequestClose={onClose}><SafeAreaView style={styles.root}><View style={styles.header}><Pressable onPress={onClose}><NavigationIcon kind="back" size={28} color="#FFF" /></Pressable><View style={styles.headerTitle}><Text numberOfLines={1} style={styles.name}>Media</Text><Text style={styles.time}>{new Date(message.createdAt).toLocaleString()}</Text></View><Pressable onPress={() => setMenu("main")}><ChatInfoIcon name="more" size={28} color="#FFF" /></Pressable></View><View style={styles.viewer}>{source ? <Image source={{ uri: source }} style={[styles.image, { transform: [{ rotate: `${rotation}deg` }] }]} resizeMode="contain" /> : failed ? <Text style={styles.failed}>Media unavailable</Text> : <Text style={styles.failed}>Loading encrypted media…</Text>}</View>{message.caption ? <Text style={styles.caption}>{message.caption}</Text> : null}<View style={styles.bottom}><Pressable onPress={onClose} style={styles.reply}><Text style={styles.replyText}>Reply</Text></Pressable></View>
    {menu ? <View style={styles.menuOverlay}><Pressable style={styles.menuDismiss} onPress={() => setMenu(null)} /><View style={styles.menu}>{(menu === "main" ? topActions : menu === "more" ? [{ label: "All media", icon: "gallery" as const, onPress: onClose }, { label: "View in gallery", icon: "gallery" as const, onPress: save }, { label: "Search on web", icon: "web" as const, onPress: () => LinkingSearch(message.caption || "ReDom media") }, { label: "Rotate", icon: "rotate" as const, onPress: () => { setRotation((current) => (current + 90) % 360); setMenu(null); } }, { label: "Set as…", icon: "set" as const, onPress: () => setMenu("set") }] : [{ label: "My profile picture", icon: "set" as const, onPress: () => Alert.alert("Profile picture", "Use Profile > Profile picture to apply this media.") }, { label: "Chat wallpaper", icon: "set" as const, onPress: () => setWallpaper("media") }, { label: "Group icon", icon: "group" as const, onPress: () => Alert.alert("Group icon", "Group icon changes are available from Group info.") }]).map((action) => <Pressable key={action.label} style={styles.menuItem} onPress={action.onPress}><ChatInfoIcon name={action.icon} size={24} color="#667085"/><Text style={styles.menuText}>{action.label}</Text></Pressable>)}{menu === "main" ? <Pressable style={styles.moreRow} onPress={() => setMenu("more")}><Text style={styles.moreText}>More</Text><Text style={styles.moreArrow}>›</Text></Pressable> : null}</View></View> : null}
  </SafeAreaView></Modal>;
}
function LinkingSearch(value: string) { const url = `https://www.google.com/search?q=${encodeURIComponent(value)}`; void import("react-native").then(({ Linking }) => Linking.openURL(url).catch(() => undefined)); }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: "#05080B" }, header: { height: 62, backgroundColor: "#05080B", flexDirection: "row", alignItems: "center", paddingHorizontal: 14 }, headerTitle: { flex: 1, marginLeft: 12 }, name: { color: "#FFF", fontSize: 18, fontWeight: "700" }, time: { color: "#98A2B3", fontSize: 12, marginTop: 2 }, viewer: { flex: 1, alignItems: "center", justifyContent: "center" }, image: { width: "100%", height: "100%" }, failed: { color: "#FFF", fontSize: 16 }, caption: { color: "#FFF", paddingHorizontal: 16, paddingBottom: 10, textAlign: "center" }, bottom: { minHeight: 68, backgroundColor: "#05080B", justifyContent: "center", alignItems: "flex-end", paddingHorizontal: 16 }, reply: { minWidth: 120, minHeight: 48, borderRadius: 24, backgroundColor: "#111A22", alignItems: "center", justifyContent: "center" }, replyText: { color: "#FFF", fontWeight: "800" }, menuOverlay: { ...StyleSheet.absoluteFillObject, justifyContent: "flex-start", alignItems: "flex-end" }, menuDismiss: { ...StyleSheet.absoluteFillObject }, menu: { marginTop: 62, marginRight: 6, width: 300, backgroundColor: "#FFF", borderRadius: 18, paddingVertical: 8, elevation: 12 }, menuItem: { minHeight: 58, paddingHorizontal: 18, flexDirection: "row", alignItems: "center", gap: 16 }, menuText: { fontSize: 16, color: "#101828", fontWeight: "600" }, moreRow: { minHeight: 56, borderTopWidth: 1, borderTopColor: "#EAECF0", paddingHorizontal: 18, flexDirection: "row", alignItems: "center" }, moreText: { flex: 1, fontSize: 16, color: "#101828" }, moreArrow: { fontSize: 28, color: "#667085" }
});
