import React,{useEffect,useMemo,useState}from"react";
import{SafeAreaView,View,Text,Pressable,StyleSheet,TextInput,ScrollView,ActivityIndicator,Alert,Linking}from"react-native";
import{useNavigation,useRoute}from"@react-navigation/native";
import{useTheme}from"../theme/ThemeProvider";
import BackIcon from"../assets/navigation/back.svg";
import{ordersPaymentsService}from"../services/ordersPaymentsService";import type{StarPackage,SavedPaymentMethod}from"../services/ordersPaymentsService";

export function StarsCheckoutScreen(){
 const n=useNavigation<any>();const route=useRoute<any>();const{colors}=useTheme();
 const countryCode=String(route.params.countryCode);const packageKey=String(route.params.packageKey);
 const[email,setEmail]=useState("");const[pin,setPin]=useState("");const[pinEnabled,setPinEnabled]=useState(false);
 const[pkg,setPkg]=useState<StarPackage|null>(null);const[countryName,setCountryName]=useState(countryCode);const[methods,setMethods]=useState<SavedPaymentMethod[]>([]);const[selectedMethod,setSelectedMethod]=useState<string|null>(null);
 const[fullName,setFullName]=useState("");const[address,setAddress]=useState("");const[city,setCity]=useState("");const[state,setState]=useState("");const[zip,setZip]=useState("");const[query,setQuery]=useState("");const[suggestions,setSuggestions]=useState<any[]>([]);
 const[loading,setLoading]=useState(true);const[paying,setPaying]=useState(false);const[status,setStatus]=useState<string|null>(null);const[reference,setReference]=useState<string|null>(null);

 useEffect(()=>{(async()=>{try{const[catalog,settings]=await Promise.all([ordersPaymentsService.starsCatalog(countryCode),ordersPaymentsService.getSettings()]);setPkg(catalog.packages.find(x=>x.key===packageKey)||null);setCountryName(catalog.selectedCountry?.name||countryCode);setPinEnabled(Boolean(settings.settings.pin_enabled));try{const pm=await ordersPaymentsService.paymentMethods();setMethods(pm.methods)}catch{setMethods([])}}catch(e){Alert.alert("ReDom Stars checkout",e instanceof Error?e.message:"Unable to load this Stars package.");}finally{setLoading(false)}})()},[countryCode,packageKey]);

 useEffect(()=>{const timer=setTimeout(()=>{if(query.trim().length>=3)void ordersPaymentsService.addressSearch(query).then(r=>setSuggestions(r.suggestions)).catch(()=>setSuggestions([]));else setSuggestions([])},350);return()=>clearTimeout(timer)},[query]);

 useEffect(()=>{const sub=Linking.addEventListener("url",({url})=>{if(url.indexOf("redom://payment/callback")!==0)return;const match=url.match(/[?&]reference=([^&]+)/);const ref=match?decodeURIComponent(match[1]):reference;if(!ref)return;setReference(ref);let cancelled=false;(async()=>{for(let attempt=0;attempt<24&&!cancelled;attempt+=1){try{const result=await ordersPaymentsService.verifyPayment(ref);const paymentStatus=String(result.payment.status);setStatus(paymentStatus);if(paymentStatus==="paid"){Alert.alert("Payment successful",String(pkg?.stars??"")+" ReDom Stars were added to your balance.",[{text:"OK",onPress:()=>n.navigate("StarsActivity")}]);return;}if(!["ongoing","pending","processing","pending_bank_transfer"].includes(paymentStatus)){return;}if(attempt<23)await new Promise(resolve=>setTimeout(resolve,5000));}catch(error){if(attempt<23){setStatus("Payment is still processing. Do not send the transfer again.");await new Promise(resolve=>setTimeout(resolve,5000));}else{setStatus("Payment is still processing. Do not send the transfer again.");}}}})();});return()=>{cancelled=true;sub.remove()}},[n,reference,pkg]);

 const submit=async()=>{if(!pkg)return;
  if(!email.trim())return Alert.alert("Transaction email","Enter the email address on your ReDom account.");
  if(!/^\S+@\S+\.\S+$/.test(email.trim()))return Alert.alert("Transaction email","Enter a valid email address.");
  if(!fullName.trim()||!(address.trim()||query.trim())||!city.trim())return Alert.alert("Billing address","Enter your full name, address and city before continuing.");
  if(pinEnabled&&!/^\d{4,8}$/.test(pin))return Alert.alert("Payment PIN","Enter your 4 to 8 digit payment PIN.");
  setPaying(true);try{const addressProvided=Boolean(fullName.trim()&&city.trim()&&(address.trim()||query.trim())); const result=await ordersPaymentsService.initializeStars({packageKey:packageKey,countryCode:countryCode,email:email.trim(),pin:pinEnabled?pin:undefined,paymentMethodId:selectedMethod||undefined,address:addressProvided?{countryCode:countryCode,countryName,fullName:fullName.trim(),addressLine1:address.trim()||query.trim(),city:city.trim(),state:state.trim()||null,postalCode:zip.trim()||null}:undefined});setReference(result.reference);if(result.checkoutUrl){await Linking.openURL(result.checkoutUrl)}else if(result.status==="success"){setStatus("paid");const verified=await ordersPaymentsService.verifyPayment(result.reference);if(verified.payment.status==="paid")n.navigate("StarsActivity");else setStatus(verified.payment.status)}else{setStatus(result.status||"pending");Alert.alert("Payment",result.status==="ongoing"?"Your payment needs further authentication.":"Payment started.")}}catch(e){Alert.alert("Payment failed",e instanceof Error?e.message:"Unable to start payment.")}finally{setPaying(false)}};

 const title=useMemo(()=>pkg?String(pkg.stars)+" ReDom Stars":"ReDom Stars",[pkg]);
 if(loading)return <SafeAreaView style={[s.root,{backgroundColor:colors.background}]}><ActivityIndicator style={{marginTop:40}} color={colors.primary}/></SafeAreaView>;
 return <SafeAreaView style={[s.root,{backgroundColor:colors.background}]}>
  <View style={[s.header,{backgroundColor:colors.surface,borderBottomColor:colors.border}]}><Pressable onPress={()=>n.goBack()}><BackIcon width={24} height={24}/></Pressable><Text style={[s.title,{color:colors.text}]}>Pay for ReDom Stars?</Text></View>
  <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
   <Text style={[s.heading,{color:colors.text}]}>{title}</Text>
   {pkg&&<><Text style={[s.price,{color:colors.text}]}>{pkg.localAmountFormatted+" · $"+pkg.usdPrice.toFixed(2)+" USD"}</Text>{pkg.firstPurchaseUsdPrice!=null&&pkg.usdPrice<pkg.regularUsdPrice?<Text style={[s.discount,{color:colors.primary}]}>{("$"+pkg.regularUsdPrice.toFixed(2))+" regular · "+pkg.firstPurchaseDiscountPercent+"% off first purchase"}</Text>:null}</>}
   <Text style={[s.muted,{color:colors.textSecondary}]}>Your payment is processed securely by Paystack. ReDom does not store your card number or CVV.</Text>
   <Text style={[s.label,{color:colors.text}]}>Email for transaction updates</Text>
   <TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="you@example.com" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   {methods.length>0&&<><Text style={[s.label,{color:colors.text}]}>Payment method</Text>{methods.map(m=><Pressable key={m.id} onPress={()=>setSelectedMethod(m.id)} style={[s.method,{borderColor:selectedMethod===m.id?colors.primary:colors.border,backgroundColor:colors.surface}]}><Text style={[s.methodTitle,{color:colors.text}]}>{(m.brand||"Card")+" "+(m.last4?"•••• "+m.last4:"")}</Text><Text style={[s.muted,{color:colors.textSecondary}]}>Saved securely with Paystack</Text></Pressable>)}</>}
   {pinEnabled&&<><Text style={[s.label,{color:colors.text}]}>Payment PIN</Text><TextInput value={pin} onChangeText={setPin} keyboardType="number-pad" secureTextEntry maxLength={8} placeholder="Enter PIN" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/></>}
   <Text style={[s.label,{color:colors.text}]}>Billing address</Text>
   <TextInput value={query} onChangeText={setQuery} placeholder="Search address" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   {suggestions.map(x=><Pressable key={x.id} onPress={()=>{setAddress(x.placeName);setQuery(x.placeName);setSuggestions([])}} style={[s.suggestion,{borderColor:colors.border,backgroundColor:colors.surface}]}><Text style={{color:colors.text}}>{x.placeName}</Text></Pressable>)}
   <TextInput value={fullName} onChangeText={setFullName} placeholder="Full name" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   <TextInput value={address} onChangeText={setAddress} placeholder="Address" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   <View style={s.row}><TextInput value={city} onChangeText={setCity} placeholder="City" placeholderTextColor={colors.textSecondary} style={[s.input,s.half,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/><TextInput value={state} onChangeText={setState} placeholder="State" placeholderTextColor={colors.textSecondary} style={[s.input,s.half,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/></View>
   <TextInput value={zip} onChangeText={setZip} placeholder="Zip code" placeholderTextColor={colors.textSecondary} style={[s.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surface}]}/>
   {status&&<Text style={[s.status,{color:status==="paid"?colors.primary:colors.textSecondary}]}>{"Status: "+status+(reference?" · "+reference:"")}</Text>}
   <Pressable disabled={paying||!pkg||pkg.payable===false} onPress={submit} style={[s.button,{backgroundColor:paying||!pkg||pkg.payable===false?colors.border:colors.primary}]}><Text style={s.buttonText}>{paying?"Opening secure checkout…":"Continue"}</Text></Pressable>
   {pkg?.availabilityReason&&<Text style={[s.muted,{color:colors.textSecondary,marginTop:10}]}>{pkg.availabilityReason}</Text>}
  </ScrollView>
 </SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1},header:{height:58,borderBottomWidth:1,flexDirection:"row",alignItems:"center",paddingHorizontal:14},title:{fontSize:18,fontWeight:"800",marginLeft:12},content:{padding:20,paddingBottom:40},heading:{fontSize:25,fontWeight:"900"},price:{fontSize:21,fontWeight:"800",marginTop:6},discount:{fontSize:13,fontWeight:"800",marginTop:5},muted:{fontSize:14,lineHeight:20,marginTop:7},label:{fontSize:16,fontWeight:"700",marginTop:22,marginBottom:8},input:{height:54,borderWidth:1,borderRadius:13,paddingHorizontal:15,fontSize:16,marginBottom:10},method:{borderWidth:1,borderRadius:14,padding:14,marginBottom:8},methodTitle:{fontSize:17,fontWeight:"800"},row:{flexDirection:"row",gap:10},half:{flex:1},suggestion:{padding:13,borderWidth:1,borderRadius:10,marginBottom:6},status:{fontSize:13,marginTop:12},button:{height:54,borderRadius:27,alignItems:"center",justifyContent:"center",marginTop:20},buttonText:{color:"#fff",fontSize:17,fontWeight:"800"}});
