export type ReDomPolicyDocument = {
  slug: string;
  title: string;
  summary: string;
  version?: string;
  effectiveAt?: string;
  sections: Array<{ heading: string; body: string }>;
};

// This catalog is the support-side, user-facing policy knowledge supplied to Gemini.
// It intentionally contains no internal implementation details or secrets.
export const REDOM_SUPPORT_POLICY_DOCUMENTS: ReDomPolicyDocument[] = [
  { slug: "terms", title: "ReDom Terms of Use", summary: "The rules governing access to and use of ReDom services.", sections: [
    { heading: "Using ReDom", body: "Use ReDom lawfully, respect other people, protect your account, and follow feature-specific rules." },
    { heading: "Your account", body: "Keep credentials and verification methods secure. ReDom may require additional verification when security signals require it." },
    { heading: "Content and conduct", body: "Do not use ReDom to facilitate abuse, fraud, scams, malware, unlawful activity, or other prohibited conduct." },
    { heading: "Changes", body: "ReDom may update these terms and will show applicable version and notice information." },
  ] },
  { slug: "privacy", title: "ReDom Privacy Policy", summary: "How ReDom collects, uses, protects and shares information.", sections: [
    { heading: "Information we use", body: "ReDom uses information needed to provide accounts, authentication, social features, security, support and disclosed product services." },
    { heading: "Visibility and control", body: "Privacy controls determine supported visibility; server-side authorization remains authoritative." },
    { heading: "Security", body: "Security events, verification and device/session information may be processed to protect accounts and the platform." },
    { heading: "Your choices", body: "ReDom provides supported privacy, security, notification, language and account controls." },
  ] },
  { slug: "community", title: "ReDom Community Standards", summary: "Safety and conduct standards for the ReDom community.", sections: [
    { heading: "Safety", body: "Threats, targeted abuse, exploitation, dangerous scams and other harmful conduct may be restricted or removed." },
    { heading: "Authenticity", body: "Do not impersonate people or deceive others about identity or affiliation." },
    { heading: "Spam and abuse", body: "Automated abuse, unsolicited bulk activity and manipulation of platform systems may be restricted." },
    { heading: "Reports and appeals", body: "Supported reports and appeals are handled through ReDom moderation and support processes." },
  ] },
  { slug: "messaging", title: "ReDom Messaging Policy", summary: "Rules, privacy controls and safety behavior for ReDom messages and conversations.", sections: [
    { heading: "Conversation access", body: "A conversation requires authentication and active membership. Server-side authorization is authoritative and client navigation never grants access." },
    { heading: "Message types", body: "ReDom messaging can support text, replies, reactions, photos, video, voice messages, audio, documents, GIFs, stickers and supported shared content. Availability can depend on platform and regional policy." },
    { heading: "Edit and delete", body: "Text messages may be edited within the supported edit window. Users may delete their own message for themselves; supported messages can also be deleted for everyone and replaced by a deletion placeholder. Deleted-for-everyone content is not returned as readable message content." },
    { heading: "Read and delivery state", body: "Sent, delivered and read state is generated by backend events. The client cannot fabricate delivery or read receipts." },
    { heading: "Replies and reactions", body: "Replies must reference a message in the same authorized conversation. Reactions are tied to the authenticated user and can be changed or removed." },
    { heading: "Notifications", body: "Message notifications follow global and per-conversation preferences. Notification previews must respect the recipient's current authorization." },
    { heading: "Safety and reporting", body: "ReDom may apply spam, scam, malware, abuse and other safety controls. Users can report supported content; moderation decisions are not delegated to client-side AI." },
    { heading: "Privacy", body: "Private conversation content is not exposed through search, public profile endpoints or AI merely because the user asks for it. Blocking, restrictions and membership checks remain authoritative." },
  ] },
  { slug: "media", title: "ReDom Messaging Media Policy", summary: "Rules for photos, video, audio, voice messages, documents and other message attachments.", sections: [
    { heading: "Storage", body: "Message media is stored by ReDom Media Storage under access-controlled message paths. Provider implementation details are internal and are not user-facing." },
    { heading: "Upload controls", body: "Uploads are authenticated, size-limited, typed and associated with the authorized conversation. Unsupported or malformed media is rejected." },
    { heading: "Voice messages", body: "Voice messages are treated as message media and may include duration and waveform metadata. Microphone permission is controlled by the operating system and the user." },
    { heading: "Privacy", body: "Media URLs are not intended to grant conversation access by themselves. Access must remain protected by ReDom authorization." },
    { heading: "Safety", body: "ReDom may scan or review supported media for malware, spam, abuse and other safety signals. A scan result does not grant permission to reveal private content." },
  ] },
  { slug: "calls", title: "ReDom Calls Policy", summary: "Privacy, permissions, safety and lifecycle rules for ReDom voice and video calls.", sections: [
    { heading: "Call access", body: "Calls require an authorized conversation membership and supported call permission. Client controls cannot bypass membership restrictions." },
    { heading: "Microphone and camera", body: "Microphone and camera access is controlled by operating-system permissions and can be disabled by the participant at any time." },
    { heading: "Encryption", body: "Call records are designed to preserve call state and security metadata; the application must not expose private provider credentials or internal signaling secrets." },
    { heading: "Call states", body: "Ringing, connecting, active, ended, declined, missed, cancelled and failed states must come from backend-confirmed events." },
    { heading: "Safety", body: "Users may use supported reporting and blocking controls. ReDom AI cannot silently join, record, intercept or reveal a private call." },
  ] },
  { slug: "notifications", title: "ReDom Notification Policy", summary: "How ReDom notification events and controls work.", sections: [
    { heading: "Notification types", body: "ReDom may notify you about messages, reactions, comments, follows, friend activity, security, verification and support." },
    { heading: "Controls", body: "Preferences determine supported notification delivery; device permissions also apply. Per-conversation controls can mute or limit message notifications." },
    { heading: "Deep links", body: "Notifications may open an associated ReDom destination after authorization is checked again." },
    { heading: "Privacy", body: "Notification previews must not expose information the recipient is no longer authorized to view." },
  ] },
  { slug: "security", title: "ReDom Security Policy", summary: "Account, device, authentication and platform security controls.", sections: [
    { heading: "Authentication", body: "ReDom uses authentication, verification challenges, device security and supported two-factor controls." },
    { heading: "Sessions and devices", body: "Users can review supported active sessions and revoke sessions they own." },
    { heading: "Risk controls", body: "Security checks may require additional verification or restrict risky actions." },
    { heading: "Secrets", body: "Passwords, codes, access tokens and provider credentials are never exposed through user-facing AI or policy surfaces." },
  ] },
  { slug: "verification", title: "ReDom Verification Policy", summary: "Eligibility, security and review principles for account verification.", sections: [
    { heading: "Eligibility", body: "Verification is subject to current ReDom requirements and applicable regional policy." },
    { heading: "Identity", body: "ReDom may request supported verification information through an approved verification flow." },
    { heading: "Review", body: "AI can explain requirements but does not independently grant or deny verification." },
    { heading: "Privacy", body: "Verification information is security-sensitive and handled according to applicable privacy and retention rules." },
  ] },
  { slug: "ai", title: "ReDom AI Policy", summary: "How ReDom AI can assist without bypassing platform controls.", version: "1.1.1", effectiveAt: "2026-09-24T00:00:00.000Z", sections: [
    { heading: "What ReDom AI can do", body: "AI can explain product behavior, assist with supported content and language tasks, guide users through workflows, generate supported images from user prompts, and help users imagine or develop creative ideas." },
    { heading: "AI information and policy", body: "The ReDom AI information dashboard provides access to AI capabilities, accuracy information, training information and this AI Policy. The AI Policy is the authoritative user-facing reference for ReDom AI boundaries." },
    { heading: "Image generation", body: "Users can explicitly request supported image generation from the ReDom AI experience. Generated images remain part of the user-invoked AI workflow and do not grant access to private conversations, accounts or protected platform data." },
    { heading: "What it cannot do", body: "AI cannot bypass authentication or privacy, expose secrets, grant verification, change ownership, approve refunds, or override regional restrictions." },
    { heading: "Messaging privacy", body: "AI must not retrieve or disclose another person's private conversation content merely because a user asks. Any AI feature operating on message content must receive content through an explicitly authorized product flow." },
    { heading: "Accuracy", body: "AI-generated responses can be inaccurate or incomplete. Users should verify important information before relying on it, especially for legal, financial, medical, security or account decisions." },
    { heading: "Refusals and safety", body: "Conflicting or unsafe requests receive an explanation and a supported safe path where possible. ReDom AI does not override ReDom safety, moderation, authorization or regional controls." },
    { heading: "Language", body: "AI follows the user's language when the requested operation supports localization." },
  ] },
  { slug: "regional", title: "ReDom Regional Policy", summary: "Country and region-specific availability and policy controls.", sections: [
    { heading: "Availability", body: "Features can differ by country or region based on product availability, provider support and applicable requirements." },
    { heading: "Server enforcement", body: "Regional restrictions are enforced by the ReDom backend; client settings cannot override server policy." },
    { heading: "Policy versions", body: "Regional policies are versioned and may have effective dates for auditability." },
  ] },
  { slug: "refunds", title: "ReDom Refund Policy", summary: "Product and country-specific rules for supported refund requests.", sections: [
    { heading: "Availability", body: "Refunds are available only when the applicable product and regional refund policy permits them." },
    { heading: "Verification", body: "A supported request may require transaction details, Account Profile ID and linked-contact verification." },
    { heading: "Review", body: "Refund decisions are made by the authorized refund workflow, not ReDom AI or the frontend." },
    { heading: "Status", body: "The application must show only backend-confirmed refund states." },
  ] },
  { slug: "support", title: "ReDom Support and Reporting Policy", summary: "How users can get help, report problems and follow supported cases.", sections: [
    { heading: "Support", body: "Use supported ReDom support channels for account, product and safety issues." },
    { heading: "Reports", body: "Reports should contain enough information to evaluate the issue without exposing unrelated private information." },
    { heading: "Case updates", body: "Support state shown in the application comes from the backend and is never fabricated by AI." },
  ] },
];

const POLICY_ALIASES: Record<string, string> = {
  terms: "terms", terms_of_use: "terms", conditions: "terms",
  privacy: "privacy", privacy_policy: "privacy", data: "privacy",
  community: "community", community_standards: "community", safety: "community",
  messaging: "messaging", messages: "messaging", chat: "messaging",
  media: "media", attachments: "media", voice: "media",
  calls: "calls", calling: "calls", video_call: "calls",
  notifications: "notifications", notification: "notifications",
  security: "security", account_security: "security",
  verification: "verification", verified: "verification", identity: "verification",
  ai: "ai", artificial_intelligence: "ai",
  regional: "regional", country: "regional", availability: "regional",
  refunds: "refunds", refund: "refunds", payments: "refunds", chargeback: "refunds",
  support: "support", reporting: "support", reports: "support",
};

export function getPolicyDocument(slug: string | null | undefined): ReDomPolicyDocument | null {
  if (!slug) return null;
  const canonical = POLICY_ALIASES[slug.trim().toLowerCase()] ?? slug.trim().toLowerCase();
  return REDOM_SUPPORT_POLICY_DOCUMENTS.find((document) => document.slug === canonical) ?? null;
}

export function renderCompletePolicy(document: ReDomPolicyDocument, requestedSections: string[] = []): string {
  const normalized = new Set(requestedSections.map((section) => section.trim().toLowerCase()).filter(Boolean));
  const selected = normalized.size
    ? document.sections.filter((section) => normalized.has(section.heading.toLowerCase()))
    : document.sections;
  const sections = selected.length ? selected : document.sections;
  return [`Policy: ${document.title}`, document.summary, "", ...sections.map((section) => `${section.heading}\n${section.body}`)].join("\n\n").trim();
}
