import {
  pgTable,
  uuid,
  varchar,
  text,
  numeric,
  integer,
  boolean,
  timestamp,
  doublePrecision,
} from "drizzle-orm/pg-core";

import { userProfiles } from "./userProfiles";

export const marketplaceListings = pgTable(
  "marketplace_listings",
  {
    // ==================================================
    // INTERNAL ID
    // ==================================================

    id: uuid("id")
      .defaultRandom()
      .primaryKey(),

    // ==================================================
    // RELATIONSHIPS
    // ==================================================

    sellerUserId: uuid("seller_user_id")
      .notNull()
      .references(() => userProfiles.id),

    buyerUserId: uuid("buyer_user_id")
      .references(() => userProfiles.id),

    // ==================================================
    // LISTING INFORMATION
    // ==================================================

    /**
     * Public Listing ID
     * Numeric only
     * Starts with 989
     * Example:
     * 9891234567
     * Generated by:
     * src/utils/idGenerator.ts
     */
    listingId: varchar("listing_id", {
      length: 10,
    })
      .notNull()
      .unique(),

    title: varchar("title", {
      length: 150,
    }).notNull(),

    description: text("description"),

    category: varchar("category", {
      length: 100,
    }).notNull(),

    condition: varchar("condition", {
      length: 50,
    }).notNull(),

    brand: varchar("brand", {
      length: 100,
    }),

    model: varchar("model", {
      length: 100,
    }),

    color: varchar("color", {
      length: 50,
    }),

    // ==================================================
    // PRICING
    // ==================================================

    price: numeric("price", {
      precision: 15,
      scale: 2,
    }).notNull(),

    currency: varchar("currency", {
      length: 10,
    }).notNull(),

    negotiable: boolean("negotiable")
      .default(false)
      .notNull(),

    offersAccepted: boolean("offers_accepted")
      .default(true)
      .notNull(),

    // ==================================================
    // INVENTORY
    // ==================================================

    quantity: integer("quantity")
      .default(1)
      .notNull(),

    quantitySold: integer("quantity_sold")
      .default(0)
      .notNull(),

    remainingStock: integer("remaining_stock")
      .default(1)
      .notNull(),

    // ==================================================
    // MEDIA
    // ==================================================

    coverImageUrl: text("cover_image_url"),

    imageUrls: text("image_urls"),

    // Product videos intentionally not supported

    // ==================================================
    // LOCATION
    // ==================================================

    country: varchar("country", {
      length: 100,
    }).notNull(),

    state: varchar("state", {
      length: 100,
    }),

    city: varchar("city", {
      length: 100,
    }),

    pickupAvailable: boolean("pickup_available")
      .default(false)
      .notNull(),

    deliveryAvailable: boolean("delivery_available")
      .default(false)
      .notNull(),

    shippingAvailable: boolean("shipping_available")
      .default(false)
      .notNull(),

    // ==================================================
    // PRODUCT STATUS
    // ==================================================

    /**
     * draft
     * pending_review
     * active
     * reserved
     * sold
     * out_of_stock
     * hidden
     * removed
     * deleted
     */
    status: varchar("status", {
      length: 30,
    })
      .default("draft")
      .notNull(),

    // ==================================================
    // MODERATION
    // ==================================================

    aiModerationScore: doublePrecision(
      "ai_moderation_score",
    ),

    /**
     * pending
     * approved
     * rejected
     */
    reviewStatus: varchar(
      "review_status",
      {
        length: 20,
      },
    )
      .default("pending")
      .notNull(),

    rejectionReason: text(
      "rejection_reason",
    ),

    approvedByModeratorId: uuid(
      "approved_by_moderator_id",
    ).references(() => userProfiles.id),

    // ==================================================
    // ANALYTICS
    // ==================================================

    views: integer("views")
      .default(0)
      .notNull(),

    saves: integer("saves")
      .default(0)
      .notNull(),

    shares: integer("shares")
      .default(0)
      .notNull(),

    messagesReceived: integer(
      "messages_received",
    )
      .default(0)
      .notNull(),

    purchases: integer("purchases")
      .default(0)
      .notNull(),

    // ==================================================
    // BUYER PROTECTION
    // ==================================================

    returnsAccepted: boolean(
      "returns_accepted",
    )
      .default(false)
      .notNull(),

    returnWindowDays: integer(
      "return_window_days",
    ),

    refundAvailable: boolean(
      "refund_available",
    )
      .default(false)
      .notNull(),

    // ==================================================
    // PROMOTION
    // ==================================================

    featuredListing: boolean(
      "featured_listing",
    )
      .default(false)
      .notNull(),

    sponsoredListing: boolean(
      "sponsored_listing",
    )
      .default(false)
      .notNull(),

    promotionExpiresAt: timestamp(
      "promotion_expires_at",
      {
        withTimezone: true,
      },
    ),

    // ==================================================
    // SYSTEM
    // ==================================================

    createdAt: timestamp(
      "created_at",
      {
        withTimezone: true,
      },
    )
      .defaultNow()
      .notNull(),

    updatedAt: timestamp(
      "updated_at",
      {
        withTimezone: true,
      },
    )
      .defaultNow()
      .notNull(),

    publishedAt: timestamp(
      "published_at",
      {
        withTimezone: true,
      },
    ),

    soldAt: timestamp(
      "sold_at",
      {
        withTimezone: true,
      },
    ),

    deletedAt: timestamp(
      "deleted_at",
      {
        withTimezone: true,
      },
    ),

  },
);