import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  boolean,
  timestamp,
} from "drizzle-orm/pg-core";

import { userProfiles } from "./userProfiles";
import { postMedia } from "./postMedia";

export const stories = pgTable("stories", {

  // ==================================================
  // INTERNAL ID
  // ==================================================

  /**
   * Internal UUID.
   */
  id: uuid("id")
    .defaultRandom()
    .primaryKey(),

  /**
   * Permanent public
   * Story Share ID.
   *
   * Generated by
   * idGenerator.ts
   */
  shareId: varchar("share_id", {
    length: 10,
  })
    .notNull()
    .unique(),

  // ==================================================
  // OWNER
  // ==================================================

  authorId: uuid("author_id")
    .notNull()
    .references(() => userProfiles.id),

  // ==================================================
  // MEDIA
  // ==================================================

  mediaId: uuid("media_id")
    .references(() => postMedia.id),

  /**
   * photo
   * video
   * text
   */
  storyType: varchar("story_type", {
    length: 20,
  })
    .notNull(),

  /**
   * Text story.
   */
  storyText: text("story_text"),

  // ==================================================
  // MUSIC
  // ==================================================

  hasMusic: boolean("has_music")
    .default(false)
    .notNull(),

  musicTitle: varchar("music_title", {
    length: 255,
  }),

  musicArtist: varchar("music_artist", {
    length: 255,
  }),

  musicDuration: integer("music_duration"),

  // ==================================================
  // STICKERS
  // ==================================================

  hasStickers: boolean("has_stickers")
    .default(false)
    .notNull(),

  // ==================================================
  // PRIVACY
  // ==================================================

  /**
   * public
   * friends
   */
  privacy: varchar("privacy", {
    length: 20,
  })
    .default("friends")
    .notNull(),

  /**
   * Professional Mode
   * defaults to public.
   */
  professionalMode: boolean("professional_mode")
    .default(false)
    .notNull(),

  // ==================================================
  // REACTIONS
  // ==================================================

  /**
   * ❤️ only.
   */
  heartCount: integer("heart_count")
    .default(0)
    .notNull(),

  // ==================================================
  // REPLIES
  // ==================================================

  replyCount: integer("reply_count")
    .default(0)
    .notNull(),

  // ==================================================
  // VIEWS
  // ==================================================

  viewCount: integer("view_count")
    .default(0)
    .notNull(),

  /**
   * Professional Mode:
   * Friends and followers
   * only.
   *
   * Normal Profile:
   * Friends only.
   */
  viewerVisibility: varchar("viewer_visibility", {
    length: 30,
  })
    .default("friends")
    .notNull(),

  // ==================================================
  // SHARING
  // ==================================================

  shareCount: integer("share_count")
    .default(0)
    .notNull(),

  // ==================================================
  // HIGHLIGHTS
  // ==================================================

  highlighted: boolean("highlighted")
    .default(false)
    .notNull(),

  // ==================================================
  // AI MODERATION
  // ==================================================

  moderationStatus: varchar("moderation_status", {
    length: 30,
  })
    .default("approved")
    .notNull(),

  /**
   * pending
   * approved
   * hidden
   * removed
   * suspended
   */

  aiReviewed: boolean("ai_reviewed")
    .default(false)
    .notNull(),

  spamDetected: boolean("spam_detected")
    .default(false)
    .notNull(),

  reported: boolean("reported")
    .default(false)
    .notNull(),

  reportCount: integer("report_count")
    .default(0)
    .notNull(),

  // ==================================================
  // STATUS
  // ==================================================

  deleted: boolean("deleted")
    .default(false)
    .notNull(),

  // ==================================================
  // EXPIRATION
  // ==================================================

  expiresAt: timestamp("expires_at", {
    withTimezone: true,
  })
    .notNull(),

  // ==================================================
  // SYSTEM
  // ==================================================

  createdAt: timestamp("created_at", {
    withTimezone: true,
  })
    .defaultNow()
    .notNull(),

  updatedAt: timestamp("updated_at", {
    withTimezone: true,
  })
    .defaultNow()
    .notNull(),

});