export interface AuthUser { id: string; username: string; publicId: string; profileId: string; firstName: string; lastName: string; email: string | null; phoneNumber: string | null; emailVerified: boolean; phoneVerified: boolean; accountStatus: string; profilePhoto?: string | null; }
export interface AuthSession { sessionId: string; accessToken: string; refreshToken: string; expiresAt: string; }
export interface LoginVerification { challengeId: string; channel: "sms" | "email" | "whatsapp" | "authenticator"; target: string; maskedTarget: string; codeLength: number; expiresAt: string; }
export interface AuthResult { success: boolean; message: string; requiresVerification?: boolean; requiresTwoFactor?: boolean; user?: AuthUser; session?: AuthSession; verification?: LoginVerification; twoFactorVerification?: LoginVerification; }
export interface AuthState { status: "loading" | "authenticated" | "unauthenticated"; user: AuthUser | null; session: AuthSession | null; }
export interface LoginInput { identifier: string; password: string; networkIp?: string; platform?: string; browser?: string; deviceName?: string; deviceId?: string; deviceType?: string; loginSource?: string; appVersion?: string; }
export interface VerifyLoginDeviceInput { challengeId: string; code: string; deviceId: string; deviceName?: string; deviceType?: string; platform?: string; browser?: string; loginSource?: string; appVersion?: string; }
export interface VerifyLoginTwoFactorInput { challengeId: string; code: string; deviceId: string; deviceName?: string; deviceType?: string; platform?: string; browser?: string; loginSource?: string; appVersion?: string; }
export interface RegisterInput { firstName: string; lastName: string; username: string; email?: string; phoneNumber?: string; password: string; dateOfBirth?: string; gender?: "male" | "female" | "custom"; userAgent?: string; platform?: string; browser?: string; deviceName?: string; deviceId?: string; deviceType?: string; loginSource?: string; appVersion?: string; }
export interface RegistrationFlowReservation { success: boolean; reservationId: string; flowId: string; expiresAt: string; }
export interface RegistrationFlowNameSaveResult { success: boolean; reservationId: string; flowId: string; expiresAt: string; }
export interface RegistrationFlowBirthdaySaveResult { success: boolean; reservationId: string; flowId: string; expiresAt: string; age: number; ageBand: "underage" | "teen" | "adult"; flowStatus: "active" | "completed"; }
export interface RegistrationFlowGenderSaveResult { success: boolean; reservationId: string; flowId: string; expiresAt: string; gender: "female" | "male" | "custom" | null; pronouns?: "She / Her" | "He / Him" | "They / Them" | "Prefer not to say" | null; }
export interface RegistrationFlowPhoneCountryResult { success: boolean; countryCode: string | null; source: "device" | "unknown" | "ipapi"; timeZone: string | null; }
export interface RegistrationFlowIpapiDetails { ip: string | null; rir: string | null; isBogon: boolean; isMobile: boolean; isSatellite: boolean; isCrawler: boolean; isDatacenter: boolean; isTor: boolean; isProxy: boolean; isVpn: boolean; isAbuser: boolean; datacenter: Record<string, unknown> | null; company: Record<string, unknown> | null; abuse: Record<string, unknown> | null; asn: Record<string, unknown> | null; location: Record<string, unknown> | null; }
export interface RegistrationFlowNetworkSecurity { ip: string | null; connection: string | null; country: string | null; countryCode: string | null; callingCode: string | null; region: string | null; city: string | null; timezone: string | null; organization: string | null; companyType: string | null; asn: number | null; datacenter: string | null; datacenterDomain?: string | null; datacenterNetwork?: string | null; vpnService: string | null; egressService: string | null; egressProvider: string | null; proxy: boolean; vpn: boolean; tor: boolean; bot: boolean; abuser: boolean; mobile: boolean; satellite: boolean; bogon?: boolean; fraudScore: number; fraudLevel?: "low" | "moderate" | "high" | "critical"; companyAbuserScore?: number; asnAbuserScore?: number; securitySignals?: string[]; ipapi?: RegistrationFlowIpapiDetails; consentedAt?: string | null; }
export interface RegistrationFlowSecurityResult { success: boolean; flowId: string; reservationId: string; security: RegistrationFlowNetworkSecurity; }
export interface RegistrationFlowSecurityConsentResult extends RegistrationFlowSecurityResult { consentedAt: string; screenCompleted: boolean; }
export interface RegistrationFlowPhoneSaveResult { success: boolean; reservationId: string; flowId: string; expiresAt: string; phoneNumber: string; countryCode: string; lookupComplete: boolean; verificationStatus: "verified"; lookupProvider: "abstract" | "twilio"; lookupType: "phone-validation" | "basic"; lookupRequestId: string; nationalFormat: string | null; phoneCountryName: string | null; callingCountryCode: string | null; validationErrors: string[] | null; valid: boolean | null; active: boolean | null; activeStatus: string | null; fraudScore: number; voip: boolean; prepaid: boolean | null; risky: boolean | null; recentAbuse: boolean | null; leaked: boolean | null; spammer: boolean | null; lineType: string | null; carrier: string | null; phoneCountry: string | null; accurateCountryCode: boolean | null; ipSecurity: { fraudScore: number; proxy: boolean; vpn: boolean; tor: boolean; botStatus: boolean; countryCode: string | null; }; }
export interface RegistrationFlowMemory { flow: { flowId: string; reservationId: string; status: string; expiresAt: string }; screens: Record<string, { completed: boolean; completedAt: string }>; identity: { firstName: string | null; lastName: string | null }; birthday: { dateOfBirth: string | null }; gender: { gender: string | null; pronouns: string | null }; phoneLookup: { phoneNumber: string | null; lookupStatus: string | null; valid: boolean | null; active: boolean | null; voip: boolean | null; fraudScore: number | null; lineType: string | null; carrier: string | null; lookupRequestId: string | null; }; networkSecurity: Partial<RegistrationFlowNetworkSecurity> & { ipFraudScore: number | null; proxy: boolean | null; vpn: boolean | null; tor: boolean | null; botStatus: boolean | null; countryCode: string | null; }; email?: { address: string; domain: string; provider: "google" | "microsoft" | "yahoo"; verificationStatus: string; savedAt: string; }; password?: { hash: string; strength: "weak" | "medium" | "strong"; rememberLoginInfo: boolean; savedAt: string; }; }
export interface RegistrationFlowMemoryResult { success: boolean; flowId: string; reservationId: string; status: string; expiresAt: string; registeredTables: string[]; memory: RegistrationFlowMemory; }
export interface RegistrationChallengeStart { contactType: "phone" | "email"; target: string; deviceId?: string; flowId?: string; reservationId?: string; }
export interface RegistrationChallengeResult { success: boolean; challengeId: string; flowId: string; contactType: "phone" | "email"; target?: string; maskedTarget: string; codeLength: number; expiresAt: string; currentStep: "contact" | "identity" | "username" | "profile" | "password" | "review"; }
export interface RegistrationChallengeSaveResult { success: boolean; challengeId: string; flowId: string; maskedTarget: string; expiresAt: string; currentStep: RegistrationChallengeResult["currentStep"]; }
export interface RegistrationCompletionResult { success: boolean; flowId: string; user: AuthUser; verification: LoginVerification; }
export interface RegistrationInitializationResult { success: boolean; flowId: string; user: AuthUser; session: AuthSession; language: string; profileId: string; publicId: string; location?: { country: string | null; region: string | null; city: string | null; timezone: string | null }; }
export interface RegistrationStepData { firstName?: string; lastName?: string; username?: string; email?: string; phoneNumber?: string; dateOfBirth?: string; gender?: "male" | "female" | "custom"; password?: string; }
export interface ResendVerificationInput { userId: string; }
export interface ForgotPasswordInput { identifier: string; }
export interface ResetPasswordInput { userId: string; code: string; password: string; }
export interface RefreshSessionInput { refreshToken: string; }
export type PasswordRecoveryChannel = "email" | "sms" | "whatsapp";
export interface PasswordRecoveryMethod { channel: PasswordRecoveryChannel; maskedTarget: string; }
export interface PasswordRecoveryLookupResult { success: boolean; accountFound: boolean; reason?: string; message?: string; account?: { firstName: string; email: string | null; phoneNumber: string | null; methods: PasswordRecoveryMethod[] }; }
export interface PasswordRecoverySendResult { success: boolean; challengeId: string; channel: PasswordRecoveryChannel; maskedTarget: string; codeLength: number; expiresAt: string; message?: string; }
export interface PasswordRecoveryVerifyResult { success: boolean; resetToken?: string; message: string; }
export interface PasswordRecoveryChangeResult extends AuthResult { }
export interface PendingRegistrationMethod { channel: "email" | "sms"; target: string; maskedTarget: string; }
export interface PendingRegistrationOptionsResult { success: boolean; firstName: string; methods: PendingRegistrationMethod[]; }
export interface PendingRegistrationSendResult { success: boolean; challengeId: string; channel: "email" | "sms"; target: string; maskedTarget: string; codeLength: 8; expiresAt: string; }
export interface PendingRegistrationInvalidateResult { success: boolean; invalidated: boolean; message: string; }
