CREATE TABLE "muted_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"muted_user_id" uuid NOT NULL,
	"mute_posts" boolean DEFAULT false NOT NULL,
	"mute_stories" boolean DEFAULT false NOT NULL,
	"mute_reels" boolean DEFAULT false NOT NULL,
	"mute_notes" boolean DEFAULT false NOT NULL,
	"mute_live_videos" boolean DEFAULT false NOT NULL,
	"mute_messages" boolean DEFAULT false NOT NULL,
	"message_mute_duration" varchar(20) DEFAULT 'until_changed' NOT NULL,
	"mute_notifications" boolean DEFAULT false NOT NULL,
	"muted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "post_media" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"post_id" uuid NOT NULL,
	"share_id" varchar(10) NOT NULL,
	"media_type" varchar(20) NOT NULL,
	"object_key" varchar(500) NOT NULL,
	"thumbnail_key" varchar(500),
	"file_name" varchar(255),
	"mime_type" varchar(100) NOT NULL,
	"file_size" bigint NOT NULL,
	"width" integer,
	"height" integer,
	"duration" integer,
	"caption" varchar(1000),
	"alt_text" varchar(500),
	"display_order" integer DEFAULT 1 NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"processing_status" varchar(25) DEFAULT 'uploading' NOT NULL,
	"moderation_status" varchar(20) DEFAULT 'pending' NOT NULL,
	"moderation_reason" varchar(100),
	"review_requested" boolean DEFAULT false NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "post_media_share_id_unique" UNIQUE("share_id")
);
--> statement-breakpoint
CREATE TABLE "posts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"share_id" varchar(10) NOT NULL,
	"content" text,
	"type" varchar(20) DEFAULT 'text' NOT NULL,
	"visibility" varchar(20) DEFAULT 'public' NOT NULL,
	"comments_enabled" boolean DEFAULT true NOT NULL,
	"sharing_enabled" boolean DEFAULT true NOT NULL,
	"edited" boolean DEFAULT false NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"published_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "posts_share_id_unique" UNIQUE("share_id")
);
--> statement-breakpoint
CREATE TABLE "restricted_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"restricted_user_id" uuid NOT NULL,
	"reason" varchar(50),
	"restriction_type" varchar(20) DEFAULT 'standard' NOT NULL,
	"duration" varchar(20) DEFAULT '24_hours' NOT NULL,
	"expires_at" timestamp with time zone,
	"restricted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "video_captions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"media_id" uuid NOT NULL,
	"caption_type" varchar(30) DEFAULT 'automatic' NOT NULL,
	"language" varchar(50) NOT NULL,
	"original_language" varchar(50),
	"translated_language" varchar(50),
	"translation_source" varchar(30),
	"closed_captions" boolean DEFAULT true NOT NULL,
	"hearing_accessible" boolean DEFAULT false NOT NULL,
	"speaker_identification" boolean DEFAULT false NOT NULL,
	"sound_descriptions" boolean DEFAULT false NOT NULL,
	"start_time_ms" integer NOT NULL,
	"end_time_ms" integer NOT NULL,
	"caption_text" text NOT NULL,
	"ai_generated" boolean DEFAULT true NOT NULL,
	"confidence_score" integer,
	"multiple_speakers_detected" boolean DEFAULT false NOT NULL,
	"review_required" boolean DEFAULT false NOT NULL,
	"subtitle_object_key" varchar(500),
	"subtitle_format" varchar(20),
	"moderation_status" varchar(20) DEFAULT 'pending' NOT NULL,
	"moderation_reason" varchar(255),
	"enabled" boolean DEFAULT true NOT NULL,
	"default_caption" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "video_comments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"media_id" uuid NOT NULL,
	"author_id" uuid NOT NULL,
	"parent_comment_id" uuid,
	"comment" text NOT NULL,
	"edited" boolean DEFAULT false NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"like_count" integer DEFAULT 0 NOT NULL,
	"reply_count" integer DEFAULT 0 NOT NULL,
	"creator_heart" boolean DEFAULT false NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"visibility" varchar(30) DEFAULT 'public' NOT NULL,
	"has_mentions" boolean DEFAULT false NOT NULL,
	"has_hashtags" boolean DEFAULT false NOT NULL,
	"moderation_status" varchar(30) DEFAULT 'approved' NOT NULL,
	"spam_detected" boolean DEFAULT false NOT NULL,
	"ai_reviewed" boolean DEFAULT false NOT NULL,
	"reported" boolean DEFAULT false NOT NULL,
	"report_count" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "video_metadata" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"media_id" uuid NOT NULL,
	"video_title" varchar(255),
	"description" text,
	"category" varchar(100),
	"language" varchar(50),
	"original_language" varchar(50),
	"publishing_status" varchar(20) DEFAULT 'draft' NOT NULL,
	"scheduled_publish_at" timestamp with time zone,
	"premiere_enabled" boolean DEFAULT false NOT NULL,
	"premiere_starts_at" timestamp with time zone,
	"published_at" timestamp with time zone,
	"audience" varchar(20) DEFAULT 'public' NOT NULL,
	"embedding_enabled" boolean DEFAULT true NOT NULL,
	"sharing_enabled" boolean DEFAULT true NOT NULL,
	"downloadable" boolean DEFAULT false NOT NULL,
	"clipping_enabled" boolean DEFAULT true NOT NULL,
	"remix_enabled" boolean DEFAULT true NOT NULL,
	"duet_enabled" boolean DEFAULT true NOT NULL,
	"closed_captions_enabled" boolean DEFAULT false NOT NULL,
	"automatic_captions_enabled" boolean DEFAULT true NOT NULL,
	"subtitle_language" varchar(50),
	"multiple_subtitles" boolean DEFAULT false NOT NULL,
	"alt_description" text,
	"sensitive_content_warning" boolean DEFAULT false NOT NULL,
	"graphic_content_warning" boolean DEFAULT false NOT NULL,
	"ai_generated_label" boolean DEFAULT false NOT NULL,
	"age_restriction" varchar(20) DEFAULT 'all' NOT NULL,
	"sponsored_content" boolean DEFAULT false NOT NULL,
	"monetization_enabled" boolean DEFAULT false NOT NULL,
	"monetization_eligible" boolean DEFAULT false NOT NULL,
	"copyright_status" varchar(30) DEFAULT 'pending' NOT NULL,
	"copyright_owner" varchar(255),
	"copyright_dispute" boolean DEFAULT false NOT NULL,
	"audio_ownership" varchar(100),
	"manual_claim" boolean DEFAULT false NOT NULL,
	"automatic_claim" boolean DEFAULT false NOT NULL,
	"ai_moderation_completed" boolean DEFAULT false NOT NULL,
	"ai_confidence_score" integer,
	"human_review_required" boolean DEFAULT false NOT NULL,
	"human_review_completed" boolean DEFAULT false NOT NULL,
	"eligible_for_recommendations" boolean DEFAULT true NOT NULL,
	"eligible_for_trending" boolean DEFAULT true NOT NULL,
	"eligible_for_explore" boolean DEFAULT true NOT NULL,
	"eligible_for_following_feed" boolean DEFAULT true NOT NULL,
	"eligible_for_friends_feed" boolean DEFAULT true NOT NULL,
	"views_count" bigint DEFAULT 0 NOT NULL,
	"likes_count" bigint DEFAULT 0 NOT NULL,
	"comments_count" bigint DEFAULT 0 NOT NULL,
	"shares_count" bigint DEFAULT 0 NOT NULL,
	"saves_count" bigint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "video_quality" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"media_id" uuid NOT NULL,
	"original_resolution" varchar(20) NOT NULL,
	"original_codec" varchar(20) NOT NULL,
	"original_bitrate" integer,
	"original_fps" integer,
	"quality_144p" boolean DEFAULT false NOT NULL,
	"quality_240p" boolean DEFAULT false NOT NULL,
	"quality_360p" boolean DEFAULT false NOT NULL,
	"quality_480p" boolean DEFAULT false NOT NULL,
	"quality_720p" boolean DEFAULT false NOT NULL,
	"quality_1080p" boolean DEFAULT false NOT NULL,
	"quality_1440p" boolean DEFAULT false NOT NULL,
	"quality_2160p" boolean DEFAULT false NOT NULL,
	"default_quality" varchar(10) DEFAULT '720p' NOT NULL,
	"upscale_allowed" boolean DEFAULT false NOT NULL,
	"adaptive_streaming" boolean DEFAULT true NOT NULL,
	"network_adaptive_playback" boolean DEFAULT true NOT NULL,
	"progressive_playback" boolean DEFAULT true NOT NULL,
	"fast_start_playback" boolean DEFAULT true NOT NULL,
	"chunked_streaming" boolean DEFAULT true NOT NULL,
	"h264" boolean DEFAULT true NOT NULL,
	"h265" boolean DEFAULT true NOT NULL,
	"av1" boolean DEFAULT false NOT NULL,
	"vp9" boolean DEFAULT false NOT NULL,
	"fps24" boolean DEFAULT false NOT NULL,
	"fps25" boolean DEFAULT false NOT NULL,
	"fps30" boolean DEFAULT true NOT NULL,
	"fps50" boolean DEFAULT false NOT NULL,
	"fps60" boolean DEFAULT false NOT NULL,
	"sdr" boolean DEFAULT true NOT NULL,
	"hdr10" boolean DEFAULT false NOT NULL,
	"hdr10_plus" boolean DEFAULT false NOT NULL,
	"dolby_vision" boolean DEFAULT false NOT NULL,
	"compressed" boolean DEFAULT false NOT NULL,
	"optimized_for_streaming" boolean DEFAULT true NOT NULL,
	"main_thumbnail_key" varchar(500),
	"preview_thumbnail_key" varchar(500),
	"animated_preview_key" varchar(500),
	"processing_status" varchar(20) DEFAULT 'waiting' NOT NULL,
	"original_object_key" varchar(500),
	"object_144p" varchar(500),
	"object_240p" varchar(500),
	"object_360p" varchar(500),
	"object_480p" varchar(500),
	"object_720p" varchar(500),
	"object_1080p" varchar(500),
	"object_1440p" varchar(500),
	"object_2160p" varchar(500),
	"automatic_quality_selection" boolean DEFAULT true NOT NULL,
	"manual_quality_selection" boolean DEFAULT true NOT NULL,
	"resume_playback" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "video_views" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"media_id" uuid NOT NULL,
	"viewer_id" uuid,
	"session_id" uuid,
	"started_at" timestamp with time zone DEFAULT now(),
	"ended_at" timestamp with time zone,
	"watch_duration_seconds" integer DEFAULT 0 NOT NULL,
	"completion_percentage" numeric(5, 2) DEFAULT '0.00' NOT NULL,
	"resume_position_seconds" integer DEFAULT 0 NOT NULL,
	"qualified_view" boolean DEFAULT false NOT NULL,
	"repeat_view" boolean DEFAULT false NOT NULL,
	"selected_quality" varchar(20) DEFAULT '720p',
	"quality_selection_mode" varchar(20) DEFAULT 'automatic',
	"playback_speed" varchar(10) DEFAULT '1x',
	"captions_enabled" boolean DEFAULT false NOT NULL,
	"subtitle_language" varchar(50),
	"device_type" varchar(30),
	"operating_system" varchar(50),
	"app_version" varchar(30),
	"network_type" varchar(30),
	"country" varchar(100),
	"region" varchar(100),
	"language" varchar(50),
	"retention_score" integer,
	"recommendation_weight" integer,
	"suspicious_view" boolean DEFAULT false NOT NULL,
	"invalid_view" boolean DEFAULT false NOT NULL,
	"subscriber_only_video" boolean DEFAULT false NOT NULL,
	"subscription_unlocked" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "muted_users" ADD CONSTRAINT "muted_users_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "muted_users" ADD CONSTRAINT "muted_users_muted_user_id_users_id_fk" FOREIGN KEY ("muted_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_media" ADD CONSTRAINT "post_media_post_id_posts_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."posts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "restricted_users" ADD CONSTRAINT "restricted_users_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "restricted_users" ADD CONSTRAINT "restricted_users_restricted_user_id_users_id_fk" FOREIGN KEY ("restricted_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_captions" ADD CONSTRAINT "video_captions_media_id_post_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."post_media"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_comments" ADD CONSTRAINT "video_comments_media_id_post_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."post_media"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_comments" ADD CONSTRAINT "video_comments_author_id_user_profiles_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_metadata" ADD CONSTRAINT "video_metadata_media_id_post_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."post_media"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_quality" ADD CONSTRAINT "video_quality_media_id_post_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."post_media"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_views" ADD CONSTRAINT "video_views_media_id_post_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."post_media"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "video_views" ADD CONSTRAINT "video_views_viewer_id_user_profiles_id_fk" FOREIGN KEY ("viewer_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;