CREATE TABLE "conversation_participants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"joined_by" uuid,
	"role" varchar(20) DEFAULT 'member' NOT NULL,
	"active_member" boolean DEFAULT true NOT NULL,
	"invited" boolean DEFAULT false NOT NULL,
	"join_request_approved" boolean DEFAULT false NOT NULL,
	"joined_by_creator" boolean DEFAULT false NOT NULL,
	"rejoined" boolean DEFAULT false NOT NULL,
	"removed_by_creator" boolean DEFAULT false NOT NULL,
	"left_group" boolean DEFAULT false NOT NULL,
	"muted" boolean DEFAULT false NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"archived" boolean DEFAULT false NOT NULL,
	"notifications_enabled" boolean DEFAULT true NOT NULL,
	"mentions_only" boolean DEFAULT false NOT NULL,
	"custom_notification_sound" varchar(255),
	"app_wallpaper" varchar(255),
	"unread_message_count" integer DEFAULT 0 NOT NULL,
	"is_typing" boolean DEFAULT false NOT NULL,
	"typing_started_at" timestamp with time zone,
	"can_join_calls" boolean DEFAULT true NOT NULL,
	"missed_call_count" integer DEFAULT 0 NOT NULL,
	"last_joined_call_at" timestamp with time zone,
	"muted_by_admin" boolean DEFAULT false NOT NULL,
	"temporarily_suspended" boolean DEFAULT false NOT NULL,
	"permanently_removed" boolean DEFAULT false NOT NULL,
	"warning_count" integer DEFAULT 0 NOT NULL,
	"removed_by_ai" boolean DEFAULT false NOT NULL,
	"removed_by_admin" boolean DEFAULT false NOT NULL,
	"report_count" integer DEFAULT 0 NOT NULL,
	"online" boolean DEFAULT false NOT NULL,
	"do_not_disturb" boolean DEFAULT false NOT NULL,
	"joined_at" timestamp with time zone DEFAULT now() NOT NULL,
	"left_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "conversations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_by" uuid NOT NULL,
	"conversation_type" varchar(20) DEFAULT 'direct' NOT NULL,
	"group_name" varchar(150),
	"group_description" text,
	"group_photo" text,
	"group_cover_photo" text,
	"verified" boolean DEFAULT false NOT NULL,
	"anyone_can_edit_info" boolean DEFAULT true NOT NULL,
	"anyone_can_invite" boolean DEFAULT true NOT NULL,
	"anyone_can_remove_members" boolean DEFAULT true NOT NULL,
	"anyone_can_pin_messages" boolean DEFAULT true NOT NULL,
	"join_approval_required" boolean DEFAULT false NOT NULL,
	"anonymous_messages_allowed" boolean DEFAULT false NOT NULL,
	"encrypted" boolean DEFAULT true NOT NULL,
	"screenshot_detection" boolean DEFAULT true NOT NULL,
	"ai_moderation_enabled" boolean DEFAULT true NOT NULL,
	"moderation_status" varchar(30) DEFAULT 'approved' NOT NULL,
	"spam_detected" boolean DEFAULT false NOT NULL,
	"scam_detected" boolean DEFAULT false NOT NULL,
	"adult_content_detected" boolean DEFAULT false NOT NULL,
	"hate_speech_detected" boolean DEFAULT false NOT NULL,
	"malware_detected" boolean DEFAULT false NOT NULL,
	"report_count" integer DEFAULT 0 NOT NULL,
	"participant_count" integer DEFAULT 0 NOT NULL,
	"message_count" integer DEFAULT 0 NOT NULL,
	"online_members" integer DEFAULT 0 NOT NULL,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"archived" boolean DEFAULT false NOT NULL,
	"archived_by_creator" boolean DEFAULT false NOT NULL,
	"locked" boolean DEFAULT false NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "message_drafts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"user_id" uuid NOT NULL,
	"draft_message" text,
	"has_draft" boolean DEFAULT false NOT NULL,
	"sent" boolean DEFAULT false NOT NULL,
	"discarded" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"sender_id" uuid NOT NULL,
	"parent_message_id" uuid,
	"forwarded_from_message_id" uuid,
	"message_type" varchar(40) DEFAULT 'text' NOT NULL,
	"message" text,
	"caption" text,
	"mentions" text,
	"hashtags" text,
	"hyperlink" text,
	"rich_link_preview" boolean DEFAULT false NOT NULL,
	"markdown" boolean DEFAULT false NOT NULL,
	"code_block" boolean DEFAULT false NOT NULL,
	"translated" boolean DEFAULT false NOT NULL,
	"like_count" integer DEFAULT 0 NOT NULL,
	"love_count" integer DEFAULT 0 NOT NULL,
	"haha_count" integer DEFAULT 0 NOT NULL,
	"wow_count" integer DEFAULT 0 NOT NULL,
	"sad_count" integer DEFAULT 0 NOT NULL,
	"angry_count" integer DEFAULT 0 NOT NULL,
	"reaction_count" integer DEFAULT 0 NOT NULL,
	"is_forwarded" boolean DEFAULT false NOT NULL,
	"edited" boolean DEFAULT false NOT NULL,
	"edited_label" boolean DEFAULT false NOT NULL,
	"edited_at" timestamp with time zone,
	"pinned" boolean DEFAULT false NOT NULL,
	"sent" boolean DEFAULT true NOT NULL,
	"delivered" boolean DEFAULT false NOT NULL,
	"read" boolean DEFAULT false NOT NULL,
	"read_at" timestamp with time zone,
	"deleted_for_me" boolean DEFAULT false NOT NULL,
	"deleted_for_everyone" boolean DEFAULT false NOT NULL,
	"deleted_placeholder" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"ai_reviewed" boolean DEFAULT false NOT NULL,
	"moderation_status" varchar(30) DEFAULT 'approved' NOT NULL,
	"spam_detected" boolean DEFAULT false NOT NULL,
	"scam_detected" boolean DEFAULT false NOT NULL,
	"adult_content_detected" boolean DEFAULT false NOT NULL,
	"violence_detected" boolean DEFAULT false NOT NULL,
	"hate_speech_detected" boolean DEFAULT false NOT NULL,
	"malware_detected" boolean DEFAULT false NOT NULL,
	"report_count" integer DEFAULT 0 NOT NULL,
	"failed_delivery" boolean DEFAULT false NOT NULL,
	"restricted_message" boolean DEFAULT false NOT NULL,
	"call_type" varchar(30),
	"call_duration_seconds" integer,
	"system_action" varchar(60),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"share_id" varchar(10) NOT NULL,
	"author_id" uuid NOT NULL,
	"media_id" uuid,
	"story_type" varchar(20) NOT NULL,
	"story_text" text,
	"has_music" boolean DEFAULT false NOT NULL,
	"music_title" varchar(255),
	"music_artist" varchar(255),
	"music_duration" integer,
	"has_stickers" boolean DEFAULT false NOT NULL,
	"privacy" varchar(20) DEFAULT 'friends' NOT NULL,
	"professional_mode" boolean DEFAULT false NOT NULL,
	"heart_count" integer DEFAULT 0 NOT NULL,
	"reply_count" integer DEFAULT 0 NOT NULL,
	"view_count" integer DEFAULT 0 NOT NULL,
	"viewer_visibility" varchar(30) DEFAULT 'friends' NOT NULL,
	"share_count" integer DEFAULT 0 NOT NULL,
	"highlighted" boolean DEFAULT false NOT NULL,
	"moderation_status" varchar(30) DEFAULT 'approved' NOT NULL,
	"ai_reviewed" boolean DEFAULT false NOT NULL,
	"spam_detected" boolean DEFAULT false NOT NULL,
	"reported" boolean DEFAULT false NOT NULL,
	"report_count" integer DEFAULT 0 NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stories_share_id_unique" UNIQUE("share_id")
);
--> statement-breakpoint
CREATE TABLE "story_viewers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"viewer_id" uuid NOT NULL,
	"viewed" boolean DEFAULT true NOT NULL,
	"is_friend" boolean DEFAULT false NOT NULL,
	"is_follower" boolean DEFAULT false NOT NULL,
	"visible_to_creator" boolean DEFAULT true NOT NULL,
	"viewed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_user_id_user_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_joined_by_user_profiles_id_fk" FOREIGN KEY ("joined_by") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversations" ADD CONSTRAINT "conversations_created_by_user_profiles_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_drafts" ADD CONSTRAINT "message_drafts_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_drafts" ADD CONSTRAINT "message_drafts_user_id_user_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_sender_id_user_profiles_id_fk" FOREIGN KEY ("sender_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stories" ADD CONSTRAINT "stories_author_id_user_profiles_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stories" ADD CONSTRAINT "stories_media_id_post_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."post_media"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_viewers" ADD CONSTRAINT "story_viewers_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "story_viewers" ADD CONSTRAINT "story_viewers_viewer_id_user_profiles_id_fk" FOREIGN KEY ("viewer_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;