CREATE TABLE "account_actions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"moderator_id" uuid,
	"report_id" uuid,
	"action_type" varchar(40) NOT NULL,
	"reason" varchar(60) NOT NULL,
	"description" text,
	"strike_level" integer DEFAULT 0 NOT NULL,
	"warning_count" integer DEFAULT 0 NOT NULL,
	"permanent" boolean DEFAULT false NOT NULL,
	"duration_hours" integer,
	"appealed" boolean DEFAULT false NOT NULL,
	"appeal_accepted" boolean DEFAULT false NOT NULL,
	"appeal_rejected" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "appeals" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"account_action_id" uuid NOT NULL,
	"report_id" uuid,
	"reviewed_by_moderator_id" uuid,
	"appeal_type" varchar(40) NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"phone_verified" boolean DEFAULT false NOT NULL,
	"recaptcha_passed" boolean DEFAULT false NOT NULL,
	"identity_verified" boolean DEFAULT false NOT NULL,
	"live_check_passed" boolean DEFAULT false NOT NULL,
	"identity_document_type" varchar(30),
	"identity_document_url" text,
	"live_check_url" text,
	"appeal_attempt" varchar(10) DEFAULT 'first' NOT NULL,
	"final_decision_reached" boolean DEFAULT false NOT NULL,
	"appeal_status" varchar(30) DEFAULT 'submitted' NOT NULL,
	"appeal_reason" varchar(150),
	"additional_explanation" text,
	"evidence_url" text,
	"attachment_url" text,
	"review_notes" text,
	"decision_reason" text,
	"internal_notes" text,
	"decision" varchar(40),
	"status" varchar(20) DEFAULT 'open' NOT NULL,
	"priority" varchar(20) DEFAULT 'normal' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reviewed_at" timestamp with time zone,
	"closed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "calls" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"started_by_user_id" uuid NOT NULL,
	"call_type" varchar(20) NOT NULL,
	"conversation_type" varchar(20) NOT NULL,
	"call_status" varchar(30) DEFAULT 'ringing' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"participant_count" integer DEFAULT 1 NOT NULL,
	"max_participants" integer DEFAULT 2 NOT NULL,
	"microphone_enabled" boolean DEFAULT true NOT NULL,
	"speaker_enabled" boolean DEFAULT true NOT NULL,
	"camera_enabled" boolean DEFAULT false NOT NULL,
	"using_front_camera" boolean DEFAULT true NOT NULL,
	"screen_sharing" boolean DEFAULT false NOT NULL,
	"connection_quality" varchar(20),
	"network_type" varchar(20),
	"encrypted" boolean DEFAULT true NOT NULL,
	"ai_reviewed" boolean DEFAULT false NOT NULL,
	"spam_detected" boolean DEFAULT false NOT NULL,
	"abuse_reported" boolean DEFAULT false NOT NULL,
	"report_count" integer DEFAULT 0 NOT NULL,
	"started_at" timestamp with time zone,
	"answered_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"duration_seconds" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "marketplace_categories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(100) NOT NULL,
	"slug" varchar(120) NOT NULL,
	"description" text,
	"icon" text,
	"banner_image_url" text,
	"parent_category_id" uuid,
	"level" integer DEFAULT 1 NOT NULL,
	"allow_offers" boolean DEFAULT true NOT NULL,
	"allow_shipping" boolean DEFAULT true NOT NULL,
	"allow_pickup" boolean DEFAULT true NOT NULL,
	"allow_returns" boolean DEFAULT false NOT NULL,
	"moderation_required" boolean DEFAULT true NOT NULL,
	"status" varchar(20) DEFAULT 'active' NOT NULL,
	"total_listings" integer DEFAULT 0 NOT NULL,
	"total_sales" integer DEFAULT 0 NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "marketplace_categories_name_unique" UNIQUE("name"),
	CONSTRAINT "marketplace_categories_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "marketplace_interactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"buyer_user_id" uuid NOT NULL,
	"seller_user_id" uuid NOT NULL,
	"interaction_type" varchar(20) NOT NULL,
	"favorite" boolean DEFAULT false NOT NULL,
	"favorited_at" timestamp with time zone,
	"offer_price" numeric(15, 2),
	"currency" varchar(10),
	"offer_message" text,
	"offer_status" varchar(20) DEFAULT 'pending' NOT NULL,
	"counter_offer_price" numeric(15, 2),
	"counter_offer_message" text,
	"offer_expires_at" timestamp with time zone,
	"offer_viewed" boolean DEFAULT false NOT NULL,
	"offer_viewed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "marketplace_listings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"seller_user_id" uuid NOT NULL,
	"buyer_user_id" uuid,
	"listing_id" varchar(10) NOT NULL,
	"title" varchar(150) NOT NULL,
	"description" text,
	"category" varchar(100) NOT NULL,
	"condition" varchar(50) NOT NULL,
	"brand" varchar(100),
	"model" varchar(100),
	"color" varchar(50),
	"price" numeric(15, 2) NOT NULL,
	"currency" varchar(10) NOT NULL,
	"negotiable" boolean DEFAULT false NOT NULL,
	"offers_accepted" boolean DEFAULT true NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"quantity_sold" integer DEFAULT 0 NOT NULL,
	"remaining_stock" integer DEFAULT 1 NOT NULL,
	"cover_image_url" text,
	"image_urls" text,
	"country" varchar(100) NOT NULL,
	"state" varchar(100),
	"city" varchar(100),
	"pickup_available" boolean DEFAULT false NOT NULL,
	"delivery_available" boolean DEFAULT false NOT NULL,
	"shipping_available" boolean DEFAULT false NOT NULL,
	"status" varchar(30) DEFAULT 'draft' NOT NULL,
	"ai_moderation_score" double precision,
	"review_status" varchar(20) DEFAULT 'pending' NOT NULL,
	"rejection_reason" text,
	"approved_by_moderator_id" uuid,
	"views" integer DEFAULT 0 NOT NULL,
	"saves" integer DEFAULT 0 NOT NULL,
	"shares" integer DEFAULT 0 NOT NULL,
	"messages_received" integer DEFAULT 0 NOT NULL,
	"purchases" integer DEFAULT 0 NOT NULL,
	"returns_accepted" boolean DEFAULT false NOT NULL,
	"return_window_days" integer,
	"refund_available" boolean DEFAULT false NOT NULL,
	"featured_listing" boolean DEFAULT false NOT NULL,
	"sponsored_listing" boolean DEFAULT false NOT NULL,
	"promotion_expires_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"published_at" timestamp with time zone,
	"sold_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "marketplace_listings_listing_id_unique" UNIQUE("listing_id")
);
--> statement-breakpoint
CREATE TABLE "marketplace_reviews" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"transaction_id" uuid NOT NULL,
	"listing_id" uuid NOT NULL,
	"reviewer_user_id" uuid NOT NULL,
	"reviewed_user_id" uuid NOT NULL,
	"review_type" varchar(20) NOT NULL,
	"rating" integer NOT NULL,
	"title" varchar(150),
	"review" text,
	"recommend_seller" boolean,
	"recommend_buyer" boolean,
	"item_as_described" boolean,
	"communication" boolean,
	"shipping_speed" boolean,
	"prompt_payment" boolean,
	"respectful_communication" boolean,
	"hidden" boolean DEFAULT false NOT NULL,
	"reported" boolean DEFAULT false NOT NULL,
	"moderator_notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "marketplace_transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"listing_id" uuid NOT NULL,
	"seller_user_id" uuid NOT NULL,
	"buyer_user_id" uuid NOT NULL,
	"transaction_id" varchar(10) NOT NULL,
	"quantity" integer DEFAULT 1 NOT NULL,
	"unit_price" numeric(15, 2) NOT NULL,
	"total_price" numeric(15, 2) NOT NULL,
	"currency" varchar(10) NOT NULL,
	"payment_method" varchar(40),
	"payment_provider" varchar(50),
	"transaction_reference" varchar(255),
	"payment_status" varchar(30) DEFAULT 'pending' NOT NULL,
	"order_status" varchar(30) DEFAULT 'pending' NOT NULL,
	"shipping_address_id" uuid,
	"shipping_cost" numeric(15, 2),
	"tracking_number" varchar(150),
	"courier_name" varchar(100),
	"estimated_delivery_date" timestamp with time zone,
	"delivered_at" timestamp with time zone,
	"buyer_protection_enabled" boolean DEFAULT true NOT NULL,
	"refund_requested" boolean DEFAULT false NOT NULL,
	"refund_approved" boolean DEFAULT false NOT NULL,
	"refund_completed" boolean DEFAULT false NOT NULL,
	"return_requested" boolean DEFAULT false NOT NULL,
	"return_approved" boolean DEFAULT false NOT NULL,
	"return_completed" boolean DEFAULT false NOT NULL,
	"cancelled_by" varchar(20),
	"cancellation_reason" text,
	"cancelled_at" timestamp with time zone,
	"seller_rated" boolean DEFAULT false NOT NULL,
	"buyer_rated" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"paid_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	CONSTRAINT "marketplace_transactions_transaction_id_unique" UNIQUE("transaction_id")
);
--> statement-breakpoint
CREATE TABLE "message_attachments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"message_id" uuid NOT NULL,
	"attachment_type" varchar(40) NOT NULL,
	"file_url" text,
	"thumbnail_url" text,
	"file_name" varchar(255),
	"mime_type" varchar(120),
	"file_extension" varchar(20),
	"file_size" integer,
	"width" integer,
	"height" integer,
	"duration_seconds" integer,
	"blur_nsfw" boolean DEFAULT false NOT NULL,
	"original_resolution" varchar(30),
	"compressed" boolean DEFAULT true NOT NULL,
	"exif_removed" boolean DEFAULT true NOT NULL,
	"thumbnail_generated" boolean DEFAULT false NOT NULL,
	"hd_available" boolean DEFAULT false NOT NULL,
	"sd_available" boolean DEFAULT true NOT NULL,
	"original_quality" varchar(30),
	"processing_completed" boolean DEFAULT false NOT NULL,
	"waveform" text,
	"playback_speed" varchar(10) DEFAULT '1x' NOT NULL,
	"transcription" text,
	"download_allowed" boolean DEFAULT false NOT NULL,
	"file_preview" boolean DEFAULT false NOT NULL,
	"password_protected" boolean DEFAULT false NOT NULL,
	"gif_provider" varchar(100),
	"sticker_pack" varchar(150),
	"animated" boolean DEFAULT false NOT NULL,
	"favorite_sticker" boolean DEFAULT false NOT NULL,
	"latitude" text,
	"longitude" text,
	"place_name" varchar(255),
	"map_link" text,
	"shared_post_id" uuid,
	"shared_story_id" uuid,
	"shared_profile_id" uuid,
	"shared_marketplace_id" uuid,
	"ai_reviewed" boolean DEFAULT false NOT NULL,
	"spam_detected" boolean DEFAULT false NOT NULL,
	"malware_detected" boolean DEFAULT false NOT NULL,
	"adult_content_detected" boolean DEFAULT false NOT NULL,
	"violence_detected" boolean DEFAULT false NOT NULL,
	"copyright_detected" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"processing" boolean DEFAULT false NOT NULL,
	"failed" boolean DEFAULT false NOT NULL,
	"virus_scanned" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "message_reads" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"message_id" uuid NOT NULL,
	"reader_id" uuid NOT NULL,
	"sent" boolean DEFAULT true NOT NULL,
	"delivered" boolean DEFAULT false NOT NULL,
	"delivered_at" timestamp with time zone,
	"read" boolean DEFAULT false NOT NULL,
	"read_at" timestamp with time zone,
	"read_receipt_enabled" boolean DEFAULT true NOT NULL,
	"read_hidden" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "message_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sender_id" uuid NOT NULL,
	"receiver_id" uuid NOT NULL,
	"conversation_id" uuid,
	"request_status" varchar(30) DEFAULT 'pending' NOT NULL,
	"receiver_accepts_requests" boolean DEFAULT true NOT NULL,
	"sender_blocked" boolean DEFAULT false NOT NULL,
	"sender_restricted" boolean DEFAULT false NOT NULL,
	"spam_check_passed" boolean DEFAULT true NOT NULL,
	"first_message_viewed" boolean DEFAULT false NOT NULL,
	"mutual_friends" integer DEFAULT 0 NOT NULL,
	"accepted" boolean DEFAULT false NOT NULL,
	"declined" boolean DEFAULT false NOT NULL,
	"ignored" boolean DEFAULT false NOT NULL,
	"cancelled" boolean DEFAULT false NOT NULL,
	"reported" boolean DEFAULT false NOT NULL,
	"blocked" boolean DEFAULT false NOT NULL,
	"ai_reviewed" boolean DEFAULT false NOT NULL,
	"spam_detected" boolean DEFAULT false NOT NULL,
	"scam_detected" boolean DEFAULT false NOT NULL,
	"adult_content_detected" boolean DEFAULT false NOT NULL,
	"malware_detected" boolean DEFAULT false NOT NULL,
	"report_count" integer DEFAULT 0 NOT NULL,
	"sender_notified_accepted" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"expired" boolean DEFAULT false NOT NULL,
	"user_not_found" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"accepted_at" timestamp with time zone,
	"declined_at" timestamp with time zone,
	"ignored_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"expired_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"recipient_user_id" uuid NOT NULL,
	"actor_user_id" uuid,
	"post_id" uuid,
	"comment_id" uuid,
	"message_id" uuid,
	"conversation_id" uuid,
	"call_id" uuid,
	"story_id" uuid,
	"reel_id" uuid,
	"video_id" uuid,
	"poll_id" uuid,
	"group_id" uuid,
	"marketplace_listing_id" uuid,
	"verification_id" uuid,
	"notification_type" varchar(60) NOT NULL,
	"title" varchar(255),
	"body" text,
	"image_url" text,
	"action_url" text,
	"actor_count" integer DEFAULT 1 NOT NULL,
	"unread" boolean DEFAULT true NOT NULL,
	"read" boolean DEFAULT false NOT NULL,
	"archived" boolean DEFAULT false NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"push_sent" boolean DEFAULT false NOT NULL,
	"in_app_delivered" boolean DEFAULT true NOT NULL,
	"email_sent" boolean DEFAULT false NOT NULL,
	"sms_sent" boolean DEFAULT false NOT NULL,
	"opened" boolean DEFAULT false NOT NULL,
	"dismissed" boolean DEFAULT false NOT NULL,
	"muted" boolean DEFAULT false NOT NULL,
	"priority" varchar(20) DEFAULT 'normal' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"read_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reports" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"reporter_user_id" uuid NOT NULL,
	"reported_user_id" uuid,
	"moderator_user_id" uuid,
	"report_target" varchar(40) NOT NULL,
	"target_id" uuid,
	"report_reason" varchar(60) NOT NULL,
	"additional_details" text,
	"user_comment" text,
	"screenshot_url" text,
	"attachment_url" text,
	"ai_evidence_summary" text,
	"ai_reviewed" boolean DEFAULT false NOT NULL,
	"ai_confidence_score" real,
	"ai_recommended_action" varchar(40),
	"auto_hidden" boolean DEFAULT false NOT NULL,
	"auto_removed" boolean DEFAULT false NOT NULL,
	"requires_human_review" boolean DEFAULT true NOT NULL,
	"moderator_action" varchar(40) DEFAULT 'pending' NOT NULL,
	"moderator_notes" text,
	"appeal_submitted" boolean DEFAULT false NOT NULL,
	"appeal_reviewed" boolean DEFAULT false NOT NULL,
	"appeal_accepted" boolean DEFAULT false NOT NULL,
	"appeal_rejected" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'open' NOT NULL,
	"priority" varchar(20) DEFAULT 'normal' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"reviewed_at" timestamp with time zone,
	"closed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "search_history" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"search_query" text NOT NULL,
	"search_type" varchar(30) DEFAULT 'all' NOT NULL,
	"recent_search" boolean DEFAULT true NOT NULL,
	"cleared_by_user" boolean DEFAULT false NOT NULL,
	"ai_ranked" boolean DEFAULT false NOT NULL,
	"recommendation_used" boolean DEFAULT false NOT NULL,
	"trending_search" boolean DEFAULT false NOT NULL,
	"trending_post" boolean DEFAULT false NOT NULL,
	"trending_label" varchar(255),
	"people_talking_count" integer DEFAULT 0 NOT NULL,
	"search_count" integer DEFAULT 1 NOT NULL,
	"clicked_result" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "account_actions" ADD CONSTRAINT "account_actions_user_id_user_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_actions" ADD CONSTRAINT "account_actions_moderator_id_user_profiles_id_fk" FOREIGN KEY ("moderator_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "account_actions" ADD CONSTRAINT "account_actions_report_id_reports_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."reports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "appeals" ADD CONSTRAINT "appeals_user_id_user_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "appeals" ADD CONSTRAINT "appeals_account_action_id_account_actions_id_fk" FOREIGN KEY ("account_action_id") REFERENCES "public"."account_actions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "appeals" ADD CONSTRAINT "appeals_report_id_reports_id_fk" FOREIGN KEY ("report_id") REFERENCES "public"."reports"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "appeals" ADD CONSTRAINT "appeals_reviewed_by_moderator_id_user_profiles_id_fk" FOREIGN KEY ("reviewed_by_moderator_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "calls" ADD CONSTRAINT "calls_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "calls" ADD CONSTRAINT "calls_started_by_user_id_user_profiles_id_fk" FOREIGN KEY ("started_by_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_interactions" ADD CONSTRAINT "marketplace_interactions_listing_id_marketplace_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."marketplace_listings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_interactions" ADD CONSTRAINT "marketplace_interactions_buyer_user_id_user_profiles_id_fk" FOREIGN KEY ("buyer_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_interactions" ADD CONSTRAINT "marketplace_interactions_seller_user_id_user_profiles_id_fk" FOREIGN KEY ("seller_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_listings" ADD CONSTRAINT "marketplace_listings_seller_user_id_user_profiles_id_fk" FOREIGN KEY ("seller_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_listings" ADD CONSTRAINT "marketplace_listings_buyer_user_id_user_profiles_id_fk" FOREIGN KEY ("buyer_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_listings" ADD CONSTRAINT "marketplace_listings_approved_by_moderator_id_user_profiles_id_fk" FOREIGN KEY ("approved_by_moderator_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_reviews" ADD CONSTRAINT "marketplace_reviews_transaction_id_marketplace_transactions_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."marketplace_transactions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_reviews" ADD CONSTRAINT "marketplace_reviews_listing_id_marketplace_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."marketplace_listings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_reviews" ADD CONSTRAINT "marketplace_reviews_reviewer_user_id_user_profiles_id_fk" FOREIGN KEY ("reviewer_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_reviews" ADD CONSTRAINT "marketplace_reviews_reviewed_user_id_user_profiles_id_fk" FOREIGN KEY ("reviewed_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_transactions" ADD CONSTRAINT "marketplace_transactions_listing_id_marketplace_listings_id_fk" FOREIGN KEY ("listing_id") REFERENCES "public"."marketplace_listings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_transactions" ADD CONSTRAINT "marketplace_transactions_seller_user_id_user_profiles_id_fk" FOREIGN KEY ("seller_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "marketplace_transactions" ADD CONSTRAINT "marketplace_transactions_buyer_user_id_user_profiles_id_fk" FOREIGN KEY ("buyer_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_attachments" ADD CONSTRAINT "message_attachments_message_id_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_reads" ADD CONSTRAINT "message_reads_message_id_messages_id_fk" FOREIGN KEY ("message_id") REFERENCES "public"."messages"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_reads" ADD CONSTRAINT "message_reads_reader_id_user_profiles_id_fk" FOREIGN KEY ("reader_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_requests" ADD CONSTRAINT "message_requests_sender_id_user_profiles_id_fk" FOREIGN KEY ("sender_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_requests" ADD CONSTRAINT "message_requests_receiver_id_user_profiles_id_fk" FOREIGN KEY ("receiver_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "message_requests" ADD CONSTRAINT "message_requests_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_recipient_user_id_user_profiles_id_fk" FOREIGN KEY ("recipient_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_actor_user_id_user_profiles_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reports" ADD CONSTRAINT "reports_reporter_user_id_user_profiles_id_fk" FOREIGN KEY ("reporter_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reports" ADD CONSTRAINT "reports_reported_user_id_user_profiles_id_fk" FOREIGN KEY ("reported_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reports" ADD CONSTRAINT "reports_moderator_user_id_user_profiles_id_fk" FOREIGN KEY ("moderator_user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "search_history" ADD CONSTRAINT "search_history_user_id_user_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("id") ON DELETE no action ON UPDATE no action;