import express from "express";import pino from "pino";import {Pool} from "pg";import crypto from "node:crypto";import {SendSmsSchema,BatchSmsSchema,E164} from "./types.js";import {encodingFor,segmentCount,encodeSegment,encodeMultipartPart} from "./encoding.js";import {ensureSchema} from "./schema.js";import {SmsStore} from "./store.js";import {SmppTransport} from "./smsc.js";
const log=pino({name:"redom-sms"}),app=express();app.use(express.json({limit:"64kb"}));
const port=Number(process.env.PORT??8090),apiKey=process.env.SMS_API_KEY,db=process.env.DATABASE_URL;if(!apiKey)throw new Error("SMS_API_KEY is required");if(!db)throw new Error("DATABASE_URL is required");
const pool=new Pool({connectionString:db,max:20}),store=new SmsStore(pool),workerId=crypto.randomUUID();
const auth=(q:express.Request)=>q.header("authorization")?.replace(/^Bearer\s+/i,"")===apiKey;const guard=(q:express.Request,r:express.Response)=>{if(!auth(q)){r.status(401).json({error:{code:"unauthorized"}});return false}return true};
function bad(r:express.Response,message:string,code="invalid_request"){return r.status(400).json({error:{code,message}})}
async function createOne(i:any,key?:string){if(!i.skipOptOutCheck&&await store.isOptedOut(i.to))throw new Error("Recipient has opted out");const enc=encodingFor(i.text),n=segmentCount(i.text);let scheduled=i.scheduledAt?new Date(i.scheduledAt):undefined;if(scheduled&&Number.isNaN(scheduled.getTime()))throw new Error("Invalid scheduledAt");if(scheduled&&scheduled.getTime()<=Date.now())throw new Error("scheduledAt must be in the future");return store.create({to:i.to,from:i.from??process.env.SMS_DEFAULT_SOURCE??"ReDom",text:i.text,encoding:enc,segments:n,clientReference:i.clientReference,metadata:i.metadata,scheduledAt:scheduled,ttlSeconds:i.ttlSeconds,routeId:i.routeId},key)}
app.get("/health",async(_q,r)=>{try{await pool.query("SELECT 1");r.json({ok:true,service:"redom-sms",smscEnabled:process.env.SMSC_ENABLED==="true"})}catch{r.status(503).json({ok:false})}});
app.get("/v1/capabilities",(_q,r)=>r.json({service:"redom-sms",version:"1.0",transports:["direct-smpp"],features:["single-send","batch-send","scheduled-send","cancellation","delivery-receipts","inbound-sms","webhooks","idempotency","opt-out","ttl","multipart","gsm7","ucs2","route-selection","retry"],thirdPartySmsApiRequired:false,carrierConnectivityRequired:true}));
app.post("/v1/messages",async(q,r)=>{if(!guard(q,r))return;try{const i=SendSmsSchema.parse(q.body),x=await createOne(i,q.header("idempotency-key")??undefined);r.status(x.created?202:200).json({id:x.row.id,object:"sms",status:x.row.status,encoding:x.row.encoding,segments:x.row.segment_count})}catch(e){bad(r,e instanceof Error?e.message:"Invalid request")}});
app.post("/v1/messages/batch",async(q,r)=>{if(!guard(q,r))return;try{const b=BatchSmsSchema.parse(q.body),out=[];for(const [n,i] of b.messages.entries())out.push(await createOne(i,(q.header("idempotency-key")??"batch")+":"+n));r.status(202).json({data:out.map(x=>({id:x.row.id,status:x.row.status,segments:x.row.segment_count}))})}catch(e){bad(r,e instanceof Error?e.message:"Invalid request")}});
app.get("/v1/messages",async(q,r)=>{if(!guard(q,r))return;r.json({data:await store.list(Number(q.query.limit??50))})});
app.get("/v1/messages/:id",async(q,r)=>{if(!guard(q,r))return;const m=await store.get(q.params.id);if(!m)return r.status(404).json({error:{code:"not_found"}});r.json({data:m,segments:await store.segments(q.params.id)})});
app.post("/v1/messages/:id/cancel",async(q,r)=>{if(!guard(q,r))return;const m=await store.cancel(q.params.id);if(!m)return r.status(409).json({error:{code:"not_cancellable",message:"Only queued or scheduled messages can be cancelled"}});r.json({data:m})});
app.post("/v1/optouts",async(q,r)=>{if(!guard(q,r))return;const phone=String(q.body?.phoneNumber??"");if(!E164.test(phone))return bad(r,"phoneNumber must be E.164");await store.optOut(phone,String(q.body?.keyword??"MANUAL"));r.status(201).json({phoneNumber:phone,status:"opted_out"})});
app.delete("/v1/optouts/:phone",async(q,r)=>{if(!guard(q,r))return;await pool.query("DELETE FROM redom_sms_optouts WHERE phone_number=$1",[q.params.phone]);r.status(204).end()});
app.post("/v1/webhooks",async(q,r)=>{if(!guard(q,r))return;const url=String(q.body?.url??"");if(!/^https:\/\//i.test(url))return bad(r,"Webhook URL must use HTTPS");const events=Array.isArray(q.body?.events)?q.body.events:[];const id="wh_"+crypto.randomUUID().replaceAll("-",""),secret="whsec_"+crypto.randomBytes(24).toString("hex");await pool.query("INSERT INTO redom_sms_webhooks(id,url,secret,events) VALUES($1,$2,$3,$4)",[id,url,secret,events]);r.status(201).json({id,url,events,secret})});
app.get("/v1/webhooks",async(q,r)=>{if(!guard(q,r))return;const x=await pool.query("SELECT id,url,events,enabled,created_at FROM redom_sms_webhooks ORDER BY created_at DESC");r.json({data:x.rows})});
app.delete("/v1/webhooks/:id",async(q,r)=>{if(!guard(q,r))return;await pool.query("UPDATE redom_sms_webhooks SET enabled=false WHERE id=$1",[q.params.id]);r.status(204).end()});
app.post("/v1/inbound",async(q,r)=>{if(q.header("x-smsc-secret")!==process.env.SMSC_INBOUND_SECRET)return r.status(401).end();const from=String(q.body?.from??""),to=String(q.body?.to??"");if(!E164.test(from)||!E164.test(to))return bad(r,"from and to must be E.164");const text=String(q.body?.text??"");if(!text)return bad(r,"text is required");const id="sms_"+Date.now().toString(36)+"_"+crypto.randomUUID().slice(0,8);const row=(await pool.query(`INSERT INTO redom_sms_messages(id,direction,source,destination,body,encoding,segment_count,status,metadata) VALUES($1,'inbound',$2,$3,$4,$5,1,'delivered',$6) RETURNING *`,[id,from,to,text,encodingFor(text),q.body?.metadata??{}])).rows[0];const kw=text.trim().toUpperCase();if(["STOP","UNSUBSCRIBE","CANCEL","END","QUIT"].includes(kw)){await store.optOut(from,kw);await store.emit(id,"message.opted_out",{keyword:kw})}await store.emit(id,"message.received");r.status(202).json({id,status:"received"})});
const smsc=process.env.SMSC_ENABLED==="true"?new SmppTransport({host:process.env.SMSC_HOST??"",port:Number(process.env.SMSC_PORT??2775),systemId:process.env.SMSC_SYSTEM_ID??"",password:process.env.SMSC_PASSWORD??"",systemType:process.env.SMSC_SYSTEM_TYPE,sourceTon:Number(process.env.SMSC_SOURCE_TON??5),sourceNpi:Number(process.env.SMSC_SOURCE_NPI??0),destTon:Number(process.env.SMSC_DEST_TON??1),destNpi:Number(process.env.SMSC_DEST_NPI??1),enquireLinkMs:Number(process.env.SMSC_ENQUIRE_LINK_MS??30000),onDeliveryReceipt:x=>store.applyReceipt(x.providerMessageId,x.status==="delivered"?"delivered":x.status==="expired"?"expired":"failed",x.errorCode,x.raw),onInbound:async x=>{const id="sms_"+Date.now().toString(36)+"_"+crypto.randomUUID().slice(0,8);await pool.query(`INSERT INTO redom_sms_messages(id,direction,source,destination,body,encoding,segment_count,status,metadata) VALUES($1,'inbound',$2,$3,$4,$5,1,'delivered',$6)`,[id,x.from,x.to,x.text,encodingFor(x.text),x.metadata??{}]);await store.emit(id,"message.received")}}):null;
async function worker(){for(;;){let current:string|undefined;try{const m=await store.claim(workerId);if(!m){await new Promise(x=>setTimeout(x,Number(process.env.SMS_QUEUE_POLL_MS??1000)));continue}current=m.id;if(m.expires_at&&new Date(m.expires_at).getTime()<=Date.now()){await pool.query("UPDATE redom_sms_messages SET status='expired',updated_at=NOW() WHERE id=$1",[m.id]);await pool.query("DELETE FROM redom_sms_queue WHERE message_id=$1",[m.id]);await store.emit(m.id,"message.expired");continue}if(!smsc){await store.fail(m.id,"No direct SMSC connection configured");continue}const parts=split(m.body,m.encoding,m.segment_count),ref=crypto.randomInt(0,256);await store.createSegments(m.id,parts);for(let i=0;i<parts.length;i++){const textPart=partText(m.body,m.encoding,i),payload=m.segment_count>1?encodeMultipartPart(textPart,m.encoding,ref,m.segment_count,i+1):parts[i];const result=await smsc.submit({id:m.id,to:m.destination,from:m.source,text:m.body,encoding:m.encoding,segments:m.segment_count,status:"processing"},i,payload);await pool.query("UPDATE redom_sms_segments SET provider_message_id=$2,status='submitted',submitted_at=NOW() WHERE message_id=$1 AND segment_index=$3",[m.id,result.providerMessageId])}await store.submitted(m.id)}catch(e){log.error({err:e,messageId:current},"SMS worker error");if(current)await store.fail(current,e instanceof Error?e.message:"SMS delivery failed",new Date(Date.now()+Number(process.env.SMS_RETRY_BASE_MS??5000)))}}}
function split(t:string,e:"GSM7"|"UCS2",n:number){if(n===1)return[encodeSegment(t,e)];const chars=[...t],max=e==="GSM7"?153:67,out:string[]=[];if(e==="GSM7"){let s="",u=0;for(const c of chars){const v="^{}\\[~]|€".includes(c)?2:1;if(u+v>max){out.push(s);s="";u=0}s+=c;u+=v}if(s)out.push(s)}else for(let i=0;i<chars.length;i+=max)out.push(chars.slice(i,i+max).join(""));return out.map(x=>encodeSegment(x,e))}
function partText(t:string,e:"GSM7"|"UCS2",i:number){if(e==="UCS2")return[...t].slice(i*67,i*67+67).join("");let out:string[]=[],s="",u=0;for(const c of[...t]){const v="^{}\\[~]|€".includes(c)?2:1;if(u+v>153){out.push(s);s="";u=0}s+=c;u+=v}if(s)out.push(s);return out[i]}
async function webhookWorker(){for(;;){const x=await pool.query("SELECT e.*,w.url,w.secret FROM redom_sms_webhook_events e JOIN redom_sms_webhooks w ON w.id=e.webhook_id WHERE e.delivered_at IS NULL AND w.enabled ORDER BY e.id LIMIT 20");for(const e of x.rows){try{const body=JSON.stringify(e.payload),sig=crypto.createHmac("sha256",e.secret).update(body).digest("hex");const resp=await fetch(e.url,{method:"POST",headers:{"content-type":"application/json","x-redom-signature":sig},body});if(!resp.ok)throw new Error("HTTP "+resp.status);await pool.query("UPDATE redom_sms_webhook_events SET delivered_at=NOW() WHERE id=$1",[e.id])}catch(err){await pool.query("UPDATE redom_sms_webhook_events SET attempts=attempts+1,last_error=$2 WHERE id=$1",[e.id,String(err)])}}await new Promise(x=>setTimeout(x,1000))}}
await ensureSchema(pool);app.listen(port,()=>log.info({port},"ReDom SMS API listening"));void worker();void webhookWorker();