import net from "node:net";
import type { SmsMessage, SmsTransport, DeliveryReceipt } from "./types.js";
const C={BIND:0x00000009,BIND_RESP:0x80000009,SUBMIT:0x00000004,DELIVER:0x00000005,DELIVER_RESP:0x80000005,ENQUIRE:0x00000015,ENQUIRE_RESP:0x80000015};
const cstr=(s:string)=>Buffer.concat([Buffer.from(s),Buffer.from([0])]);
const pdu=(cmd:number,seq:number,body:Buffer)=>{const b=Buffer.alloc(16+body.length);b.writeUInt32BE(b.length);b.writeUInt32BE(cmd,4);b.writeUInt32BE(0,8);b.writeUInt32BE(seq,12);body.copy(b,16);return b};
const readC=(b:Buffer,o:number)=>{const e=b.indexOf(0,o);if(e<0)throw new Error("Malformed SMPP C-string");return{value:b.subarray(o,e).toString(),next:e+1}};
export class SmppTransport implements SmsTransport{
 private socket?:net.Socket;private seq=1;private pending=new Map<number,{resolve:(v:{status:number;body:Buffer})=>void,reject:(e:Error)=>void}>();private buffer=Buffer.alloc(0);private timer?:NodeJS.Timeout;
 constructor(private cfg:{host:string;port:number;systemId:string;password:string;systemType?:string;sourceTon:number;sourceNpi:number;destTon:number;destNpi:number;enquireLinkMs:number;onDeliveryReceipt?:(r:DeliveryReceipt)=>Promise<void>}){}
 private async connect(){if(this.socket&&!this.socket.destroyed)return;this.socket=await new Promise<net.Socket>((resolve,reject)=>{const s=net.createConnection({host:this.cfg.host,port:this.cfg.port});const fail=(e:Error)=>{s.destroy();reject(e)};s.once("error",fail);s.once("connect",()=>{s.removeListener("error",fail);resolve(s)})});this.socket.on("data",d=>this.onData(d)).on("close",()=>this.rejectAll(new Error("SMSC connection closed")));const body=Buffer.concat([cstr(this.cfg.systemId),cstr(this.cfg.password),cstr(this.cfg.systemType??""),Buffer.from([0x34,0,0]),cstr("")]);const r=await this.request(C.BIND,body);if(r.status!==0)throw new Error(`SMSC bind failed status=0x${r.status.toString(16)}`);this.timer=setInterval(()=>void this.request(C.ENQUIRE,Buffer.alloc(0)).catch(()=>{}),this.cfg.enquireLinkMs)}
 private rejectAll(e:Error){for(const p of this.pending.values())p.reject(e);this.pending.clear()}
 private onData(d:Buffer){this.buffer=Buffer.concat([this.buffer,d]);while(this.buffer.length>=4){const len=this.buffer.readUInt32BE(0);if(len<16||this.buffer.length<len)break;const b=this.buffer.subarray(0,len);this.buffer=this.buffer.subarray(len);const cmd=b.readUInt32BE(4),status=b.readUInt32BE(8),seq=b.readUInt32BE(12),body=b.subarray(16);if(cmd===C.DELIVER){void this.handleDeliver(body);this.write(pdu(C.DELIVER_RESP,seq,Buffer.alloc(0)));continue}const p=this.pending.get(seq);if(p){this.pending.delete(seq);p.resolve({status,body})}}}
 private write(b:Buffer){if(!this.socket||this.socket.destroyed)throw new Error("SMSC disconnected");this.socket.write(b)}
 private request(cmd:number,body:Buffer):Promise<{status:number;body:Buffer}>{const seq=this.seq++;return new Promise((resolve,reject)=>{this.pending.set(seq,{resolve,reject});try{this.write(pdu(cmd,seq,body))}catch(e){this.pending.delete(seq);reject(e as Error)}setTimeout(()=>{const p=this.pending.get(seq);if(p){this.pending.delete(seq);p.reject(new Error("SMPP request timeout"))}},15000)})}
 private async handleDeliver(body:Buffer){let p=readC(body,0);p=readC(body,p.next);p=readC(body,p.next);p=readC(body,p.next);const dataCoding=body[p.next+5]??0,smLen=body[p.next+6]??0,text=body.subarray(p.next+7,p.next+7+smLen).toString(dataCoding===8?"utf16le":"utf8"),m=text.match(/id[:=](\S+).*stat[:=](DELIVRD|UNDELIV|EXPIRED|REJECTD)/i);if(m&&this.cfg.onDeliveryReceipt)await this.cfg.onDeliveryReceipt({providerMessageId:m[1],status:m[2].toUpperCase()==="DELIVRD"?"delivered":m[2].toUpperCase()==="EXPIRED"?"expired":m[2].toUpperCase()==="UNDELIV"?"failed":"rejected",raw:text})}
 async submit(message:SmsMessage,_segmentIndex:number,payload:Buffer){await this.connect();const esm=message.segments>1?0x40:0,coding=message.encoding==="UCS2"?8:0;const body=Buffer.concat([cstr(""),Buffer.from([this.cfg.sourceTon,this.cfg.sourceNpi]),cstr(message.from),Buffer.from([this.cfg.destTon,this.cfg.destNpi]),cstr(message.to),Buffer.from([esm,0,0]),cstr(""),cstr(""),Buffer.from([1,0,coding,payload.length]),payload]);const r=await this.request(C.SUBMIT,body);if(r.status!==0)throw new Error(`SMSC submit_sm failed status=0x${r.status.toString(16)}`);return{providerMessageId:readC(r.body,0).value}}
 async close(){if(this.timer)clearInterval(this.timer);this.socket?.end();this.socket=undefined}
}