import { createHash, randomInt, randomUUID } from "node:crypto";
import { pool } from "../../database/db";
import { env } from "../../config/env";

export const REFUND_MINIMUM_REVIEW_MINUTES = 10;
export const REFUND_FEATURE_ENABLED = env.refunds.enabled;

export type RefundStatus =
  | "transaction_required"
  | "account_profile_required"
  | "verification_code_sent"
  | "awaiting_verification"
  | "account_under_review"
  | "refund_review_pending"
  | "refund_reviewing"
  | "approved"
  | "denied"
  | "refund_processing"
  | "refunded"
  | "closed";

export function hashRefundCode(code: string): string {
  return createHash("sha256").update(code).digest("hex");
}

export function generateRefundCode(): string {
  return randomInt(0, 1_000_000).toString().padStart(6, "0");
}

export function minimumReviewAvailableAt(from = new Date()): Date {
  return new Date(from.getTime() + REFUND_MINIMUM_REVIEW_MINUTES * 60_000);
}

export function maskRefundTarget(value: string | null | undefined): string | null {
  if (!value) return null;
  const normalized = value.replace(/\s+/g, "");
  if (normalized.length <= 4) return "••••";
  return `${normalized.slice(0, 2)}••••••${normalized.slice(-2)}`;
}

export async function createDormantRefundRequest(input: {
  caseId: string;
  userId: string;
  productKey?: string | null;
  countryCode?: string | null;
}): Promise<{ id: string; status: RefundStatus; reviewAvailableAt: Date }> {
  const availableAt = minimumReviewAvailableAt();
  const result = await pool.query(
    `INSERT INTO refund_requests (id, case_id, user_id, product_key, country_code, status, review_available_at)
     VALUES ($1, $2, $3, $4, $5, 'transaction_required', $6)
     RETURNING id, status, review_available_at`,
    [randomUUID(), input.caseId, input.userId, input.productKey ?? null, input.countryCode ?? null, availableAt],
  );
  return {
    id: String(result.rows[0].id),
    status: result.rows[0].status as RefundStatus,
    reviewAvailableAt: new Date(String(result.rows[0].review_available_at)),
  };
}

export function buildRefundCompletionEmail(input: {
  transactionNumber: string;
  amount: string;
  currency: string;
  targetMasked: string;
  time: string;
  country: string;
  expectedBy: string;
  caseNumber: string;
}): { subject: string; text: string } {
  return {
    subject: `Refund completed — Transaction ${input.transactionNumber}`,
    text: `ReDom Refund Confirmation\n\nYour refund has been completed.\n\nTransaction: ${input.transactionNumber}\nAmount: ${input.amount} ${input.currency}\nRefund sent to: ${input.targetMasked}\nTime: ${input.time}\nCountry: ${input.country}\nRefund expected to arrive by: ${input.expectedBy}\n\nSupport Case: ${input.caseNumber}\n\nThis refund notification is generated by ReDom Refund Services.`,
  };
}

export function buildRefundSupportClosureReply(input: { transactionNumber: string; caseNumber: string }): string {
  return `Your refund for transaction ${input.transactionNumber} has been completed.\n\nThis refund support case is now closed. For security, case number ${input.caseNumber} has been invalidated and cannot be reused.`;
}
