import { createHash, randomInt, randomUUID } from "node:crypto";
import axios from "axios";
import { Resend } from "resend";
import { createSupportCase, addSupportMessage, permanentlyCloseSupportCase, sendSupportEmail } from "../support/support.service";
import { pool } from "../../database/db";
import { env } from "../../config/env";
import { twilioSmsProvider } from "../../lib/providers/sms/twilio-sms-provider";

export const REFUND_MINIMUM_REVIEW_MINUTES = 10;
export const REFUND_FEATURE_ENABLED = true;
export const STARS_REFUND_WINDOW_MINUTES = 10;
const resend = new Resend(env.email.resend.apiKey);
const REFUND_SECURITY_WARNING = "Security warning: ReDom will never ask for your password, payment PIN, CVV, full card number, bank login, or a one-time verification code outside the official refund verification flow. Never forward or share a verification code with anyone.";

export type RefundStatus =
  | "transaction_required"
  | "account_profile_required"
  | "verification_code_sent"
  | "awaiting_verification"
  | "account_under_review"
  | "refund_review_pending"
  | "refund_reviewing"
  | "approved"
  | "denied"
  | "refund_processing"
  | "refunded"
  | "closed";

export function hashRefundCode(code: string): string {
  return createHash("sha256").update(code).digest("hex");
}

export function generateRefundCode(): string {
  return randomInt(0, 1_000_000).toString().padStart(6, "0");
}

export function minimumReviewAvailableAt(from = new Date()): Date {
  return new Date(from.getTime() + REFUND_MINIMUM_REVIEW_MINUTES * 60_000);
}

export function maskRefundTarget(value: string | null | undefined): string | null {
  if (!value) return null;
  const normalized = value.replace(/\s+/g, "");
  if (normalized.includes("•")) return normalized;
  if (normalized.length <= 4) return "••••";
  if (normalized.length >= 10) return normalized.slice(0, 3)+"••••••••"+normalized.slice(-1);
  return normalized.slice(0, 2)+"••••••"+normalized.slice(-2);
}

export async function createDormantRefundRequest(input: {
  caseId: string;
  userId: string;
  productKey?: string | null;
  countryCode?: string | null;
}): Promise<{ id: string; status: RefundStatus; reviewAvailableAt: Date }> {
  const availableAt = minimumReviewAvailableAt();
  const result = await pool.query(
    `INSERT INTO refund_requests (id, case_id, user_id, product_key, country_code, status, review_available_at)
     VALUES ($1, $2, $3, $4, $5, 'transaction_required', $6)
     RETURNING id, status, review_available_at`,
    [randomUUID(), input.caseId, input.userId, input.productKey ?? null, input.countryCode ?? null, availableAt],
  );
  return {
    id: String(result.rows[0].id),
    status: result.rows[0].status as RefundStatus,
    reviewAvailableAt: new Date(String(result.rows[0].review_available_at)),
  };
}

export function buildRefundCompletionEmail(input: {
  transactionNumber: string;
  amount: string;
  currency: string;
  targetMasked: string;
  time: string;
  country: string;
  expectedBy: string;
  caseNumber: string;
}): { subject: string; text: string } {
  return {
    subject: `Refund completed — Transaction ${input.transactionNumber}`,
    text: `ReDom Refund Confirmation\n\nYour refund has been completed.\n\nTransaction: ${input.transactionNumber}\nAmount: ${input.amount} ${input.currency}\nRefund sent to: ${input.targetMasked}\nTime: ${input.time}\nCountry: ${input.country}\nRefund expected to arrive by: ${input.expectedBy}\n\nSupport Case: ${input.caseNumber}\n\nThis refund notification is generated by ReDom Refund Services.`,
  };
}

export function buildRefundSupportClosureReply(input: { transactionNumber: string; caseNumber: string }): string {
  return `Your refund for transaction ${input.transactionNumber} has been completed.\n\nThis refund support case is now closed. For security, case number ${input.caseNumber} has been invalidated and cannot be reused.`;
}


export type StarsRefundResult = { success:boolean; status:string; code?:string; reason?:string; transactionNumber?:string; caseNumber?:string; refundId?:string|null; refundStatus?:string|null; target?:string|null };
function normalizeRefundTransactionNumber(value:string):string {
 const raw=value.trim().toUpperCase().replace(/\s+/g,"");
 if(/^\d{13}$/.test(raw)) return "R-"+raw;
 if(/^R\d{13}$/.test(raw)) return "R-"+raw.slice(1);
 return raw;
}
function starsRefundCutoff(paidAt:Date):Date { return new Date(paidAt.getTime()+STARS_REFUND_WINDOW_MINUTES*60_000); }
function nonRefundablePayload(transactionNumber:string,caseNumber:string,cutoff:Date):StarsRefundResult { return {success:false,status:"non_refundable",code:"STARS_NON_REFUNDABLE",reason:"ReDom Stars are non-refundable 10 minutes after the purchase is completed.",transactionNumber,caseNumber}; }
function refundTargetFromMetadata(metadata:any):{type:string;masked:string|null} { const d=metadata?.paymentDetails??{}; const channel=String(d.channel??"").toLowerCase(); if(channel.includes("card")) return {type:"card",masked:d.last4?"•••• "+String(d.last4).slice(-4):"original card"}; return {type:channel.includes("bank")||channel.includes("transfer")?"bank_account":"original_payment_rail",masked:d.account?String(d.account):"original payment account"}; }

function refundTargetDisplay(metadata:any, fallbackMasked:string|null):string {
  const d=metadata?.paymentDetails??{};
  const channel=String(d.channel??"").toLowerCase();
  const brand=d.brand?String(d.brand):d.type?String(d.type):channel.includes("card")?"Card":channel.includes("bank")||channel.includes("transfer")?"Bank Account":"Original Payment";
  const fullAccount=d.account??d.accountNumber??d.refundAccountNumber;
  const masked=fullAccount ? maskRefundTarget(String(fullAccount)) : (fallbackMasked ?? "original payment rail");
  if(channel.includes("card")) return brand.split(/\s+/)[0]+" Card "+masked;
  if(channel.includes("bank")||channel.includes("transfer")) return "Bank Account "+masked;
  return brand+" "+masked;
}

async function sendRefundSupportStatus(input:{email:string;caseNumber:string;transactionNumber:string;status:string;reason:string;target?:string|null;nextStep?:string}):Promise<void> {
  const targetLine=input.target ? "\nRefund destination: "+input.target : "";
  const nextLine=input.nextStep ? "\n\nNext step:\n"+input.nextStep : "";
  const body="Refund Support Update\n\nTransaction: "+input.transactionNumber+"\nStatus: "+input.status+"\nReason: "+input.reason+targetLine+nextLine+"\n\nSupport Case: "+input.caseNumber+"\n\n"+REFUND_SECURITY_WARNING;
  await sendSupportEmail(input.email, "Re: Refund Support Case "+input.caseNumber+" — "+input.status, body);
}

async function sendRefundTerminalEmail(input:{email:string;caseNumber:string;transactionNumber:string;status:string;reason:string;target:string;amount:string;currency:string;refundId?:string|null}):Promise<void> {
  const { error } = await resend.emails.send({
    from: env.refunds.from,
    to: [input.email],
    subject: "Refund "+input.status+" — "+input.transactionNumber,
    text: "ReDom Refund Services\n\nTransaction: "+input.transactionNumber+"\nStatus: "+input.status+"\nReason: "+input.reason+"\nAmount: "+input.amount+" "+input.currency+"\nRefund destination: "+input.target+"\n"+(input.refundId ? "Refund ID: "+input.refundId+"\n" : "")+"\nSupport Case: "+input.caseNumber+"\n\nThis refund transaction has been permanently recorded. The ReDom Transaction ID cannot be used to submit another refund request.\n\n"+REFUND_SECURITY_WARNING,
  });
  if (error) throw new Error("Refund status email could not be sent: "+error.message);
}

async function closeAndInvalidateRefund(input:{refundRequestId:string;caseId:string;transactionNumber:string;userId:string;caseNumber:string;outcomeStatus:string;reason:string;refundId?:string|null}):Promise<void> {
  await pool.query("UPDATE refund_requests SET status=$1, decision_reason=$2, case_invalidated_at=COALESCE(case_invalidated_at, now()), updated_at=now() WHERE id=$3",[input.outcomeStatus,input.reason,input.refundRequestId]);
  await pool.query("UPDATE refund_transaction_locks SET outcome_status=$1, outcome_reason=$2, refund_id=COALESCE($3, refund_id), case_id=$4, case_number=$5, invalidated_at=COALESCE(invalidated_at, now()), updated_at=now() WHERE transaction_number=$6 AND user_id=$7",[input.outcomeStatus,input.reason,input.refundId??null,input.caseId,input.caseNumber,input.transactionNumber,input.userId]);
  await permanentlyCloseSupportCase(input.caseId);
}

async function sendRefundVerificationEmail(email:string,code:string,transactionNumber:string):Promise<void> { const r=await resend.emails.send({from:env.refunds.from,to:[email],subject:"ReDom Refund Verification — "+transactionNumber,text:"Your ReDom Stars refund verification code is "+code+". It expires in 10 minutes. If you did not request this refund, do not use the code and contact ReDom Support.\n\n"+REFUND_SECURITY_WARNING}); if(r.error) throw new Error(r.error.message); }

async function issueRefundSecurityChallenge(refundRequestId:string,userId:string,email:string,phone:string|null,transactionNumber:string):Promise<{channel:string;target:string}> {
  await pool.query("UPDATE refund_verification_challenges SET consumed_at=COALESCE(consumed_at,now()) WHERE refund_request_id=$1 AND consumed_at IS NULL",[refundRequestId]);
  const expiresAt=new Date(Date.now()+10*60_000);
  if(phone) {
    const code=randomInt(10_000_000,100_000_000).toString();
    try {
      await twilioSmsProvider.sendOtp({channel:"sms",to:phone,code,expiresAt});
      await pool.query("INSERT INTO refund_verification_challenges(refund_request_id,user_id,channel_type,target_masked,code_hash,expires_at,attempt_count,max_attempts) VALUES($1,$2,'sms',$3,$4,$5,0,3)",[refundRequestId,userId,maskRefundTarget(phone),hashRefundCode(code),expiresAt]);
      return {channel:"sms",target:maskRefundTarget(phone)??"phone"};
    } catch {}
  }
  const fallback=randomInt(100_000,1_000_000).toString();
  await pool.query("INSERT INTO refund_verification_challenges(refund_request_id,user_id,channel_type,target_masked,code_hash,expires_at,attempt_count,max_attempts) VALUES($1,$2,'email',$3,$4,$5,0,3)",[refundRequestId,userId,email,hashRefundCode(fallback),expiresAt]);
  await sendRefundVerificationEmail(email,fallback,transactionNumber);
  return {channel:"email",target:email};
}

export async function issueStarsRefundSecurityChallenge(input:{userId:string;transactionNumber:string}):Promise<StarsRefundResult> {
  const normalized=normalizeRefundTransactionNumber(input.transactionNumber); const q=await pool.query("SELECT rr.id,rr.case_id,rr.status,u.email,u.phone_number,sc.case_number FROM refund_requests rr JOIN users u ON u.id=rr.user_id JOIN support_cases sc ON sc.id=rr.case_id WHERE rr.transaction_number=$1 AND rr.user_id=$2 ORDER BY rr.created_at DESC LIMIT 1",[normalized,input.userId]);
  if(!q.rows[0]) return {success:false,status:"transaction_required",code:"REFUND_REQUEST_NOT_FOUND",reason:"Refund request not found.",transactionNumber:input.transactionNumber};
  const row=q.rows[0];
  const challenge=await issueRefundSecurityChallenge(String(row.id),input.userId,String(row.email),row.phone_number?String(row.phone_number):null,normalized);
  await pool.query("UPDATE refund_requests SET status='verification_code_sent',verification_sent_at=now(),updated_at=now() WHERE id=$1",[row.id]);
  return {success:true,status:"verification_code_sent",transactionNumber:normalized,caseNumber:String(row.case_number),target:challenge.target};
}

export async function startStarsRefund(input:{userId:string;transactionNumber:string;caseId?:string;caseNumber?:string}):Promise<StarsRefundResult> {
 const transactionNumber=normalizeRefundTransactionNumber(input.transactionNumber);
 const tx=await pool.query("SELECT pt.*,u.email,u.phone_number,up.id AS profile_id FROM payment_transactions pt JOIN users u ON u.id=pt.user_id LEFT JOIN user_profiles up ON up.user_id=pt.user_id WHERE pt.redom_transaction_id=$1 AND pt.user_id=$2 LIMIT 1",[transactionNumber,input.userId]);
 if(!tx.rows[0]) return {success:false,status:"transaction_not_found",code:"TRANSACTION_NOT_FOUND",reason:"The ReDom Transaction ID could not be found for this account.",transactionNumber};
 const row=tx.rows[0];
 if(String(row.purpose)!=="stars_purchase") return {success:false,status:"not_refundable_product",code:"NOT_STARS_PURCHASE",reason:"Only ReDom Stars purchases use this refund policy.",transactionNumber};
 if(String(row.status)!=="paid") return {success:false,status:"not_refundable_status",code:"TRANSACTION_NOT_PAID",reason:"This transaction is not a completed Stars purchase.",transactionNumber};
 const paidAt=row.paid_at?new Date(String(row.paid_at)):null; if(!paidAt) return {success:false,status:"not_refundable_status",code:"PAID_AT_MISSING",reason:"The completed payment has no refund timestamp.",transactionNumber};
 const existingLock=await pool.query("SELECT outcome_status,case_number FROM refund_transaction_locks WHERE transaction_number=$1 LIMIT 1",[transactionNumber]);
 if(existingLock.rows[0]) return {success:false,status:"refund_already_requested",code:"REFUND_TRANSACTION_LOCKED",reason:"A refund request has already been recorded for this ReDom Transaction ID. The transaction cannot be submitted for refund a second time.",transactionNumber,caseNumber:existingLock.rows[0].case_number??undefined};
 const lock=await pool.query("INSERT INTO refund_transaction_locks(transaction_number,user_id,outcome_status) VALUES($1,$2,'requested') ON CONFLICT(transaction_number) DO NOTHING RETURNING transaction_number",[transactionNumber,input.userId]);
 if(!lock.rows[0]) return {success:false,status:"refund_already_requested",code:"REFUND_TRANSACTION_LOCKED",reason:"A refund request has already been recorded for this ReDom Transaction ID. The transaction cannot be submitted for refund a second time.",transactionNumber};
 let caseRecord:any;
 if(input.caseId && input.caseNumber) {
   caseRecord={id:input.caseId,caseNumber:input.caseNumber};
   await pool.query("UPDATE refund_transaction_locks SET case_id=$1,case_number=$2,updated_at=now() WHERE transaction_number=$3",[caseRecord.id,caseRecord.caseNumber,transactionNumber]);
 } else {
   try { caseRecord=await createSupportCase({userId:input.userId,subject:"ReDom Stars refund "+transactionNumber,category:"refund_payment"}); await pool.query("UPDATE refund_transaction_locks SET case_id=$1,case_number=$2,updated_at=now() WHERE transaction_number=$3",[caseRecord.id,caseRecord.caseNumber,transactionNumber]); } catch(error) { await pool.query("DELETE FROM refund_transaction_locks WHERE transaction_number=$1 AND user_id=$2",[transactionNumber,input.userId]); throw error; }
 }
 const cutoff=starsRefundCutoff(paidAt); const eligible=Date.now()<cutoff.getTime(); const target=refundTargetFromMetadata(row.metadata);
 await pool.query("INSERT INTO refund_requests(case_id,user_id,product_key,transaction_number,account_profile_id,country_code,currency,amount,status,review_available_at,decision,decision_reason,refund_target_type,refund_target_masked) VALUES($1,$2,'stars_purchase',$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)",[caseRecord.id,input.userId,transactionNumber,row.profile_id??null,row.country_code??null,row.currency,Number(row.amount_minor??0)/100,eligible?"account_profile_required":"non_refundable",cutoff,eligible?null:"denied",eligible?null:"Stars are rigidly non-refundable after 10 minutes.",target.type,target.masked]);
 if(!eligible) {
  const reason="ReDom Stars are rigidly non-refundable after 10 minutes.";
  await addSupportMessage({caseId:caseRecord.id,senderType:"system",body:"Refund denied: "+reason+" Status: non_refundable. Cutoff: "+cutoff.toISOString()+"."});
  const request=await pool.query("SELECT id FROM refund_requests WHERE transaction_number=$1 ORDER BY created_at DESC LIMIT 1",[transactionNumber]);
  await closeAndInvalidateRefund({refundRequestId:String(request.rows[0].id),caseId:caseRecord.id,transactionNumber,userId:input.userId,caseNumber:caseRecord.caseNumber,outcomeStatus:"non_refundable",reason});
  return nonRefundablePayload(transactionNumber,caseRecord.caseNumber,cutoff);
 }
 const challenge=await issueRefundSecurityChallenge(String((await pool.query("SELECT id FROM refund_requests WHERE transaction_number=$1 ORDER BY created_at DESC LIMIT 1",[transactionNumber])).rows[0].id),input.userId,String(row.email),row.phone_number?String(row.phone_number):null,transactionNumber);
 await pool.query("UPDATE refund_requests SET status='verification_code_sent',verification_sent_at=now(),updated_at=now() WHERE transaction_number=$1",[transactionNumber]);
 const nextStep=challenge.channel==="sms" ? "Enter the 8-digit security code sent to your verified ReDom phone ("+challenge.target+")." : "Enter the 6-digit fallback security code sent to your ReDom email.";
 await addSupportMessage({caseId:caseRecord.id,senderType:"ai",senderEmail:env.email.supportFrom,body:"Refund request received and the transaction has been authenticated to your ReDom account.\n\nNext step: "+nextStep+"\n\nSupport Case: "+caseRecord.caseNumber+"\n\n"+REFUND_SECURITY_WARNING+"\n\n"+REFUND_SECURITY_WARNING});
 await sendRefundSupportStatus({email:String(row.email??""),caseNumber:caseRecord.caseNumber,transactionNumber,status:"Refund request under review — security verification required",reason:"The transaction was matched to your ReDom account.",target:target.masked,nextStep}).catch(()=>undefined);
 return {success:true,status:"verification_code_sent",transactionNumber,caseNumber:caseRecord.caseNumber,target:challenge.target};
}

export async function verifyStarsRefundAccountProfile(input:{userId:string;transactionNumber:string;accountProfileId:string}):Promise<StarsRefundResult> {
  // Account Profile is no longer required. Preserve the endpoint for older clients but use the authenticated account security flow.
  return issueStarsRefundSecurityChallenge({userId:input.userId,transactionNumber:input.transactionNumber});
}

export async function completeStarsRefund(input:{userId:string;transactionNumber:string;code:string}):Promise<StarsRefundResult> {
 const transactionNumber=normalizeRefundTransactionNumber(input.transactionNumber); const client=await pool.connect();
 try {
  await client.query("BEGIN");
  const q=await client.query("SELECT rr.*,sc.case_number,pt.id AS payment_id,pt.reference,pt.paid_at,pt.status AS payment_status,pt.amount_minor,pt.currency,pt.metadata,u.email,u.phone_number FROM refund_requests rr JOIN support_cases sc ON sc.id=rr.case_id JOIN payment_transactions pt ON pt.redom_transaction_id=rr.transaction_number JOIN users u ON u.id=pt.user_id WHERE rr.transaction_number=$1 AND rr.user_id=$2 ORDER BY rr.created_at DESC LIMIT 1 FOR UPDATE",[transactionNumber,input.userId]);
  if(!q.rows[0]) throw new Error("Refund request not found.");
  const row=q.rows[0]; const cutoff=starsRefundCutoff(new Date(String(row.paid_at)));
  if(Date.now()>=cutoff.getTime()) {
   const reason="ReDom Stars are rigidly non-refundable after 10 minutes.";
   await client.query("UPDATE refund_requests SET status='non_refundable',decision='denied',decision_reason=$1,case_invalidated_at=COALESCE(case_invalidated_at,now()),updated_at=now() WHERE id=$2",[reason,row.id]);
   await client.query("UPDATE refund_transaction_locks SET outcome_status='non_refundable',outcome_reason=$1,invalidated_at=COALESCE(invalidated_at,now()),updated_at=now() WHERE transaction_number=$2",[reason,transactionNumber]);
   await client.query("COMMIT");
   await addSupportMessage({caseId:String(row.case_id),senderType:"system",body:"Refund denied: "+reason+"\n\n"+REFUND_SECURITY_WARNING});
   await sendRefundSupportStatus({email:String(row.email??""),caseNumber:String(row.case_number??""),transactionNumber,status:"Non-refundable",reason,target:refundTargetDisplay(typeof row.metadata==="string"?JSON.parse(row.metadata):row.metadata??{},row.refund_target_masked)}).catch(()=>undefined);
   await permanentlyCloseSupportCase(String(row.case_id));
   return nonRefundablePayload(transactionNumber,String(row.case_number??""),cutoff);
  }

  const ch=await client.query("SELECT id,channel_type,target_masked,code_hash,expires_at,consumed_at,attempt_count,max_attempts FROM refund_verification_challenges WHERE refund_request_id=$1 ORDER BY created_at DESC LIMIT 1",[row.id]);
  if(!ch.rows[0]||ch.rows[0].consumed_at||new Date(String(ch.rows[0].expires_at)).getTime()<Date.now()) throw new Error("Refund verification code expired. Request a new code.");
  const attemptsResult=await client.query("SELECT COALESCE(SUM(attempt_count),0) AS failed_attempts FROM refund_verification_challenges WHERE refund_request_id=$1",[row.id]);
  const attempts=Number(attemptsResult.rows[0]?.failed_attempts??0);
  if(hashRefundCode(input.code)!==String(ch.rows[0].code_hash)) {
   const failedAttempt=attempts+1;
   await client.query("UPDATE refund_verification_challenges SET attempt_count=$1,failed_at=now(),consumed_at=now() WHERE id=$2",[failedAttempt,ch.rows[0].id]);

   if(failedAttempt>=3) {
    const reason="Refund security verification failed after 3 incorrect codes. The refund case has been permanently closed for security.";
    await client.query("UPDATE refund_requests SET status='refund_verification_failed',decision='denied',decision_reason=$1,case_invalidated_at=COALESCE(case_invalidated_at,now()),updated_at=now() WHERE id=$2",[reason,row.id]);
    await client.query("UPDATE refund_transaction_locks SET outcome_status='refund_verification_failed',outcome_reason=$1,invalidated_at=COALESCE(invalidated_at,now()),updated_at=now() WHERE transaction_number=$2",[reason,transactionNumber]);
    await client.query("COMMIT");
    const metadata=typeof row.metadata==="string"?JSON.parse(row.metadata):row.metadata??{};
    const target=refundTargetDisplay(metadata,row.refund_target_masked);
    await sendRefundTerminalEmail({email:String(row.email),caseNumber:String(row.case_number),transactionNumber,status:"Request Closed — Security Verification Failed",reason,target,amount:String(row.amount_minor??0),currency:String(row.currency??"")}).catch(()=>undefined);
    await addSupportMessage({caseId:String(row.case_id),senderType:"ai",senderEmail:env.email.supportFrom,body:"Your refund request has been processed. Security verification failed after 3 incorrect codes, so the refund case is permanently closed and cannot be reused.\n\n"+REFUND_SECURITY_WARNING});
    await permanentlyCloseSupportCase(String(row.case_id));
    return {success:false,status:"refund_verification_failed",code:"REFUND_VERIFICATION_LOCKED",reason,transactionNumber,caseNumber:String(row.case_number)};
   }

   // The incorrect code is consumed immediately. A fresh code is generated for every remaining attempt.
   const nextExpiresAt=new Date(Date.now()+10*60_000);
   const channel=String(ch.rows[0].channel_type);
   const nextCode=channel==="sms" ? randomInt(10_000_000,100_000_000).toString() : randomInt(100_000,1_000_000).toString();
   const nextTarget=channel==="sms" ? maskRefundTarget(String(row.phone_number??"")) : String(row.email);
   await client.query("COMMIT");

   if(channel==="sms") {
    try {
     await twilioSmsProvider.sendOtp({channel:"sms",to:String(row.phone_number??""),code:nextCode,expiresAt:nextExpiresAt});
     await pool.query("INSERT INTO refund_verification_challenges(refund_request_id,user_id,channel_type,target_masked,code_hash,expires_at,attempt_count,max_attempts) VALUES($1,$2,'sms',$3,$4,$5,0,3)",[row.id,row.user_id,nextTarget,hashRefundCode(nextCode),nextExpiresAt]);
     await pool.query("UPDATE refund_requests SET status='verification_code_sent',verification_sent_at=now(),updated_at=now() WHERE id=$1",[row.id]);
     await addSupportMessage({caseId:String(row.case_id),senderType:"ai",senderEmail:env.email.supportFrom,body:"The previous verification code is no longer valid. A new 8-digit security code has been sent to your verified ReDom phone ("+nextTarget+"). This is failed attempt "+failedAttempt+" of 3. Enter the new code.\n\n"+REFUND_SECURITY_WARNING});
     return {success:false,status:"verification_code_sent",code:"NEW_CODE_REQUIRED",reason:"The previous code was incorrect and has been invalidated. A new 8-digit code was sent.",transactionNumber,caseNumber:String(row.case_number),target:nextTarget};
    } catch {
     const fallback=randomInt(100_000,1_000_000).toString();
     const fallbackExpiresAt=new Date(Date.now()+10*60_000);
     await pool.query("INSERT INTO refund_verification_challenges(refund_request_id,user_id,channel_type,target_masked,code_hash,expires_at,attempt_count,max_attempts) VALUES($1,$2,'email',$3,$4,$5,0,3)",[row.id,row.user_id,String(row.email),hashRefundCode(fallback),fallbackExpiresAt]);
     await sendRefundVerificationEmail(String(row.email),fallback,transactionNumber);
     await pool.query("UPDATE refund_requests SET status='verification_code_sent',verification_sent_at=now(),updated_at=now() WHERE id=$1",[row.id]);
     await addSupportMessage({caseId:String(row.case_id),senderType:"ai",senderEmail:env.email.supportFrom,body:"The previous phone code is no longer valid. SMS delivery failed, so a new 6-digit fallback code has been sent to your ReDom email.\n\n"+REFUND_SECURITY_WARNING});
     return {success:false,status:"verification_code_sent",code:"NEW_EMAIL_CODE_REQUIRED",reason:"The previous code was incorrect. A new 6-digit email fallback code was sent.",transactionNumber,caseNumber:String(row.case_number),target:String(row.email)};
    }
   }

   await pool.query("INSERT INTO refund_verification_challenges(refund_request_id,user_id,channel_type,target_masked,code_hash,expires_at,attempt_count,max_attempts) VALUES($1,$2,'email',$3,$4,$5,0,3)",[row.id,row.user_id,String(row.email),hashRefundCode(nextCode),nextExpiresAt]);
   await sendRefundVerificationEmail(String(row.email),nextCode,transactionNumber);
   await pool.query("UPDATE refund_requests SET status='verification_code_sent',verification_sent_at=now(),updated_at=now() WHERE id=$1",[row.id]);
   await addSupportMessage({caseId:String(row.case_id),senderType:"ai",senderEmail:env.email.supportFrom,body:"The previous verification code is no longer valid. A new 6-digit security code has been sent to your ReDom email. This is failed attempt "+failedAttempt+" of 3. Enter the new code.\n\n"+REFUND_SECURITY_WARNING});
   return {success:false,status:"verification_code_sent",code:"NEW_CODE_REQUIRED",reason:"The previous code was incorrect and has been invalidated. A new 6-digit code was sent.",transactionNumber,caseNumber:String(row.case_number),target:String(row.email)};
  }

  await client.query("UPDATE refund_verification_challenges SET consumed_at=now() WHERE id=$1",[ch.rows[0].id]);
  if(String(row.payment_status)!=="paid") throw new Error("The Stars payment is not currently refundable.");
  const existing=await client.query("SELECT refund_status FROM payment_transactions WHERE id=$1 FOR UPDATE",[row.payment_id]);
  if(["pending","processing","needs-attention","processed","initiating"].includes(String(existing.rows[0]?.refund_status??""))) throw new Error("A refund has already been initiated for this transaction.");
  const metadata=typeof row.metadata==="string"?JSON.parse(row.metadata):row.metadata??{}; const target=refundTargetFromMetadata(metadata);
  const reviewAt=new Date(Date.now()+12*60*60*1000);
  await client.query("UPDATE refund_requests SET status='account_under_review',decision=NULL,decision_reason='Security verification completed. Automated product eligibility review scheduled.',verified_at=now(),review_started_at=now(),review_available_at=$1,updated_at=now() WHERE id=$2",[reviewAt,row.id]);
  await client.query("INSERT INTO refund_reviews(refund_request_id,eligibility_result,transaction_result,policy_version,started_at) VALUES($1,'pending','verified','stars-refund-v2',now())",[row.id]);
  await client.query("UPDATE refund_transaction_locks SET outcome_status='account_under_review',outcome_reason='Security verification completed; awaiting automated product review.',updated_at=now() WHERE transaction_number=$1",[transactionNumber]);
  await client.query("COMMIT");
  const reviewNext="Your security verification was successful. ReDom will review the specific product, transaction state, refund rules, and whether the product has already been used. This review can take up to 12 hours.";
  await addSupportMessage({caseId:String(row.case_id),senderType:"ai",senderEmail:env.email.supportFrom,body:"Security verification successful. Your refund request is now under review.\n\nNext step: "+reviewNext+"\n\nCase Number: "+String(row.case_number)+"\n\n"+REFUND_SECURITY_WARNING});
  await pool.query("UPDATE support_cases SET status='awaiting_support',updated_at=now() WHERE id=$1 AND status <> 'closed'",[row.case_id]);
  await sendRefundSupportStatus({email:String(row.email),caseNumber:String(row.case_number),transactionNumber,status:"Refund request under review",reason:"Security verification was successful and the refund review has started.",target:target.masked,nextStep:reviewNext}).catch(()=>undefined);
  return {success:true,status:"account_under_review",transactionNumber,caseNumber:String(row.case_number),target:target.masked};
 } catch(error) { await client.query("ROLLBACK").catch(()=>undefined); throw error; } finally { client.release(); }
}

export async function sendRefundProviderEmail(input:{email:string;caseNumber:string;transactionNumber:string;status:string;reason:string;target?:string|null;refundId?:string|null;amount?:string;currency?:string}):Promise<void> {
 const targetLine=input.target ? "\nRefund destination: "+input.target : "";
 const amountLine=input.amount && input.currency ? "\nAmount: "+input.amount+" "+input.currency : "";
 const refundLine=input.refundId ? "\nRefund ID: "+input.refundId : "";
 const {error}=await resend.emails.send({from:env.refunds.from,to:[input.email],subject:"ReDom Refunds — "+input.status+" — "+input.transactionNumber,text:"ReDom Refund Services\n\nTransaction: "+input.transactionNumber+"\nStatus: "+input.status+"\nReason: "+input.reason+amountLine+targetLine+refundLine+"\n\nCase Number: "+input.caseNumber+"\n\n"+REFUND_SECURITY_WARNING+"\n\n"+REFUND_SECURITY_WARNING});
 if(error) throw new Error(error.message);
}

export async function processRefundSupportEmail(input:{senderEmail:string;message:string;subject?:string|null;caseNumber?:string|null}):Promise<{handled:boolean;caseNumber?:string|null}> {
 const email=input.senderEmail.trim().toLowerCase();
 const account=await pool.query("SELECT id,email,first_name,last_name,phone_number FROM users WHERE lower(email)=lower($1) LIMIT 1",[email]);
 if(!account.rows[0]) {
   await sendSupportEmail(email,"ReDom Refund Request — Email Not Connected","Your refund request could not be initiated because this email address is not connected to an existing ReDom account. Please send the request from the email address connected to your ReDom account.\n\n"+REFUND_SECURITY_WARNING);
   return {handled:true,caseNumber:null};
 }
 const user=account.rows[0];
 let caseRecord:any=null;
 if(input.caseNumber) caseRecord=await getSupportCaseForRefundCase(input.caseNumber,email);
 if(!caseRecord) caseRecord=await createSupportCase({userId:String(user.id),requesterEmail:email,subject:"ReDom Refund Request",category:"refund_payment"});
 const records=await pool.query("SELECT pt.id,pt.redom_transaction_id,pt.reference,pt.purpose,pt.status,pt.amount_minor,pt.currency,pt.created_at,pt.metadata FROM payment_transactions pt WHERE pt.user_id=$1 ORDER BY pt.created_at DESC LIMIT 100",[user.id]);
 if(!records.rows.length) {
   const reply="No transaction records were found for "+email+". Please try again later.\n\n"+REFUND_SECURITY_WARNING;
   await addSupportMessage({caseId:caseRecord.id,senderType:"ai",senderEmail:env.email.supportFrom,body:reply});
   await sendSupportEmail(email,"ReDom Refund Request — No Transaction Records",reply+"\n\nCase Number: "+caseRecord.caseNumber);
   await permanentlyCloseSupportCase(caseRecord.id);
   return {handled:true,caseNumber:caseRecord.caseNumber};
 }
 const current=await pool.query("SELECT rr.transaction_number,rr.status FROM refund_requests rr WHERE rr.case_id=$1 ORDER BY rr.created_at DESC LIMIT 1",[caseRecord.id]);
 if(current.rows[0]) {
   const codeMatch=input.message.match(/\b(\d{6}|\d{8})\b/);
   if(codeMatch && ["verification_code_sent","awaiting_verification"].includes(String(current.rows[0].status))) {
     const result=await completeStarsRefund({userId:String(user.id),transactionNumber:String(current.rows[0].transaction_number),code:codeMatch[1]});
     return {handled:true,caseNumber:caseRecord.caseNumber};
   }
   return {handled:true,caseNumber:caseRecord.caseNumber};
 }
 const token=input.message.match(/\b(R-?\d{13}|\d{13}|T\d{6,})\b/i);
 if(!token) {
   const name=[user.first_name,user.last_name].filter(Boolean).join(" ")||"there";
   const reply="Hello "+name+",\n\nYour refund request is under review for account authentication. We found transaction records for "+email+". Please enter the number after R- (the 13 digits only) or the whole ReDom Transaction ID, or enter the Provider Reference Number. The reference is matched case-insensitively.\n\nCase Number: "+caseRecord.caseNumber+"\n\n"+REFUND_SECURITY_WARNING;
   await addSupportMessage({caseId:caseRecord.id,senderType:"ai",senderEmail:env.email.supportFrom,body:reply});
   await sendSupportEmail(email,"ReDom Refund Request — Transaction ID Required",reply);
   return {handled:true,caseNumber:caseRecord.caseNumber};
 }
 const supplied=normalizeRefundTransactionNumber(token[1]);
 const tx=await pool.query("SELECT redom_transaction_id,reference,purpose,status FROM payment_transactions WHERE user_id=$1 AND (upper(redom_transaction_id)=upper($2) OR upper(reference)=upper($2)) ORDER BY created_at DESC LIMIT 1",[user.id,supplied]);
 if(!tx.rows[0]) {
   const reply="The Transaction ID or Provider Reference Number you entered could not be verified against "+email+". Please reply with the exact ReDom Transaction ID or Provider Reference Number from your account. ReDom transaction numbers may be entered as the 13 digits after R- or as the complete R- transaction ID.\n\nCase Number: "+caseRecord.caseNumber+"\n\n"+REFUND_SECURITY_WARNING;
   await addSupportMessage({caseId:caseRecord.id,senderType:"ai",senderEmail:env.email.supportFrom,body:reply});
   await sendSupportEmail(email,"ReDom Refund Request — Transaction Not Verified",reply);
   return {handled:true,caseNumber:caseRecord.caseNumber};
 }
 const result=await startStarsRefund({userId:String(user.id),transactionNumber:String(tx.rows[0].redom_transaction_id),caseId:String(caseRecord.id),caseNumber:String(caseRecord.caseNumber)});
 return {handled:true,caseNumber:result.caseNumber??caseRecord.caseNumber};
}

async function getSupportCaseForRefundCase(caseNumber:string,email:string):Promise<any|null> {
 const r=await pool.query("SELECT * FROM support_cases WHERE case_number=$1 AND lower(requester_email)=lower($2) AND category='refund_payment' AND closed_at IS NULL LIMIT 1",[caseNumber.toUpperCase(),email]);
 return r.rows[0]??null;
}

export async function applyStarsRefundWebhook(event:string,data:any):Promise<void> {
 const reference=String(data?.transaction_reference??data?.transaction?.reference??""); if(!reference) return;
 const refundStatus=event.replace(/^refund\\./,"");
 const client=await pool.connect();
 try {
  await client.query("BEGIN");
  const tx=await client.query("SELECT id,user_id,amount_minor,metadata,redom_transaction_id,refund_status FROM payment_transactions WHERE reference=$1 FOR UPDATE",[reference]);
  if(!tx.rows[0]) { await client.query("COMMIT"); return; }
  const row=tx.rows[0];
  const request=await client.query("SELECT rr.id,rr.case_id,sc.case_number,rr.user_id,rr.status,rr.refund_target_masked,rr.currency,rr.amount,u.email FROM refund_requests rr JOIN support_cases sc ON sc.id=rr.case_id JOIN users u ON u.id=rr.user_id WHERE rr.transaction_number=$1 ORDER BY rr.created_at DESC LIMIT 1 FOR UPDATE",[row.redom_transaction_id]);
  if(!request.rows[0]) { await client.query("COMMIT"); return; }
  const rr=request.rows[0];
  const previousStatus=String(rr.status);
  const target=String(rr.refund_target_masked??"original payment rail");
  const reason=String(data?.reason??data?.message??(refundStatus==="processed"?"Refund successfully processed by the bank or payment processor.":refundStatus==="failed"?"The bank or payment processor rejected the refund.":"Refund is being processed by the bank or payment processor."));
  await client.query("UPDATE payment_transactions SET refund_status=$1,refund_id=COALESCE($2,refund_id),refund_processed_at=CASE WHEN $1='processed' THEN now() ELSE refund_processed_at END,refund_error=CASE WHEN $1='failed' THEN COALESCE($3,refund_error) ELSE NULL END,updated_at=now() WHERE id=$4",[refundStatus,data?.refund_reference?String(data.refund_reference):null,data?.reason?String(data.reason):null,row.id]);
  let finalStatus:string;
  let customerStatus:string;
  let terminal=false;
  let bankStatus:string;
  if(refundStatus==="processed") {
    let metadata:any={}; try { metadata=typeof row.metadata==="string"?JSON.parse(row.metadata):row.metadata??{}; } catch {}
    const stars=Number(metadata?.stars??0);
    if(Number.isInteger(stars)&&stars>0) {
      const account=await client.query("SELECT balance FROM redom_stars_accounts WHERE user_id=$1 FOR UPDATE",[row.user_id]);
      const balance=BigInt(String(account.rows[0]?.balance??"0"));
      const duplicate=await client.query("SELECT 1 FROM redom_stars_transactions WHERE payment_transaction_id=$1 AND type='refund' LIMIT 1",[row.id]);
      if(!duplicate.rows[0]) {
        if(balance<BigInt(stars)) throw new Error("Refund processed but Stars balance is insufficient for reversal.");
        const next=balance-BigInt(stars);
        await client.query("UPDATE redom_stars_accounts SET balance=$1,updated_at=now() WHERE user_id=$2",[next.toString(),row.user_id]);
        await client.query("INSERT INTO redom_stars_transactions(user_id,payment_transaction_id,type,stars,balance_after,package_key,currency,amount_minor,reference) VALUES($1,$2,'refund',$3,$4,$5,$6,$7,$8)",[row.user_id,row.id,-stars,next.toString(),metadata?.packageKey??null,metadata?.currency??null,row.amount_minor,"refund:"+reference]);
      }
    }
    finalStatus="refunded"; bankStatus="Bank processed"; customerStatus="Refund Successful"; terminal=true;
  } else if(refundStatus==="failed") {
    finalStatus="refund_rejected"; bankStatus="Bank rejected"; customerStatus="Refund Rejected"; terminal=true;
  } else if(refundStatus==="needs-attention") {
    finalStatus="refund_needs_attention"; bankStatus="Bank details required"; customerStatus="Refund requires bank details"; terminal=false;
  } else if(refundStatus==="processing") {
    finalStatus="refund_processing"; bankStatus="Bank processing"; customerStatus="Refund under review"; terminal=false;
  } else {
    finalStatus="refund_processing"; bankStatus="Bank review pending"; customerStatus="Refund under review"; terminal=false;
  }
  if(previousStatus===finalStatus) { await client.query("COMMIT"); return; }

  await client.query("UPDATE refund_requests SET status=$1,decision=CASE WHEN $2 THEN 'approved' ELSE decision END,decision_reason=$3,refund_completed_at=CASE WHEN $2 THEN now() ELSE refund_completed_at END,updated_at=now() WHERE id=$4",[finalStatus,terminal,reason,rr.id]);
  await client.query("UPDATE refund_transaction_locks SET outcome_status=$1,outcome_reason=$2,refund_id=COALESCE($3,refund_id),updated_at=now() WHERE transaction_number=$4",[finalStatus,reason,data?.refund_reference?String(data.refund_reference):null,row.redom_transaction_id]);
  await client.query("COMMIT");

  const supportText=terminal?bankStatus+" — "+customerStatus+". "+reason+" Destination: "+target+". The refund case is now closed and the transaction is permanently locked against another refund request.":bankStatus+" — "+customerStatus+". "+reason+" Destination: "+target+".";
  await addSupportMessage({caseId:String(rr.case_id),senderType:"system",body:supportText});
  if(String(rr.email)) await sendRefundProviderEmail({
    email:String(rr.email),caseNumber:String(rr.case_number),transactionNumber:String(row.redom_transaction_id),
    status:bankStatus+" — "+customerStatus,reason,target,
    refundId:data?.refund_reference?String(data.refund_reference):null,
    amount:String(row.amount_minor),currency:String(rr.currency)
  }).catch(()=>undefined);

  if(terminal) {
    if(String(rr.email)) await sendRefundTerminalEmail({email:String(rr.email),caseNumber:String(rr.case_number),transactionNumber:String(row.redom_transaction_id),status:bankStatus+" — "+customerStatus,reason,target,amount:String(row.amount_minor),currency:String(rr.currency),refundId:data?.refund_reference?String(data.refund_reference):null}).catch(()=>undefined);
    await pool.query("UPDATE refund_requests SET case_invalidated_at=COALESCE(case_invalidated_at,now()),updated_at=now() WHERE id=$1",[rr.id]);
    await pool.query("UPDATE refund_transaction_locks SET invalidated_at=COALESCE(invalidated_at,now()),updated_at=now() WHERE transaction_number=$1",[row.redom_transaction_id]);
    await permanentlyCloseSupportCase(String(rr.case_id));
  }
 } catch(error) { await client.query("ROLLBACK").catch(()=>undefined); throw error; } finally { client.release(); }
}
