import { randomBytes, randomInt } from "node:crypto";
import { and, eq, gt, lte } from "drizzle-orm";
import { db } from "../../database/db";
import { registrationChallenges } from "../../database/registration-challenges.schema";
import { registrationFlowReservations } from "../../database/registration-flow-reservations.schema";
import { users } from "../../database/schema";
import { verifications } from "../../database/verifications.schema";
import { fraudService } from "./fraud.service";
import { passwordService } from "./password.service";
import { phoneService } from "./phone.service";
import { emailService } from "./email.service";
import { publicIdService } from "./public-id.service";
import { profileIdService } from "./profile-id.service";
import { verificationService } from "./verification.service";
import { registrationFlowReservationService } from "./registration-flow-reservation.service";
import { registrationFlowMemoryService } from "./registration-flow-memory.service";

type RegistrationStep = "contact" | "identity" | "username" | "profile" | "password" | "review";
type RegistrationContactType = "phone" | "email";
type RegistrationGender = "male" | "female" | "custom";
const CHALLENGE_TTL_MS = 30 * 60 * 1000;
const FLOW_ID_MIN_LENGTH = 6;
const FLOW_ID_MAX_LENGTH = 16;
const FLOW_ID_GENERATION_ATTEMPTS = 12;

function maskFlowId(flowId: string) { return flowId.length > 4 ? `${flowId.slice(0, 4)}••••••••✓` : `${flowId}✓`; }
function generateNumericFlowId(): string { const length = randomInt(FLOW_ID_MIN_LENGTH, FLOW_ID_MAX_LENGTH + 1); const bytes = randomBytes(length); let flowId = ""; for (let index = 0; index < length; index += 1) { let byte = bytes[index]!; while (byte >= 250) byte = randomBytes(1)[0]!; flowId += String(byte % 10); } return flowId; }
function maskTarget(target: string, type: RegistrationContactType) { if (type === "phone") { const digits = target.replace(/\s/g, ""); return digits.length > 7 ? `${digits.slice(0, 5)}•••${digits.slice(-4)}` : `${digits.slice(0, 2)}••••`; } const [local, domain] = target.split("@"); if (!local || !domain) return "••••"; return `${local.slice(0, 2)}•••@${domain}`; }

export class RegistrationChallengeService {
  private async deleteExpired(challengeId?: string) { const now = new Date(); await db.delete(registrationChallenges).where(challengeId ? and(eq(registrationChallenges.id, challengeId), lte(registrationChallenges.expiresAt, now)) : lte(registrationChallenges.expiresAt, now)); }
  async purgeExpired() { await this.deleteExpired(); }
  private async getActive(challengeId: string) { await this.deleteExpired(challengeId); const challenge = await db.query.registrationChallenges.findFirst({ where: and(eq(registrationChallenges.id, challengeId), eq(registrationChallenges.status, "pending"), gt(registrationChallenges.expiresAt, new Date())) }); if (!challenge) throw new Error("Registration flow not found or expired."); return challenge; }
  private async generateFlowId() { for (let attempt = 0; attempt < FLOW_ID_GENERATION_ATTEMPTS; attempt += 1) { const flowId = generateNumericFlowId(); const active = await db.query.registrationChallenges.findFirst({ where: and(eq(registrationChallenges.flowId, flowId), gt(registrationChallenges.expiresAt, new Date())) }); if (!active) return flowId; } throw new Error("Unable to allocate a unique registration Flow ID."); }
  async start(params: { contactType: RegistrationContactType; target: string; requestIp?: string; userAgent?: string; deviceId?: string; reservationId?: string; flowId?: string; }) {
    await this.deleteExpired(); const normalizedTarget = params.contactType === "phone" ? phoneService.validate(params.target) : emailService.validate(params.target); const existing = await db.query.users.findFirst({ where: params.contactType === "phone" ? eq(users.phoneNumber, normalizedTarget) : eq(users.email, normalizedTarget) }); if (existing && !(existing.accountStatus === "pending" && existing.emailVerified === false && existing.phoneVerified === false)) throw new Error(params.contactType === "phone" ? "That phone number is already registered." : "That email address is already registered.");
    let flowId: string; let reservedFirstName: string | null = null; let reservedLastName: string | null = null; let reservedDateOfBirth: string | null = null; let reservedGender: RegistrationGender | null = null; let reservedPasswordHash: string | null = null; let reservedEmail: string | null = null; let reservedPhoneNumber: string | null = null;
    if (params.reservationId || params.flowId) { if (!params.reservationId || !params.flowId) throw new Error("Registration Flow ID reservation is incomplete."); const reservation = await registrationFlowReservationService.consume(params.reservationId, params.flowId, params.deviceId); const flowMemory = await registrationFlowMemoryService.get({ reservationId: params.reservationId, flowId: params.flowId, deviceId: params.deviceId }); const memory = flowMemory.memory; flowId = reservation.flowId; reservedFirstName = reservation.firstName; reservedLastName = reservation.lastName; reservedDateOfBirth = reservation.dateOfBirth; reservedGender = memory.gender?.gender === "male" || memory.gender?.gender === "female" || memory.gender?.gender === "custom" ? memory.gender.gender : null; reservedPasswordHash = memory.password?.hash ?? null; reservedEmail = memory.email?.address ?? null; reservedPhoneNumber = memory.phoneLookup?.phoneNumber ?? null; if (params.contactType === "email" && reservedEmail && reservedEmail !== normalizedTarget) throw new Error("The email address does not match this registration flow."); if (params.contactType === "phone" && reservedPhoneNumber && reservedPhoneNumber !== normalizedTarget) throw new Error("The phone number does not match this registration flow."); } else { flowId = await this.generateFlowId(); }
    const now = new Date(); const [challenge] = await db.insert(registrationChallenges).values({ flowId, contactType: params.contactType, target: normalizedTarget, normalizedTarget, firstName: reservedFirstName, lastName: reservedLastName, email: reservedEmail, phoneNumber: reservedPhoneNumber, dateOfBirth: reservedDateOfBirth, gender: reservedGender, passwordHash: reservedPasswordHash, currentStep: reservedFirstName && reservedLastName ? "identity" : "contact", status: "pending", requestIp: params.requestIp, userAgent: params.userAgent, deviceId: params.deviceId, expiresAt: new Date(now.getTime() + CHALLENGE_TTL_MS), createdAt: now, updatedAt: now }).returning(); if (!challenge) throw new Error("Unable to start registration flow."); return { success: true, challengeId: challenge.id, flowId: maskFlowId(challenge.flowId), contactType: challenge.contactType as RegistrationContactType, maskedTarget: maskTarget(normalizedTarget, params.contactType), expiresAt: challenge.expiresAt.toISOString(), currentStep: challenge.currentStep as RegistrationStep };
  }
  async saveStep(params: { challengeId: string; step: RegistrationStep; data: { firstName?: string; lastName?: string; username?: string; email?: string; phoneNumber?: string; dateOfBirth?: string; gender?: "male" | "female" | "custom"; password?: string; }; }) { const challenge = await this.getActive(params.challengeId); const patch: Record<string, unknown> = { currentStep: params.step, updatedAt: new Date() }; if (params.data.firstName !== undefined) patch.firstName = params.data.firstName.trim(); if (params.data.lastName !== undefined) patch.lastName = params.data.lastName.trim(); if (params.data.username !== undefined) patch.username = params.data.username.trim(); if (params.data.dateOfBirth !== undefined) patch.dateOfBirth = params.data.dateOfBirth; if (params.data.gender !== undefined) patch.gender = params.data.gender; if (params.data.email !== undefined) { const email = emailService.validate(params.data.email); if (challenge.contactType === "email" && email !== challenge.normalizedTarget) throw new Error("This email address does not match the registration flow."); patch.email = email; } if (params.data.phoneNumber !== undefined) { const phone = phoneService.validate(params.data.phoneNumber); if (challenge.contactType === "phone" && phone !== challenge.normalizedTarget) throw new Error("This phone number does not match the registration flow."); patch.phoneNumber = phone; } if (params.data.password !== undefined) { passwordService.validate(params.data.password); patch.passwordHash = await passwordService.hash(params.data.password); } await db.update(registrationChallenges).set(patch).where(and(eq(registrationChallenges.id, challenge.id), eq(registrationChallenges.status, "pending"))); const updated = await this.getActive(challenge.id); return { success: true, challengeId: updated.id, flowId: maskFlowId(updated.flowId), maskedTarget: maskTarget(updated.normalizedTarget, updated.contactType as RegistrationContactType), expiresAt: updated.expiresAt.toISOString(), currentStep: updated.currentStep as RegistrationStep }; }
  async complete(params: { challengeId: string; submitted?: { email?: string; phoneNumber?: string } }) {
    const challenge = await this.getActive(params.challengeId); if (params.submitted?.email !== undefined) { const submittedEmail = emailService.validate(params.submitted.email); if (challenge.contactType === "email" && submittedEmail !== challenge.normalizedTarget) throw new Error("The email address does not match this registration flow."); if (challenge.contactType !== "email" && challenge.email !== submittedEmail) throw new Error("The email address does not match this registration flow."); } if (params.submitted?.phoneNumber !== undefined) { const submittedPhone = phoneService.validate(params.submitted.phoneNumber); if (challenge.contactType === "phone" && submittedPhone !== challenge.normalizedTarget) throw new Error("The phone number does not match this registration flow."); if (challenge.contactType !== "phone" && challenge.phoneNumber !== submittedPhone) throw new Error("The phone number does not match this registration flow."); } if (!challenge.firstName || !challenge.lastName || !challenge.username) throw new Error("Registration details are incomplete."); if (!challenge.dateOfBirth || !challenge.gender || !challenge.passwordHash) throw new Error("Registration security details are incomplete."); const email = challenge.email ?? (challenge.contactType === "email" ? challenge.normalizedTarget : null); const phoneNumber = challenge.phoneNumber ?? (challenge.contactType === "phone" ? challenge.normalizedTarget : null); if (!email && !phoneNumber) throw new Error("A contact method is required."); if (await db.query.users.findFirst({ where: eq(users.username, challenge.username) })) throw new Error("Username is already registered."); const existingEmail = email ? await db.query.users.findFirst({ where: eq(users.email, email) }) : null; const existingPhone = phoneNumber ? await db.query.users.findFirst({ where: eq(users.phoneNumber, phoneNumber) }) : null; const legacyPending = existingEmail && existingEmail.accountStatus === "pending" && !existingEmail.emailVerified && !existingEmail.phoneVerified ? existingEmail : existingPhone && existingPhone.accountStatus === "pending" && !existingPhone.emailVerified && !existingPhone.phoneVerified ? existingPhone : null; if (existingEmail && existingEmail.id !== legacyPending?.id) throw new Error("Email address is already registered."); if (existingPhone && existingPhone.id !== legacyPending?.id) throw new Error("Phone number is already registered.");
    const verification = await verificationService.createVerification({ userId: legacyPending?.id ?? null, purpose: challenge.contactType === "phone" ? "PHONE_VERIFICATION" : "EMAIL_VERIFICATION", target: challenge.normalizedTarget, channel: challenge.contactType === "phone" ? "sms" : "email", requestedLength: 6, firstName: challenge.firstName, requestIp: challenge.requestIp ?? undefined, userAgent: challenge.userAgent ?? undefined, deviceId: challenge.deviceId ?? undefined, sessionId: challenge.id });
    const reservation = await db.query.registrationFlowReservations.findFirst({ where: and(eq(registrationFlowReservations.flowId, challenge.flowId), eq(registrationFlowReservations.status, "active"), gt(registrationFlowReservations.expiresAt, new Date())) }); if (reservation) { const memory = { ...((reservation.memory ?? {}) as Record<string, any>) }; memory.verification = { challengeId: verification.challengeId, channel: verification.channel, target: verification.target, maskedTarget: maskTarget(verification.normalizedTarget, challenge.contactType), expiresAt: verification.expiresAt.toISOString(), status: "pending", updatedAt: new Date().toISOString() }; await db.update(registrationFlowReservations).set({ memory, registeredTables: [...new Set([...(reservation.registeredTables ?? []), "verifications"])] as string[] }).where(eq(registrationFlowReservations.id, reservation.id)); }
    return { success: true, flowId: maskFlowId(challenge.flowId), verification: { challengeId: verification.challengeId, channel: verification.channel, target: verification.target, maskedTarget: maskTarget(verification.normalizedTarget, challenge.contactType), codeLength: verification.codeLength, expiresAt: verification.expiresAt } };
  }
  async verify(params: { verificationChallengeId: string; code: string }) {
    const verification = await db.query.verifications.findFirst({ where: eq(verifications.id, params.verificationChallengeId) }); if (!verification) throw new Error("Verification challenge not found."); if (!["PHONE_VERIFICATION", "EMAIL_VERIFICATION"].includes(verification.purpose)) throw new Error("Verification challenge is invalid for registration."); const challengeId = verification.sessionId; if (!challengeId) throw new Error("Registration challenge is missing."); const challenge = await this.getActive(challengeId); if (challenge.contactType === "email" && verification.purpose !== "EMAIL_VERIFICATION") throw new Error("Verification challenge does not match this registration."); if (challenge.contactType === "phone" && verification.purpose !== "PHONE_VERIFICATION") throw new Error("Verification challenge does not match this registration."); if (verification.normalizedTarget !== challenge.normalizedTarget) throw new Error("Verification target does not match this registration.");
    await verificationService.verifyVerification({ challengeId: verification.id, code: params.code, purpose: verification.purpose as "PHONE_VERIFICATION" | "EMAIL_VERIFICATION" }); const verifiedAt = new Date(); let user = verification.userId ? await db.query.users.findFirst({ where: eq(users.id, verification.userId) }) : null; if (verification.userId && !user) throw new Error("Registration account not found."); const email = challenge.email ?? (challenge.contactType === "email" ? challenge.normalizedTarget : null); const phoneNumber = challenge.phoneNumber ?? (challenge.contactType === "phone" ? challenge.normalizedTarget : null);
    if (user) { const duplicateUsername = await db.query.users.findFirst({ where: and(eq(users.username, challenge.username!), eq(users.id, user.id)) }); if (!duplicateUsername) { const conflictingUsername = await db.query.users.findFirst({ where: eq(users.username, challenge.username!) }); if (conflictingUsername && conflictingUsername.id !== user.id) throw new Error("Username is already registered."); } const [updatedUser] = await db.update(users).set({ firstName: challenge.firstName!, lastName: challenge.lastName!, username: challenge.username!, email, phoneNumber, passwordHash: challenge.passwordHash!, dateOfBirth: challenge.dateOfBirth!, gender: challenge.gender as "male" | "female" | "custom", ...(verification.purpose === "PHONE_VERIFICATION" ? { phoneVerified: true } : { emailVerified: true }), accountStatus: "active", updatedAt: verifiedAt }).where(eq(users.id, user.id)).returning(); user = updatedUser ?? user; }
    else { const usernameConflict = await db.query.users.findFirst({ where: eq(users.username, challenge.username!) }); const emailConflict = email ? await db.query.users.findFirst({ where: eq(users.email, email) }) : null; const phoneConflict = phoneNumber ? await db.query.users.findFirst({ where: eq(users.phoneNumber, phoneNumber) }) : null; if (usernameConflict) throw new Error("Username is already registered."); if (emailConflict) throw new Error("Email address is already registered."); if (phoneConflict) throw new Error("Phone number is already registered."); const publicId = await publicIdService.generate(); const profileId = await profileIdService.generate(); const [createdUser] = await db.insert(users).values({ firstName: challenge.firstName!, lastName: challenge.lastName!, username: challenge.username!, publicId, profileId, email, phoneNumber, passwordHash: challenge.passwordHash!, dateOfBirth: challenge.dateOfBirth!, gender: challenge.gender as "male" | "female" | "custom", emailVerified: verification.purpose === "EMAIL_VERIFICATION", phoneVerified: verification.purpose === "PHONE_VERIFICATION", accountStatus: "active", profileIdVisibility: "public", createdAt: verifiedAt, updatedAt: verifiedAt }).returning(); if (!createdUser) throw new Error("Unable to create account after verification."); user = createdUser; }
    await fraudService.checkRegistration({ userId: user.id, email: user.email ?? "", phoneNumber: user.phoneNumber ?? "", ipAddress: challenge.requestIp ?? undefined, userAgent: challenge.userAgent ?? undefined });
    const reservation = await db.query.registrationFlowReservations.findFirst({ where: eq(registrationFlowReservations.flowId, challenge.flowId) }); if (reservation) { const memory = { ...((reservation.memory ?? {}) as Record<string, any>) }; memory.verification = { ...(memory.verification ?? {}), challengeId: verification.id, status: "verified", verifiedAt: verifiedAt.toISOString(), target: verification.target, channel: verification.channel }; await db.update(registrationFlowReservations).set({ memory }).where(eq(registrationFlowReservations.id, reservation.id)); }
    if (verification.purpose === "EMAIL_VERIFICATION") { await emailService.sendRegistrationConfirmation({ firstName: user.firstName, lastName: user.lastName, email: user.email ?? verification.normalizedTarget, registeredAt: verifiedAt, flowId: challenge.flowId, userAgent: challenge.userAgent ?? "" }); }
    // IMPORTANT: keep the registration challenge until initialization consumes it. The customization screen
    // immediately calls /register/initialize, which needs the challenge to create the session/login history,
    // finalize the Flow ID and remove the transient registration records. Deleting it here caused the
    // "Registration verification is not complete or has expired" error on the customization screen.
    return { success: true, message: "Account verified successfully." };
  }
  async getFlow(challengeId: string) { const challenge = await this.getActive(challengeId); return { success: true, challengeId: challenge.id, flowId: maskFlowId(challenge.flowId), contactType: challenge.contactType as RegistrationContactType, maskedTarget: maskTarget(challenge.normalizedTarget, challenge.contactType as RegistrationContactType), currentStep: challenge.currentStep as RegistrationStep, expiresAt: challenge.expiresAt.toISOString() }; }
}

export const registrationChallengeService = new RegistrationChallengeService();